### ISSUE TITLE
Speed up spec suite

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-rails#1023]
The current spec suite takes forever to run. This has really been slowing down the pace of issues. A few things we can consider to help with this:
- [ ] Trim the build matrix if possible
- [ ] Use `spring`-ified stubs for cuke features (Rails 4.1+ only)
- [ ] Consider using the [`parallel_tests`](https://github.com/grosser/parallel_tests) gem
- [ ] Look into [caching dependencies](http://docs.travis-ci.com/user/caching/)
- [ ] Consider trying out [bundler's --standalone mode](http://myronmars.to/n/dev-blog/2012/03/faster-test-boot-times-with-bundler-standalone) with cuke features
- [ ] Separate the rails environment parts in various [spec](http://articles.coreyhaines.com/posts/active-record-spec-helper/) [helpers](https://github.com/rspec/rspec-rails/issues/990)

**Comment by klyonrad** [comment]
Hey, this issue can be closed, right? I don't think you can become significantly faster with travis anyway and 10-15 minutes for one integration test suite run seems fine (and running `rake spec` is blazingly fast)

**Comment by JonRowe** [comment]
I'm going to close this as stale for now, we could speed up the suite by splitting the build up into simpler parallel bits, maybe as part of a move to github actions or something...

**Comment by benoittgt** [comment]
I will try next week to run rspec-core or rspec-rails on github actions on a fork, to see if it could help us. :)
