### ISSUE TITLE
Feature testing Issue

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-rails#1042]
Moved from rspec/rspec-core#1555; original issue by @gopesht

I am getting this  error:

> An error occurred in an after hook ActionView::Template::Error: undefined method `sponsorship_levels` for nil:NilClass occurred at `app/views/admin/sponsorships/index.html.haml:6`:in `block in _app_views_admin_sponsorships_index_html_haml__1335523313015117388_62294240`
> 
> F
> An error occurred in an after hook ActionView::Template::Error: undefined method `sponsorship_levels` for nil:NilClass occurred at app/views/admin/sponsorships/index.html.haml:6:in `block in _app_views_admin_sponsorships_index_html_haml__1335523313015117388_62294240`
> 
> F
> 
> Failures:
> 
>  1) SponsorshipRegistration admin behaves like sponsorship registration register sponsors
>     Failure/Error: Unable to find matching line from backtrace
>     ActiveRecord::StatementInvalid:
>       SQLite3::BusyException: database is locked: DELETE FROM sqlite_sequence where name = 'conferences';
>     Shared Example Group: "sponsorship registration" called from ./spec/features/sponsorship_registrations_spec.rb:41
>     # ./spec/support/database_cleaner.rb:20:in `block (2 levels) in <top (required)>'
> 
>  2) SponsorshipRegistration organizer behaves like sponsorship registration register sponsors
>     Failure/Error: Unable to find matching line from backtrace
>     ActiveRecord::StatementInvalid:
>       SQLite3::BusyException: database is locked: DELETE FROM sqlite_sequence where name = 'conferences_questions';
>     Shared Example Group: "sponsorship registration" called from ./spec/features/sponsorship_registrations_spec.rb:45
>     # ./spec/support/database_cleaner.rb:20:in `block (2 levels) in <top (required)>`

the `index.html.haml` file contains:

``` haml
#new-sponsorship-dialog
  = semantic_form_for :sponsorship_registration, :html => {:id => "sponsorship-add-form"}  do |f|
    = f.input :name, :label => "Sponsorship Name"
    = f.input :email_id, :label => "Sponsorship Email"
    = f.input :organization_id, as: :select, collection: Organization.all
    = f.input :sponsorship_level_id, :as => :select, :collection => @conference.sponsorship_levels
    = f.input :contact_no, :label => "Phone Number"
    = f.input :amount_donated
    = f.input :method_of_donation
    = f.action :submit, :button_html => { :value => "Save", :class => "btn btn-primary" }
```

there is error at `sponsorship_level_id` as said

please help

**Comment by PraveenMSD** [comment]
In the test / test_help.rb file

#Probably about the 8th and 9th lines
`
parallelize(workers: :number_of_processors, with: :threads)
`

Comment out
`
# parallelize(workers: :number_of_processors, with: :threads)
`
As a result, no error was displayed and the test passed !!
