### ISSUE TITLE
Update feature cukes to provide proper info on setting request type

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-rails#1044]
We haven't been very clear on the different way the request format other than `html` (i.e. `json`, `xml`, etc) can be set for the different specs.

Honestly, off the top of my head I never remember and always have to go digging to find it. We need to do this for the following:

- [ ] Controller specs (this should add `format: :json` to the params hash)
- [ ] Request specs
- [ ] Feature specs

Thanks to @6ewis for bringing this up in IRC.

**Comment by frmendes** [comment]
Have there been any updates on this?

As far as I could tell, it's basically updating the Cucumber features to account for `xml` and `json`, right?

**Comment by samphippen** [comment]
@jdax @ryanclark2 @sarahmei it looks like there are commits related to this in your repo(s). Is this work you want to carry forward, or are we clear to have @frmendes go ahead on this one?

**Comment by samphippen** [comment]
@frmendes while there looks like work started here, it hasn't been touched for over a year, so you're probably clear to go ahead 🚀. You might be free to be able to draw work from others, but if you want to open a pr, I'm sure everyone will be ✨

**Comment by frmendes** [comment]
That's pretty much why I asked, since there was work started but with 1+ years on it. I'll check it out. Thanks! 🎉

**Comment by frmendes** [comment]
Actually, I was now digging into it and this appears to [have been merged](https://github.com/rspec/rspec-rails/pull/1435) into the main repo.

**Comment by ryanclark2** [comment]
Sorry for the late response, but IIRC this was done and merged. Lemme know
if I can help more.

Thanks,
Ryan

**Comment by samphippen** [comment]
Cool. I'll close this out then!
