### ISSUE TITLE
Hard bump the capybara version

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-rails#1095]
If we still have a dependency on capybara, we should hard bump the version on 4.0. Additionally, reach out to the capybara team early on this process to better coordinate any changes that need to be made, and sync the releases between the two gems.

Related to: #1091, #1094

**Comment by pirj** [comment]
Rails [depended on Capybara 2.15+ up until now](https://github.com/rails/rails/blob/6-0-stable/Gemfile#L12) (6-0-stable as of [`04e08ee17`](https://github.com/rails/rails/commit/04e08ee17fb8dc5374edc01226881a7c4ece3fdf).

There are [bump](https://github.com/rails/rails/pull/36615/files#diff-e79a60dc6b85309ae70a6ea8261eaf95R548) [commits](https://github.com/rails/rails/commit/161e622cf21a9680a2d8b6e588e5d97e720e4eca) in `master` to depend on 3.2.6+, but it's not released/tagged yet, presumably might happen in 6.1.

Capybara seems stable, 3.0 is around for three years already, and there are no plans for 4.0 as far as I can see.

With this in mind, wondering if we sh bump it to `~> 3.0` or rely on Rails to pick a version they need to use under the hood.

**Comment by JonRowe** [comment]
Whats the minimum version supported by our current matrix, should at least bump to that if you want to tackle @pirj?

**Comment by pirj** [comment]
`capybara` first appeared [as `~> 2.7.0` in Rails 5.1.0.beta1](https://github.com/rails/rails/commit/9730b1dba6d1bb9684a54915ac3735d9c0eade26#diff-b7fa9d561299f29d274d90ebbade03caR29), was bumped [to `~> 2.13.0` in Rails 5.1.0.rc1](https://github.com/rails/rails/commit/eadbc82c47fd157ed4f1eb4c4983ab0734023106), [remained `~> 2.13.0` in 5.1.0](https://github.com/rails/rails/blob/v5.1.0/Gemfile#L17) and [is `> 2.15` in `5-1-stable`](https://github.com/rails/rails/blob/5-1-stable/Gemfile#L20).

I intend to bump it to `>= 2.13` from [our current `~> 2.13`](https://github.com/rspec/rspec-rails/blob/8b2b8ff7ed0f7b98e00cb25604b7e9ea93db8b02/Gemfile#L51) to allow for both 2 & 3, and a smoother [transition](https://github.com/teamcapybara/capybara/blob/master/UPGRADING.md) between the two.

**Comment by JonRowe** [comment]
It would be better to do `~> 2.13, ~> 3.0` to exclude 4 until we're compatible (and we'll need to check we're 3.x compatible)
