### ISSUE TITLE
uninitialized constant RSpec::Support (NameError)

### ISSUE THREAD

**Issue by rahul100885** [rspec/rspec-rails#1113]
I have upgraded from rspec-rails version 2.99.0 to 3.0.1. but when ever I try to run any command, it is giving following error. 

> /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/formatters/documentation_formatter.rb:1:in `<top (required)>': uninitialized constant RSpec::Support (NameError)
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/stopwatch_formatter-1.0.0/lib/stopwatch_formatter.rb:1:in`<top (required)>'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `require'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in`block (2 levels) in require'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `each'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in`block in require'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `each'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in`require'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler.rb:132:in `require'
>     from /home/rahul/workspace/org/sample_app/config/application.rb:8:in`<top (required)>'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:79:in `require'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:79:in`block in server'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:76:in `tap'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:76:in`server'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/commands.rb:17:in`<top (required)>'
>     from /home/rahul/workspace/org/sample_app/bin/rails:8:in `require'
>     from /home/rahul/workspace/org/sample_app/bin/rails:8:in`<top (required)>'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/client/rails.rb:27:in `load'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/client/rails.rb:27:in`call'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/client/command.rb:7:in `call'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/client.rb:26:in`run'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/bin/spring:48:in `<top (required)>'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/binstub.rb:11:in`load'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/binstub.rb:11:in `<top (required)>'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
>     from /home/rahul/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /home/rahul/workspace/org/sample_app/bin/spring:16:in`<top (required)>'
>     from bin/rails:3:in `load'
>     from bin/rails:3:in`<main>'

**Comment by mooreniemi** [comment]
Related issue (for googlers following the trail): https://github.com/grosser/rspec-instafail/issues/16
