### ISSUE TITLE
Controller's inheritence is changed when running as a suite

### ISSUE THREAD

**Issue by edpaget** [rspec/rspec-rails#1130]
I encountered a strange problem when using [Doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) and RSpec after doorkeeper-gem/doorkeeper@84f809aa98fcde3272d45e0381ebb6829df8f8f7. 

I am using rspec-rails 3.0.3 and had the issue using both MRI 2.1.2 and JRuby-1.7.13 in 2.0 mode. [Here](https://travis-ci.org/zooniverse/Panoptes/jobs/30758877) is a link to one of my CI builds showing the failure.  

Basically I have overridden a couple of Doorkeeper's built in controllers resulting an inheritance chain that looks like `MyController < MyModule < Doorkeeper::AuthorizationsController < Doorkeeper::ApplicationController < Helpers::Controller ...`. [This](https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/controllers/doorkeeper/authorizations_controller.rb) is the class I'm inheriting from. 

The problem I'm encountering is that when I run my full suite with `bundle exec rspec` the `ApplicationController` [here](https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/controllers/doorkeeper/authorizations_controller.rb#L2) is being interpreted as my application's `ApplicationController` and my inheritance chain is changed to  `MyController < MyModule < Doorkeeper::AuthorizationsController < ApplicationController <  ...`

I'm not sure the best way to break this down into a test case for you, but as some example code. 

_app/controllers/application_controller.rb_

``` ruby
class ApplicationController < ActionController::Base
end
```

_app/controllers/authorizations_controller.rb_

``` ruby
class AuthorizationsController < Doorkeeper::AuthorizationsController
  before_action :flash_dance

  private

  def flash_dance
    flash[:notice] = "DANCE!"
  end
end
```

_spec/controllers/authorizations_controller.rb_

``` ruby
require 'rails_helper'

RSpec.describe AuthorizationsController, type: :controller do
  it 'should throw a method undefined error when run as a suite'
     expect{get :new}.to raise_error(NoMethodError)
  end

   it 'should redirect when run individually' do
     get :new
     expect(response).to redirect_to("/users/sign_in")
   end
end
```

What I'm observing is that `bundle exec rspec` the first test would succeed and the second would fail and `bundle exec rspec spec/controllers/authorizations_controller.rb` the first test would fail and the second succeed.

Let me know if there's any more info that would be helpful.

**Comment by VesQ** [comment]
Just a tip for future readers: We encountered this same problem and remedied it by turning on `config.eager_load = true` in our test environment configuration. No need to manually require any files.
