### ISSUE TITLE
receive_message_chain unable to receive counts

### ISSUE THREAD

**Issue by craineum** [rspec/rspec-rails#1134]
This is with rspec-rails 3.0.2.
expect receive defaults to only allow one call, but when trying:

```
expect(Rails).to receive_message_chain(:application, :secrets, client_id: client_id).twice
```

I get:

```
Failure/Error: expect(Rails).to receive_message_chain(:application, :secrets, client_id: client_id).twice
NoMethodError:
  undefined method `twice' for #<RSpec::Mocks::Matchers::ReceiveMessageChain:0x00000005ec8b00>
```

There is a secondary issue that I am trying to track down where in my code I am only calling Rails.application.secrets.client_id, once, but the expect tells me that it is happening twice.

**Comment by ashwintastic** [comment]
> ```
> call_count = 0
> allow(Rails).to receive_message_chain(:application, :secrets, :client_id) do
>   call_count += 1
>   client_id
> end
> 
> # do stuff
> expect(call_count).to eq(2)
> ```
> 
> That said, is there any reason you can't do `expect(Rails.application.secrets).to receive(:client_id).twice.and_return(client_id)`?
> 
> And in general, using message expectations is generally best used only for command methods, but this is a query method so I wouldn't tent to use a message expectation at all.

It didn't work for me call_count is 0 for me. but the block is getting executed
