### ISSUE TITLE
Improve route spec generation for controller generators

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-rails#1160]
If you use the Rails generator to create a controller with some actions, it will automatically add basic routes for it. This feature would need to do two things:
1. Automatically add passing specs for the generated routes
2. If no actions / routes were specified, include our default filler message

From #1155 (see [discussion](https://github.com/rspec/rspec-rails/pull/1155#issuecomment-53575521))

**Comment by b-lambert** [comment]
Looks like @glittershark gave up on this? I'd be happy to take it on!

**Comment by samphippen** [comment]
@b-lambert go ahead! As far as I'm aware we've not seen any further action on this pull request :)

**Comment by siakaramalegos** [comment]
I'm not sure I quite understand what the request is - rspec already generates a controller test for any route specified in the generator. What's an example of an improved test?

For example, if you run `rails g controller Delete test`, it generates a controller spec file with the content:
```
require 'rails_helper'

RSpec.describe DeleteController, type: :controller do

  describe "GET #test" do
    it "returns http success" do
      get :test
      expect(response).to have_http_status(:success)
    end
  end

end
```

If the `test` route is removed from the generated command, this is what you get instead:
```
require 'rails_helper'

RSpec.describe DeleteController, type: :controller do

end
```

What do we want instead?

**Comment by samphippen** [comment]
@siakaramalegos I believe the idea is to generate routing specs: https://www.relishapp.com/rspec/rspec-rails/v/2-4/docs/routing-specs

**Comment by siakaramalegos** [comment]
Oh interesting! I'll wait a bit to see if @b-lambert picks it up.

**Comment by glittershark** [comment]
I had actually done this (two years ago D:) but gave up when I couldn't manage to make the tests pass. Maybe I can see if I can dredge it up from a backup on whatever computer I had then

**Comment by b-lambert** [comment]
@glittershark see what you can dredge up!

**Comment by 00dav00** [comment]
@cupakromer @b-lambert @glittershark If you guys don't I would like to work on this one :)

**Comment by b-lambert** [comment]
I'm no longer working on it so it's up to @glittershark

**Comment by 00dav00** [comment]
@cupakromer [This PR](https://github.com/rspec/rspec-rails/pull/1806) should cover the requested feature.

CC  @b-lambert

**Comment by klyonrad** [comment]
Seems like this issue can be closed with https://github.com/rspec/rspec-rails/pull/2134, right?
