### ISSUE TITLE
Getting "invalid option: --pattern" for post-3.0.2 rspec-rails gem.

### ISSUE THREAD

**Issue by jasnow** [rspec/rspec-rails#1171]
**Getting "invalid option: --pattern" for 3.0.3+ rspec-rails gem.**
1. Created new branch "pattern-invalid-option" under https://github.com/jasnow/tasks repo:
    https://github.com/jasnow/tasks/tree/pattern-invalid-option
   My master branch is using rspec-rails 3.0.2 currently.
2. Removed hard coded gem version 3.0.2 for rspec-rails in Gemfile therefore using 3.1.0.
3. Ran "bundle" then "rake" and got this (minor edits):

```
    /home/dell/.rvm/rubies/ruby-2.1.2/bin/ruby -I/home/dell/.rvm/gems/
    ruby-2.1.2@tasks/gems/rspec-core-3.1.2/lib:/home/dell/.rvm/gems/
    ruby-2.1.2@tasks/gems/rspec-support-3.1.0/lib /home/dell/.rvm/
    gems/ruby-2.1.2@tasks/gems/rspec-core-3.1.2/exe/rspec
     --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
    ......

    Finished in 0.39711 seconds (files took 3.72 seconds to load)

    6 examples, 0 failures

    Randomized with seed 9180

    **invalid option: --pattern**

    minitest options:
        -h, --help                       Display this help.
        -s, --seed SEED                  Sets random seed
        -v, --verbose                    Verbose. Show progress processing files.
        -n, --name PATTERN               Filter run on /pattern/ or string.

    Known extensions: pride
        -p, --pride                      Pride. Show your testing pride!

    /home/dell/.rvm/rubies/ruby-2.1.2/bin/ruby -I/home/dell/.rvm/gems/
    ruby-2.1.2@tasks/gems/rspec-core-3.1.2/lib:/home/dell/.rvm/gems/
    ruby-2.1.2@tasks/gems/rspec-support-3.1.0/lib /home/dell/.rvm/
    gems/ruby-2.1.2@tasks/gems/rspec-core-3.1.2/exe/rspec
    --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```
1. PS: If this is not related to rspec-rails gem, I am very willing to move it to a new issue list (another gem).

**Comment by knightq** [comment]
Thank you all, the 

    # prevent Test::Unit's AutoRunner from executing during RSpec's rake task
   Test::Unit.run = true if defined?(Test::Unit) && Test::Unit.respond_to?(:run=)

saved my life (or at least it made it slightly better)

**Comment by paulwalker** [comment]
Using the same line in the Rakefile resolved the issues I had with some rake tasks as well.

**Comment by kris-luminar** [comment]
Thanks @batter your solution fixed this issue for me! :neckbeard:
