### ISSUE TITLE
Feature Request: Anonymous mailer

### ISSUE THREAD

**Issue by JuanitoFatas** [rspec/rspec-rails#1182]
RSpec has an [anonymous controller](https://www.relishapp.com/rspec/rspec-rails/docs/controller-specs/anonymous-controller) which comes in handy to test the "base" controller of other controllers, please see this example:
##### app/controllers/admin/base_controller.rb

``` ruby
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required

  layout 'admin'

  private

    def admin_required
      render text: 'Unauthorized', status: :unauthorized unless current_user.admin?
    end
end
```
##### spec/controllers/admin/base_controller_spec.rb

``` ruby
require 'rails_helper'

RSpec.describe Admin::BaseController, :type => :controller do
  controller do
    def index
      head :ok
    end
  end

  describe '#index' do
    def do_request
      get :index
    end

    context "as non-admin" do
      before { sign_in create(:user) }

      it 'raises error' do
        do_request
        expect(response).to have_http_status(:unauthorized)
        expect(response).not_to be_success
      end
    end

    context "as admin" do
      before { sign_in create(:user, :with_admin) }

      it 'does not raise error' do
        do_request
        expect(response).to be_success
      end
    end
  end
end
```

I use a similar structure for my mailers. 

My current implementation would need me to add a `test` to `BaseMailer` and add a corresponding view for that `test` method:

``` ruby
# base_mailer.rb
class BaseMailer < ActionMailer::Base
  default from:     'Support <support@example.com>',
          reply_to: 'Support <support@example.com>'

  def test
    mail
  end
end

# app/views/base_mailer/test.html.erb

# spec/mailers/base_mailer_spec.rb
RSpec.describe Admin::BaseController, :type => :mailer do
  describe '#test' do
    let(:email) { email_to }

    def email_to
      BaseMailer.test
    end

    it { expect(email).to deliver_from 'Support <support@example.com>' }
    it { expect(email).to reply_to     'Support <support@example.com>' }
  end
end
```

Anonymous mailer would be: Just create a method in `mailer` block and does not need to add a `test` method to `BaseMailer` and get rid of `test` view:
##### app/mailers/base_mailer.rb

``` ruby
class BaseMailer < ActionMailer::Base
  layout 'mailer'

  default from:     'Support <support@example.com>',
          reply_to: 'Support <support@example.com>',
end
```
##### spec/mailers/base_mailer_spec.rb

``` ruby
require 'rails_helper'

RSpec.describe Admin::BaseController, :type => :mailer do
  mailer do # <= Anonymous mailer!
    def test
      mail
    end
  end

  describe '#welcome' do
    let(:email) { email_to }

    def email_to
      mailer.test # <= Anonymous mailer!
    end

    it { expect(email).to deliver_from 'Support <support@example.com>' }
    it { expect(email).to     reply_to 'Support <support@example.com>' }
  end
end
```

What do you think?

P.S. This mailer testing syntax is from: https://github.com/bmabey/email-spec

**Comment by nickrivadeneira** [comment]
@JonRowe Mailers can share functionality through [observers and interceptors](http://api.rubyonrails.org/classes/ActionMailer/Base.html#class-ActionMailer::Base-label-Observing+and+Intercepting+Mails). Additionally, there is indeed a base mailer - `ApplicationMailer`.

I'd be 👍  on this feature, however I also agree that using `Class.new` can be sufficient enough given that shared mailer logic is less common than shared controller logic.
