### ISSUE TITLE
Routing specs undefined method 'message' on Ruby 2.2

### ISSUE THREAD

**Issue by nathany** [rspec/rspec-rails#1262]
When upgrading from Ruby 2.1.5 to Ruby 2.2 I see test failures in all our routing specs.

```
Failure/Error: expect(get("/time_sheets")).to route_to("time_sheet/time_sheets#day")
     NoMethodError:
       undefined method `message' for #<#<Class:0x007fa9ab213160>:0x007fa998fe2948>
```

This is using rspec-rails 3.1.0 and **Rails 4.0.12**. I tried testing against rspec-rails master but it appears to be a bit convoluted.

```
Could not find gem 'rspec-core (= 3.2.0.pre) ruby', which is required by gem 'rspec-rails (>= 0) ruby', in any of the
sources.
```

I see you are already testing against Ruby 2.2 and Travis CI is passing. Curious.

**Comment by marnen** [comment]
Note that this is not a Ruby 2.2 issue exclusively. I'm having the same problem with Rails 4.0, Ruby 2.0, and rspec-rails 2.13.

**Comment by marnen** [comment]
I'm getting the same NoMethodError on `message` as described in the OP. I'll try to point you to a usable commit.

**Comment by marnen** [comment]
I've just made the code in question available at https://github.com/marnen/quorum2/tree/route_to-error. In particular, see https://github.com/marnen/quorum2/blob/route_to-error/spec/controllers/events_controller_spec.rb#L14. This fails with Ruby 2.0, as described [above](https://github.com/rspec/rspec-rails/issues/1262#issuecomment-68941898).

This is not *too* critical for me, since I'll soon be removing the controller specs and replacing them with Cucumber stories, but it would be nice if `route_to` worked as documented.

**Comment by diazruy** [comment]
FWIW I'm seeing this same error on Ruby 2.1.5, Rails 4.0.13 and rspec-rails 2.14.2

**Comment by cupakromer** [comment]
It seems the error is specific to attempting to use the routing matchers in controller specs, not routing specs.

@diazruy is that where you see the error as well?

**Comment by diazruy** [comment]
@cupakromer I am getting this in all of my specs in `spec/routing` as of my upgrade to Rails 4. Tests were passing on 3.2.18

```
# spec/routing/agents_spec.rb

describe "routes for Agents" do
  it "routes /agents/1/bob-smith to the agent show" do
    expect(get("/agents/1/bob-smith")).to route_to(
      controller: 'property/agents',
      id: '1',
      action: 'show',
      permalink: 'bob-smith'
    )
  end
end

```

**Comment by cupakromer** [comment]
@diazruy what rspec, rails, and ruby versions specifically?

**Comment by diazruy** [comment]
@cupakromer Ruby 2.1.5, Rails 4.0.13 and rspec-rails 2.14.2

**Comment by giedriusr** [comment]
Same here, controller specs.
Rails: 4.0.13, Ruby 2.2, RSpec 3.1

**Comment by the-teacher** [comment]
Hello!

btw: @giedriusr Hello! it's me again =)

* ruby-2.2.0
* activesupport-4.0.0
* rspec 3.1.0

and I have few failed test too

```ruby
  1) PagesController routing routes to #new
     Failure/Error: expect(get("/pages/new")).to route_to("pages#new")
     NoMethodError:
       undefined method `message' for #<#<Class:0x007f86a897a8c0>:0x007f86aa820360>
     # /Users/admin/.rvm/gems/ruby-2.2.0/gems/actionpack-4.0.0/lib/action_dispatch/testing/assertions/routing.rb:171:in `method_missing'
     # /Users/admin/.rvm/gems/ruby-2.2.0/gems/actionpack-4.0.0/lib/action_dispatch/testing/assertions/routing.rb:47:in `assert_recognizes'
     # ./spec/routing/pages_routing_spec.rb:11:in `block (3 levels) in <top (required)>'
```

**Comment by giedriusr** [comment]
Hi @the-teacher :-)
Perhaps it's not an issue with 2.2 as https://github.com/rspec/rspec-rails/issues/1262#issuecomment-68941898 says, but I actually switched back to 2.1.5 until this is solved.
