### ISSUE TITLE
UnknownHttpMethod for routing specs that route all HTTP methods

### ISSUE THREAD

**Issue by dideler** [rspec/rspec-rails#1274]
_Not sure if this is an RSpec issue, opening an issue here just in case._

Some of my routing specs are suddenly failing for routes that match all HTTP methods.

```ruby
# config/routes.rb

match '/webhooks/mailgun/emails', to: 'webhooks/mailgun#emails', via: :all
```

```ruby
# spec/controllers/webhooks/mailgun_controller_spec.rb

it "routes all HTTP methods to #emails" do
  expect(all: 'webhooks/mailgun/emails').to route_to(controller: 'webhooks/mailgun', action: 'emails')
end

# Same error when using shoulda-matchers syntax
it { should route(:all, 'webhooks/mailgun/emails').to(action: :emails) }
```

Gives the failure
```
1) Webhooks::MailgunController should route ALL webhooks/mailgun/emails to/from {:action=>"emails", :controller=>"webhooks/mailgun"}
   Failure/Error: expect(all: 'webhooks/mailgun/emails').to route_to(controller: 'webhooks/mailgun', action: 'emails')
   ActionController::UnknownHttpMethod:
     ALL, accepted HTTP methods are OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE, CONNECT, PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK, VERSION-CONTROL, REPORT, CHECKOUT, CHECKIN, UNCHECKOUT, MKWORKSPACE, UPDATE, LABEL, MERGE, BASELINE-CONTROL, MKACTIVITY, ORDERPATCH, ACL, SEARCH, MKCALENDAR, and PATCH
```

I recently upgraded to Rails 4.2. Could it be caused by the new HTTP method (MKCALENDAR) added in Rails 4.2 and RSpec not taking that into consideration? https://github.com/rails/rails/pull/15121

**Comment by dideler** [comment]
I should mention that the spec passes if I test a bunch of different HTTP methods individually, e.g.
```ruby
it { should route(:get, 'webhooks/mailgun/emails').to(action: :emails) }
it { should route(:post, 'webhooks/mailgun/emails').to(action: :emails) }
it { should route(:put, 'webhooks/mailgun/emails').to(action: :emails) }
it { should route(:delete, 'webhooks/mailgun/emails').to(action: :emails) }
```

It's just when I use `:all` that the spec fails.

**Comment by cupakromer** [comment]
`all` is not a valid method as per the error message. The issue you linked to is not related. You can see in your error message that `MKCALENDAR` is listed as one of the valid messages.

Those specs pass because they use `get`, `post`, `put`, and `delete`; not `all`.

**Comment by dideler** [comment]
`all` isn't a valid HTTP method but it is a valid route option. It's used to match all verbs (see http://guides.rubyonrails.org/routing.html#http-verb-constraints). My routing tests that used `all` always passed before upgrading to Rails 4.2, so I'm not sure why they're failing now, but I'll just mark them as broken.

**Comment by JonRowe** [comment]
This is handled by Rails so it's likely they've changed the allowed routes for testing under Rails 4.2, instead you will probably find that the individual ones pass because all accepts hthem.
