### ISSUE TITLE
'no implicit conversion of Hash into String' when creating tmp folder for request specs

### ISSUE THREAD

**Issue by arturictus** [rspec/rspec-rails#1279]
we are having this issue when running request specs, making them all to fail in multiple environments:
- 3 different laptops (Mac, Linux)
- Codeship (Ubuntu)

It fails here:
/Users/[user]/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tmpdir.rb:27:in `expand_path'

When I run this code with irb all the ENV variables are strings or nil:
2.1.3 :020 > [ENV['TMPDIR'], ENV['TMP'], ENV['TEMP'], @@systmpdir, '/tmp', '.']
=> ["/var/folders/nz/qf7zdmgn0hjgcpfcnqbflcyw0000gn/T/", nil, nil, "/tmp", "/tmp", "."]

If I stop the execution when test is running in this line I get hashes

(byebug) [ENV['TMPDIR'], ENV['TMP'], ENV['TEMP'], @@systmpdir, '/tmp', '.']
[{}, {}, {}, "/tmp", "/tmp", "."]

Looks like ENV is not properly set.

gems installed:
rspec (3.0.0)
      rspec-core (~> 3.0.0)
      rspec-expectations (~> 3.0.0)
      rspec-mocks (~> 3.0.0)
    rspec-core (3.0.4)
      rspec-support (~> 3.0.0)
    rspec-expectations (3.0.4)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.0.0)
    rspec-mocks (3.0.4)
      rspec-support (~> 3.0.0)
    rspec-rails (3.0.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.0.0)
      rspec-expectations (~> 3.0.0)
      rspec-mocks (~> 3.0.0)
      rspec-support (~> 3.0.0)
    rspec-support (3.0.4)
mongoid-rspec (2.0.0.rc1)

I paste the trace in here:

 TypeError:
       no implicit conversion of Hash into String
     # /Users/arturpanach/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tmpdir.rb:28:in `expand_path'
     # /Users/arturpanach/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tmpdir.rb:28:in `block in tmpdir'
     # /Users/arturpanach/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tmpdir.rb:26:in `each'
     # /Users/arturpanach/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tmpdir.rb:26:in `tmpdir'
     # /Users/arturpanach/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tmpdir.rb:106:in `tmpdir'
     # /Users/arturpanach/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tmpdir.rb:138:in `create'
     # /Users/arturpanach/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tmpdir.rb:86:in `mktmpdir'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/firefox/profile.rb:73:in `layout_on_disk'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/firefox/launcher.rb:58:in `create_profile'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/firefox/launcher.rb:34:in `block in launch'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/firefox/socket_lock.rb:20:in `locked'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/firefox/launcher.rb:32:in `launch'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/firefox/bridge.rb:24:in `initialize'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/common/driver.rb:31:in `new'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/common/driver.rb:31:in `for'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver.rb:67:in `for'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:13:in `browser'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:45:in `visit'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/support/sign_in_macros.rb:8:in `capybara_sign_in'
     # ./spec/requests/assistant_can_use_as_traveler_spec.rb:9:in `block (3 levels) in <top (required)>'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:349:in `run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:410:in `block in run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:410:in `each'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:410:in `run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:485:in `run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:340:in `run_before_example'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:147:in `block in run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `call'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `block (2 levels) in <class:Procsy>'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-rails-3.0.2/lib/rspec/rails/adapters.rb:72:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:430:in `block (2 levels) in run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `call'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `block (2 levels) in <class:Procsy>'
     # ./spec/rails_helper.rb:39:in `block (3 levels) in <top (required)>'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/database_cleaner-1.3.0/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/database_cleaner-1.3.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `call'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:38:in `block (2 levels) in <top (required)>'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:430:in `block (2 levels) in run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `call'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `block (2 levels) in <class:Procsy>'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:432:in `run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:485:in `run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:303:in `with_around_example_hooks'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:145:in `run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:494:in `block in run_examples'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:490:in `map'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:490:in `run_examples'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:457:in `run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `block in run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `map'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `block (2 levels) in run_specs'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `map'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `block in run_specs'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/reporter.rb:54:in `report'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:108:in `run_specs'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:86:in `run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/gems/rspec-core-3.0.4/exe/rspec:4:in `<top (required)>'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/bin/rspec:23:in `load'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/bin/rspec:23:in `<main>'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/bin/ruby_executable_hooks:15:in `eval'
     # /Users/arturpanach/.rvm/gems/ruby-2.1.3@quality/bin/ruby_executable_hooks:15:in `<main>'

**Comment by cupakromer** [comment]
I don't see this as an rspec issue. The top of your stack trace is from Selenium, Capybara, and your custom file: `./spec/support/sign_in_macros.rb:8:in capybara_sign_in'`.

rspec-rails does not do anything to modify your environment. We add the line `ENV['RAILS_ENV'] ||= 'test'` in the `spec/rails_helper.rb` file but you can always adjust that.

**Comment by cupakromer** [comment]
I suggest checking your Rails initializers too. Someone may have adjusted the ENV there.

**Comment by arturictus** [comment]
You are right, I was mocking ENV in certain test. It was spreading to multiple test in random way (that made harder to find the reason). I suppose because of the random test execution of them. 

That was my mocking:
shared_context 'set_env_for_something' do		
-  before do		
-    allow(ENV).to receive(:[]).and_return({})		
-    allow(ENV).to receive(:[]).with('some_key').and_return('some_value')				
-  end		
-end

Do the mocking should not spread to all tests?

Thanks for your help

**Comment by cupakromer** [comment]
That will apply to all specs where that shared context is loaded. It should be clean up after each spec.

**Comment by myronmarston** [comment]
@cupakromer is right; it should only spread to tests that have included the shared context.  It is possible there's some bug causing it to "leak" to other tests but we'd need an reproducible example to dig into that.

Regardless, my suggestion is to not stub `ENV` at all.  There are a few issues with stubbing it like you have:

* `ENV` values are strings, but you've stubbed it to return a blank hash as the default key.  It's easy to make that kind of mistake when you stub it.
* Things in ruby, the stdlib and some gems depend upon certain ENV values and it's hard to know what ENV entries they depend on.  When you mock ENV, you risk breaking them.
* When you stub `ENV` you are treating `ENV` as a hash but `ENV` is NOT a hash (it's simply hash-like -- see http://www.ruby-doc.org/core-2.2.0/ENV.html) and doesn't act exactly like hash in every way.  When you stub it based on how a hash works you run the risk of subtlety changing the behavior of `ENV` since it's not a hash.
* Stubbing `ENV.[]` assumes that you are going to access your key via the `[]` method but there are other ways to access it (e.g. `ENV.fetch('SOME_KEY')`) and your stubbing doesn't support that. Thus, your stubbing is more tightly coupled to the implementation and it makes your specs your brittle.

Instead, I would recommend defining a helper method that makes it easy to safely mutate ENV for particular specs:

``` ruby
module EnvHelpers
  def with_env_vars(vars)
    original = ENV.to_hash
    vars.each { |k, v| ENV[k] = v }

    begin
      yield
    ensure
      ENV.replace(original)
    end
  end
end

RSpec.configure do |c|
  c.include EnvHelpers
end
```

Then in any spec you can use this:

``` ruby
it 'does something with the FOO environment variable' do
  with_env_vars 'FOO' => 'bar' do
    # logic that depends upon ENV['FOO'] goes here
  end
end
```

**Comment by arturictus** [comment]
@myronmarston Thanks, that looks great.!!
I fix it adding to the rails_helper the ENV variables:
```ruby
config.before :all do
    ENV['my_key'] = 'my_value'
 end
```
I'll try to reproduce de error in an open project to check how it leaks to specs not in the context.

**Comment by myronmarston** [comment]
First off, `config.before(:all)` will run more than once -- it will run once per top level example group.  It's slightly confusing (as `:all` would make you think it would run once before all specs in the entire suite), but it really just adds a `before(:all)` hook to every top-level example group.  If you want a global hook that runs only once, use `before(:suite)` -- that runs once before any examples run, and then `after(:suite)` runs at the end after all examples are complete.  The confusion about `config.before(:all)` is what caused us to introduce `:context` and `:example` in RSpec 3 as aliases for `:all` and `:each` hooks -- `config.before(:context)` is much clearer.

All that's to say that you probably want to assign `ENV['my_key']` in a `before(:suite)` hook, or consider setting it directly in `spec_helper` (without being in a hook at all) as there's really no need to wait until the entire suite loads before setting it.

I'd still encourage you to use the helper method I pasted above over your `EnvVarMacros` as stubbing ENV is brittle for reasons outlined above, and I see no benefits to stubbing over my solution that simply temporarily mutates ENV.

**Comment by arturictus** [comment]
@myronmarston 
I've done a gem following your advice.
Thanks.
https://github.com/arturictus/env_test_helpers
