### ISSUE TITLE
Wrong index method name when generating integration_test

### ISSUE THREAD

**Issue by carlesjove** [rspec/rspec-rails#1287]
Hello. I'm not sure if this is a bug or if it's due to something on my side, but when I generate an `integration_test` the example that is generated has a `[resource name here]_index_path`, which is a non existent method, since and `index` route is called with `[resource name]_path`.

I'm don't use Rspec that often, so before making a PR I want to make sure this is a bug and not the expected behaviour.

Cheers

**Comment by cupakromer** [comment]
What command did you use? It looks like the behavior you describe happens if you give it a plural name (or one that Rails can't find in the routes). Otherwise it should generate it properly.

**Comment by carlesjove** [comment]
That must be why. I usually generate the specs files _before_ creating the routes or anything else, and I might have used the plural name. Something in the lines of `$ rails g integration_test expenses`.

Feel free to close the issue. Thank you!
