### ISSUE TITLE
Conflict of rspec (3.1) default and rails (4.2) .gitignore causes load issues

### ISSUE THREAD

**Issue by hugocorbucci** [rspec/rspec-rails#1288]
I've just run into this silly problem where my .rspec specified ```--require rails_helper``` but my .gitignore included the .rspec file. As a result, my local spec runs would pass but my CI spec runs would fail with an error saying it couldn't load my model classes.

Any way rspec-rails could either change the default require for rspec or ensure the .rspec file is not ignored or change the spec rake task to require the rails_helper by default?

**Comment by myronmarston** [comment]
We don't auto-require anything by default.  `spec_helper` and `rails_helper` are just standard conventions for how to organize things (and thus a good starting point from generated files).  It's entirely up to you how you want to manage that (e.g. by putting requires at the top of each file, or having a `--require` option in `.rspec`, or some other way).  Given that we don't want to force these things on users and we also don't want to couple ourselves to git (which any .gitignore logic would do), I don't think there's anything we can or should do about this.

Note that we do _not_ recommend gitignoring `.rspec`.  That file is intended to be under source control.  A developer's personal project preferences can go in a git-ignored `.rspec-local` file.

**Comment by hugocorbucci** [comment]
Gotcha. So it's my mistake. Each of my spec files should be requiring rails_helper if they are rails dependent files. Makes sense.

Adjusted my .rspec as well.

Thank you.
