### ISSUE TITLE
Minor update on website doc

### ISSUE THREAD

**Issue by oliveiraethales** [rspec/rspec-rails#1290]
Helloez! Dunno if this should be created here, but didn't find another place. (:

In the website, at the [directory structure section](https://relishapp.com/rspec/rspec-rails/v/3-1/docs/directory-structure), it is written: `Request specs reside in the spec/requests directory`. I believe it should be improved to something like: `Request specs reside in the spec/requests directory. The directory can also be named 'integration' or 'api'`. The repo readme/doc is already like this, so this minor update is only needed on the website. (:
Would happily provide a PR if it is possible, otherwise, let this be just a reminder for the person that will update the website. :D

Cheers!

**Comment by cupakromer** [comment]
@oliveiraethales thanks for noticing that. Feel free to submit a PR for this. I'm happy to accept it. Cheers!

**Comment by soulcutter** [comment]
Would be a nice addition. :sparkles:

**Comment by oliveiraethales** [comment]
Hey guys, here it is: https://github.com/rspec/rspec-rails/pull/1293

:3 :heartbeat:

**Comment by cupakromer** [comment]
Great thanks! :blue_heart:
