### ISSUE TITLE
Big spec file

### ISSUE THREAD

**Issue by nicolas-besnard** [rspec/rspec-rails#1296]
Has my application grow, the spec on my controller become heavy. I thought about creating one file by action. I'll end with the architecture :

specs/controller/api/users/index_spec.rb
specs/controller/api/users/create_spec.rb
...

Do you think it's a good idea ?

**Comment by JonRowe** [comment]
It's up to you how you feel you should structure your tests, the way you suggest will cause you no issues. However Github issues are not the place to ask this sort of advice, in future please use the irc channel (#rspec on freenode) or the mailing list / google group (https://groups.google.com/forum/#!forum/rspec)

**Comment by myronmarston** [comment]
If your logic is so complicated that it requires a very large spec file, it may be telling you something about the complexity of your implementation and suggesting that you should perhaps refactor it to be composed of multiple smaller pieces.
