### ISSUE TITLE
Can no longer test for focused specs in 3.2.0

### ISSUE THREAD

**Issue by dankohn** [rspec/rspec-rails#1300]
I've been using the following test in spec_helper.rb to have tests fail on our continuous integration machines if focus has been set:
```ruby
  config.before(:suite) do
    next unless config.filter_run
                .is_a?(Hash) && config.filter_run[:focus] && ENV['CI']
    fail 'Don\'t commit focused specs.'
  end
```
This works correctly with rspec-rails 3.1.0 but in 3.2.0 `config.filter_run[:focus]` is always set to `true` and so my tests can never run. How can I test whether focus has been set?

**Comment by myronmarston** [comment]
> but in 3.2.0 `config.filter_run[:focus]` is always set to `true`

AFAIK, we didn't change anything about filtering (or default filters) in 3.2.  I just spun up a fresh project to check and indeed, `filter_run[:focus]` is _not_ `true` in a fresh project using `rspec` 3.2.  It's probably something in your environment setting it.

All that said, I don't think that snippet does what you want:

* `config.filter_run` is a method used to _set_ filters.  It doesn't have a meaningful return value.  Here are our docs on that method: http://rspec.info/documentation/3.2/rspec-core/RSpec/Core/Configuration.html#filter_run_including-instance_method
* `config.inclusion_filter` returns the filters that have been set, and is probably what you meant to use. (Docs here: http://rspec.info/documentation/3.2/rspec-core/RSpec/Core/Configuration.html#inclusion_filter-instance_method)
* All that said, checking `inclusion_filter` only checks to see if a `:focus` filter has been set; it tells you nothing about if any specs have been committed with `:focus` metadata which I think would be what you want.

I'd probably deal with this with something like:

``` ruby
RSpec.configure do |config|
  config.before(:example, :focus) do
    raise "This example was committed with `:focus` and should not have been"
  end if ENV['CI']
end
```

**Comment by dankohn** [comment]
I'm not sure what's special about my environment, but I can confirm that only changing the rspec-rails version caused the error.

In any event, your proposal works flawlessly. I really appreciate it, and especially the super quick turnaround.

**Comment by myronmarston** [comment]
> I'm not sure what's special about my environment, but I can confirm that only changing the rspec-rails version caused the error.

Weird.  Can you put together a reproducible example?  It does sounds like you may have run into a regression, but I can't repro, so I can't solve it with out an example...

**Comment by dankohn** [comment]
I would, but I believe I was using `config.filter_run[:focus]` incorrectly, and your code makes much more sense, so I don't think we should worry about. Thanks again.
