### ISSUE TITLE
When url_for is called in a view spec with `:use_route` an error is raised

### ISSUE THREAD

**Issue by jcoyne** [rspec/rspec-rails#1302]
Backtrace: https://gist.github.com/jcoyne/e21f2f3d07b1025e6692

**Comment by cupakromer** [comment]
View specs are sort of a hybrid but rely on some "functional" test style setup. Can you please provide more details on how the spec which causes this stack trace is setup?

Is this a view spec for an engine? Or are you attempting to reference a mounted engine's route from a base app? Or is this a test dummy app inside the engine itself?

Please note that Rails 4.2 has deprecated `:use_route` and it is now [removed from `master`](https://github.com/rails/rails/blob/e4cfd353a47369dd32198b0e67b8cbb2f9a1c548/actionpack/CHANGELOG.md).

**Comment by jcoyne** [comment]
Here's the spec: 
```ruby
require 'spec_helper'

describe 'collections/_thumbnail_default.html.erb' do
  let(:document) { SolrDocument.new :id => 'xyz', :format => 'a', :thumbnail_url => 'http://localhost/logo.png' }
  let :blacklight_config do
    Blacklight::Configuration.new do |config|
      config.index.thumbnail_field = :thumbnail_url
    end
  end

  before do
    assign :response, double(:params => {})
    allow(view).to receive(:blacklight_config).and_return(blacklight_config)
    allow(view).to receive(:render_grouped_response?).and_return(false)
    allow(view).to receive(:current_search_session).and_return nil
    allow(view).to receive(:search_session).and_return({})
    render 'collections/thumbnail_default', document: document, document_counter: 1
  end

  it "renders a thumbnail" do
    expect(rendered).to have_selector 'div.document-thumbnail a img[src="http://localhost/logo.png"]'
  end
end
```

**Comment by jcoyne** [comment]
The test covers some functionality provided by a mounted engine. Here's the part in the mounted engine that seems to trigger the issue:

https://github.com/projectblacklight/blacklight/blob/master/app/helpers/blacklight/url_helper_behavior.rb#L85

It is not using `:use_route` only actiondispatch/actionview are.

**Comment by samphippen** [comment]
@jcoyne is this still an issue for you? If so, could you send us a full rails app we can clone with some instructions on how to reproduce the issue. I appreciate you providing a spec, but it references a couple of top level constants that aren't clear to me how to set up, and a full app would clear that up. Thanks 👍

**Comment by jcoyne** [comment]
This was so long ago... we must have figured out some way that we worked around it. Thanks.
