### ISSUE TITLE
rspec-rails 3.2 with Rails 4.2 causes deprecation warnings on failed matchers

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-rails#1306]
## Issue

> **Note:** This issue does not happen with other rspec-rails + Rails version combinations.

The issue was first noticed when using composable matchers to verify a response object. When the expectation failed the following deprecation warning was written by Rails:

```
DEPRECATION WARNING: `ActionDispatch::Response#to_ary` no longer performs implicit
conversion to an array. Please use `response.to_a` instead, or a splat like `status,
headers, body = *response`. (called from flatten at /path/to/a/thing_spec.rb:4)
```
## Steps to Reproduce

This is easily reproduced in any `controller` or `request` spec which has a `response` object of type: `ActionDispatch::Response`. In fact the issue can happen outside of composable matchers.

To reproduce, simply perform a `get` to a valid path then run:

``` ruby
[response].flatten
```
## Root Cause

The reason this happens is with the improvements with composable matchers in: rspec/rspec-expectations#713

It just so happens that having a response object with a composed diffable matcher sends the code path into the [following](https://github.com/rspec/rspec-support/blob/v3.2.0/lib/rspec/support/differ.rb#L131):

``` ruby
array = array.flatten(1) until (array == array.flatten(1))
```

When the contents of the array include an `ActionDispatch::Response` object, Ruby's `flatten` method checks to see if it responds to `to_ary`; Ruby's implicit "this thing is an array" converter message. Only objects that respond to this method are then attempted to be flattened again by having `to_ary` called on them, performing the check on the returned array elements.

This is disappointing behavior on the part of `ActionDispatch::Response` as that object really is not an array. This history is a bit more complicated though, as Rails is a Rack app, and Rack responses are array triplets. So it does make sense to a degree why this came about. However, splat and `to_a` work on the response object so the implicit `to_ary` is not necessary. I'm glad to see this is being deprecated / removed and the response object being treated as just that, an object.

_**Q.E.D This is not the fault of RSpec or something that is easily avoided.**_
## Workarounds

Unknown at this time - outside of disabling deprecations warnings in Rails.
## Solution

Unknown at this time.

Attempting to wrap `ActionDispatch::Response` objects with a custom wrapper seems not only a very invasive code change, but prone to many problems. I'd hate to break someone's code as we've changed the contract from under them by removing `to_ary` even though it shouldn't be relied on.

Attempting to `undef`, while being easier on rspec-rails' part, has the same code breaking potential.

**Comment by cupakromer** [comment]
More just documenting this for others who may come across it. It certainly was a head scratcher for me when it first appeared.

**Comment by myronmarston** [comment]
One hacky solution is for rspec-rails to redefine `RSpec::Support::Differ#safely_flatten`, and put logic that avoids calling `flatten` on an array of `ActionDispatch::Response`.

Not pretty, but seems potentially better.

**Comment by pirj** [comment]
I might be missing something, but wouldn't the build job fail if there was something on stderr?
Can't find any `DEPRECATION` message in e.g. [this build](https://travis-ci.org/github/rspec/rspec-rails/jobs/663477686).

Closing as chances are this is not an issue anymore.
