### ISSUE TITLE
invalid option: --format

### ISSUE THREAD

**Issue by askuratovsky** [rspec/rspec-rails#1312]
```bash
$ rspec spec --format documentation
... test results
invalid option: --format
Usage: ...
```
Why rspec warn me about this option? Test results printed exactly in this format "documentation", but with this warning and usage.
```bash
 $ bundle show | grep rspec
  * rspec-core (3.2.0)
  * rspec-expectations (3.2.0)
  * rspec-mocks (3.2.0)
  * rspec-rails (3.2.0)
  * rspec-support (3.2.1)
```
This option is in the official documentation. https://relishapp.com/rspec/rspec-core/v/3-2/docs/command-line/format-option

**Comment by cupakromer** [comment]
@askuratovsky is the usage about minitest (you haven't included what command it is complaining about)?

What rails and ruby versions are you using? This was an issue in the past but should have been fixed in the 3.2 release.

**Comment by askuratovsky** [comment]
If you speak about gem minitest, no i don't use it.
ruby 2.1.5p273
rails 3.2.21

**Comment by cupakromer** [comment]
Are you using the test unit gem?

**Comment by askuratovsky** [comment]
Yes. After uninstalling gem test-unit the problem gone. There is a conflict with gem test-unit?
Anyway, thank you!

**Comment by myronmarston** [comment]
> There is a conflict with gem test-unit?

You can use test-unit's assertions module with RSpec but you can't load test-unit's test runner and RSpec's test runner in the same process.  In this case, test-unit's test runner was also trying to parse CLI args and was complaining about not understanding the `--format` arg.  We have no control over other test runners that try to parse CLI args and blow up with errors when you use RSpec-specific options, so the only solution is to stop loading the other test runner.

**Comment by cupakromer** [comment]
Out of curiosity what was the version of the `test-unit` gem you are using?

**Comment by askuratovsky** [comment]
> Out of curiosity what was the version of the test-unit gem you are using?

-    test-unit (3.0.8)

**Comment by cupakromer** [comment]
Thanks that helps. I disabled the auto runner for Ruby 2.2+ b/c the test-unit or minitest gems are now required for your Rails version. However, older Ruby versions include a test-unit out of the box. I'll add the single line of code to handle the test-unit gem's changes. :heart:
