### ISSUE TITLE
3.1.0 -> 3.2.0 breaks url generation

### ISSUE THREAD

**Issue by 97jaz** [rspec/rspec-rails#1313]
When I updated from rspec-rails 3.1.0 to 3.2.0, url generation (as in, `url_for`) broke. I get errors like:
```
ActionView::Template::Error: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
from /[...]/[...]/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/http/url.rb:45:in `full_url_for'
```

I am not setting default_url_options. I could do so, but the point is that the code works fine with the previous version of rspec-rails, and it breaks with the new one.

**Comment by 97jaz** [comment]
A very important point I forgot to mention: I get these errors, not only in tests, but in normal, interactive use in my development environment. (rspec-rails is included in both the development and test gem groups, per the installation instructions.)

**Comment by cupakromer** [comment]
I haven't experience this issue on any of my projects which use Rails 4.2 and RSpec 3.2. That error comes from inside Rails; rspec-rails doesn't modify that class, nor that method. If you remove `rspec-rails` from the development group, do you still see the problem in interactive use?

Can you share the repository or provide a simple one which replicates the issue?

**Comment by 97jaz** [comment]
That's the thing. If I revert to rspec-rails 3.1, the problem goes away completely, so it's definitely caused by rspec-rails or one of its dependencies.

**Comment by 97jaz** [comment]
Sorry -- the repo is private; it's my employer's product, and, unsurprisingly, it's rather large, so it may be difficult to produce a minimal example that exhibits the issue. Based on the behavior I'm seeing, I just assumed that rspec-rails was insinuating itself inside the URL-generation code. If that's not the case, this is rather mysterious.

**Comment by cupakromer** [comment]
Can you share the line of code which causes the problem? Are you calling a specific URL generator or passing some sort of specific options to it?

**Comment by cupakromer** [comment]
I skimmed the diff (https://github.com/rspec/rspec-rails/compare/v3.1.0...v3.2.0) and didn't see anything that looks like it would be related.

Was the only different in the `Gemfile.lock` the rspec libs or were more libs updated?

**Comment by seuros** [comment]
I think s/he upgrading between rails 4.1 and 4.2 too.

**Comment by 97jaz** [comment]
It happens in a bunch of places. The specific example that I included in the issue actually comes from Devise, here: [https://github.com/plataformatec/devise/blob/v3.4.1/app/views/devise/mailer/reset_password_instructions.html.erb#L5].

However, the same error occurs (frequently) in a helper in our application. The offending line is:
```ruby
authenticated_redirect_url(token.encoded_payload)
```
...where `authenticated_redirect_url` refers to a line in `/config/routes` that looks like:
```ruby
get "/link/:encoded_payload" => "authenticated_links#authenticate_and_redirect", :as => "authenticated_redirect", :constraints => { :encoded_payload => /[^\/]+/  }
```

In both cases, it's trying to build a URL based on a route, and it complains that it doesn't know what host to use. 

As for the changes: originally, I upgraded rspec-rails while removing guard (I did this, because no one on our team was using guard, and there were some version dependency issues.) It occurred to me that removing guard might have been responsible for the change, so I created another branch where I *only* removed guard and did not upgrade rspec-rails. That branch did not exhibit the problem.

@seuros No, I am not upgrading rails at the same time.

**Comment by cupakromer** [comment]
Can you shared the diff of your `Gemfile.lock` between the "good" and "bad" commits?

**Comment by 97jaz** [comment]
@cupakromer sure: https://gist.github.com/97jaz/4fda96b4dd7033c290cd

As I mentioned, this diff includes the removal of guard-related gems, too. But I did test a branch where only the guard-related gems were removed, and the problem did not occur.

I'll also try to create a branch that keeps the guard gems and upgrades rspec-rails, just to be sure.

**Comment by 97jaz** [comment]
Yeah, okay, I just created a new branch in which I upgraded rspec-rails from 3.1.0 => 3.2.0 and upgraded guard-rspec as well (since the dependencies wouldn't be met otherwise). This branch also exhibits the problem. The Gemfile.loc diff is here: https://gist.github.com/97jaz/8db1a6bf100a402c22ab

**Comment by 97jaz** [comment]
Just so you know, the *only* changes in this latest branch are in `Gemfile`, `Gemfile.lock`, and `vendor/cache/...`.

**Comment by cupakromer** [comment]
Any idea why this gem was downgraded?

```diff
-    wbix-client (0.0.6)
+    wbix-client (0.0.3)
```

Since I can't find it on rubygems I'm guessing it's a private gem.

**Comment by 97jaz** [comment]
`wbix-client` is one of our gems, and no, that really shouldn't have been downgraded. However, it didn't change in the second diff.

**Comment by cupakromer** [comment]
Just to rule it out, be sure to stop spring, guard, and any other preloaders. Also for local stuff stop the rails server / touch `tmp/restart.txt`. Just to make sure we have all the newer gems properly loaded in the Rails server.

Can you create a single simple spec which exhibits the issue and then run it from the command line adding the `--backtrace` flag?

If it's related to what you linked earlier, this sample spec should generate your error:

```ruby
require "rails_helper"

RSpec.describe Devise::PasswordsController, type: :controller do
  include Devise::TestHelpers

  it "cause a Missing host error" do
    @request.env["devise.mapping"] = Devise.mappings[:user]
    expect(
      controller.edit_password_url(User.new, reset_password_token: 'test')
    ).to eq "http://test.host/users/password/edit?reset_password_token=test"
  end
end
```

**Comment by cupakromer** [comment]
The error you originally logged _should_ be caused by something not getting set properly. Normally Rails grabs the host from the request sent to the server. This way it is flexible to respond the same way even if you move the server to a new machine, change the DNS name, or use the direct IP.

The error tells me that nothing was set. Generally, if this is not set or defined, then the call chain falls back on whatever the current `routes` scope has configured. By default it has nothing configured for `:host` and the value is `nil`. Both rspec-rails and capybara set this up internally to prevent this from happening. It is also possible for you to set it directly in some cases or set it in an environment or initializer file. Rails TestCase call chain does the same thing.

See #1275 for a related issue with more details about that setting.

**Comment by cupakromer** [comment]
Having said all that, I still don't see anything in the diff from 3.1.0 to 3.2.0 that is related.

**Comment by 97jaz** [comment]
That test passed; however, I'm not sure if it attempted to create the email message (which is where the url is generated). At least, I think I would normally see that in the test log, and I don't in this case.

**Comment by 97jaz** [comment]
Yeah, I should have mentioned: not all route urls fail. In fact, all of the failures seem to be in the context of ActionMailer, though you have to climb the stack quite a ways to get into ActionMailer code. For example: https://gist.github.com/97jaz/70d5b3b31f93cb06b5fc.

Now, we *do* set default_url_options specifically for ActionMailer in an initializer:
```ruby
  config.action_mailer.default_url_options = {
    host: CFG["APP_HOST"],
    port: CFG["APP_PORT"],
    protocol: CFG["APP_URL_SCHEME"]
  }
```
What's more, I've already checked: these *are* set when the tests run. I added some code to print out these values in a failing example:

```ruby
  it "sends emails only to subscribed users in the correct timezone" do
    Timecop.freeze(daily_job_time) do
      p Rails.application.config.action_mailer.default_url_options
      DailyEmailJob.enqueue_batch
    end

    expect(email_for(subscribed_account.email).size).to eq 1
    expect(email_for(unsubscribed_account.email).size).to eq 0
    expect(email_for(different_timezone_account.email).size).to eq 0
  end
```

The output includes: `{:host=>"localhost", :port=>"3000", :protocol=>"http"}`.

So, it's as if these values are no longer being used, for some reason. But really, nothing has changed except what you see in the Gemfile.lock diff. I don't know what to make of it.

I can make tests pass if I add a similar configuration for `routes.default_url_options` (which we do not normally set). So what I'm wondering is if the action mailer config isn't being used, and the route config is being used in its place, for some reason.

**Comment by 97jaz** [comment]
Okay, I've pretty much figured it out. I added these two lines to the top of my `config/initializers/action_mailer.rb` (which is where I set ActionMailer's `default_url_options`):
```ruby
ActiveSupport.on_load(:action_mailer) { puts "action_mailer loaded" }
puts "in action_mailer initializer"
```

When I run this with rspec-rails 3.1.0, I see:
```
in action_mailer initializer
action_mailer loaded
```
but with 3.2.0, the order is reversed. This indicates that rspec-rails 3.2.0 is causing ActionMailer to be loaded earlier than it was before. Consequently, when the initializer runs, it's too late to affect the configuration (by that time, the railtie has already made use of the configuration options [https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/railtie.rb#L41]).

I wonder if this change is a consequence of rspec-rails 3.2.0 trying to set the mailer preview path (though it's not obvious to me why this would cause ActionMailer to be loaded earlier).

**Comment by 97jaz** [comment]
Yes, and I just verified that if I move the configuration of ActionMailer's `default_url_options` to `application.rb` (rather than doing it in an initializer), the problem does not occur. So it's definitely a loading order issue.

**Comment by cupakromer** [comment]
Thanks for that great debugging info :heart: We _did_ add somethings specifically for `ActionMailer`. So that is likely related. I will look into it further.

**Comment by cupakromer** [comment]
> I wonder if this change is a consequence of rspec-rails 3.2.0 trying to set the mailer preview path (though it's not obvious to me why this would cause ActionMailer to be loaded earlier).

Yes, it is directly related. Part of that is this check: `if ::RSpec::Rails::FeatureCheck.has_action_mailer_preview?`. That is basically just `if defined?(::ActionMailer::Preview)`. When `defined?` is called in Ruby if the constant is not defined, Ruby attempts to lookup if it can be defined, such as with `autoload`. This is what causes the class to get loaded early.

**Comment by cupakromer** [comment]
Based on some testing I would advise you to not set `ActionMailer` options in an initializer via a `Rails.application.configure do` block. That should only be done from the environments file or the application file directly. The reason I say this is because you do not control the load order of the initializers. If another one happens to load the constant your initializer will have the same problem.

From what I have found if you want to use an initializer then you should define things on the `ActionMailer` object itself:

```ruby
ActionMailer::Base.smtp_settings = {
  :address              => "smtp.gmail.com",
  :port                 => 587,
  :domain               => "test.com",
  :authentication       => "plain",
  :enable_starttls_auto => true
}

ActionMailer::Base.default_url_options[:host] = "localhost:3000"
```

With that warning being stated, there is something rspec-rails can do to not be the source of your issue. I will submit a PR shortly.

**Comment by dbslone** [comment]
I experienced the same issue and found that using 

`Rails.application.routes.default_url_options[:host] = 'localhost:5000'`

and in my spec files changing `root_url` to `root_path` solved the issue. For some reason `root_url` yields the host: `test.host` but `root_path` will return localhost:5000.

**Comment by kntmrkm** [comment]
In my environment.

3.1.0 can see Mailer Preview.
but 
3.2.0, 3.2.1 can not see Mailer Preview.
（http://localhost:3000/rails/mailers）

this problem is related the issue?

**Comment by cupakromer** [comment]
> this problem is related the issue?

Likely not, did you set the path to your mailers in your environments file?

**Comment by kntmrkm** [comment]
I have set path like below.

config/environments/development.rb
`config.action_mailer.default_url_options = { host: "localhost:3000" }`

but, Preview does not show yet.

Current environment setting works well for 3.1.0.
I changed just version of rspec-rails.

I think this is a issue of rspec-rails.

**Comment by cupakromer** [comment]
@kntmrkm you need to set the preview path:

```
config.action_mailer.preview_path = 'path/to/your/previews'
```

I think I see the problem though. RSpec didn't have preview path support before. However, if you created previews they were put in the "test" location. I'm guessing your existing preview path is the `test/mailers/previews` location.

I guess we could check to see if that path exists and has content. If so, use it instead of the RSpec path.

**Comment by kntmrkm** [comment]
OK I got it. It works.

Thanks!

Rspec 3.2.0 can set a preview path wherever I like. right?
but, rspec does not check default rails preview path.

**Comment by cupakromer** [comment]
> Rspec 3.2.0 can set a preview path wherever I like. right?
> but, rspec does not check default rails preview path.

Correct. Currently, if an explicit path has not been set by the project we set one to the `spec/mailers/previews` path. We shim in front of the test unit call which sets it to `test/mailers/previews` if it hasn't been set. However, we did miss the case where a project already has previews in the `test/` location.
