### ISSUE TITLE
modify default pattern for rspec path

### ISSUE THREAD

**Issue by wendy0402** [rspec/rspec-rails#1316]
I have rails application with several engines inside it, and put the spec files in each engines folder. To run the rspec i need to run this command
```
rspec --pattern 'spec/**/*_spec.rb, engines/**/*_spec.rb'
```

is there a way to add this pattern by default so I only need to run `rspec` only?

thanks

**Comment by cupakromer** [comment]
You can add that to your `.rspec` or `.rspec-local`. See http://www.relishapp.com/rspec/rspec-core/v/3-2/docs/configuration/read-command-line-configuration-options-from-files
