### ISSUE TITLE
Action Mailer preview_path warning

### ISSUE THREAD

**Issue by kamen-hursev** [rspec/rspec-rails#1325]
Is it really necessary to output a warning: 'Action Mailer `preview_path` is not the RSpec default.' when the preview_path is changed to something different than its default value?

**Comment by cupakromer** [comment]
This is being removed, is part of a PR that will be submitted later today

**Comment by kamen-hursev** [comment]
Great, thanks! :smile:

**Comment by cupakromer** [comment]
Closing per #1327
