### ISSUE TITLE
Custom route constraint is ignored when defining routes in spec

### ISSUE THREAD

**Issue by seanknox** [rspec/rspec-rails#1328]
I have a spec that defines a route with a custom constraint for an anonymous controller. It's called as a shared example:

```ruby
RSpec.shared_examples 'an Admin page' do
  controller do
    def custom
      render nothing: true
    end
  end

  before do
    this_controller = controller
    routes.draw do
      constraints Constraints::AdminCheck.new do
        get 'custom' => "#{this_controller.controller_path}#custom"
      end
    end
  end

  # fails because routing constraint Constraints::AdminOnly isn't called
  context 'with a normal user logged in' do
    login_normal_user
    it { expect(get :custom).to redirect_to('/') }
  end
end
```
The actual constraint class is in use and works with routing and other controller specs. However in this case, the constraint class `Constraints::AdminOnly` is never actually invoked. Is there something I'm missing

**Comment by cupakromer** [comment]
Controller specs do not go through the request routing phase as a normal web request does. The purpose of controller specs is to test your controller behavior, not the router. The router is simply used to verify that there is a route to the specific action. At the end of the day, controller specs are really just a thin shim on top of `ActionController::TestCase`.

Based on your shared example, it looks like you are trying to test your constraint class and/or the Rails router, not the controller. Anonymous controllers are intended to be used to test shared controller behavior for classes such as `ApplicationController`.

I would just write a normal RSpec style spec to test the constraint class. You can create a test request class from Rails or Rack to pass to the constraint's `matches?` method.

If you wish to test the router as well, I suggest looking into [`request`](https://www.relishapp.com/rspec/rspec-rails/v/3-2/docs/request-specs/request-spec) and [`feature`](https://www.relishapp.com/rspec/rspec-rails/v/3-2/docs/feature-specs/feature-spec) specs. Those will require a real controller and route in `config/routes.rb` though.

**Comment by seanknox** [comment]
That makes sense. Now my routing specs test access/no access to a particular route based on the constraint. I removed notions of access from the controllers that are now handled by the constraint. Thanks!
