### ISSUE TITLE
3.2.1 breaks scaffold generation

### ISSUE THREAD

**Issue by sideshowbandana** [rspec/rspec-rails#1331]
The removal of example_invalid_attributes in https://github.com/rspec/rspec-rails/commit/98a2a70f3174ce0db739aace08719d0d43e1e7a2 causes scaffold generation to fail with this exception: https://gist.github.com/sideshowbandana/66fe0d3a735c11c16ae5

Steps to reproduce:
gem install rspec-rails -v 3.2.1
rails g scaffold foo

**Comment by cupakromer** [comment]
@sideshowbandana I am not able to reproduce your issue. I've tried with Rails 3.2 and 4.2. Here is my output with Rails 4.2 (https://gist.github.com/cupakromer/17d3043ce865001d3315)

What are your Rails and Ruby versions?

**Comment by cupakromer** [comment]
I notice you are using Rails 4.2 with slim. I added slim and still can't reproduce. I've updated my gist with it's output as well. These were the gems installed when I added slim:

- temple 0.7.5
- slim 3.0.2
- slim-rails 3.0.1 

Which version of slim are you using?

**Comment by sideshowbandana** [comment]
Hey, thanks for getting back to me.
* slim (3.0.2)
* slim-rails (3.0.1)
* ruby-2.0.0-p247
* rails (4.2.0)
* rspec (3.2.0)
  * rspec-core (3.2.1)
  * rspec-expectations (3.2.0)
  * rspec-html-matchers (0.7.0)
  * rspec-mocks (3.2.1)
  * rspec-rails (3.2.1)
  * rspec-support (3.2.2)

**Comment by sideshowbandana** [comment]
Ah, I think it's actually user error. It's using lib/templates/rspec/scaffold/controller_spec.rb to generate the new scaffold. However, that file was created when using an older version of rspec. I removed the template and it works like a charm.

**Comment by JonRowe** [comment]
Closed then :)
