### ISSUE TITLE
Update documentation for job specs

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-rails#1335]
We are missing both README, rdoc, and cuke feature based documentation of the new job specs.

**Comment by cupakromer** [comment]
We should be sure to include any new matchers in those docs (#1334).

/cc @seuros for any ideas

**Comment by seuros** [comment]
Right. I will free some time to do this.

**Comment by samphippen** [comment]
@seuros I know it's been a little while, but is this still something you'd be interested in looking at?

**Comment by benoittgt** [comment]
Is it still needed? I would like to give a try.

**Comment by contrepoint** [comment]
am working on the readme for this. then I'll get to rdoc.

Googling brings up `Cucumber` as a first result but I'd like to clarify what `cuke` refers to - could someone help, please? Thank you.

**Comment by samphippen** [comment]
Hi Friends. We use https://relishapp.com/rspec/rspec-rails/docs for our documentation. These are autogenerated from cucumber features ([example](https://github.com/rspec/rspec-rails/blob/master/features/controller_specs/anonymous_controller.feature)). This task is to create some .feature files for job specs.

**Comment by sgerrand** [comment]
👋  @samphippen: I'm working on this now, should have a PR in today.

**Comment by samphippen** [comment]
@sgerrand awesome! thanks so much 👍
