### ISSUE TITLE
could not connect to server: Connection refused Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432?

### ISSUE THREAD

**Issue by SanjayYadav90** [rspec/rspec-rails#1337]
I am using Rails 4.2 along with ruby 2.2.0

I am getting this issue due to I was trying to give permission for my new Dump for my DB
i Used chmod 777 -R *.* followed by the path of Postgres 

PG::ConnectionBad (could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
):
  activerecord (4.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `initialize'
  activerecord (4.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `new'
  activerecord (4.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `connect'
  activerecord (4.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:548:in `initialize'
  activerecord (4.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
  activerecord (4.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
  activerecord (4.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:440:in `new_connection'
  activerecord (4.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `checkout_new_connection'
  activerecord (4.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:421:in `acquire_connection'
  activerecord (4.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:356:in `block in checkout'
  /home/sanjay/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in `checkout'
  activerecord (4.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
  /home/sanjay/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
  activerecord (4.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:546:in `retrieve_connection'
  activerecord (4.0.3) lib/active_record/connection_handling.rb:79:in `retrieve_connection'
  activerecord (4.0.3) lib/active_record/connection_handling.rb:53:in `connection'
  activerecord (4.0.3) lib/active_record/migration.rb:792:in `current_version'
  activerecord (4.0.3) lib/active_record/migration.rb:800:in `needs_migration?'
  activerecord (4.0.3) lib/active_record/migration.rb:379:in `check_pending!'
  activerecord (4.0.3) lib/active_record/migration.rb:366:in `call'

Can I have Solution for this....

**Comment by cupakromer** [comment]
This doesn't sound like an RSpec issue. I suspect you will get the same errors if you ran `RAILS_ENV=test bin/rails console`.

With that being said. I would suggest making sure you can connect to the PostgreSQL database using `psql` first. The PostgreSQL docs (http://www.postgresql.org/docs/) should provide better details on how to ensure:

- you have the database files in the proper location
- you have the proper permissions to allow `localhost` _and_ `127.0.0.1` connections to PostgreSQL
- verify that you have a database with the proper name setup for the test environment

BTW, from your stacktrace it looks like you are running Rails 4.0 and Ruby 2.1.3

**Comment by SanjayYadav90** [comment]
than for your idea.
I had resolved this problem. It was due to Postgres database.

**Comment by prasanthrubyist** [comment]
Hi, @SanjayYadav90 I've also same problem in AWS server can you explain, How can i fix this problem?

**Comment by SanjayYadav90** [comment]
In my case It was permission issue on my PostgreSQL Dump.

I provide proper permission and got my issue resolved.

**Comment by prasanthrubyist** [comment]
Thanks, I got passanger path issue Now i fixed thanks

**Comment by pirj** [comment]
Again, it doesn't sound like an RSpec issue. RSpec Rails is a wrapper around Rails' testing, and it's using the connection that Rails provides. You may want to debug this with `RAILS_ENV=test rails console` or `RAILS_ENV=test rails dbconsole`.
As a side note, you probably don't want to allow your Postgres to accept connections from the Internet (`0.0.0.0`).
