### ISSUE TITLE
Getting error while updating Feedback ActiveModel::ForbiddenAttributesError in Admin::FeedbacksController#update

### ISSUE THREAD

**Issue by SanjayYadav90** [rspec/rspec-rails#1342]
ActiveModel::ForbiddenAttributesError

Rails.root: /home/sanjay/Project/slips/Testing/99slips

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>"aWeSMV65GxDFJ2bn48StDp9QfM16vFFvP0hVPe3FgeU=",
 "feedback"=>{"user_id"=>"447",
 "title"=>"dashboard blocks re- addition",
 "description"=>"on the dashboard,
 once a block is removed by clicking on the cross button,
 how do i get it back again on the page?",
 "status"=>"0",
 "image"=>""},
 "commit"=>"Update Feedback",
 "id"=>"21"}
Toggle session dump
Toggle env dump

Response

Headers:

Controller I have is like-
class FeedbacksController < InheritedResources::Base

  private

    def feedback_params
      params.require(:feedback).permit!
    end
 end

**Comment by cupakromer** [comment]
This doesn't sound like an RSpec issue. That error comes from the Rails and/or the model itself. From the [Rails 4.2 docs](http://api.rubyonrails.org/classes/ActiveModel/ForbiddenAttributesError.html):

> Raised when forbidden attributes are used for mass assignment.
> 
> ```ruby
> class Person < ActiveRecord::Base
> end
> 
> params = ActionController::Parameters.new(name: 'Bob')
> Person.new(params)
> # => ActiveModel::ForbiddenAttributesError
> 
> params.permit!
> Person.new(params)
> # => #<Person id: nil, name: "Bob">
> ```

The params and code snippet you provided doesn't indicate a clear cause. I would suggest looking at the full stacktrace to see what line of code is throwing the issue. RSpec doesn't do anything special with the params when it sends them in.

**Comment by SanjayYadav90** [comment]
I was missing permission thats why I was getting this error, just i code as

Feedback.rb
 controller do
    def permitted_params
      params.permit!
    end
  end

as I was using Activeadmin!!

Thnx you....
