### ISSUE TITLE
Examples get doubled

### ISSUE THREAD

**Issue by JuanitoFatas** [rspec/rspec-rails#1348]
Hello,

I found when I run a spec under `spec/support` folder of a Rails project, examples got doubled.

Given these files:

##### spec/support/life_helper.rb

```ruby
module LifeHelper
  def answer
    42
  end
end
```

##### spec/spec_helper.rb
<sup>*comments stripped*</sup>

```ruby
$LOAD_PATH << File.expand_path("../..", __FILE__)

Dir["spec/support/**/*.rb"].each { |f| require f }

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.include LifeHelper
end
```

##### spec/support/life_helper_spec.rb

```ruby
describe LifeHelper do
  it "answer" do
    expect(answer).to eq 42
  end
end
```

When I run `bundle exec rspec`, I got:

```
..

Finished in 0.00083 seconds (files took 0.08148 seconds to load)
2 examples, 0 failures
```

`bundle exec rspec --profile`:

```
..

Top 2 slowest examples (0.00049 seconds, 63.3% of total time):
  LifeHelper answer
    0.00043 seconds ./spec/support/life_helper_spec.rb:2
  LifeHelper answer
    0.00006 seconds ./spec/support/life_helper_spec.rb:2

Finished in 0.00077 seconds (files took 0.13751 seconds to load)
2 examples, 0 failures
```

What did I go wrong? Thanks!

--

Repository to reproduce this issue: https://github.com/JuanitoFatas/rspec-2x

**Comment by cupakromer** [comment]
You are "manually" requiring all support files in your `spec/spec_helper.rb` here:

```ruby
Dir["spec/support/**/*.rb"].each { |f| require f }
```

The rspec runner later runs using the pattern specified, which defaults to `spec/**/*_spec.rb`, loading any specs it finds. That pattern matches `spec/support/*_spec.rb` so those spec files are loaded twice.

**Comment by JuanitoFatas** [comment]
Hi Aaron,

What is the correct way to require files under spec/support? Without `Dir["spec/support/**/*.rb"].each { |f| require f }`, the spec does not load my `LifeHelper`:

```diff
diff --git a/spec/spec_helper.rb b/spec/spec_helper.rb
index c3438a9..314e7a6 100644
--- a/spec/spec_helper.rb
+++ b/spec/spec_helper.rb
@@ -1,6 +1,5 @@
 $LOAD_PATH << File.expand_path("../..", __FILE__)

-Dir["spec/support/**/*.rb"].each { |f| require f }

 RSpec.configure do |config|
   config.expect_with :rspec do |expectations|
```

```
$ bundle exec rspec
/Users/Juan/null/rspec-2x/spec/spec_helper.rb:13:in `block in <top (required)>': uninitialized constant LifeHelper (NameError)
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core.rb:101:in `configure'
	from /Users/Juan/null/rspec-2x/spec/spec_helper.rb:4:in `<top (required)>'
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1181:in `require'
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1181:in `block in requires='
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1181:in `each'
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1181:in `requires='
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration_options.rb:110:in `block in process_options_into'
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration_options.rb:109:in `each'
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration_options.rb:109:in `process_options_into'
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration_options.rb:22:in `configure'
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:96:in `setup'
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:85:in `run'
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:70:in `run'
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:38:in `invoke'
	from /Users/Juan/.gem/ruby/2.2.1/gems/rspec-core-3.2.2/exe/rspec:4:in `<top (required)>'
	from /Users/Juan/.gem/ruby/2.2.1/bin/rspec:23:in `load'
	from /Users/Juan/.gem/ruby/2.2.1/bin/rspec:23:in `<main>'
```

Thanks!

**Comment by myronmarston** [comment]
`require 'support/life_helper'` works fine.

Personally, I consider the "require each file under this directory" pattern to be an anti-pattern.  As you've seen it has pitfalls, and even when it works, you're adding to the boot time of RSpec when you run any individual spec, even those that don't need those support files.  I prefer requiring the support files in the specs that need them, and keeping `spec_helper.rb` very light-weight.

Still, if you've weighed the pros and cons and still want to follow that approach, here are some alternate ways to make things work:

* Move `spec/support/life_helper_spec.rb` to another directory (maybe `spec/support_specs/life_helper_spec.rb`.  As long as you use the "require each file under this dir" approach, you should make sure that dir is only support files and not any spec files.
* Add a `unless f =~ /_spec.rb$/` condition to the require loop to skip files that look like spec files.

**Comment by JuanitoFatas** [comment]
Thanks Myron. I understand now. I was assuming require `*_spec.rb` files caused no problem because Ruby `require` won't load it twice.

I'll go require at the place I need it. 

Thanks!!!

Have a good day!
