### ISSUE TITLE
config.include usage in following manner: config.include "ModuleName", type: "Multiple tags here"

### ISSUE THREAD

**Issue by jiggneshhgohel** [rspec/rspec-rails#1349]
**Environment**
```
Rails 4.2.0
ruby-2.2.1 [ x86_64 ]
rspec-core  3.2.2
rspec-rails   3.2.1
```

In my **/spec/rails_helper.rb** I have included **Devise** helpers for spec files tagged with `type: :controller`

```
RSpec.configure do |config|
   ...
   ....
   config.include Devise::TestHelpers, type: :controller
end
```

Now I need these helpers for spec files tagged with  `type: :request`. Is there a provision to specify multiple values to `:type` option? For e.g.

`config.include Devise::TestHelpers, type: :controller, :request`,  or 

`config.include Devise::TestHelpers, types: [:controller, :request]`

Thanks,
Jiggneshh

**Comment by cupakromer** [comment]
You will need to write the include again:

```ruby
config.include Devise::TestHelpers, type: :request
```

The metadata matches are exact. So `type: [:controller, :request]` would expect a spec that has the type specified as an array.

**Comment by yagudaev** [comment]
I agree with @jiggneshhgohel seeing the following code my instinct that it was similar to rails and I could change it to `types` and it would all work. I do understand what you are talking about @cupakromer but it is a technical reason. The design of the interface should accommodate what the user would expect to be able to do.

At the very least, we should give a warning "Unsupported filter option `types`" if possible.

**Comment by Jack-Barry** [comment]
I just used a loop to save some keystrokes.

```rb
for type in [:controller, :request] do
  config.include Devise::Test::ControllerHelpers, type: type
end
```

**Comment by aldrienht** [comment]
My aim is to have type for :controller & :model
the above suggestion does not worked in my end.
I tried to remove the type argument, and it works for both  :**controller** & :**model**
