### ISSUE TITLE
Start testing on rails 5

### ISSUE THREAD

**Issue by arthurnn** [rspec/rspec-rails#1358]
Can we relax rails dependency on master. and start testing this against latest rails master?
thanks

**Comment by cupakromer** [comment]
Thanks for brining this up @arthurnn. We are working out what our plans are for the future and this is part of it. Updates should be coming in the next week or two which will address this.

**Comment by arthurnn** [comment]
Thanks, let me know.
I am working in upgrading discourse to run on latest rails, and one of the last dependencies that need to run is rspec-rails.

**Comment by jasnow** [comment]
I have found several issues on some Rails apps I have upgraded. Do we want
  * separate issues and a "rails5" label or 
  * just add them to this issue

until we officially start with the Rails 5 port?

**Comment by cupakromer** [comment]
> separate issues and a "rails5" label

Please :blue_heart:

**Comment by cupakromer** [comment]
Update on this issue (/cc @arthurnn). I have not forgotten about this. I have had several discussions with the RSpec core team about what our plan should and will be. Unfortunately, things get a bit complex. We need to take into account:

- following SemVer (so dropping version support mid-release is not really an option; unless rspec-rails decides to not follow SemVer :grimacing:)
- the current release process (same Major.Minor versions across all rspec gems)
- Ruby version support plans
- the history of supporting Rails 3.0 - 3.2 despite those versions having had support dropped by Rails core team

Additionally, timelines between RSpec 4 and Rails 5 release plans have been in question too.

I'm open to getting more community feedback on possible strategies for handling this. Does anyone know of a good medium to elicit polls from a large audience?

**Comment by jasnow** [comment]
>> separate issues and a "rails5" label

Then we can tag (label) #1358 and #1392 with "rails5". Any more?

**Comment by cupakromer** [comment]
Done and done. :heart: Thanks for reminding me I hadn't created the label yet (>ლ)

**Comment by samphippen** [comment]
This is being done in #1492

**Comment by arthurnn** [comment]
thanks @samphippen

**Comment by JonRowe** [comment]
Closing in favour of #1492, we've also been running builds since #1485
