### ISSUE TITLE
undefined method `web_console' Rails::Application::Configuration

### ISSUE THREAD

**Issue by frenesim** [rspec/rspec-rails#1368]
I have this on my rails configuration 
config.web_console.whitelisted_ips = '10.11.50.22'
which works as supposed, but i can't run test unless I comment it.

So:
shell> rspec
I get:
undefined method `web_console' for #<Rails::Application::Configuration:0x00000002305190> (NoMethodError)

It may be a web-console issue, but I can't figure that. (I will open an issue for web-console as well.

**Comment by cupakromer** [comment]
The docs for `web-console` show the gem only being included in the "development" environment. Thus that setting will not be available in the "test" environment. It looks like you need to either include the gem in both environments, or move where you set the config at.

I'm guessing if the gem is only in your "development" environment you will have problems when you run the app in production. I suggest changing where you set the configuration to one of the environment specific files; if `web-console` supports that.

**Comment by frenesim** [comment]
Many thanks. Helped me to understand my error better. I was including the configuration for all environments and just needed to do it in development.
Obviously, nothing to do with rspec.
