### ISSUE TITLE
response.content_type should not remove charset

### ISSUE THREAD

**Issue by joelpresence** [rspec/rspec-rails#1371]
Hi,

When I run rails and perform a certain request, I get a response with:

```
Content-Type: application/json; charset=utf-8
```

However, when performing an Rspec controller test against that same controller, the `response.content_type` is just `application/json` which is not correct.  Somehow, rspec is splitting off charset into `response.charset` which comes back as `utf-8`.  This feels odd to do this since the actual header name where the charset is returned is `Content-Type`.

I'm not sure which code is doing this and obviously not breaking a bunch of existing tests is a concern, but this seems like a mismatch to me ...

Thoughts?

Thanks!

**Comment by JonRowe** [comment]
As per rspec/rspec-core#1965 this is a Rails issue.

**Comment by joelpresence** [comment]
OK, sorry, misunderstood, my fault.  I'll file against rails.

**Comment by cupakromer** [comment]
The `response` object in controller specs is an instance of `ActionController::TestResponse`. However, `content_type` is inherited from `ActionDispatch::Response`. Per [`ActionDispatch::Response#content_type`](https://github.com/rails/rails/blob/a63760cea7d858/actionpack/lib/action_dispatch/http/response.rb#L54-L66) this is by design:

```ruby
    # Sets the HTTP response's content MIME type. For example, in the controller
    # you could write this:
    #
    #  response.content_type = "text/plain"
    #
    # If a character set has been defined for this response (see charset=) then
    # the character set information will also be included in the content type
    # information.
    attr_reader   :content_type

    # The charset of the response. HTML wants to know the encoding of the
    # content you're giving them, so we need to send that along.
    attr_accessor :charset
```

You are asking about the actual header value. You can get that from:

```ruby
expect(response.headers).to include(
  "Content-Type" => "application/json; charset=utf-8"
)
```
