### ISSUE TITLE
Problems when test view in new space.

### ISSUE THREAD

**Issue by RathanakSreang** [rspec/rspec-rails#1376]
I try to write a test on my view which locate in admin/examinations/index.html.erb and in this view it render admin/examinations/_examination.html.erb but I got problem  it render to examintions/_examination instead. so how can I solve this probelm?

**Comment by JonRowe** [comment]
So you are attempting to render a partial and its not picking up the full directory pattern?

**Comment by RathanakSreang** [comment]
yes

**Comment by cupakromer** [comment]
@RathanakSreang does this just happen in the spec or in the web view as well?

Can you please share the exact syntax you are using to render the partial in your view?

**Comment by RathanakSreang** [comment]
@cupakromer  yes it is happen in spec only.
###In admin/examinations/index.html.erb

<div class="form-area col-sm-6 col-sm-offset-3">
  <%= t("admin.title.all_examination") %>
  <div class="row">
    <div class="col-sm-6 col-sm-push-6">
      <%= form_tag admins_examinations_path, method: "get", class: "form-inline" do %>
        <div class="form-group">
          <%= label_tag :status %> 
          <%= select_tag :status, options_for_select(Settings.status.to_h.values.map {|element| [element, element]}, selected: params[:status]), {class: "form-control"} %>
        </div>
        <%= submit_tag t("button.search"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div><hr />
  <%= will_paginate @examinations, renderer: BootstrapPagination::Rails %>
  <ul class="list-group">
    <%= render @examinations %>
  </ul>
</div>

##################in admin/examinations/_examintion.html.erb
<li class="list-group-item">
  <%= link_to "#{examination.subject.name} | #{l examination.created_at}", [:admins, examination.user, examination] %>
  <span class="pull-right"><%= link_to t("admin.link.go_to_correction_page"), edit_admins_examination_path(examination) %></span>
</li>

**Comment by JonRowe** [comment]
So I'm guessing Rails doesn't know you're in the admin namespace here, so the wrong partial name is inferred, you can work around this by using the pull partial name like `render partial: 'admin/examinations/examinations'`

**Comment by RathanakSreang** [comment]
@JonRowe 
Now my test code work fine.
 thanks
