### ISSUE TITLE
rspec:request generator not shown in "bin/rails g --help"

### ISSUE THREAD

**Issue by eliotsykes** [rspec/rspec-rails#1377]
The rspec:request generator is not being shown in the output of `bin/rails g --help`. Any pointers on what might cause this?

**Comment by cupakromer** [comment]
That is because there is no `rspec:request` generator. The request specs are created as part of the scaffold generation process.

I see how this can be confusing. We can include a standalone generator for requests.

**Comment by cupakromer** [comment]
I take that back. It is named `rspec:integration`. That is still confusing so it is something we should consider updating.
