### ISSUE TITLE
Add deprecation warning when 'mock_model' and 'stub_model' have been used.

### ISSUE THREAD

**Issue by evolve2k** [rspec/rspec-rails#1390]
My app is currently reporting "undefined method `stub_model' for many old specs. Searching around revealed that these methods were deprecated in rspec 3.0.

Would be much nicer to have rspec report that the messages had been deprecated and suggest the user use another approach or install 'rspec-activemodel-mocks' gem than just report NoMethodError as it does currently. 

Something similar in nature to this message I found via Stackoverflow:
"mock_model and stub_model are removed since version 3.0.0 of rspec-rails. rspec mocks are externalized in an another gem rspec-activemodel-mocks . You should include it in your Gemfile and try it.".

ref: http://stackoverflow.com/questions/24059805/rspec-view-undefined-method-stub-model

**Comment by myronmarston** [comment]
> Searching around revealed that these methods were deprecated in rspec 3.0.

No, they were deprecated in 2.99 and removed in 3.0.

Did you follow the 2.x -> 2.99 -> 3.x upgrade process? That provides detailed deprecation warnings about every single API that has a breaking change in 3.0.  Our [upgrade guide](http://rspec.info/upgrading-from-rspec-2/) provides detailed step-by-step instructions for the upgrade process.

We specifically _don't_ want to continue providing the APIs for 2.99 deprecations in 3.x as that would obligate us to continue to support the deprecated APIs until RSpec 4 and the entire reason we put a ton of effort into creating 2.99 was to avoid that.
