### ISSUE TITLE
allow no longer works with ActiveRecord classes

### ISSUE THREAD

**Issue by greysteil** [rspec/rspec-rails#1394]
Known issue over at https://github.com/rspec/rspec-mocks, but I thought it might be useful to have a clone of https://github.com/rspec/rspec-mocks/issues/972 to flag this to anyone else seeing lots of failing specs when upgrading to 3.3.0.

**Comment by myronmarston** [comment]
Thanks.  I have a fix in #1395.  I hope to release it later in the weekend.

**Comment by greysteil** [comment]
:heart:

**Comment by myronmarston** [comment]
rspec-rails 3.3.1 has been released with a fix.
