### ISSUE TITLE
Bad request.path interpretation in controller specs

### ISSUE THREAD

**Issue by erez-rabih** [rspec/rspec-rails#1397]
Hi,

I am using Rails 3.2.11 and the following rspec gems:
  * rspec (2.13.0)
  * rspec-core (2.13.1)
  * rspec-expectations (2.13.0)
  * rspec-html-matchers (0.4.0)
  * rspec-mocks (2.13.0)
  * rspec-rails (2.13.0)

I have a PostsController and a corresponding spec file.
When testing the show action for example, I see inside the controller that the request.path is the wrong one.
```ruby
# In spec
get :show, id: @post.id
# Inside controller
request.path # => /players/2
```
So it looks like the PostsController spec prefixes the request.path with players instead of posts.
Has anyone else bumped into this? Any known solutions?

Thanks!

**Comment by JonRowe** [comment]
Sorry but it'd be impossible to help you without a more detailed look at your controller.

You should also attempt to upgrade your version of rspec to the most recent (3.3.x) should you think theres an rspec bug here, as the version you're using isn't supported anymore. If you follow our upgrading instructions it should be fairly painless. See http://rspec.info/upgrading-from-rspec-2/
