### ISSUE TITLE
No route matches for namespaced controllers - rails 3 -> 4 upgrade

### ISSUE THREAD

**Issue by dudo** [rspec/rspec-rails#1399]
I'm attempting to upgrade an app to Rails 4.2.1 and RSpec 3.2.0. I have several nested controllers and I'm getting quite a few errors. I'd like to point out that with Rails 3.2.21 and RSpec 2.14.1 this was working normally.

    > bundle exec rspec spec/controllers/admin/address/primaries_controller_spec.rb
    app/controllers/admin/address/primaries_controller.rb:1: warning: toplevel constant Address referenced by Admin::Address

    Failure/Error: xhr :post, :create, params
       ActionController::UrlGenerationError:
         No route matches {:action=>"create", :address_primary=>{:street=>"69564 Dach Cliffs", :apt=>"405", :city=>"West Morrisview", :state=>"NY", :zip=>"00501", :addressable_attributes=>{:id=>"1"}, :addressable_type=>"Business"}, :controller=>"address/primaries", :field=>"primary_address"}
       # ./spec/controllers/admin/address/primaries_controller_spec.rb:26:in `block (4 levels) in <top (required)>'

This is the spec:
```
require 'rails_helper'
require 'admin/address/primaries_controller'

describe Admin::Address::PrimariesController do
  let(:address_attrs) { FactoryGirl.attributes_for(:primary_address) }
  context 'primary address' do
    let(:params) { { field:    'primary_address',
                     address_primary: address.merge(addressable) } }

    describe 'valid input' do
      let(:address) { address_attrs }

      it 'creates a new business primary address' do
        xhr :post, :create, params
        ... expectations ...
      end
    end
  end
end
```

So during the rails 4.2 upgrade I realized not only that rspec wasn't compatible, but several routing deprecation warnings were cleared up with an upgrade... so I had a pile of specs to fix anyway, so I ran transpec, upgraded the gem, ran transpec again, and here I am.

Another batch seems similar.

```
require 'rails_helper'

describe AppInformationController do
  context 'valid partials' do
    before { get :show, {id: template.to_s} }

    after { is_expected.to respond_with(:success) }

    context 'faqs' do
      let(:template) { :faqs }
      it { is_expected.to render_template(template) }
    end
  end
end
```
    > bundle exec rspec spec/controllers/app_information_controller_spec.rb

    Failure/Error: it { is_expected.to render_template(template) }
         expecting <"faqs"> but rendering with <["layouts/app_information/_navigation", "app_information/_title", "layouts/app_information/_start_works", "app_information/_faqs", "app_information/show", "layouts/application/_head", "layouts/application/_navigation", "layouts/application/_messages", "layouts/application/_footer", "layouts/application"]>

This seems different, but there are dozens of these, and they all show up around namespacing.

I've been googling for days... can I get some help headed in the right direction here?

**Comment by JonRowe** [comment]
RSpec 3.x is most certainly compatible with Rails 4.2, however I suggest you upgrade RSpec before upgrading rails. Run your app on RSpec 3.3 and Rails 3.2 and get it green before attempting to upgrade rails to figure out where the error is coming from

**Comment by dudo** [comment]
Oh, I know RSpec 3 and Rails 4 are fine. I was referring to RSpec 2 and Rails 4.2.

**Comment by JonRowe** [comment]
My advice still stands, as RSpec is back compatible it's worthwhile completing that upgrade before you upgrade your app (you can even still do this if you've already started with a bit of git foo ;)), we're well aware RSpec 2 doesn't support Rails 4.2 but we don't support RSpec 2 (in part because we've made so much effort to make upgrading painless)

**Comment by cupakromer** [comment]
I'm a little confused which version of rspec-rails and Rails you are reporting demonstrating the issue. Can you let us know which one has the error in question. Please also confirm that the issue you are asking about is the final one: `expecting <"faqs"> but rendering with <["layouts/app_information/_navigation", ...`

This looks like it's a controller spec, have you either added metadata `type: :controller` or set the [`infer_spec_type_from_file_location!](https://relishapp.com/rspec/rspec-rails/v/3-3/docs/upgrade#file-type-inference-disabled) configuration option?

**Comment by dudo** [comment]
It is a controller. I have the `infer_spec_type_from_file_location!` there, but tried the manual way as well. No dice either way. 

As for versions, this is the latest RSpec with the latest Rails.

**Comment by cupakromer** [comment]
Can you share your controller code? I'm most interested in the line of code you call for `redirect_to` or `render` for this action? As well as any view related defaults you setup else where in the control or parent controller.

**Comment by cupakromer** [comment]
Based on the error it looks like you are rendering a partial. Try which tends to have the convention that it is prefixed with an underscore. So while `render partial: "faq"` is acceptable in the controller, the actual file (template) is `app_information/_faqs.html.erb` (or slim or json etc). Try `render_template(:_faq)` to denote it is a partial.

**Comment by dudo** [comment]
Oh, and as for my question, I'm more concerned with the first issue. I was able to get around the rendering issue by using strings, and explicitly defining the template location, ie `render_template('app_information/_faqs')`

The 'no route matches error' is what really has me tripped up. that has something to do with namespacing, but I just can't get my finger on it.

**Comment by JonRowe** [comment]
The routing one is because somewhere along the line it's lost the 'admin' part...

**Comment by cupakromer** [comment]
I believe you may be calling `Address` somewhere in your code. Classes are just constants in Ruby. So the standard, sometimes unexpected, Ruby constant look-up rules still apply:

```ruby
class Address
  def to_s
    "OUTTER"
  end
end

module Admin
  class Address
    def to_s
      "INNER"
    end
  end
end

class Admin::Controller
  def get_address
    # Really the top level ::Address
    Address.new.to_s
  end
end

module Admin
  class OtherController
    def get_address
      Address.new.to_s
    end
  end
end

puts Admin::Controller.new.get_address
puts Admin::OtherController.new.get_address
```

See also: http://cirw.in/blog/constant-lookup.html

**Comment by cupakromer** [comment]
Rail's version of autoloading also has some issues. See http://urbanautomaton.com/blog/2013/08/27/rails-autoloading-hell/ and http://guides.rubyonrails.org/autoloading_and_reloading_constants.html

I've never run into this, but a quick check of my work apps shows I don't really nest models in this fashion. I may nest similar controller names, but I don't have to models with the same name but different controllers...yet.

**Comment by dudo** [comment]
Address is a database backed model, yes. And it's a namespace.

    namespace :admin do
      namespace :address do
        resources :primaries, only: [:create, :update]
        ...
      end
      ...
    end

Admin is also a database model. Do I agree with that decision? No, I inherited this. I spent a bit of time trying to change the namespacing, but that rabbit hole got deep quickly.

Sounds like an issue with Rails, not RSpec, but the app works fine... just the specs are failing

**Comment by cupakromer** [comment]
Right ok, I missed it the first go around. Your error is (I adjusted the hash order here):

```
No route matches { :action=>"create", :controller=>"address/primaries", params...}
```

This seems to be loading the wrong scope, which is causing the problem. The warning about which `Address` is being loaded appears on line 1 of your controller:

```
app/controllers/admin/address/primaries_controller.rb:1: warning: toplevel constant Address referenced by Admin::Address
```

Is that just the following or something else?

```ruby
class Admin::Address::PrimariesController < ActionController::Base
```

I would advise making sure all necessary parent constants are properly loaded prior to the files. This is really an issue with Ruby constant lookup semantics and Rails autoloading semantics. If necessary, in the controller class specify the nesting manually:

```ruby
module Admin
  module Address
    class PrimariesController < ActionController::Base
    end
  end
end
```

It is likely the app runs fine because Rails preloads files for production and the order it loads things happens to be the order which makes this happy.

**Comment by dudo** [comment]
`Admin is not a module (TypeError)` and the actual page doesn't load anymore. Same error. http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#nesting-and-qualified-constants seems to suggest that explicitly defining the modules is the preferred method as well.

**Comment by cupakromer** [comment]
`Admin is not a module (TypeError)` I'm guessing that code base has it defined as a class. You can still nest inside constants that are classes:

```ruby
class Admin
  class Address # Unless this is also a module (i.e. ::Admin::Address)
    class PrimariesController < ActionController::Base
    end
  end
end
```

The only problem you now face is if this is loaded first, Rails will not autoload the actual class `Admin`, nor `Admin::Address`; which means those class def won't get autoloaded. Worse if you manually required those files _after_ this one loads you'll get a superclass mismatch error.

The only way I see resolving this is to manually require the actual other class dependencies at the top of this file, in the order of admin, then the admin/address, and then finally allow this controller to get defined.

I'm going to close this as it's a Ruby constant lookup and Rails autoloading issue.
