### ISSUE TITLE
Controller specs convert request.query_params keys into symbols

### ISSUE THREAD

**Issue by odedniv** [rspec/rspec-rails#1410]
For some reason, only in controller specs (as opposed to request specs, feature specs, and a normal rails server) calling `request.query_parameters` from within the controller returns a hash with symbols for keys.

Everywhere else comes out as a hash with strings for keys (which makes a lot of sense, this is user input after all). On a side note `params` is fine, it generates a hash with strings for keys in controller specs.

This doesn't matter if the request was made with strings for keys: controller specs _always_ uses symbols and everywhere else _always_ use strings.

Reproduce:

```ruby
# specs
RSpec.describe UsersController, type: :controller do
  before { get :index, 'a' => 1, 'b' => 2 }
  ...
end
RSpec.describe "Users", type: :request do
  before { get "/users", a: 1, b: 2 }
  ...
end

# UsersController
def index
  pp request.query_parameters
  # From controller spec:
  # => { :a => 1, :b => 2 }
  # From everywhere else:
  # => { "a" => 1, "b" => 2 }
end
```

Versions:

    rails (4.2.3)
    rspec-core (3.3.1)
    rspec-expectations (3.3.0)
    rspec-mocks (3.3.1)
    rspec-rails (3.3.2)
    rspec-support (3.3.0)

**Comment by cupakromer** [comment]
Thanks for logging this :heart: Unfortunately, this is an issue with Rails :frowning:.

The RSpec controller tests utilize the same logic that `ActionController::TestCase`. The logic which sets up that part of the request is handled deeper inside the request setup logic; outside the scope of RSpec.

Here is a repo of the the same behavior using the Rails default minitest functional test:

```ruby
# app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  def index
    p params
    p request.query_parameters
    p request.query_parameters["foo"]
    p request.query_parameters[:foo]
    p request.query_parameters.class
  end
end
```

```ruby
# test/controllers/widgets_controller_test.rb
require 'test_helper'

class WidgetsControllerTest < ActionController::TestCase
  test "should get index" do
    puts "No params"
    get :index

    puts "\nString params"
    get :index, "foo" => 123

    puts "\nSymbol params"
    get :index, foo: 123
  end
end
```

Results in:

```
No params
{"controller"=>"widgets", "action"=>"index"}
{}
nil
nil
Hash

String params
{"foo"=>"123", "controller"=>"widgets", "action"=>"index"}
{:foo=>"123"}
nil
"123"
Hash

Symbol params
{"foo"=>"123", "controller"=>"widgets", "action"=>"index"}
{:foo=>"123"}
nil
"123"
Hash
```

However, as you have reported, this differs from say the actual request:

```
{"foo"=>"123", "controller"=>"widgets", "action"=>"index"}
{"foo"=>"123"}
"123"
"123"
ActiveSupport::HashWithIndifferentAccess
```

If this is causing an issue for you I suggest logging it with the Rails team.

**Comment by odedniv** [comment]
Thanks, this one was a little hard to track

**Comment by lichtamberg** [comment]
Sorry to post here, but I have the same problem now, @odedniv did you find a solution for this?

**Comment by odedniv** [comment]
Sorry @lichtamberg I don't even remember why this issue bothered me :x
