### ISSUE TITLE
Rspec throwing unknown attribute error based on how migration is setup

### ISSUE THREAD

**Issue by balla121** [rspec/rspec-rails#1411]
Hi,

I was getting unknown attribute error for my approved instance method for my appointment class because of how my migration was set up...

rspec would throw the error when i added the "approved" attribute to the migration like this: 
 add_column :appointments, :approved, :boolean

but after I rolledback my database and instead placed the column where my table was created as such:

create_table :appointments do |t|
  ...
  t.boolean :approved
end

no error is thrown in that case

**Comment by cupakromer** [comment]
Could you provide the exact error message and migration files? RSpec doesn't do anything with your migration. Depending on your version of Rails we do different things. For Rails 4.2 we simply call `ActiveRecord::Migration.maintain_test_schema!` which you can see in your `spec/rails_helper.rb`. That code is all provided by Rails.

**Comment by cupakromer** [comment]
@balla121 were you able to resolve this? Without more information I'm not sure we can provide further assistance. I'm going to close this for now. If you are still having issues please let us know. :heart:
