### ISSUE TITLE
Upgrade from 2.99 to 3.3 is causing controller test failures

### ISSUE THREAD

**Issue by jeffheifetz** [rspec/rspec-rails#1415]
I was following the guide(http://rspec.info/upgrading-from-rspec-2/)  and was able to have all tests pass in 2.99 without deperecation warnings, but when I actually upgraded to 3.0, I got a slew of failures.

I'm using rails 4.2.3 and rspec-rails 3.3.2

All of the failures look like this.

```
Got 0 failures and 2 other errors:
       Shared Example Group: "a user was created successfully" called from ./spec/controllers/api/v1/user_controller_spec.rb:650

       114.1) Failure/Error: Unable to find matching line from backtrace
              ArgumentError:
                comparison of Symbol with Module failed
              # /Users/jeffheifetz/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.3/lib/action_controller/test_case.rb:656:in `<'
              # /Users/jeffheifetz/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.3/lib/action_controller/test_case.rb:656:in `setup_controller_request_and_response'

       114.2) Failure/Error: Unable to find matching line from backtrace
              NoMethodError:
                undefined method `each' for nil:NilClass
              # /Users/jeffheifetz/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.3/lib/action_controller/test_case.rb:58:in `teardown_subscriptions'
```

**Comment by cupakromer** [comment]
Sorry you ran into this :crying_cat_face:. To resolve it you'll need to either add the `type: :controller` metadata or declare [`config.infer_spec_type_from_file_location!`](https://relishapp.com/rspec/rspec-rails/v/3-3/docs/upgrade#file-type-inference-disabled) in your setup. The full rspec-rails upgrade guide is here: https://relishapp.com/rspec/rspec-rails/v/3-3/docs/upgrade

Did you use the transpec tool suggested in both guides? I was under the impression that it [helped with the spec type](https://github.com/yujinakayama/transpec#implicit-spec-types-in-rspec-rails) conversion as part of the upgrade.

**Comment by JonRowe** [comment]
Are you sure thats the issue @cupakromer? Looks like the controller test case stuff is included given thats where the error is coming from, also doesn't `rspec-rails` 2.99 warn about that change?

**Comment by jeffheifetz** [comment]
I'm pretty confident thats not the issue. As @JonRowe implied, the 2.99 edition correctly warned me of that issue.

Additionally I have both added that to the config and added the type metadata but the problem persists.

**Comment by JonRowe** [comment]
Can you gist your spec?

**Comment by jeffheifetz** [comment]
I don't mind gisting my specs, but I don't think its related to the spec content. After the upgrade I have 1205/1298 tests failing

**Comment by JonRowe** [comment]
Well we generally can't identify what's going wrong without an example, you've neither provided a stack trace or any snippets showing where the error is originating. The normal usage is well tested across a range of different Rails and Ruby versions so it's much more likely that you're doing something we don't expect rather than a genuine bug is happening. One thing that's likely just based of the error message is the use of implicit subjects and not using a Controller class as the subject, e.g. changing the subject to a symbol, this was something that changed in the 2/3 process.

**Comment by jeffheifetz** [comment]
I found one issue, which was related to FactoryGirl. In our old specs we just called create, but in the new one we need to explicitly invoke FactoryGirl. I'm working through those to try and find a more generic situation. I'll update shortly

**Comment by jeffheifetz** [comment]
OK I think I've tracked the whole thing down to nested describe blocks.

In our old code we had something like the following and switching from symbols to strings seemed to do it.
```
describe Controller do
  describe :create do
  end
end
```

**Comment by JonRowe** [comment]
Yep, that will change `subject` to `:create` so naturally won't work with the rails test helpers, setting it back to a string e.g. `'create'` will fix it.

**Comment by myronmarston** [comment]
Thanks for reporting this, @jeffheifetz.  There's a deprecation warning missing from 2.99 that you unearthed.  I opened rspec/rspec-core#2025 to track that work.
