### ISSUE TITLE
rspec-rails for a rails project without db connection

### ISSUE THREAD

**Issue by JoostVanAverbeke** [rspec/rspec-rails#1416]
Good afternoon,

I have a rails 4.2.1 project which doesn't use db connection.
I am using rspec-rails (3.3.2) to test my rails application.

I am using a rails_helper.rb and a spec_helper.rb file generated by the generator 
	rails generate rspec:install.

When I add the following to the rails_helper.rb file:
	require 'rspec/rails'
I get the following error:

	ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base
	-e:1:in `load'
	-e:1:in `<main>'
	
So I replaced the 
	require 'rspec/rails'
by requiring the individual submodules

	# Load any of our adapters and extensions early in the process
	require 'rspec/rails/adapters'
	require 'rspec/rails/extensions'

	# Load the rspec-rails parts
	require 'rspec/rails/view_rendering'
	require 'rspec/rails/matchers'
	require 'rspec/rails/configuration'

But it fails to require 'rspec/rails/configuration' submodule.

I need the configuration module because I want to set the
  config.infer_spec_type_from_file_location!
parameter.

Do you have any ideas how to solve my problem?

Thanks in advance for any help.

Regards,

Joost

**Comment by cupakromer** [comment]
Can you please share the following files:

- `spec/spec_helper.rb`
- `spec/rails_helper.rb`
- `config/application.rb`

By default if rspec-rails does not detect `ActiveRecord` when you run `rails g rspec:install` then it will not attempt to add settings to configure it. Specifically, the following settings should _**not**_ be in your helper files:

- `ActiveRecord::Migration.maintain_test_schema!`
- `ActiveRecord::Migration.check_pending!`
- `config.fixture_path = "#{::Rails.root}/spec/fixtures"`
- `config.use_transactional_fixtures = true`

If you have none of those settings, there are still one or two runtime checks for `ActiveRecord` that are performed. However, if you have configured your Rails application to not use `ActiveRecord` those checks should fail. Please be aware that we have had reports that _other_ gems do not respect your application setup and sometimes load `ActiveRecord` inappropriately. If that happens, rspec-rails will likely see `ActiveRecord` during the runtime checks.

**Comment by JoostVanAverbeke** [comment]
Good evening,

First of all thanks for your quick response.
My project is available on github. It is a clone from an existing project https://github.com/glyph-fr/devise_remote_client for which I am adding RSpec tests.

The master branch https://github.com/JoostVanAverbeke/devise_remote_client contains the application (it is gem) with the specs running in a rspec-rails 2.14.2 environment. 
All tests are turning green.

I have created a branch https://github.com/JoostVanAverbeke/devise_remote_client/tree/usage_of_rspec-rails_3_3_2 for which I have upgraded to rspec-rails 3.3.2.
When I run these rspec tests I get the following error:
ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base 
/Users/joost/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:570:in `retrieve_connection’ 
/Users/joost/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.3/lib/active_record/connection_handling.rb:113:in `retrieve_connection’ 
/Users/joost/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.3/lib/active_record/connection_handling.rb:87:in `connection’ 
/Users/joost/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.3/lib/active_record/fixtures.rb:501:in `create_fixtures’ 
/Users/joost/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.3/lib/active_record/fixtures.rb:979:in `load_fixtures’ 
/Users/joost/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.3/lib/active_record/fixtures.rb:952:in `setup_fixtures’ 
/Users/joost/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.2.3/lib/active_record/fixtures.rb:826:in `before_setup' -e:1:in `load' -e:1:in `<main>'

I hope this gives you enough info about the application (gem) and its environment.

Thanks in advance for your help.

Regards,
Joost


Op 9 jul. 2015, om 18:18 heeft Aaron Kromer <notifications@github.com> het volgende geschreven:

**Comment by JonRowe** [comment]
The issue is on L22 of `spec/dummy/config/initializers/devise.rb`, you're requiring the devise ActiveRecord ORM adaptor which loads ActiveRecord which in turn causes our code to insert fixture support and expect ActiveRecord to be usable. Removing this line turns your specs green.

**Comment by cseeger** [comment]
@JonRowe - thanks!
