### ISSUE TITLE
Possible to use RSpec core 3.3 with this gem so I can use --only-failures?

### ISSUE THREAD

**Issue by gregblass** [rspec/rspec-rails#1417]
Is it possible to use the RSpec core 3.3 in my rails app so I can use the --only-failures option? That is amazing and I want it today!!

**Comment by myronmarston** [comment]
It should be. Have you tried upgrading?

**Comment by cupakromer** [comment]
I just tried this on a work project and it worked great :heart:. However, you will need to add the new configuration option for it to your `spec/spec_helper.rb` file:

```ruby
  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"
```

I have verified that running `rails generate rspec:install` will properly include that configuration setting; but that's usually just for new apps - or if you haven't customized the `spec/spec_helper.rb` file and would like to update it.

Don't forget to add `/spec/examples.txt` to your `.gitignore` file.

Glad you like the new features! :smile_cat:

**Comment by tansaku** [comment]
@gregblass @cupakromer do you happen to know how to pass the `--only-failures` option in when using the rails task? i.e `bundle exec rails spec`?

**Comment by JonRowe** [comment]
Are the new rails tasks similar to rake tasks? Theres an `rspec_opts` for the Rake task which would allow you to do this.

**Comment by tansaku** [comment]
ah, excellent thanks @JonRowe
