### ISSUE TITLE
All specs fail with uninitialized constant RSpec::Rails::FixtureSupport when used with ammeter gem

### ISSUE THREAD

**Issue by bigtunacan** [rspec/rspec-rails#1427]
I added the ammeter gem so I could test generators, now every spec fails with the following error 

    /Users/bigtunacan/.rvm/gems/ruby-1.9.3-p547@rails3/gems/rspec-rails-3.3.2/lib/rspec/rails/example/rails_example_group.rb:14:in `<module:RailsExampleGroup>': uninitialized constant RSpec::Rails::FixtureSupport (NameError)

**Comment by cupakromer** [comment]
I believe this is related to: alexrothenberg/ammeter#48. Unfortunately at this time there isn't much rspec-rails can do about that. You can try requiring rspec-rails before ammeter as a work around.
