### ISSUE TITLE
Re-write existing matchers to provide our own implementation

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-rails#1441]
Pros:
- We control the implementation providing finer grain control over flow, features, errors messages, etc.
- It starts the process of migrating away from all of the hidden state that gets setup in the different spec types. Eventually, this will help make the separation between the "object under test", and it's state, from the test, and it's local state, explicit.
- The matchers will fit more logically into the current `expect(object_under_test).to some_behavior` that RSpec promotes (currently we doc this format, but behind the scenes the argument to expect is ignored by many of the rspec-rails matchers as they are instead passed the spec scope :grimacing:; the `assert_xyz` methods are already on the spec scope with lots of hidden state)

Cons:
- If Rails changes some internal details we depend on we need to update (previously those changes were handled automatically by the `assert_xyz` methods from Rails)
- If Rails provides a new matcher feature, we now need to update our matchers to support it, instead of simply inheriting the feature _if_ it worked with how we were forwarding parameters

**Comment by pirj** [comment]
> Rails changes some internal details we depend on we need to update

and also to keep both versions to support both Rails versions, before and after the change.

**Comment by JonRowe** [comment]
I'm going to close this because the point of `rspec-rails` is mostly to wrap Rails, and provide the same experience. Its less of a hassle with our new version policy.
