### ISSUE TITLE
Warn on context fixture helper

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-rails#1442]
Fixtures are controlled by the underlying `ActiveRecord::TestFixtures` code. Which sets up fixtures before **each** example. While the database _may_ have fixture data in it before this point, that data will be reset once the test fixture code runs.

When the `fixtures` message is sent in an example group, or global fixtures are defined, the Active Record test fixtures register the accessors in an anonymous module. That module is included in the example group's ancestors.

Which means the accessor helpers are available in any example group instance; thus they are available in `before(:context)` and `after(:context)`. However, the internal fixture setup and cache has not been performed yet. Attempting to call a fixture helper prior to the fixtures being setup, raises an undefined method on `NilClass` error.

Related: #1201 and #1208

**Comment by samphippen** [comment]
Reproduction case is put a file called `spec/models/widgets_spec.rb` in a rails app with a "Widget" model.

```ruby
require 'rails_helper'

RSpec.describe Widget, type: :model do
  fixtures :widgets

  describe 'fixture loaded in a before context' do
    before :context do
      widgets :a
    end

    it 'works' do
    end
  end
end
```

**Comment by samphippen** [comment]
@cupakromer I have a sketch of a fix for this. I'm going to clean it up a little and PR it tomorrow.
