### ISSUE TITLE
Using `spec_helper` and selectively disabling Spring

### ISSUE THREAD

**Issue by andyw8** [rspec/rspec-rails#1443]
I really like that RSpec has introduced separate `spec_helper` and `rails_helper` but I've been wondering how this fits with Spring.

If I'm running `rspec` through Spring, then Rails will always be loaded, so it's easy to accidentally add a dependency that requires Rails to be loaded (e.g. using `Object#blank?`).

Ideally I would want any spec which requires `rails_helper` to run via Spring, and otherwise it should run without Spring.

I'm consideringconfiguring my editor to pass `DISABLE_SPRING=1` to the `rspec` command whenever there's an absence of `rails_helper` in the spec being tested.

Is there any better way to achieve this?

**Comment by cupakromer** [comment]
Good question!

I did some rough testing with Rails 4.2 and it looks like if you do not springify your `bin/rspec` binstub, or if you just run `bundle exec rspec`, then you have nothing to worry about. The default behavior seem to be exactly as you desire :smile_cat:.

However, with a new app Spring won't even consider auto-starting until I ran: `bundle exec spring binstub --all`. After that I made sure the `bin/rspec` file had not been modified - it had not. Then I made sure spring was not running - it was not. I ran a non-Rails loading spec (i.e. dependent only on `spec/spec_helper`) then successfully confirmed Spring was still not running. I then ran a Rails loading spec (i.e. dependent on `spec/rails_helper`) and also successfully confirmed that Spring was now running.

I then re-ran the non-Rails spec and it was just as fast; so it does not appear that running RSpec will load or even use Spring until you have springified your app and one of the specs causes Rails to load.

Now, if you've specifically springified `bin/rspec` then you are telling Spring to always load when you run RSpec. I'm not sure I have any suggestions beyond: 1) don't do that or 2) create a 2nd binstub so you have one normal and one loading spring.

Cheers!

**Comment by andyw8** [comment]
Thanks for the reply @cupakromer. I forgot to say that I'm using [https://github.com/jonleighton/spring-commands-rspec](spring-commands-rspec) to add Spring support to RSpec. I believe that without that, RSpec will never make use of Spring.

You make an interesting pointing having separate Spring and non-Spring versions of the `rspec` binary, I may look into that.
