### ISSUE TITLE
use_transactional_fixtures = true raises ActiveRecord::TransactionIsolationError

### ISSUE THREAD

**Issue by Chocksy** [rspec/rspec-rails#1450]
We have this piece of code where we create a serializable transaction. Something like this:

```ruby
Activity.transaction(isolation: :serializable) do
   user_ids = [1,2,3]
   activities = Activity.where(activities: { user_id: user_ids })
   TeamPayments.build({...})
end
```

And in rails_helper.rb we have set `config.use_transactiona_fixtures = true` but by running any tests will raise this exception: `ActiveRecord::TransactionIsolationError: cannot set transaction isolation in a nested `.

Is there any way to override the transaction per test so we don't get this error? Or do we have to stick to database_cleaner gem to get this working?

We use:
```ruby
rspec-rails (3.3.3)
...
rails (4.2.3)
```

**Comment by JonRowe** [comment]
I believe that something along these lines would work:

```Ruby
around do |example|
  original_value = RSpec.configuration.use_transactional_fixtures
  RSpec.configuration.use_transactional_fixtures = false
  example.run
  RSpec.configuration.use_transactional_fixtures = original_value
end
```

**Comment by JonRowe** [comment]
But no, otherwise I believe you'd have to turn off the transactional fixtures and use database cleaner (or similar) to make this work.

**Comment by Chocksy** [comment]
ok thanks @JonRowe for the quick answer. I was thinking of some setting we could add that would get the specs working as they were before.

**Comment by JonRowe** [comment]
This is something Rails handles, we just expose an easy way to configure it, so sadly you'll have to change your code or your tests to make this work.
