### ISSUE TITLE
Getting syntax error, unexpected keyword_end, expecting '}' on valid `put` request

### ISSUE THREAD

**Issue by sadaf2605** [rspec/rspec-rails#1454]
It works fine:

    post :create, params_with_product

But it fails with syntax error syntax error, `unexpected keyword_end, expecting '}'` when I do:

    put :update, :id => @item.id, params_with_product

Where:

    let(:params_with_product) { item: FactoryGirl.attributes_for(:item_without_product)}

**Comment by sadaf2605** [comment]
put :update, { :id => @item.id }.merge(params_with_product)

**Comment by JonRowe** [comment]
> `let(:params_with_product) { item: FactoryGirl.attributes_for(:item_without_product)}`

This is not valid Ruby, the `{}` are defining a block to pass to `let` so you need an additional `{}` around the hash you're trying to pass back. e.g.

 `let(:params_with_product) { { item: FactoryGirl.attributes_for(:item_without_product)} }`
