### ISSUE TITLE
Deprecation warning in Rails Edge (v5) when running rspec

### ISSUE THREAD

**Issue by zdavis** [rspec/rspec-rails#1455]
Running rspec with Rails master returns the following deprecation warning:

DEPRECATION WARNING: use_transactional_fixtures= is deprecated and will be removed from Rails 5.0 (use use_transactional_tests= instead). (called from block in <module:FixtureSupport> at /opt/rubies/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-rails-3.1.0/lib/rspec/rails/fixture_support.rb:25)

**Comment by smolnar** [comment]
@zdavis +1.

https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/fixture_support.rb#L25

Maybe use conditions based on Rails version to make this compatible?

**Comment by soulcutter** [comment]
We need a way to run a build against rails master. Right now we can't install it because it depends on an unreleased version of sprockets. This should be fixable, but it's just one of those hurdles to getting this fixed up.

**Comment by marcusg** [comment]
any updates here?

**Comment by JonRowe** [comment]
Replaced by #1485
