### ISSUE TITLE
Can't set host in routing specs

### ISSUE THREAD

**Issue by ngw** [rspec/rspec-rails#146]
Hi, I'm trying to set a different host using a subdomain (test.example.com).
The route I'm trying to test is the following (rails 3 rc1):

  match 'profile', :to => 'users#profile', :constraints => {:subdomain => /.+/ }

I've searched everywhere, but the host! method that everybody mentions doesn't seem to exist anymore, and @request is nil. No answers on rspec-users as well.
Is this feature missing or I'm simply doing it in the wrong way ?

**Comment by devraj1206** [comment]
It is success but if we run all specs failing these examples
Example:
   In my case 
        rspec spec/routing/individual_routing_spec.rb 
            4 examples ,0 fails
  When I run all specs rspec spec/
            17 examples,4 fails
