### ISSUE TITLE
Generator Templating

### ISSUE THREAD

**Issue by baweaver** [rspec/rspec-rails#1460]
Noticed a few things in the generators, and wanted to make sure there was interest here before delving around. If this is considered overkill or too opinionated, I can make this into a separate plugin.

---------------

# Controllers

Looking at: https://github.com/rspec/rspec-rails/blob/master/lib/generators/rspec/controller/templates/controller_spec.rb#L7-L12

```ruby
describe "GET #<%= action %>" do
  it "returns http success" do
    get :<%= action %>
    expect(response).to have_http_status(:success)
  end
end
```

Not all controller actions are GET requests, and this could likely be generated per action type which can be predictable. Also, some of the failure branches could be written out easily as well.

Depending on the model, we could also likely infer that certain instance variables will be set from pluralization. Take that one step further and you could reasonably create factories or pull fixtures depending on other generators that may be present (not sure how I'd swing that one honestly.)

# Models

Looking at: https://github.com/rspec/rspec-rails/blob/master/lib/generators/rspec/model/templates/model_spec.rb

We could probably fill more out than simply referencing that it's pending. Depending on opinions, one could test automatically for fields or associations (model_id). Not much more that could be done here without the model being filled out.

---------

What'd be nice is if, given a more filled out model or controller, this could potentially generate more rigorous RSPEC templates.

Admittedly I'm not incredibly fond of writing more code than I have to, so this is one of my stops at automating more of my Rails workflow. Next on the list is Angular, and perhaps Ember with Rails SOA type generators.

This issue is far more of gauging interest than anything, and if this is even worth considering from the point of view of this project.

EDIT - For clarification, I'm perfectly willing to put up code for this one, it's not asking for this to be done as much as if there's interest in it.

**Comment by xaviershay** [comment]
Disclaimer: I don't use these, so take these opinions with a grain of salt.

The generated specs are usually the least interesting ones for me.

> Depending on opinions, one could test automatically for fields or associations (model_id).

I wouldn't typically write dedicated tests for these. If they're not covered by other public interfaces, I don't really care. So I probably wouldn't support auto-generating them.

> Not all controller actions are GET requests, and this could likely be generated per action type which can be predictable.

Yeah there's likely a simple thing that would improve this.

> Also, some of the failure branches could be written out easily as well.

What were you thinking?

**Comment by baweaver** [comment]
Fair on the models.

Scaffolded code has failure branches for actions like Create, Update, and Delete that could be written out as well.

**Comment by JonRowe** [comment]
I'm really not in favour of expanding the generators I haven't seen a single case where they've been used to create valuable tests, you pretty much have to delete them the moment they're generated to be of any use at all, personally I think it'd be better to reduce the cruft they produce to a bare minimum (pretty much `RSpec.describe <Thing>, type: <type> do \n ... \n end`

**Comment by samphippen** [comment]
I agree with the comments here that expanding generated specs isn't that much of a good idea. I don't get a lot of value out of those generated specs, and I think people might see false value in them if we expand them. I'm going to close this issue.
