### ISSUE TITLE
how to test rendering a partial for several objects

### ISSUE THREAD

**Issue by vorant94** [rspec/rspec-rails#1472]
hello, there is what I've found in documentation:
```ruby
require "rails_helper"

RSpec.describe "widgets/index" do
  it "displays all the widgets" do
    assign(:widgets, [
      Widget.create!(:name => "slicer"),
      Widget.create!(:name => "dicer")
    ])

    render

    expect(rendered).to match /slicer/
    expect(rendered).to match /dicer/
  end
end
```
but this test doesn't make difference if I write in view
```ruby
<%= render @widgets %>
```
or
```ruby
<% @widgets.each do |widget| %>
  <p><%= widget.name %></p>
<% end %>
```
then I tried this:
```ruby
require "rails_helper"

RSpec.describe "rendering locals in a partial" do
  it "displays the widget" do
    widget = Widget.create!(:name => "slicer")

    render "widgets/widget", :widget => widget

    expect(rendered).to match /slicer/
  end
end
```
but it works only for rendering one object i.e. for
```ruby
<%= render @product %>
```
and not for 
```ruby
<%= render @products %>
```
so how do I test that my list of widgets renders a partial for each widget?

**Comment by JonRowe** [comment]
>but this test doesn't make difference if I write in view
>```ruby
<%= render @widgets %>
```
>or
>```ruby
<% @widgets.each do |widget| %>
  <p><%= widget.name %></p>
<% end %>
```

Thats exactly the point, the test shouldn't check how you implement it, merely assert what you need to check is output.

> so how do I test that my list of widgets renders a partial for each widget?

You need to check that a detail (or details) from each widget is rendered, you shouldn't care how that is done, a partial is a nice way to DRY it up but you shouldn't be testing for that specifically.

**Comment by JonRowe** [comment]
Closed because this isn't an issue or feature request.
