### ISSUE TITLE
how to match one image twice

### ISSUE THREAD

**Issue by vorant94** [rspec/rspec-rails#1473]
how do I test my view that it outputs one image twice?

**Comment by soulcutter** [comment]
The RSpec team uses GitHub issues to discuss bugs and development of the RSpec libraries. A forum such as StackOverflow would be a better place to ask for specific how-to advice.

You should be able to write any arbitrary tests against the `rendered` value in view specs.

**Comment by JonRowe** [comment]
Assuming you have capybara loaded, you could do something like `expect(all(:css, "img[href='path/to/img']").size).to eq 2`
