### ISSUE TITLE
Relish App Docs are down

### ISSUE THREAD

**Issue by marcamillion** [rspec/rspec-rails#1477]
For whatever reason the Relish App is down.

Was it a free app that got nuked in some Heroku change?

**Comment by NelsonScott** [comment]
Still down as of 10AM PDT

**Comment by myronmarston** [comment]
We don't run relishapp.  @mattwynne does.  Matt, can you take a look at getting relish back on line?

In the meantime, you can use our API docs at rspec.info:

rspec.info/documentation

**Comment by mattwynne** [comment]
I'm on it.

**Comment by mattwynne** [comment]
We're back.

**Comment by mattwynne** [comment]
FYI don't assume a cedar-14 upgrade will be plain sailing. Some C extension refused to build and had to get ripped out and replaced. Not exactly what I had in mind for this evening!

**Comment by myronmarston** [comment]
Thanks, @mattwynne!

**Comment by NelsonScott** [comment]
:+1: :100:

**Comment by marcamillion** [comment]
Nice. +1

Thanks Matt!

On Friday, October 16, 2015, Scott Nelson <notifications@github.com> wrote:

> [image: :+1:] [image: :100:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rspec/rspec-rails/issues/1477#issuecomment-148868140>.
>


-- 
Marc Gayle
www.marcgayle.com
www.twitter.com/marcgayle
