### ISSUE TITLE
Automatically pluralize scoped controllers generator

### ISSUE THREAD

**Issue by adham90** [rspec/rspec-rails#1481]
When generating a `controller` with `rails g rspec:controller` the filename didn't get pluralized automatically

run: `$ rails g rspec:controller question`
output:
```bash
create  spec/controllers/question_controller_spec.rb
```

what if the file name get pluralized automatically?
I could try to implement this if it's accepted.

**Comment by JonRowe** [comment]
Thanks for the suggestion but we don't want to guess as to wether you want a pluralised name or not. If you want the pluralised name you should specify it plural on the command line.
