### ISSUE TITLE
Missing matcher for rendering text

### ISSUE THREAD

**Issue by Bartuz** [rspec/rspec-rails#1482]
Is it possible to examine if `get` request rendered text?

I know there are hacks like `response.body == 'any string'` but it does not interest me. I'm just wondering if there is "RSpec™" way to do it.

Having this rspec:
```
RSpec.describe MyController, type: :controller do
  controller do
    def index
      render text: 'Hellow'
    end
  end

  describe 'rendering' do
    subject { get :index }
    it { is_expected.to render_template(text: 'Hellow')}
  end
end
```
I would love to be able to call `it { is_expected.to render_template(text: 'Hellow')}`. It raises:
```
     Failure/Error: it { is_expected.to render_template(text: 'Hellow') }
     ArgumentError:
       Unknown key: :text. Valid keys are: :layout, :partial, :locals, :count, :file
```
or maybe `    it { is_expected.to render_template('Hellow')}`
```
     Failure/Error: it { is_expected.to render_template('Hellow') }
       expecting <"Hellow"> but rendering with <[]>
```

Is there any RSpec™ way to accomplish it?

**Comment by Bartuz** [comment]
Answer on that from SO: http://stackoverflow.com/a/33393300/2047418

**Comment by myronmarston** [comment]
I agree.  The "RSpec way", as you call it, isn't to use a different for every situation -- it's to use whatever expresses the expectation well and provides a good error message.  Using `eq` works just fine here.  Closing.
