### ISSUE TITLE
Controller tests are unable to reach controller

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [rspec/rspec-rails#1491]
I am using rspec-rails 3.2.1

I have controller test for a controller that is only accessible via a routing constraint. The routing constraint  looks at the `Accept` header to determine whether to route to that controller or not.

The route looks something like:
```ruby
scope constraint: VersionConstraint.new do
  post '/members', to: 'v3/members#create'
end
```

The constraint looks something like:
```ruby
class VersionConstraint
  def matches?(req)
    !!(req.accept =~ /application\/vnd\.api\+json; version=3/)
  end
end
```

My controller tests look something like
```ruby
describe V3::MembersController, 'POST #create' do
  before do
    post :create # with some other parameters
  end
end
```

Which gives me the error
```
ActionController::UrlGenerationError:
       No route matches {:action=>"create", :apikey=>"123456789", :controller=>"v3/members", :format=>:json}
```

I even tried setting the the header in the tests:
```ruby
describe V3::MembersController, 'POST #create' do
  before do
    @request.accept = 'application/vnd.api+json; version=3' # did not change anything
    @request.headers['Accept'] = 'application/vnd.api+json; version=3' # did not change anything
    @request.headers['HTTP_ACCEPT'] = 'application/vnd.api+json; version=3' # did not change anything

    post :create # with some other parameters
  end
end
```

I attempted to make a request outside of my tests and the constraint is working correctly.

Is there any way to make the controller tests not care about the routing infrastructure? It seems kind of silly; like it cares enough to look at the routing infrastructure, but not enough to apply the constraints...

**Comment by JonRowe** [comment]
You need to do `post :create, your_params, 'ACCEPT' => 'application/vnd.api+json; version=3'` as the post command creates it's own request.

> I am using rspec-rails 3.2.1

Please consider upgrading to `3.3.x`, semantic versioning means theres no reason to lag behind! :)

**Comment by myronmarston** [comment]
> Please consider upgrading to 3.3.x, semantic versioning means theres no reason to lag behind! :)

Except 3.3.x _is_ behind, since 3.4 was just released. I think @JonRowe meant to upgrade to 3.4 :).

**Comment by JonRowe** [comment]
Cough, I did :)
