### ISSUE TITLE
have_enqueued_job must have a way to be used after the job has been enqueued

### ISSUE THREAD

**Issue by sobrinho** [rspec/rspec-rails#1495]
I have a service object which creates a active record object, enqueue a background job for that object and returns the object.

I would like to ensure that the job has been scheduled with the given object but there is no way to do that, i.e.:

``` ruby
expect {
  my_model = MyServiceObject.call(...)
}.to have_enqueued_job(MyJob).with(my_model) }
```

I was expecting something like:

``` ruby
my_model = MyServiceObject.call(...)

expect(MyJob).to have_been_enqueued.with(my_model)

# or this

expect(MyJob).to have_been_enqueued.with(GlobalID.create(my_model))
```

Makes sense? There is any other way to do that?

**Comment by JonRowe** [comment]
```Ruby
expect {
  my_model = MyServiceObject.call(...)
}.to have_enqueued_job(MyJob).with(GlobalID.create(my_model))
```

should work, as it compares the arguments on the queue

**Comment by JonRowe** [comment]
Scoping might be an issue tho, as my_model would have to exist first

**Comment by samphippen** [comment]
@sobrinho can you confirm this is still an issue after @JonRowe's answer please?

**Comment by sobrinho** [comment]
It wouldn't work because the expect block does not leak the variable:

``` ruby
irb(main):001:0> x = lambda { foo = 1 }
=> #<Proc:0x007febfc155050@(irb):1 (lambda)>
irb(main):002:0> x.call
=> 1
irb(main):003:0> foo
NameError: undefined local variable or method `foo' for main:Object
	from (irb):3
	from /usr/bin/irb:12:in `<main>'
```

**Comment by sobrinho** [comment]
Declaring the variable before the block gets called works but it's tricky to understand.

A better way would be to have an API similar to this:

``` ruby
it 'enqueues an job' do
  my_model = MyServiceObject.call(...)

  expect(MyJob).to have_been_enqueued.with(GlobalID.create(my_model))
end
```

**Comment by JonRowe** [comment]
This will work:

```ruby
my_model = nil
expect {
  my_model = MyServiceObject.call(...)
}.to have_enqueued_job(MyJob) { |arg| expect(arg).to eq GlobalID.create(my_model) }
```

**Comment by samphippen** [comment]
@JonRowe we need to be able to provide a better api than that IMO! That's very non-obvious.

**Comment by JonRowe** [comment]
We do, we provide `with`, but the object isn't known about at the time of the creation of expectation, an another alternative would be to refactor the service to take in its collaborators rather than relying on the return value being created. The block format for the matcher is currently required to garner detail about changes in queue size.

**Comment by samphippen** [comment]
@JonRowe so do we close this, or is there something we can do?

**Comment by JonRowe** [comment]
I'm going to say no, theres nothing we can do at this time.
