### ISSUE TITLE
PUT vs PATCH behaviour

### ISSUE THREAD

**Issue by NekoNova** [rspec/rspec-rails#1498]
## Description ##
Let me start by providing a bit of background information. We are currently in the process of upgrading our Rails 3.2 application to 4.2. During the upgrade we ran into a problem where we have the following route originally defined:

```
resources :entities, except: [:show] do
    member do
      put :change_monitoring_status
    end
  end
```

When I run the command `rake routes`, I can clearly see the route `change_monitoring_status` being defined as a member route of the supplier, with `PUT`
However, when we generate a form using `simple_form` and rails for this route, the method is being submitted as `PATCH`. Which according the changes in Rails 4 should be okay.

The problem however is that results in a `404 - Not Found` on our production application because the route is defined as PUT, but we submit PATCH.
So we tried to write an RSpec test to mimic this behaviour.

```
 describe '#change_monitoring_status' do

    before(:each) do
      sign_in user
    end

    it 'fails when put is used' do
      expect {
        put :change_monitoring_status, id: entity.id, _method: "PUT", form_object: {  }
      }.to raise_error
    end

    it 'works when patch is used' do
      expect {
        patch :change_monitoring_status, id: supplier.id, _method: "PATCH", form_object: {  }
      }.to_not raise_error
    end
  end
```

However this does not produce the desired behaviour. The `PUT` request is still going through, not throwing an error. The `PATCH` test passes as expected when we changed the route definition.
Yet, this is the weird part: 

* Route is defined now as **PUT**
* `PUT` still works in RSpec
* `PATCH` works in RSpec
* `PATCH` does not work on production.

Are we testing/understanding the problem wrong here, or are we looking in the wrong place?

**Comment by JonRowe** [comment]
@NekoNova RSpec uses Rails underlying test semantics to work this out so it's behaving as Rails would, so I suggest you're looking in the wrong place. It could be Rails itself at fault (unlikely) but I'd imagine it's more likely your app server / front end is doing something with the `PATCH` requests.

**Comment by NekoNova** [comment]
we've actually dived deeper into this and came to an interesting conclusion:

When you write ControllerTests, this behaviour occurs.
However, when you write Integration tests, the behaviour is working as expected.

I will open an issue with Rails for this.
