### ISSUE TITLE
assigns don't work on controller spec

### ISSUE THREAD

**Issue by yzhrain** [rspec/rspec-rails#15]
on UserController.rb,i write following code :
@user = User.new

but on UserController spec file
assigns[:user].should_not be_nil  # failed!!

assigns[:user] return nil alway.

**Comment by imaginationcoder** [comment]
hi all,  
i am using rails 4 and rspec 3.4.
At my controller spec, assigns is always empty. 

Can some one help me here. Thanks in advance
