### ISSUE TITLE
pass a `let` variable like a argument to `shared_example`?

### ISSUE THREAD

**Issue by VoTaiTri** [rspec/rspec-rails#1511]
hello, i've some problem with `shared_example`
anyone can help me? thank!
first, i've defined variable by `let` block like that : 
```ruby
let(:messages) do
  {
    auth_false: "Access denied",
    # other messages
  }
end
```
and my `shared_examples` like :
```ruby
shared_examples "get danger flash" do |message|
  it{ expect(flash[:danger]).to eq(message) }
end
```
in my test case, i call : 
```ruby
it_should_behave_like "get danger flash", messages[:auth_false]
```
and when i run rspec, i get error:
`'method_missing': undefined local variable or method 'auth_false' for ...`
so, can't we pass a `let` variable like a argument to `shared_examples` like above?

**Comment by myronmarston** [comment]
You can pass a block to `it_should_behave_like` to define hooks, `let` declarations, etc for use by the shared group:

``` ruby
shared_examples "get danger flash" do
  it{ expect(flash[:danger]).to eq(message) }
end

it_should_behave_like "get danger flash" do
  let(:message) { messages[:auth_false] }
end
```

**Comment by VoTaiTri** [comment]
@myronmarston. thanks you so much!
