### ISSUE TITLE
Dependency problem actionpack with rails 5

### ISSUE THREAD

**Issue by alestuber** [rspec/rspec-rails#1517]
Hi,

I'm trying to update rspec 3.1 to some of the new versions (3.2, 3.3, 3.4) to get the following bug fix on 3.2:
```
Bug Fixes:

Fix rspec:feature generator to use RSpec namespace preventing errors when monkey-patching is disabled. (Rebecca Skinner, #1231)
```
I'm using Rails 5 beta and there lies the problem: I can't update rspec to any version newer than 3.1 because of the dependency on actionpack (which can't use the actionpack (= 5.0.0.beta1)):
```
rspec-rails (>= 3.2) was resolved to 3.2.0, which depends on
      actionpack (<= 4.2, >= 3.0)

----------------------
```
That said, I can run the tests if I put RSpec.feature by hand on my tests, or if I enable monkey_patching even though that's not the "better way".

**Comment by jasnow** [comment]
Try this in your Gemfile:
```
  gem 'rspec-rails'       , github: 'rspec/rspec-rails'
  gem 'rspec-core'        , github: 'rspec/rspec-core'
  gem 'rspec-expectations', github: 'rspec/rspec-expectations'
  gem 'rspec-mocks'       , github: 'rspec/rspec-mocks'
  gem 'rspec-support'     , github: 'rspec/rspec-support
```

**Comment by JonRowe** [comment]
As above, you need to use the `master` version of `rspec-rails` and friends, but we're working on getting out a version that supports the beta (although this will similarly be a beta for us)
