### ISSUE TITLE
Custom Rails exceptions app is not performed in controller specs

### ISSUE THREAD

**Issue by d3crypt3d** [rspec/rspec-rails#1530]
Hello, I'm having trouble when testing controller specs. I use a custom exceptions app:
```ruby
module RailsApp
  class Application < Rails::Application
    # other config stuff
    config.exceptions_app = FooApp.new(Rails.public_path)
  end
end
```
 And everything works as expected when I use curl or browser. But when I try to test it with Rspec I observe a strange behaviour: seems my exceptions app is **omitted** by my specs at all (discovered this with debugging)! And I get 200 status intead of 404 when requesting a non-existing resource. 
I have already set `config.consider_all_requests_local = false` and `config.action_dispatch.show_exceptions = true` in `config/enironments/test.rb`, but it changes nothing. Here is an example from my specs:
```ruby
RSpec.describe API::V1::ProjectsController do
  describe "DELETE #destroy" do
    let(:proj) { create(:project) }

    subject { response }

    # following works like a charm
    context "with valid id" do
      before { make_request :delete, :destroy, id: proj.id }

      it { is_expected.to have_http_status(204) }
      it { expect(Project.exists? proj).to be_falsey }
    end

    # fails - exceptions app doesn't start at all; the description is:
    # Failure/Error: before { make_request :delete, :destroy, id: proj.id + 1 }
    #        ActiveRecord::RecordNotFound:
    #            Couldn't find Project with 'id'=980192933
    # but response ruturns with the status 200 - that's why the test fails
    context "when a resourse is not found" do
      before { make_request :delete, :destroy, id: proj.id + 1 }

      it { is_expected.to have_http_status(404).and have_content_type(:json) }
    end
end
```
I have the following gems versions: rails (4.1.1), rspec-rails (3.0.0), rspec (2.99.0), rspec-expectations (3.0.0), rspec-its (1.0.1).

**Comment by JonRowe** [comment]
You actually want to raise exceptions, not show them, a 200 would be the page response showing the exception and backtrace in standard Rails format (ala development mode). This is not something RSpec controls directly, you need to configure Rails to load your custom exception handling.

**Comment by d3crypt3d** [comment]
But I have already done that. And as I said, everything works fine when I use curl (I start the server in test environment).

**Comment by JonRowe** [comment]
RSpec is not responsible for setting up controllers for tests, we leave that to Rails, (rspec-rails is a thin shim around Rails own test setup), maybe raise the issue there?

**Comment by JonRowe** [comment]
Although is `config.action_dispatch.show_exceptions = true` a typo? As you need this to be `false` to get exceptions actually raised... (or am I misunderstanding how the exception app works?)

**Comment by d3crypt3d** [comment]
@JonRowe said
> Although is config.action_dispatch.show_exceptions = true a typo?

No, it's not a typo. By default it's set to false:
```ruby
# Raise exceptions instead of rendering exception templates.
  config.action_dispatch.show_exceptions = false
```

@JonRowe said
> RSpec is not responsible for setting up controllers for tests, we leave that to Rails, (rspec-rails is a thin shim around Rails own test setup), maybe raise the issue there?

If I knew what actually happens under the hood when a controller spec is invoked... 
Yesterday I was experementing a lot. I discovered that controller specs **completely omit** `ActionDispatch::ShowExceptions` instance. This stuff works in pair with `ActionDispatch::ExceptionWrapper` and another app, that process an exception in further (by default `ActionDispatch::PublicExceptions`). So, seems beacuse ExceptionWrapper has not been invoked, controller spec doesn't properly process different kind of errors until one explicitly sets this at controller level. For example, when I start a controller spec where 404 situation is imitated, the response with an error is returned, although having status 200 (see my first post). But if I explicitly set the following at controller level:
```ruby
rescue_from 'ActiveRecord::RecordNotFound' do |exception|
    # Setting status: :not_found is vitaly important!
    render json: {errors: exception.message}, status: :not_found
end
```
everything works like a charm. I tried to use the default configuration file for test environment, but it changes nothing. And again, there are no problems when using **curl** - Rails' apps, those are supposed to handle errors, do what they are meant to do, when Rails having been started withing **same environment with same configuration**. 
So whose responsibility to start a bunch of exceptions app during the controller testing?

**Comment by JonRowe** [comment]
Rails determines what runs where, starting up a server is not the same as
initialising a controller for a test. If you write a feature spec for this
you'll probably find it behaves as you expect.

**Comment by d3crypt3d** [comment]
Yes, it does behave a different for each kind of specs. When it comes for controller specs, all actions are performed within the controller scope - seems this is the way it's designed. Nevertheless, thank you John.

**Comment by pixeltrix** [comment]
@d3crypt3d controller specs are essentially unit tests for controllers and as such do not exercise the full stack - the action is called directly on the instance of the controller and not through Rack. Therefore the exception middleware is never called and knows nothing about the exception. This is a common misconception - the number of times I've pointed it out on the Rails bug tracker has probably reached double figures. What you need to use for testing your exception app is a request spec - that sends a proper request to the app and it will show any exceptions if the config is set correctly (which it appears that you have done).

In Rails 5.0 `ActionController::TestCase` is deprecated (softly - we don't log a warning) because we improved the performance of integration tests so much that they are faster than controller tests in Rails 4.2 so it doesn't make sense to keep the distinction between controller specs and request specs. What that means for the future of controller specs in RSpec I don't know. :smile:

**Comment by JonRowe** [comment]
@d3crypt3d it means when you hard deprecate them we will too

**Comment by d3crypt3d** [comment]
@pixeltrix how does Rails configure each kind of specs? I mean under the hood.

**Comment by pixeltrix** [comment]
@d3crypt3d Rails defines a number of minitest/test-unit classes - one for each type of test, e.g `ActionController::TestCase`, `ActionView::TestCase`, etc. Inside each of these classes there's a `Behavior` module that rspec-rails uses to create the various example groups, controller specs, view specs, etc. These `Behaviour` modules include a lot of other modules like `Rails.application.routes.url_helpers` that are needed for supporting assertions on routes, etc. Then there's also quite a bit of glue code in there to tie everything together. Even some of the matchers are essentially wrappers around Rails assertion methods like `assert_template`.

Exact details are a little bit too much to go into here but here are the main ones that are more than just a few lines:

[ActionController::TestCase][1]
[ActionDispatch::IntegrationTest][2]
[ActionVIew::TestCase][3]

[1]: https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb
[2]: https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb
[3]: https://github.com/rails/rails/blob/master/actionview/lib/action_view/test_case.rb

**Comment by JonRowe** [comment]
Yeah `rspec-rails` is just a thin wrapper around Rails own testing stuff
