### ISSUE TITLE
route_to: test route with params inside route get an error

### ISSUE THREAD

**Issue by petRUShka** [rspec/rspec-rails#154]
rake routes:
<code>admin_subdomain_order GET    /admin/:subdomain/posts/:id(.:format)      {:controller=>"admin/posts", :action=>"show"}</code>
spec:
<code>{:get => "/admin/subdomain/posts/221"}.should route_to({ :controller => "admin/posts", :action => "show", :id => "221", :subdomain => 'subdomain'})</code>
Output:
<code><pre>    Failure/Error: {:get => "/admin/subdomain/posts/221"}.should route_to({ :controller => "admin/posts", :action => "show", :id => "221", :subdomain => 'subdomain'})
    found extras <{:subdomain=>"subdomain"}>, not <{}>.
    Expected block to return true value.
    # /home/petrushka/.bundler/ruby/svn/rails-b7c4523/actionpack/lib/action_dispatch/testing/assertions/routing.rb:87:in `assert_generates'
    # /home/petrushka/.bundler/ruby/svn/rails-b7c4523/actionpack/lib/action_dispatch/testing/assertions/routing.rb:124:in`assert_routing'
    # ./spec/controllers/admin/posts_controller_spec.rb:41:in `block (3 levels) in <top (required)>'
</pre></code>

Rspec.2.0.0.beta.19
rails.rc from master branch
ruby 1.9.3dev (2010-05-08 trunk 27674) [x86_64-linux]

**Comment by abo-elleef** [comment]
@petRUShka I got the same issue and got it fixed inspired by[ this blog post ](http://til.obiefernandez.com/posts/b540850342-using-defaulturloptions-in-rspec-with-rails-5 ) and play around with debugger
