### ISSUE TITLE
No documentation for testing Mailers in README

### ISSUE THREAD

**Issue by andrewhavens** [rspec/rspec-rails#1552]
I see examples of most other common classes in the README. However, I don't see any examples for testing mailers. I happen to be trying to test a mailer, and looking for examples, but I am finding it hard to find examples of how to test html emails with RSpec. An example in the README would be helpful for others trying to do this.

**Comment by JonRowe** [comment]
Thanks for this, closing in favour of #1553, check it out if you still need some help :)
