### ISSUE TITLE
Rspec installation error - Invalid argument @ dir_s_mkdir

### ISSUE THREAD

**Issue by emclab** [rspec/rspec-rails#1555]
I just moved to a new laptop running on Win 10/ruby 2.2.2/Rails 4.2.0 (No problem on previous Win 8 ruby 2.0.0/Rails 4.2/rspec 3.2). Now when installing rspec, there is a strange error below:
```
$ rails g rspec:install
   identical  .rspec
       exist  spec
      create  spec/C:/Users/Jun C/AppData/Local/Temp/d20160219-10996-1x6hu8w/spec/spec_helper.rb
C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Invalid argument @ dir_s_mkdir - C:/D/code/rails_proj/engines/simple_orderx/spec/C: (Errno::EINVAL)
        from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
        from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
        from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
        from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
        from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:210:in `each'
        from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:61:in `block in invoke!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
```
There is /spec under Rails app root. The spec-helper file should be generated under /spec as /spec/spec-helper.rb. However the installation tried to generate spec-helper at spec/C:/Users/Jun C/AppData/Local/Temp/d20160219-10996-1x6hu8w/spec/. It seems that the path is wrong.

Here is the line in Gemfile:

`s.add_development_dependency "rspec-rails", ">= 3.2.0"`

Here is the config in engine.rb
```
   config.generators do |g|
      g.template_engine :erb
      g.integration_tool :rspec
      g.test_framework :rspec
      g.fixture_replacement :factory_girl, :dir => "spec/factories"  
    end  
```
The rspec version is 3.2.2. How to fix this wrong path in rspec installation?

**Comment by JonRowe** [comment]
As I mentioned in my reply to your email, can you try this:

```
require 'tempfile'
Dir.mktmpdir { |d| puts d }
```

In irb/ruby? It should work without an error...

**Comment by emclab** [comment]
Hi, Here is the output of irb:

C:\D\code\rails_proj\engines\simple_orderx>irb
irb(main):001:0> require 'tempfile'
=> true
irb(main):002:0> Dir.mktmpdir { |d| puts d}
C:/Users/JUNC~1/AppData/Local/Temp/d20160225-10316-1oexvut
=> nil
irb(main):003:0>

Not sure why it points to C:/Users/JUNC~1.... The app is under c:\d\code\rails_proj\engines\simple_orderx.

**Comment by JonRowe** [comment]
Thats working as expected, tmp directories are created in your system temp location

**Comment by emclab** [comment]
What caused the error in generator then?

**Comment by JonRowe** [comment]
Honestly I don't know at this point, it looks like it's trying to combine the tmpdir path with your project path, this could be a Rails thing, or it could be an RSpec thing, none of the core team use windows so this isn't easy for us to check.

**Comment by JonRowe** [comment]
So I've looked into this, we create files based on a template, and place them into a temp directory to give to Rails. It's Rails that copies them into place in your project not us, and this error is happening when that happens, I suggest you open an issue with Rails :/

**Comment by sydneywu** [comment]
Hi i am also encountering this problem. Instead of waiting for Rails team to solve this problem, can you tell us what exactly does rails g rspec:install create? Are we able to do it manually? Will need this to proceed with a tutorial i am going through

**Comment by jasnow** [comment]
```
      create  .rspec
      create  spec (directory)
      create  spec/spec_helper.rb
      create  spec/rails_helper.rb
```

**Comment by alxmcr** [comment]
Hello everyone.

Checking online, I found that the problem is that the **above-2.8.0 versions** causes problems with **Windows 7 (in my case: 32-bit)**

A possible **solution** to run the command, without problems:

**Gemfile**

```
group: do test
   gem 'rspec-rails', '2.8'
end
```

But, comparing, possible **differences**, I found that there is a change with higher version **2.8**, such as **3.0**:

**.rspec** (generated: gem 'rspec-rails', **'~> 3.0'**)

```
--color
--require spec_helper
```

Now,

**.rspec** (generated: gem 'rspec-rails', '2.8'**)

```
--colour
```

There was a change **"--color"** to **"--colour"** and apparently there is a new property "--require spec_helper".

The truth, if not the possible cause of the problem? or is there another ?.

_**Please, I would be very grateful, if you help me solve this problem.**_

**Comment by nbogis** [comment]
The problem with your solution @alxmcr is that everything is generated fine except  rails_helper.rb. I did what you suggested but the rails helper file is not part of the installation files. I assume we need this file to run the tests. Did they introduce this file on versions > 3.0?

**Comment by adamw005** [comment]
> Hi i am also encountering this problem. Instead of waiting for Rails team to solve this problem, can you tell us what exactly does rails g rspec:install create? Are we able to do it manually? Will need this to proceed with a tutorial i am going through



> ```
>       create  .rspec
>       create  spec (directory)
>       create  spec/spec_helper.rb
>       create  spec/rails_helper.rb
> ```

spec/rails_helper.rb:
https://github.com/rspec/rspec-rails/blob/master/lib/generators/rspec/install/templates/spec/rails_helper.rb
