### ISSUE TITLE
append_view_path monkey patch breaks API

### ISSUE THREAD

**Issue by ramhoj** [rspec/rspec-rails#1556]
https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/view_rendering.rb#L77 is being called instead of Rails' implementation https://github.com/rails/rails/blob/7f18ea14c893cb5c9f04d4fda9661126758332b5/actionview/lib/action_view/view_paths.rb#L51

The difference is that rspec-rails' version expects a string while Rails' version also accepts an array.

Fixing this could be done with something like:
```ruby
decorators = Array(new_path).map { |path| _path_decorator(path) }
lookup_context.view_paths.push(*decorators)
```
#1551 might resolve this by accident if merged.

**Comment by JonRowe** [comment]
Yep it appears the array handling was lost in the previous fix for Rails 5 (we used `Array.wrap` previously)
