### ISSUE TITLE
RSpec tests fail with RecordNotFound error when querying on shard

### ISSUE THREAD

**Issue by tipycalFlow** [rspec/rspec-rails#1562]
Hi,
I'm facing the following error (trace included) in my rspec tests that fail for records that exist on different shards:

    ActiveRecord::RecordNotFound:
           Couldn't find PushApplication with 'id'=9
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/activerecord-4.2.3/lib/active_record/core.rb:155:in 'find'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/ar-octopus-0.8.5/lib/octopus/scope_proxy.rb:43:in 'block in method_missing'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:226:in 'block (2 levels) in run_queries_on_shard'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:476:in 'using_shard'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:225:in 'block in run_queries_on_shard'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:462:in 'keeping_connection_proxy'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:224:in 'run_queries_on_shard'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/ar-octopus-0.8.5/lib/octopus/shard_tracking.rb:30:in 'run_on_shard'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/ar-octopus-0.8.5/lib/octopus/scope_proxy.rb:43:in 'method_missing'
    ./app/controllers/push_applications_controller.rb:165:in 'find_application'   <<--------------------
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430:in 'block in make_lambda'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:162:in 'call'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:162:in 'block in halting'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in 'call'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in 'block in call'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in 'each'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in 'call'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in 'run_callbacks'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in 'process_action'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in 'process_action'
    /Users/aakash/.rvm/gems/ruby-2.2.2@rails4/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in 'block in process_action'

The `find_application` method inside push_applications_controller queries for a push_app object like so:
`PushApplication.using(:shard_name).find(params[:id])`. I'm guessing this is because FactoryGirl lazy loads objects so there's no record available in actual test db but I'm not sure of the correct way of doing this. Any ideas?

**Comment by JonRowe** [comment]
You need to ensure your shard is setup with test data before querying it, I can't suggest anything here as you've not mentioned anything about that. FactoryGirl doesn't create anything unless you tell it to so I suggest you do that before querying it.

**Comment by tipycalFlow** [comment]
In my controller spec, I create the object instance `let!(:push_application) { create(:push_application, account: account) }` and log the object before the query. I can see that it has the id (and other attributes defined in FactoryGirl) for which no record was found, which makes it difficult to debug.

**Comment by JonRowe** [comment]
I'm not sure what you're sharding here (or using to do it) but is it possible it's ending up in the wrong shard?

**Comment by tipycalFlow** [comment]
I wasn't doing it right. Indeed, Rspec doesn't save data to database unless told to do so, which was why the queries were failing. Instead of `let`, I'm using the standard way `Model.using(:shard_name).new` so now the actual controller and rspec are on the same page. Apologies for the trouble.

**Comment by JonRowe** [comment]
RSpec doesn't sae data at all ;)
