### ISSUE TITLE
autosave/nested-attributes issue

### ISSUE THREAD

**Issue by sjreich** [rspec/rspec-rails#1564]
rails: 4.2.5.1
rspec-rails: 3.4.2

I was trying to sort out an issue in my code concerning updating one object via an associated object, and I think I discovered an rspec issue.  If this is just a newbie error, forgive me.

The problematic code:

```ruby
    t1 = Thing1.create(name: 'first1')
    t2 = Thing2.create(name: 'first2')
    t1.thing2s << t2
    params = { thing2_name: 'second2' }
    t1.update(params)
    t2.reload
    puts t2.name
```

The background setup:

```ruby
class Thing1 < ActiveRecord::Base
  has_many :thing2s
  accepts_nested_attributes_for :thing2s

  def thing2_name
    thing2s.first.name
  end

  def thing2_name=(input)
    thing2s.first.name = input
  end
end

#######

class Thing2 < ActiveRecord::Base
  belongs_to :thing1
end
```

If I run the problematic code in the rails console, the final output is "second2", as (I think) it ought to be.
If I stick that exact same code into an rspec test, the final output is "first2".  (Obviously, it's an ugly-looking test, but I was just trying to isolate the variables here.)

**Comment by JonRowe** [comment]
The "correct" output of your snippet is "first2" as that's t2's name and you never change it, I don't know why you get `'second2'` in `rails console` but you shouldn't as that name should be a completely seperate instance of `Thing2` which you never touch

**Comment by sjreich** [comment]
Hm, are you sure you're fully appreciating the interaction between `has_many` and `accepts_nested_attributes_for`?  That combination should allow you to change one object through an associated object.

What I'm trying to do is only a slight variation on what's described in the [documentation for Active Record Nested Attributes](http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html).  Here's the relevant portion from the documentation:

### One-to-many

Consider a member that has a number of posts:
```
class Member < ActiveRecord::Base
  has_many :posts
  accepts_nested_attributes_for :posts
end
```
You can now set or update attributes on the associated posts through an attribute hash for a member: include the key :posts_attributes with an array of hashes of post attributes as a value.

For each hash that does not have an id key a new record will be instantiated, unless the hash also contains a _destroy key that evaluates to true.
```
params = { member: {
  name: 'joe', posts_attributes: [
    { title: 'Kari, the awesome Ruby documentation browser!' },
    { title: 'The egalitarian assumption of the modern citizen' },
    { title: '', _destroy: '1' } # this will be ignored
  ]
}}

member = Member.create(params[:member])
member.posts.length # => 2
member.posts.first.title # => 'Kari, the awesome Ruby documentation browser!'
member.posts.second.title # => 'The egalitarian assumption of the modern citizen'
```

**Comment by sjreich** [comment]
Thanks for your time, in any case.

**Comment by JonRowe** [comment]
> Hm, are you sure you're fully appreciating the interaction between has_many and accepts_nested_attributes_for? That combination should allow you to change one object through an associated object.

Yes, however you are not specifying an id, thus it creates a new thing2. To modify an existing thing2 you must specify it's id.

**Comment by sjreich** [comment]
Thanks for sticking with me here - I still think there's an issue.  On further investigation, it looks like the discrepancy stems from `autosave` (which comes along with `accepts_nested_attributes_for`).

New setup:
```ruby
class Thing1 < ActiveRecord::Base
  has_many :thing2s, autosave: true
end

###########

class Thing2 < ActiveRecord::Base
  belongs_to :thing1
end
```
New code for generating the discrepancy:
```ruby
    t1 = Thing1.create
    t2 = Thing2.create(name: 'original_name')
    t1.thing2s << t2
    t1.thing2s.first.name = 'new_name'
    t1.save
    t2.reload
    puts t2.name
```

If you run that code in the console, the output is 'new_name'.  If you stick the exact same code in a test, the output is 'original_name'.

Again, maybe I'm missing something, but 'new_name' seems like the expected result here.  The whole point of `autosave` is that saving a parent also saves its children.

**Comment by JonRowe** [comment]
In the case above, `new_name` is the expected result assuming autosave is working, this is the opposite setup to your first example. Have you checked what `t2= t1.thing2s.first; t2.name = 'new_name'; t2.save!` does?

However this cannot be an RSpec issue, we don't do anything interfering with the save process, it's all up to your tests and implementation, if you paste your test structure I might be able to spot if you're doing something odd.

**Comment by sjreich** [comment]
If I stick in what you suggested, I get 'new_name' as the result either way (console of rspec).  This confirms my hunch that there's something weird about `autosave`.

But if rspec doesn't interfere with the save process at all, then... it's a mystery, and I can let it go.

The discrepancy-producing code above, wrapped in an it-block and a describe-block, is literally the extent of my tests.  As I said, this was just a dummy app I set up to try to get clear on some behavior in a more complicated app.

**Comment by Viktor-Ivliev** [comment]
JonRowe , You need to use [0]. Because "first" use ActiveRecord and initialisere new object id (not cache)
t1.thing2s[0].name = 'new_name'
