### ISSUE TITLE
Best rspec version for Rails 5

### ISSUE THREAD

**Issue by lesliev** [rspec/rspec-rails#1566]
Can the maintainers clarify what the recommended version of rspec for Rails 5 would be right now? It seems to be 3.5.0.beta1, but I noticed that just putting "rspec" in Gemfile will give you a much older released version which was non-specific about its actionpack requirements.

**Comment by JonRowe** [comment]
Rails 5 is only supported by `3.5.0.beta1` and above (this includes `master`)

**Comment by lesliev** [comment]
Thanks!
