### ISSUE TITLE
have_enqueued_job can't be used with data that has not yet been created

### ISSUE THREAD

**Issue by jschroeder9000** [rspec/rspec-rails#1576]
This is somewhat a continuation of #1495.  I am using rspec-rails 3.4.2.

The crux of the issue is that data created in the `expect` block can't be used for validation in parameters to `with`.

E.g. if I have a controller like:

```ruby
UsersController < ApplicationController
  def create
    @user = User.create user_params
    UserMailer.welcome(@user).deliver_later
  end
end
```

And I want to write a test that checks that the mailer was enqueued with the correct parameters, I might write a test like:

```ruby
it 'sends welcome email' do
  expect {
    post :create, params
  }.to have_enqueued_job(ActionMailer::DeliveryJob).with(
    'UserMailer',
    'welcome',
    'deliver_now',
    Account.order(:created_at).last,
  )
end
```

But that doesn't work because the parameters passed to `with` are evaluated before the `expect` block is executed.

In #1495, @JonRowe suggests doing something like:

```ruby
my_model = nil
expect {
  my_model = MyServiceObject.call(...)
}.to have_enqueued_job(MyJob) { |arg| expect(arg).to eq GlobalID.create(my_model) }
```

But that doesn't actually work.  The block after `have_enqueued_job` never actually gets executed.  AFAICT there is no supported way of doing something like this so I thought it might be worth another look.

I have worked around this with a monkey patch like so:

```ruby
module RSpec
  module Rails
    module Matchers
      module ActiveJob
        class HaveEnqueuedJob
          private

          def serialized_attributes
            args_to_serialize = []
            @args.each do |arg|
              arg = arg.call if Proc === arg
              args_to_serialize << arg
            end

            {}.tap do |attributes|
              attributes[:args]  = ::ActiveJob::Arguments.serialize(args_to_serialize) if args_to_serialize.any?
              attributes[:at]    = @at.to_f if @at
              attributes[:queue] = @queue if @queue
              attributes[:job]   = @job if @job
            end
          end
        end
      end
    end
  end
end
```

Then I can change my test to pass lambdas to `with` that get evaluated after the `expect` block is executed:

```ruby
it 'sends welcome email' do
  expect {
    post :create, params
  }.to have_enqueued_job(ActionMailer::DeliveryJob).with(
    'UserMailer',
    'welcome',
    'deliver_now',
    -> {Account.order(:created_at).last},
  )
end
```

I wonder if there is an argument to be made to legitimize the use of lambdas like this given that GlobalID does not support serializing procs/lambdas?  Any other thoughts on supporting this type of scenario?

**Comment by JonRowe** [comment]
We're not going to accept lambdas as arguments like that, `with {}` should work and if not someone should fix that.

**Comment by jschroeder9000** [comment]
Here's a sample app demonstrating it doesn't work:

https://github.com/jschroeder9000/rails-rspec-1576

See especially:

https://github.com/jschroeder9000/rails-rspec-1576/blob/master/spec/controllers/users_controller_spec.rb

Unfortunately, I'm not sure where to begin trying to fix it.

**Comment by JonRowe** [comment]
Have a look at `lib/rspec/rails/matchers/active_job.rb`, it needs to store a block passed into `with` or `initialize` and utilise in `matches?`

**Comment by JonRowe** [comment]
Happy to help review a PR updating the documentation, its basically the same usage as `with` from `receive(...).with(...)` from rspec-mocks

**Comment by SzNagyMisu** [comment]
Thanks a lot!
I will most happily provide a PR, only I don't see where I should start so that it will update the docs on relishapp (which repo to fork, which file to update...).

**Comment by JonRowe** [comment]
This repo, the cucumber features for the matcher, and/or add rdoc comments to the method

**Comment by SzNagyMisu** [comment]
Opened PR #2015
