### ISSUE TITLE
bundler: command not found: rspec

### ISSUE THREAD

**Issue by luckymaniac** [rspec/rspec-rails#1584]
After "bundle install" and "rails generate rspec:install", I run "bundle exec rspec", but I got 
bundler: command not found: rspec
Install missing gem executables with `bundle install`

I am using rails 4.1.1
Someone please let me know what I have to do.

**Comment by JonRowe** [comment]
You need to have `rspec` in your `Gemfile` for bundler to run rspec, but if your having issues with that then you need to talk to the bundler team as to why it isn't install things properly.

**Comment by luckymaniac** [comment]
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails', '~> 3.0'
end

Is there something wrong with it?

**Comment by JonRowe** [comment]
Not that I can see, (bar the turbolinks bit but I'm assuming thats a typo) but this isn't an RSpec issue, you should ask the Bundler team why your install can't see the executable
