### ISSUE TITLE
Can't find method in ApplcationHelper

### ISSUE THREAD

**Issue by draveness** [rspec/rspec-rails#1586]
I use RSpec to test posts_controller, and call a method in ApplicationHelper

```
RSpec.describe Api::V1::PostsController, type: :controller do

  render_views

  before(:each) do
    create(:user_with_posts, posts_count: 40)
  end

  describe "posts#index API" do
    it "is true" do

      get :index, format: :json

      json = JSON.parse(response.body)

      puts json

    end
  end
end
```

posts_controller.rb

```
class Api::V1::PostsController < Api::V1::BaseController
  def index
    @posts = paginate(Post.all)
  end
end
```

index.json.builder

```
json.paginate_meta do
  paginate_meta_attributes(json, @posts)
end

json.posts do
  json.array! @posts do |post|
    json.(post, :id, :title, :content)
    json.author do
      json.(post.author, :id, :email, :nickname)
    end
  end
end
```

application_helper.rb

```
module ApplicationHelper

  def paginate_meta_attributes(json, object)
    json.(object,
          :current_page,
          :next_page,
          :prev_page,
          :total_pages,
          :total_count)
  end
end
```

And when I run rspec

```
  1) Api::V1::PostsController posts#index API is true
     Failure/Error: paginate_meta_attributes(json, @posts)

     ActionView::Template::Error:
       undefined method `paginate_meta_attributes' for #<#<Class:0x007f8286389c70>:0x007f8286389310>
     # ./app/views/api/v1/posts/index.json.jbuilder:2:in `block in _app_views_api_v__posts_index_json_jbuilder__4514465265669488631_70099287053960'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder.rb:38:in `block in set!'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder.rb:266:in `block in _merge_block'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder.rb:305:in `_scope'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder.rb:266:in `_merge_block'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder.rb:38:in `set!'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder/jbuilder_template.rb:74:in `set!'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder.rb:66:in `method_missing'
     # ./app/views/api/v1/posts/index.json.jbuilder:1:in `_app_views_api_v__posts_index_json_jbuilder__4514465265669488631_70099287053960'
     # ./spec/controllers/posts_controller_spec.rb:14:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `paginate_meta_attributes' for #<#<Class:0x007f8286389c70>:0x007f8286389310>
     #   ./app/views/api/v1/posts/index.json.jbuilder:2:in `block in _app_views_api_v__posts_index_json_jbuilder__4514465265669488631_70099287053960
```

I don't why, but I define this method in ApplicationHelper, how to solve this problem.

Thx a lot.

**Comment by JonRowe** [comment]
As I stated on your other issue, helper inclusion is determined by Rails, can you provide your Rails version? Also have you checked that you're not restricting the helpers included in your parent controllers?

**Comment by Draveness** [comment]
Rails version is 4.2.4

I don't know whether I restrict it or not. But I don't change the entire app hierachy. I search ApplicationHelper globally and I just get one result.

![a5d1d39f-8349-4117-967b-fd954504f024](https://cloud.githubusercontent.com/assets/6493255/14069211/8686a52a-f4c9-11e5-91b7-d2088bd09fd2.png)

I didn't mention this module in other place

**Comment by chrisarcand** [comment]
Does the app behave as you expect with that helper _outside_ of RSpec? Unless it does, I sincerely doubt this is an RSpec issue and suggest consulting the [Ruby on Rails: Talk mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk), the [Ruby on Rails StackOverflow Q&A tag](http://stackoverflow.com/questions/tagged/ruby-on-rails), or the #rubyonrails IRC channel on irc.freenode.net. 

But this is already open, so: Is `Api::V1::BaseController` inheriting from `ApplicationController`? Rails looks up helpers automatically by the controller name against the helper name, so unless ApplicationController is somewhere up your inheritance chain that helper will not be included in your API posts controller.

**Comment by Draveness** [comment]
Yes `Api::V1::BaseController` inherit from ApplicationController. And I can use the method in ApplicationHelper directly in index.json.jbuilder

**Comment by chrisarcand** [comment]
Are you using normal Rails or `rails-api` (or `--api` in Rails 5, whichever)? Looks like autoloading helpers is a thing you'd have to enable, if so.

There are also numerous open issues having to do with jbuilder being screwy about including helpers in the correct context, your backtrace seems to indicate something similar.

**Comment by Draveness** [comment]
No..I'm not, my rails version is 4.2.4.. But that's ok.. Thx a lot

**Comment by tisba** [comment]
I'm in the process of upgrading an app to rails 5, and I have a similar maybe related issue.

I have a view spec and no custom view helpers are loaded.

```ruby
require "rails_helper"

RSpec.describe "Listing component", type: :view do
  it 'does something' do
    expect(view.test_helper_foo).to eq("meh")
  end
end
```

```
module ApplicationHelper
  def test_helper_foo
    "meh"
  end
end
```

Will result in

```
  1) Listing component does something
     Failure/Error: expect(view.test_helper_foo).to eq("meh")

     NoMethodError:
       undefined method `test_helper_foo' for #<#<Class:0x00000009881338>:0x00000009878210>
     # ./spec/components/test_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:153:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:152:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'
```

This is on Ruby 2.3.3, rspec 3.5, Rails 5.0.1.

**Comment by samphippen** [comment]
@tisba any chance you could follow these steps and provide us with a simple rails app to reproduce? Given that you're able to produce it right now in your app, do you think you could extract it to a new rails 5 app?

Thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by railsbros-dirk** [comment]
@tisba @samphippen I had the same issue and tl;dr is this is unrelated to RSpec :)

I found the following:

* If you have `RAILS_ENV` already set to `development` (i.e. by setting it in `/etc/environment`)
* And use `rails-controller-testing` (and/or `haml_lint` in some cases)
* And then run a view spec you won't have access to helper defined in your application.

The solution was to **not** require both `haml_lint` (which isn't required in the first place, but could just loaded in the `Rakefile`) and `rails-controller-testing` in the `Gemfile`. To still use `rails-controller-testing` you need to require it in `spec/rails_helper.rb` right **before** `require 'rspec/rails'`.

I didn't went further down to investigate the source of the problem though.

**Comment by JonRowe** [comment]
Closing as stale, I think this may have been a path error with where the helper was.
