### ISSUE TITLE
Bundle: Could not find gem 'rspec-rails

### ISSUE THREAD

**Issue by DevotionGeo** [rspec/rspec-rails#1588]
I am playing with Rails 5.0.0.beta3.
Installed rspec-rails 3.5.0.beta2 using `gem install rspec-rails --pre` 
Then included `gem 'rspec-rails', '~> 3.5', '>= 3.5.0.beta2'` in my Gemfile,
when I executed `bundle install`, I got the following error
**_Could not find gem 'rspec-rails (>= 3.5.0.beta2, ~> 3.5)' in any of the gem sources listed in your Gemfile or available on this machine._**

Everything else is installing and working fine, so I thought it might be the problem with rspec-rails than bundler.

**Comment by JonRowe** [comment]
I think this is because you've tried to specify `~> 3.5` and `>= 3.5.0.beta2` I'd try just the later.
