### ISSUE TITLE
undefined method `+' for nil:NilClass in have_rendered

### ISSUE THREAD

**Issue by aselder** [rspec/rspec-rails#1590]
I have the following spec:

```
    it "should complain about a missing template" do
      get :show, template: 'cdcdcdcdc'
      expect(response).to render_template(:file => "#{Rails.root}/public/404.html")
    end
```
We're in the process of upgrading from Rail 3 to Rails 4. Currently we're on Rails 4.0.13
This spec passed under Rails 3, but is failing under Rails 4 with the following error:
`undefined method '+' for nil:NilClass` at the following line: `rspec-rails-3.4.2/lib/rspec/rails/matchers/have_rendered.rb:39:in 'failure_message'`

**Comment by aselder** [comment]
With a little prying, here's the rescued exception message: 
`"Expected [] to include \"/Users/aselder/Development/orders/public/404.html\"."`

**Comment by samphippen** [comment]
@aselder  thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by samphippen** [comment]
@aselder I'm going to close this. If you can hand us a reproduction case, we can certainly take a look at it, and re-open.
