### ISSUE TITLE
Adding things to request.env for a request spec

### ISSUE THREAD

**Issue by tomprats** [rspec/rspec-rails#1594]
It seems pretty simple to add headers along with a request

    get "/some/path", {}, { simple: "This is a header" }

Which is then accessible in the controller with `request.headers[:magic]`. My problem comes when my controller expects certain information to be in `request.env`. I am not quite even sure how something gets there in the first place, but in working with Shibboleth, that's how certain details are passed.

Any ideas on how this is possible?

**Comment by JonRowe** [comment]
Have you tried manipulating `request` from your spec directly? This functionality is provided by the Rails helpers so I'm not entirely sure what'd happen.

**Comment by tomprats** [comment]
`request` is nil before the request and then after is too late. Is there another way to do that, or do I have to do something special to have `request` exist first?

**Comment by JonRowe** [comment]
Is this a request / feature spec or a controller spec? Headers and params should be the only outside things that can effect `request.env`, I'm assuming your Shibboleth implementation is injecting things into `request.env` via middleware, controller specs don't always have middleware attached to them.

**Comment by tomprats** [comment]
That makes a lot of sense. I'll look into injecting values in a middleware I attach to my related tests. Thanks for your help!

**Comment by tomprats** [comment]
Just a helpful hint to anyone who runs into this. I ended up adding the following middleware

    class RequestMiddleware
      def initialize(app)
        @app = app
      end

      def call(env)
        env.merge!(env["HTTP_ENV"] || {})
        @app.call(env)
      end
    end

So that I could add things to `request.env` like so

    get "/some/path", {}, { env { simple: "Woo!" }}

And then in your controller you can use `request.env["simple"]`

**Comment by JonRowe** [comment]
You shouldn't need to do that, you should just attach your shibboleth middleware, or stub the request value yourself.
