### ISSUE TITLE
Issue in 3.4 with passing a PathSet to prepend_view_path

### ISSUE THREAD

**Issue by brentdodell** [rspec/rspec-rails#1595]
In our multi-tenant app, we create an `ActionView::PathSet` for once for each tenant's view path, then pass the current tenant's `PathSet` to `prepend_view_path` in the `application_controller` for each request.

I believe that passing an `ActionView::PathSet` into `prepend_view_path` should be allowed according to [this](http://api.rubyonrails.org/classes/ActionView/ViewPaths/ClassMethods.html#method-i-prepend_view_path) and prior to upgrading rspec-rails to 3.4 we had no issues with this. 

The error I get is `TypeError: no implicit conversion of ActionView::PathSet into String`

It appears that the breaking changes were implemented here: https://github.com/rspec/rspec-rails/commit/42b44a6a6d81e5554128ed6552825ed35faaf2cb#diff-2

Edit:
Also, I believe this is related... Though we don't use it in our app I believe it should be supported. When using a custom `Resolver` (subclass of `::ActionView::FileSystemResolver`) and passing the `CustomResolver.new` to `prepend_view_path` I get the following error: `ArgumentError: path already is a Resolver class`.

I should note that the two things that are throwing rspec errors above work in the rails app...they do what they're intended to do and the tenant-specific views render.

**Comment by JonRowe** [comment]
This has already been fixed as part of #1580

**Comment by brentdodell** [comment]
> This has already been fixed as part of #1580, please try against master and open if you can still reproduce.

Thank you. I had not seen that PR.
