### ISSUE TITLE
rails-5-stable has rspec-expectations (= 3.2.0.pre) as a dependency, and this version does not exist!

### ISSUE THREAD

**Issue by bsodmike** [rspec/rspec-rails#1600]
Hi all,

Noting the [above entry in the gemspec](https://github.com/rspec/rspec-rails/blob/rails-5-support/rspec-rails.gemspec#L33..L39) I took a look at rspec-expectations both @ rubygems.org and the repo on github, but the tagged release of `3.2.0.pre` does not exist anymore.  The error I'm getting is,

```
Bundler could not find compatible versions for gem "rspec-expectations":
  In Gemfile:
    rspec-rails (>= 0) ruby depends on
      rspec-expectations (= 3.2.0.pre) ruby

    rspec-expectations (>= 0) ruby
Could not find gem 'rspec-expectations (= 3.2.0.pre) ruby', which is required by gem 'rspec-rails (>= 0) ruby', in any
of the sources.
```

Looking at attempting to patch this.

**Comment by bsodmike** [comment]
This issue is also affected by `rspec-support` as a pre-release version has not been tagged/released.

```
Bundler could not find compatible versions for gem "rspec-support":
  In Gemfile:
    rspec-rails (>= 0) ruby depends on
      rspec-support (= 3.5.0.pre) ruby
Could not find gem 'rspec-support (= 3.5.0.pre) ruby', which is required by gem 'rspec-rails (>= 0) ruby', in any of
the sources.
```

**Comment by JonRowe** [comment]
When you're using a pre-release version of rspec we expect you to load all of the rspec gems together from github, this sort of thing is a side effect of that

**Comment by bsodmike** [comment]
@JonRowe agreed, but I am unable to get this working from github's master branch and even tried the `rails-5-support` branch.  Due to the `.pre` tag on the version, the way the gemspec has been setup is that it ends up being unable to resolve dependencies.

Please see my PR #1601, which for the time being has resolved this for me - I'm currently doing this in a latest Rails 5 build.

```
group :development, :test do
  gem 'rspec-rails', github: 'bsodmike/rspec-rails', branch: 'fix/issue_1600'
end
```

**Comment by bsodmike** [comment]
@JonRowe just to be sure, I've tried your suggestion,

```ruby
  %w[rails core expectations mocks support].each do |name|
    gem "rspec-#{name}", github: "rspec/rspec-#{name}", branch: 'master'
  end
```

STDOUT:

```ruby
Updating git://github.com/rspec/rspec-rails.git
Updating git://github.com/rspec/rspec-core.git
Updating git://github.com/rspec/rspec-expectations.git
Updating git://github.com/rspec/rspec-mocks.git
Updating git://github.com/rspec/rspec-support.git
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies....
Bundler could not find compatible versions for gem "rspec-mocks":
  In Gemfile:
    rspec-rails (>= 0) ruby depends on
      rspec-mocks (= 3.5.0.pre) ruby

    rspec-mocks (>= 0) ruby

    rspec-activemodel-mocks (>= 0) ruby depends on
      rspec-mocks (< 4.0, >= 2.99) ruby

    guard-rspec (>= 0) ruby depends on
      rspec (< 4.0, >= 3.5.0.beta) ruby depends on
        rspec-mocks (= 3.5.0.beta3) ruby

    rspec-mocks (>= 0) ruby
```

**Comment by JonRowe** [comment]
I the issue here is:

```ruby
guard-rspec (>= 0) ruby depends on
      rspec (< 4.0, >= 3.5.0.beta)
```

I'm not sure how `beta` compares to `pre` but try removing this and then trying again

**Comment by bsodmike** [comment]
Still get stuck on this though,

```ruby
  In Gemfile:
    rspec-rails (>= 0) ruby depends on
      rspec-mocks (= 3.5.0.pre) ruby

    rspec-mocks (>= 0) ruby

    rspec-activemodel-mocks (>= 0) ruby depends on
      rspec-mocks (< 4.0, >= 2.99) ruby

    guard-rspec (>= 0) ruby depends on
      rspec (< 4.0, >= 2.99.0) ruby depends on
        rspec-mocks (~> 2.99.0) ruby

    rspec-mocks (>= 0) ruby
```

**Comment by JonRowe** [comment]
Just remove guard altogether temporarily?

**Comment by bsodmike** [comment]
Guard's needed for our current work flow, to ensure specs are run [along side with livereload](https://github.com/guard/guard-livereload).  As guard is unrelated to RSpec itself, I'll continue managing the corrections myself; chances are it'll resolve itself once v3.5.0 is released.  Thanks for the assistance @JonRowe.
