### ISSUE TITLE
Useless warning

### ISSUE THREAD

**Issue by thomasbiddle** [rspec/rspec-rails#1609]
```
WARNING: Shared example group 'accountable' has been previously defined at:
  /My/Project/spec/support/shared_examples/concerns/accountable_spec.rb:3
...and you are now defining it at:
  /My/Project/spec/support/shared_examples/concerns/accountable_spec.rb:3
The new definition will overwrite the original one.
```

This is happening for every file in that folder. It warns that something is defined twice, the new definition being.. in the exact same place.

I'm on `3.4.2`

**Comment by JonRowe** [comment]
Is it possible you're requiring the file twice? Ruby usually protects against this but can be tricked (for example if you don't use the full filepath). 

A quick check would be to put a `puts 'foobar'` in that file and see if it printed twice when running your specs...

**Comment by thomasbiddle** [comment]
@JonRowe - Hm, not that I can see! I removed every redundant 'require rails_helper' in my files in-case it was somehow requiring something twice. Testing a `puts 'foobar'` only returns once.

My files are required in my `spec_helper.rb` via `Dir[File.dirname(__FILE__) + "/support/**/*.rb"].each {|f| require f }`

**Comment by JonRowe** [comment]
Ah, actually I know what's happening, you are requiring them twice, but don't realise it. You are requiring them manually and then we are loading them, please rename them to not have `_spec` at the end.

**Comment by myronmarston** [comment]
FWIW, a simple way to see how a file is being loaded is to add this to the top of it:

``` ruby
puts "Loading #{__FILE__}"
puts caller.join("\n")
puts
```

That'll show you how it is being loaded multiple times.

**Comment by thomasbiddle** [comment]
@JonRowe  - Success! Interesting, if I remove the manual load - it doesn't get required; however by renaming to not have `_spec` everything works but the warning is removed. Thanks!

@myronmarston Great to know for future reference, much appreciated!

**Comment by JonRowe** [comment]
>  if I remove the manual load - it doesn't get required;

It probably does, but probably not before it's used...
