### ISSUE TITLE
assert_select in request specs needs document_root_element

### ISSUE THREAD

**Issue by timdiggins** [rspec/rspec-rails#1610]
when using rails' assert_select (defined in https://github.com/rails/rails-dom-testing) we have to configure a document_root_element - this seems to happen automatically in controller tests when `render_views(true)` but doesn't happen in request specs

A fix is to add a support file to spec/support like (adapted from http://stackoverflow.com/questions/36214550/rspec-integration-testing-testing-how-many-anchor-tags):

```
module AssertSelectSupport
  def document_root_element
    html_document.root
  end
end

RSpec.configure do |config|
  config.include AssertSelectSupport, :type => :request
end
```

But shouldn't this either be built into rspec-rails or referenced from the docs?

**Comment by JonRowe** [comment]
Request specs aren't intended to be used for introspecting views, please use controller specs with render views turned on or feature specs.
