### ISSUE TITLE
Uninitialized constant ActiveRecord::Base

### ISSUE THREAD

**Issue by pacoguzman** [rspec/rspec-rails#1611]
On a rails 4.2.6 app that doesn't require 'active_record/railtie' the block `RSpec::Mocks.configuration.when_declaring_verifying_double` defined from the `rspec/rails/active_record.rb` file raises and `Unitialized constant ActiveRecord::Base`

I would like to collaborate on solving this problem but I'm not sure what is the proper solution:

```ruby
defined?(ActiveRecord::Base) # instead just defined?(ActiveRecord)
```

And a suggestion in how this can be tested if a test is needed will be really appreaciated

**Comment by jonstacks** [comment]
+1 I have run into the same problem in my Rails app that does not require the 'active_record/railtie'.

**Comment by JonRowe** [comment]
Something is erroneously defining `ActiveRecord` in these instances, you should find out what is defining it and prevent it from happen as this is not the only thing that will break in these scenarios. I will expand the check however.

**Comment by jonstacks** [comment]
@JonRowe,

I was able to track down what was defining it after your helpful suggestion. Thank you!
