### ISSUE TITLE
No route matches for inherited (create) action

### ISSUE THREAD

**Issue by simonknoll** [rspec/rspec-rails#1612]
Hi,
I have 2 versions of my API(1&2) the controller of api version 2 inherits from the controller of api version 1. The problem is, specs for version 1 are running fine, but when i run specs in version 2, it tells me

> ActionController::UrlGenerationError: No route matches {:action=>"create", :controller=>"api/mobile/v2/samples"}

```
#version 1
class Api::Mobile::V1::SamplesController < ApplicationController
  def create
   #dummy
  end
end

#version 2
require "meta_data"
class Api::Mobile::V2::SamplesController < Api::Mobile::V1::SampleController
  include MetaData
end


#spec for version 1
require 'rails_helper'
RSpec.describe Api::Mobile::V1::SamplesController, type: :controller do
  describe "POST #create" do
    it "performs a post" do
      post :create
    end
  end
end

#spec for version 2
require 'rails_helper'
RSpec.describe Api::Mobile::V2::SamplesController, type: :controller do
  describe "POST #create" do
    it "performs a post" do
      post :create
    end
  end
end
```

**Comment by JonRowe** [comment]
Have you defined a route for V2?

**Comment by simonknoll** [comment]
yes, I am using this already in my production app and clients can successfully connect to my api v2 route

**Comment by JonRowe** [comment]
Your extracted snippets work for me on Rails 4.2, (once I corrected a typo), can you provide more information? This is typically handled by Rails anyhow, so you could try to see if you can make this work in minitest...

**Comment by simonknoll** [comment]
@JonRowe  thanks for your efforts, could the problem be, that I am using Rails 4.0.12 and Ruby 2.1.2
I've attached my Gemfile.lock
[Gemfile.lock](https://github.com/rspec/rspec-rails/files/286095/Gemfile.lock.txt)

**Comment by JonRowe** [comment]
Just double checking, but in your real app:

`class Api::Mobile::V2::SamplesController < Api::Mobile::V1::SampleController` thats `Api::Mobile::V1::SamplesController` and not `Api::Mobile::V1::SampleController` right?

**Comment by samphippen** [comment]
@simonknoll  Thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by samphippen** [comment]
Hi @simonknoll I'm going to go ahead and close this. If you're able to provide a repo we can clone given the steps above to demonstrate this issue, we can totally re-open. Thanks so much once again ^_^
