### ISSUE TITLE
 To continue using it,     add 'gem 'rails-controller-testing'' to your Gemfile

### ISSUE THREAD

**Issue by jennytech** [rspec/rspec-rails#1620]
Failure/Error: expect(response).to render_template("index")
NoMethodErroe:
 assert_template has been extracted to a gem. To continue using it,
    add 'gem 'rails-controller-testing'' to your Gemfile
after I add gem and bunble install,It still shows same error.
![1](https://cloud.githubusercontent.com/assets/16144214/15299701/671d9da8-1b5a-11e6-8c84-2112a534588b.png)
![56](https://cloud.githubusercontent.com/assets/16144214/15299706/6b3bd332-1b5a-11e6-9d0d-46f29f5e3819.png)

**Comment by mrageh** [comment]
@jennytech checkout https://github.com/rails/rails-controller-testing#rspec

**Comment by JonRowe** [comment]
This is due to the deprecation of those methods by the rails team, if you use the `rails-controller-testing` gem with RSpec 3.5.0 betas (or master) these methods will work again.
