### ISSUE TITLE
Expected response to be a <3XX: redirect>, but was a <200: OK>

### ISSUE THREAD

**Issue by jennytech** [rspec/rspec-rails#1622]
```Ruby
require 'rails_helper'

describe UsersController, :type => :controller do 

    
    before do
        @user = User.create!(email: "ewhroa@hotmail.com", password: "90eargresy")
    end

    describe "GET #show" do

        context "Users is logged in" do
          before do
            sign_in @user
          end

          it "loads correct user details" do
            get :show, id: @user.id
            expect(response).to have_http_status(200)
            expect(assigns(:user)).to eq @user
          end
        end

      context "No user logged in" do
        it "redirects to login" do
          get :show, id: @user.id
          expect(response).to redirect_to(root_path)
        end
      end
    end
end
```
![c](https://cloud.githubusercontent.com/assets/16144214/15329900/5292c402-1c0f-11e6-8fe2-58b0eb5558a8.png)
`

**Comment by JonRowe** [comment]
Hi without knowing your controller implementation we can't help you with whats wrong with your code, but given your spec it's extremely unlikely this is an RSpec bug.

For future reference you need to use triple backticks ```` ``` ```` to wrap multiple line blocks in github markdown (or ident every line by 4 spaces), e.g.
 
    ```Ruby
    class MyClass
      ...
    end
    ```

**Comment by timodegen** [comment]
Maybe you have an exception for user authentication in your users_controller for the show method.

**Comment by tbroad-ramsey** [comment]
I am experiencing this issue, albeit possibly for different reasons.

Here is my test:
```
    it "should redirect" do
      VCR.use_cassette("some_vcr_recording") do
        expect(subject).to redirect_to ENV["REDIRECT_URL"]

        get billing_account_path
      end
    end
```

Here is the failure:
```
Failure/Error: expect(subject).to redirect_to ENV["REDIRECT_URL"]
       Expected response to be a <3XX: redirect>, but was a <200: OK>
```

Here is the controller implementation:
```
class AccountsController < ApplicationController
  before_action :redirect_where_i_tell_you_to

  def billing
    # ...does controller stuff
  end

private

  def redirect_where_i_tell_you_to
    redirect_to ENV["REDIRECT_URL"] # this will always redirect obviously, but for testing purposes...
  end
end
```

**Comment by JonRowe** [comment]
You don't include `subject` in your snippet, but it doesn't act like a block, you haven't done `get` yet so theres no way it should pass, its likely its just the default request object.

**Comment by tbroad-ramsey** [comment]
@JonRowe I have tried moving the `expect` call after the `get ...` and it still does not work. `subject` is the controller in question, `AccountsController`.

**Comment by JonRowe** [comment]
@tbroad-ramsey yep thats never going to work, the matcher expects a response.

**Comment by tbroad-ramsey** [comment]
@JonRowe Gotcha. So, I may have some conflicting configuration with my `RSpec` setup, because when instead I do what is shown below, it is _not_ using the response I pass-in, but instead a global `@response` object that says it returned with a `200`. The `response` that is returned to me in my example spec correctly identifies itself as a `302` redirect. Any ideas of why this would be happening (outside of conflicting configuration with WebMock or VCR or something)?

```
...
response = get billing_account_path
expect(response).to redirect_to ENV["REDIRECT_URL"]
...
```

**Comment by pirj** [comment]
It would be significantly easier to reason about this code if you could provide your `subject { ... }` declaration in full @tbroad-ramsey.

**Comment by tbroad-ramsey** [comment]
@pirj The `subject` is the RSpec default for controller specs, which is just an instance of the controller in question which is `AccountsController`

**Comment by pirj** [comment]
Sorry, I've missed your message.
As to my memory, it's not necessary to assign the result of `get` to `response` to have the result in it.
Can you set a breakpoint to after `get` and check what's in `response`? Try assigning the returning value of `get` to, say, `res`, and compare the two?
Can you please provide a minimal reproduction example if those two are really different?

**Comment by ngouni** [comment]
i have the same error and don't know how to fix it
my test:

RSpec.describe WoundsController, type: :controller do

      describe "wound is created" do
        context "Test if wound has been created"
        it "should select successfully" do
          # wound = create(:wound)
          patient = Patient.create({ firstname: "Hermann", lastname: "Buhlert Test", birthdate: Date.new(1960, 03, 26) })
          employee = Employee.create({firstname: "Lukas", lastname: "Pietsch", doctor: false })
          wound = Wound.create({ name: "Schnittwunde, Hand", patient: patient, localisation: 1, age: Date.new(2020, 06, 12), recurrence: 2 })
          wound.id.present?
          expect(response).to redirect_to wounds_path
        end
      end
    
     
end


failure :
 Expected response to be a <3XX: redirect>, but was a <200: OK>

**Comment by pirj** [comment]
I'm missing any HTTP interaction that can result in a redirect in your example @ngouni

**Comment by tbroad-ramsey** [comment]
@pirj On the left is the return value of the `get` call, and on the right is the global `response` object. They are two different instances and are actually different classes. One is a `Rack::MockResponse` and the other is `ActionDispatch::TestResponse`.

![compare_response_values](https://user-images.githubusercontent.com/42982667/85402778-e0e6ed00-b521-11ea-831e-cae789be6cfb.png)

**Comment by pirj** [comment]
Does this persist if you `get` first, and `expect(reponse)` after like you do in this example?
```ruby
get billing_account_path
expect(response).to redirect_to ENV["REDIRECT_URL"]
```

Will `response` be a 200 or a 302?
[Docs](https://relishapp.com/rspec/rspec-rails/v/4-0/docs/request-specs/request-spec) you should perform the action first, and make an expectation after:
```ruby
    get "/widgets/new"
    expect(response).to render_template(:new)

    post "/widgets", :params => { :widget => {:name => "My Widget"} }
    expect(response).to redirect_to(assigns(:widget))
```

I can guess that for some reason `response` evaluates to some default response. This is confusing to me.
Can you debug it where this default response comes from?
I can't reproduce, for me `response` before `get`/`post` evaluates to `nil`.

**Comment by tbroad-ramsey** [comment]
@pirj I can verify that doing the following:

```
get billing_account_path
expect(response).to redirect_to ENV["REDIRECT_URL"]
```

will `FAIL`. It fails with the message "Expecting 3XX but got 2XX".

**Comment by pirj** [comment]
@tbroad-ramsey can you please provide a reproduction example of that behaviour?
Can you debug the issue, and check where `response` is initialized? I suggest you set a breakpoint in `Rack::MockResponse.initialize`, or in your code before `get` and check where `response` is defined.
Otherwise we're doing this in the dark, and it's really hard to guess.

**Comment by tbroad-ramsey** [comment]
@pirj It turns out that it was an issue with our applications rspec config. We are using the `Rack::Test::Methods` module which alters the way you check redirects and such, and breaks rspec-rails methodology. Thanks for your help!

**Comment by pirj** [comment]
Happy to help, and good to know you've solved the mystery @tbroad-ramsey.
