### ISSUE TITLE
How to solve "`last_comment` is deprecated" for Rails 5?

### ISSUE THREAD

**Issue by AntonyBaasan** [rspec/rspec-rails#1624]
I understand that older version of rspec gives this error.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.

I have rspec-code v3.3.0 and rspec-rails 3.1.0
![screenshot 2016-05-20 11 39 32](https://cloud.githubusercontent.com/assets/4986601/15436698/83959ed0-1e80-11e6-97d9-fa3d8f94b0b8.png)

My Rails is v5.0.0.rc1
![screenshot 2016-05-20 11 40 08](https://cloud.githubusercontent.com/assets/4986601/15436935/7627ed06-1e81-11e6-899f-21b6ddcd7ba1.png)

Changed gem file rspec-rails version to v3.4 and run bundle update.
I got actionpack conflict:
![screenshot 2016-05-20 11 45 52](https://cloud.githubusercontent.com/assets/4986601/15436859/1c32292e-1e81-11e6-9438-f1d2a75db303.png)

How do we deal with this case?

**Comment by myronmarston** [comment]
The deprecation warning comes from a recently released version of Rake, and we fixed rspec-core to not use the deprecated API in rspec-core 3.4.4.  You can upgrade to that version.

BTW, if you are using rails 5, you'll need to use rspec 3.5:

http://rspec.info/blog/2016/02/rspec-3-5-0-beta1-has-been-released/

**Comment by AntonyBaasan** [comment]
Sorry, just used v3.5.0.beta3. Works OK.

**Comment by AntonyBaasan** [comment]
Thank you, Myron. The link is helpful.
