### ISSUE TITLE
Mailer spec describes "InvitationMailerMailer" class

### ISSUE THREAD

**Issue by radar** [rspec/rspec-rails#1627]
**Steps to reproduce**

1. Add rspec-rails `~> 3.5.0.beta3`  to a Rails application.
2. Run `rails g mailer invitation`
3. See that `spec/mailers/invitation_mailer_spec.rb` describes "InvitationMailerMailer" class.

**Comment by radar** [comment]
My bad, I had actually run `rails g mailer invitation_mailer`.

**Comment by JonRowe** [comment]
^_^
