### ISSUE TITLE
have_enqueued_jobs only supports block expectations

### ISSUE THREAD

**Issue by lucasgomide** [rspec/rspec-rails#1629]
Hi, I'm using the version rspec-rails 3.4.0 and rails 4.2.5.

I'm trying test two class, one model another service. Test enqueue job on service work. But test on model not working.

**Model**

```
it 'should enqueue FooWorker' do
      subject.enqueue
      expect(FooWorker).to have_enqueued_job({bar: 123}.to_json)
    end
```

I got this error.

```
expect(FooWorker).to have_enqueued_job({})
ArgumentError: have_enqueued_jobs only supports block expectations
from /Users/lucasgomide/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-rails-3.4.0/lib/rspec/rails/matchers/active_job.rb:22:in `matches?'
```

```
FooWorker.jobs
=> [{"class"=>"FooWorker",
  "args"=>
   [{"bar"=>"123"}],
  "retry"=>false,
  "queue"=>"default",
  "jid"=>"af7f9fcadb9bfcfe8f5a86f4",
  "created_at"=>1464268005.2628741}]
```

**Service**
```
it 'should enqueue FooWorker' do
        service = FooService.new
        service.enqueue
        expect(FooWorker).to have_enqueued_job({})
      end
```

````
Finished in 0.93083 seconds (files took 4.54 seconds to load)
1 example, 0 failures
```

any ideia ?

tks

**Comment by JonRowe** [comment]
That's not how the expectation works in that version, you need to use the block form as the error suggests: e.g.
```
service = FooService.new
expect {
  service.enqueue
}.to have_enqueued_job(FooWorker).with({})
```

See https://relishapp.com/rspec/rspec-rails/v/3-4/docs/matchers/have-enqueued-job-matcher

**Comment by JonRowe** [comment]
The next version of rspec-rails will support `expect(FooWorker).to have_been_enqueued` but that's not yet released.

**Comment by lucasgomide** [comment]
Yep, nice.. i'll try it !

But does not make sense not working on Model class and work on Service class..

**Comment by JonRowe** [comment]
Code was psuedo code, the important bit is that the job is enqueued inside the block.

**Comment by lucasgomide** [comment]
tks @JonRowe
