### ISSUE TITLE
The recognized options did not match after Rails 4 upgrade?

### ISSUE THREAD

**Issue by bigtunacan** [rspec/rspec-rails#1642]
I have an existing spec that passed on Rails 3 that looks something like this.

    expect(:post => '/controller/action?parm=foo').to route_to(:controller => 'controller', :action => 'action')

This passed with Rails 3.  Now that I've upgrade to Rails 4 it fails with an error message

> Failure/Error: :post => '/controller/action?parm=foo'
> The recognized options <{"action" => "action", "controller" => "controller", "parm" => "foo"}> 
> did not match
> <"controller" => "controller", "action" => "action">

**Comment by mrageh** [comment]
I think the problem is that you need to add the key value pair `param => foo`

```
expect(:post => '/controller/action?parm=foo').to route_to(:controller => 'controller', :action => 'action', :parm => 'foo')
```

**Comment by bigtunacan** [comment]
@mrageh, yep; this was the issue.  Thanks.
