### ISSUE TITLE
Raise exceptions for requests returning non-successful status codes

### ISSUE THREAD

**Issue by sidonath** [rspec/rspec-rails#1646]
I got burned today and lost a lot of time by my own mistake and a request spec that didn't guide me in the right direction.

I had a request spec that was doing two requests: the first one was a "set up" request and the other one was a request whose response I was actually testing.

I didn't do any assertions after the first request as its status was not of concern and because the logic it was doing was tested in a separate unit. I had some expectations about the second request that were not getting fulfilled.

After a lot of debugging I realized I had a bug in a unit that was separately tested (but I forgot to cover a rather important case), which was causing the "set up" request to fail. As I didn't have any assertions, I didn't have a clue it was failing. If I knew it was failing I would know where to look for a problem.

Thus, I'd like to propose a change: let's make requests fail an example if they return a non-successful status code.

I understand this wouldn't be backwards compatible change, but we could either provide additional request methods (e.g. something like `get!` which would raise an exception for 4xx and 5xx statuses), or maybe a global config option (and provide a way to opt-out on a request basis).

I'd be happy to contribute a PR if you think something like this would be useful.

**Comment by JonRowe** [comment]
Thanks for the suggestion but `rspec-rails` is a thin wrapper around Rails own test helpers, this functionality is mirrored between the two and I don't think theres sufficient value in this to warrant diverging and adding our own methods or behaviour on top here. 

Remember you can always implement this your self as a helper module, and you could even extract it into a gem to share with others if you feel really strongly about this. Something like this should work:

```Ruby
module RaiseOnBadErrors
  def process(*args, &block)
    super
    raise 'unsuccesfull' unless last_response.success?
  end
  RSpec.configuration.include self, type: :request
  RSpec.configuration.include self, type: :feature
end
```

**Comment by JonRowe** [comment]
Alternatively you could set an expectation after any call you expect to succeed as a a safety...

**Comment by sidonath** [comment]
@JonRowe thanks for the feedback! I guess I can do this in the app and see how it works for us and if it makes sense to get this into Rails itself
