### ISSUE TITLE
Depracation warning for `config.raise_in_transactional_fixtures` in Rails 5

### ISSUE THREAD

**Issue by devonestes** [rspec/rspec-rails#1649]
I just upgraded to Rails 5 and Rspec 3.5 this morning, and I'm trying to clear out depreciation notices. I got the following one when running my tests:

```
DEPRECATION WARNING: ActiveRecord::Base.raise_in_transactional_callbacks= is deprecated, has no effect and will be removed without replacement.
```

I removed `Rspec.configure { |config| config.raise_in_transactional_callbacks = true }` from my `spec_helper.rb` file, but I'm still seeing the deprecation warning. I'm assuming that there is a basic config in `rspec-rails` that sets that value to either true or false, and that's what's still throwing the deprecation warning.

Thanks for the super quick turnaround on getting Rspec 3.5 out the door!

**Comment by JonRowe** [comment]
As far as I know that isn't an RSpec config option, and we don't call it anywhere (you can grep our code to see this) you might want to grep your codebase or gems to find the source of this.

**Comment by devonestes** [comment]
Yeah, I checked our codebase and came up empty, but in all honestly I just _assumed_ it was Rspec since that's where we were using that config before. Looks like it's not, though, so I'll check elsewhere!

**Comment by JonRowe** [comment]
Try doing `puts config.method(:raise_in_transactional_callbacks=).source_location` to see where it's coming from?

**Comment by devonestes** [comment]
Thanks for the tip! Found the issue - of course it was in an internal gem that someone else maintained...
