### ISSUE TITLE
Possible `redirect_back` support in Rails 5?

### ISSUE THREAD

**Issue by jmmastey** [rspec/rspec-rails#1659]
Hey all,

I'm game to submit a PR if anyone has a workable approach, but so far I'm stumped here. This question has reference: http://stackoverflow.com/questions/38162970/testing-redirect-back-in-rails-5.

Basically, I'm interested in testing for the usage of the new `redirect_back` API in Rails, but under the hood it just calls vanilla `redirect_to`, which makes it a little tough. Meanwhile, I still get a deprecation notice for asserting like:

    expect(response).to redirect_to(:back)

That test is still green but clearly deprecated. What would work now, but be more than I really need, would be to 1) send a referer and assert redirection to that referer, and 2) assert redirection to the fallback path provided to `redirect_back`.

Is anyone else interested in this feature? I can dig some more, but unless someone else sees a clever solution, I think it'd require a PR to actionpack to make them properly aware of `redirect_back` calls.

Thanks!
Joe

**Comment by JonRowe** [comment]
`expect(response).to redirect_to('path/to/previous/location')`?

**Comment by JonRowe** [comment]
Or set a specific referrer header and assert on that?

**Comment by jmmastey** [comment]
Oh agreed, those do work, but they seem far less literate than the previous
ability to just check that we redirected to "back".

If it's not enough difference for anyone else I can just use those methods,
but I'll feel like I've lost communicativeness in my tests.

**Comment by JonRowe** [comment]
Unless theres a new rails equivalent theres not much to do about that.

**Comment by samphippen** [comment]
We provide compatability with supported Rails APIs for the versions of Rails we support. That is, if an API is gone in the version of rails you're using, it is not RSpec's responsibility to provide that API instead. Given that Rails is getting rid of the `redirect(:back)`. I don't think this is a feature we should special case.

**Comment by JonRowe** [comment]
@jmmastey do you know if Rails is going to provider a `assert_redirect_back` or the like? I'm guessing this might be a no given there switch away from controller tests...

**Comment by jmmastey** [comment]
Thanks for the feedback both of you. Totally agreed / understood that we'd need an API to hook. There's no `assert_redirect_back` yet, and I don't see any discussion on it. I'm going to close this for now. If I open that conversation and they _do_ provide that assertion, I'll reopen and reapproach the conversation.

Thanks all.

**Comment by obromios** [comment]
In my test suite, using ```rails 5.2.3``` the following works:
`expect(response).to redirect_to 'http://test.hostwhere_I_came_from'`
