### ISSUE TITLE
rspec:generate won't work with faker

### ISSUE THREAD

**Issue by amingilani** [rspec/rspec-rails#1663]
Can't install rspec with faker:
```bash
$ bin/rails generate rspec:install
Could not find faker-1.6.5 in any of the sources
Run `bundle install` to install missing gems.
$ bundle exec rails generate rspec:install
Could not find faker-1.6.5 in any of the sources
Run `bundle install` to install missing gems.
$ rails generate rspec:install
Could not find faker-1.6.5 in any of the sources
Run `bundle install` to install missing gems.
```

System Info
----------------

```bash
$ bundle exec rails -v
Rails 5.0.0
$ bundle exec bundle -v
Bundler version 1.12.5
$ bundle list | grep faker
  * faker (1.6.5)
$ bundle list | grep rspec-rails
  * rspec-rails (3.5.1)
```

Here's the gemfile:

```ruby
source 'https://rubygems.org'

ruby '2.3.1'
gem 'rails', '~> 5.0.0'

group :development, :test do
  gem 'rspec-rails'
  ...
  gem 'faker', '~> 1.6', '>= 1.6.5'
end
```

Running OSX with zsh, and rvm

**Comment by amingilani** [comment]
Upon commenting out `faker`

```bash
$ rails generate rspec:install
Could not find notiffany-0.1.0 in any of the sources
Run `bundle install` to install missing gems.
$ bundle list | grep notiffany
  * notiffany (0.1.0)
```

**Comment by amingilani** [comment]
This is insane:
```bash
gem source
*** CURRENT SOURCES ***

https://rubygems.org/
```

**Comment by samphippen** [comment]
Hi @amingilani 

Thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by amingilani** [comment]
I'm sorry, this wasn't an rspec issue, it was a `spring` issue. Following this [post](https://jasonplayne.com/web-dev/rails-generate-could-not-find-in-any-of-the-sources) fixed it when i killed it.
