### ISSUE TITLE
Stuck when running "rails generate rspec:install" with rails-5

### ISSUE THREAD

**Issue by ahmadhasankhan** [rspec/rspec-rails#1665]
Nothing happening while running rspec:install command, I am using Ruby-2.2.3 and Rails-5.

```
gem 'rails', '~> 5.0.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'rspec-rails', '~> 3.4'
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'capybara', '~> 2.5'
end

group :test do
  gem 'shoulda-matchers', '~> 3.0', require: false
  gem 'database_cleaner', '~> 1.5'
  gem 'faker', '~> 1.6.1'
end
```

**Comment by JonRowe** [comment]
Not sure if we changed anything with generators, but you need `gem 'rspec-rails', '~> 3.5'` minimum for Rails 5 support, try upgrading?

**Comment by ahmadhasankhan** [comment]
Working now Thanks  👍

**Comment by rjaralikatti** [comment]
I am still facing this issue. @ahmadhasankhan did you do anything for it to work? I am using rails 5.2.0 and rspec-rails 3.7

**Comment by JonRowe** [comment]
Make sure you restarted spring if you recently upgraded.

**Comment by rjaralikatti** [comment]
Thanks @JonRowe that was the issue. Its fixed.
