### ISSUE TITLE
Scaffold generator generates invalid controller specs on versions prior to Rails 5

### ISSUE THREAD

**Issue by yujinakayama** [rspec/rspec-rails#1669]
In #1603, we made scaffold generator to generate controller specs with HTTP request method (`#get`, `#post`, etc.) with keyword arguments:

``` diff
- post '/books', { book: { title: 'Foo' } }
+ post '/books', params: { book: { title: 'Foo' } }
```

... regardless of the current project's Rails version.

However the keyword arguments are actually supported only on Rails 5 (https://github.com/rails/rails/pull/18323). The CI in #1603 was passing because [they were skipped](https://github.com/rspec/rspec-rails/blob/v3.5.1/lib/generators/rspec/scaffold/templates/controller_spec.rb#L27-L33).

**Comment by JonRowe** [comment]
This should work on some older Rails @yujinakayama, as the support for hash style params has been aroun a while, which version are we seeing issues with?

**Comment by qx** [comment]
@JonRowe rails 4.2.x get this error
and 5.0.0 get below error
```
  1) RobotsController PUT #update with invalid params re-renders the 'edit' template
     Failure/Error: expect(response).to render_template("edit")
       expecting <"edit"> but was a redirect to <http://test.host/robots/1>
     # ./spec/controllers/robots_controller_spec.rb:141:in `block (4 levels) in <top (required)>'

```
All not work
And why you close my issue without any comments?

**Comment by yujinakayama** [comment]
```
$ bundle exec rails --version
Rails 4.2.7
$ bundle exec rspec --version
3.5.1
```

Here's a repro project:

* https://github.com/yujinakayama/rspec-rails-1669
* https://travis-ci.org/yujinakayama/rspec-rails-1669/builds/152039866

```
 3) BooksController POST #create with valid params creates a new Book
     Failure/Error: params.require(:book).permit(:title)
     
     ActionController::ParameterMissing:
       param is missing or the value is empty: book
```
