### ISSUE TITLE
skip generating specs for new/edit routes/controllers/views for API only app

### ISSUE THREAD

**Issue by audy** [rspec/rspec-rails#1672]
RSpec currently generates specs for new and edit routes, controllers and views for a new Rails (5.0.0) app generated with `--api`, when running `rails g scaffold ...`. These tests fail and are unnecessary.

Can these be skipped? If not, would this be a useful feature to add to RSpec (automatically detecting an API-only app and not generating the unnecessary specs)?

## unnecessary specs

- [ ] view specs
- [ ] certain controller specs (new, edit)

**Comment by JonRowe** [comment]
It would certainly make sense for the generator to be aware of `--api` and produce different specs accordingly, if you'd like to tackle that feel free!

**Comment by AustinMCrane** [comment]
if there is anyway i could help with this let me know, this is an inconvenience and would be helpful by default when generating an api only app.

**Comment by mrageh** [comment]
I'd like to go ahead and tackle this issue @JonRowe for api only apps are we not supposed to generate view specs?

**Comment by audy** [comment]
@mrageh I started making a list of unnecessary specs in the original issue body.

**Comment by AustinMCrane** [comment]
Some generated specs could be more helpful for testing against JSON responses or status codes as well, for instance you can replace the redirect checks with http status code checks and JSON formats

**Comment by danrabinowitz** [comment]
Is this issue resolved by https://github.com/rspec/rspec-rails/pull/1685 ?

**Comment by JonRowe** [comment]
I believe so
