### ISSUE TITLE
Expect doesn't wait for visit to complete

### ISSUE THREAD

**Issue by MihaiDinculescu** [rspec/rspec-rails#1673]
Using Rspec 4.5.1 and capybara 2.7.1

    1.1) Failure/Error:
          expect {
            visit api_admin_users_index_path
          }.to raise_error

          expected Exception but nothing was raised
        # ./spec/features/admin_users_spec.rb:26:in `block (3 levels) in <top (required)>'

    1.2) Failure/Error: raise ActionController::RoutingError, "No route matches [#{env['REQUEST_METHOD']}] #{env['PATH_INFO'].inspect}"

        ActionController::RoutingError:
          No route matches [GET] "/api/admin/users"

As you can notice the error is thrown and is not caught after the expect block completes.

**Comment by JonRowe** [comment]
Hi,  is this error being raised in your controller? RSpec can't rescue exceptions from inside your Rails stack when it's being run in a server / client style, only when it's directly invoking code itself (like any normal Ruby app).

**Comment by MihaiDinculescu** [comment]
What you are saying makes sense but I don't think it's true. The error seems to be bubbling up to rspec correctly.

The following code passes the test.

        expect {
            visit api_admin_users_index_path
            expect(page).to have_text 'test'
        }.to raise_error(ActionController::RoutingError)

**Comment by JonRowe** [comment]
Are you using rack-test?

**Comment by MihaiDinculescu** [comment]
I'm force to use it apparently.

        actionpack (5.0.0)
          actionview (= 5.0.0)
          activesupport (= 5.0.0)
          rack (~> 2.0)
          rack-test (~> 0.6.3)
          rails-dom-testing (~> 2.0)
          rails-html-sanitizer (~> 1.0, >= 1.0.2)

**Comment by JonRowe** [comment]
```
expect {
  visit api_admin_users_index_path
  expect(page).to have_text 'test'
}.to raise_error(ActionController::RoutingError)
```

Tells me that capybara is not waiting long enough

**Comment by MihaiDinculescu** [comment]
I'm haven't modified the default wait time and I have also tested with 2.6.2 and 2.5.

**Comment by JonRowe** [comment]
As far as I know `visit` doesn't wait for the page to finish, as it's the matchers that are expected to block for the wait time until content is loaded.

Long and the short of it, it's not the intended usage to expect errors to bubble up from feature specs like this, can you refactor this to use get or find another way to perform the assertion?

**Comment by MihaiDinculescu** [comment]
Yeah, I'm reaching the same conclusion.

Unfortunately it looks like I'm forced into using feature specs for testing routes that are using Devise's `autheticate!`.

I guess I'm stuck with using a dummy expect.

**Comment by JonRowe** [comment]
You shouldn't need to use feature specs for that, whats broken with request specs?

**Comment by JonRowe** [comment]
(closing because this isn't an RSpec Rails issue, I'm happy to keep helping however)

**Comment by MihaiDinculescu** [comment]
I haven't tried request specs. It sounds like a great idea, I'll try it tomorrow. Thanks for all the help.

**Comment by MihaiDinculescu** [comment]
It worked flawlessly, thank you very much!
