### ISSUE TITLE
How to successfully log in in request specs?

### ISSUE THREAD

**Issue by RyanKim01** [rspec/rspec-rails#1674]
I'm writing request specs to test certain API calls. I found out that Capybara's way of logging in only works in feature spec since Capybara 2.0. So I cannot use it anymore.

Unfortunately, all of my API calls would not work without logging in and I cannot find a correct of logging in using Devise. In request spec files, how can I successfully log in to successfully run test on API calls?

**Comment by JonRowe** [comment]
Programatically login as you would when hitting your app normally, then hit your api?

**Comment by RyanKim01** [comment]
Can you show an example to successfully log in in request spec?
I was calling a below method and it is not working.

>  def login_user
>     before(:each) do
>       debugger
>       @request.env["devise.mapping"] = Devise.mappings[:user]
>       user = FactoryGirl.create(:user)
>       sign_in user
>     end
>   end

**Comment by JonRowe** [comment]
Request specs are designed to emulate a full stack request, thus you have to login as you would in a browser. e.g if you sending a header, send a header, if you're appending a token, append a token in the params, if you're going to /login, filling in username password, do that.

**Comment by samphippen** [comment]
@RyanKim01 the rspec-rails issue tracker is more for bugs/features than it is for help requests. Would you mind emailing your question to our mailing list rspec@googlegroups.com, where the wider community can help you answer it there.
