### ISSUE TITLE
Question about fixtures

### ISSUE THREAD

**Issue by cathawk** [rspec/rspec-rails#1682]
Hi there,

I have a question regarding fixtures. We are currently using RSpec to run a suite of acceptance tests. There is a lot of duplicated setup/teardown associated with these tests. We are using fixtures, opening browsers for corresponding fixture users, logging them in, and redirecting to the application. We would like to be able to organize the set of tests in such a way that we can minimize the number of times were are repeating these steps.

Is there any way to be able to include calls to fixtures in a before(:context) or before(:all) block? It would be extremely helpful for acceptance tests to be able to do that. Any help would be most appreciated!

Aaron

**Comment by JonRowe** [comment]
As far as I know we don't stop you calling fixtures in context hooks, Rails is largely in control of this, so I might be wrong, but you'd need to remove any database wiping you have at the end of each example, and turn off transactional fixtures. You'd also need to make sure you remove the fixtures at the appropriate point manually. You'd also need to use `order: :defined` within those example groups to make sure they're not randomly activated.

It's not really recommended to do this (instead consider refactoring to reduce the amount of test setup you need per acceptance test) as the benefit of isolation of tests outweighs the performance boost by saving a few steps.
