### ISSUE TITLE
Request spec environment is 'test' when run alone, but 'production' when run as a suite

### ISSUE THREAD

**Issue by kieraneglin** [rspec/rspec-rails#1688]
**Versions**
OS: OSX 10.11.1
Ruby: 2.3
Rails: 5.0
Rspec, rspec-core, and rspec-rails: 3.5.0

**Steps to reproduce**
1. Create new Rails 5 project
2. Create basic home controller and routes
3. Create feature spec with the contents `puts Rails.env`
4a. Run the spec using `rspec <path to request spec>`
4b. Run as a suite using `rspec spec`

**Expected behavior**
Step 4 should return `test` in both circumstances

**Actual behavior**
Step 4a returns `test` and step 4b returns `production`

**Pictures**
- [The spec itself](http://imgur.com/iYcDFrz)
- [When ran alone](http://imgur.com/GnhIehN)
- [When ran as a suite](http://imgur.com/viIwjcX)

**Comment by JonRowe** [comment]
I believe you have something setting the production environment via the environment variables RACK_ENV or RAILS_ENV when running the entire suite, try grepping your codebase.

**Comment by kieraneglin** [comment]
@JonRowe, there are no hits for `RACK_ENV`, and `RAILS_ENV` never gets set to production

**Comment by JonRowe** [comment]
@kieraneglin we never modify those values ourself except to test so it must be coming from somewhere, are you using a .env file or other environment variable setting method? Whats the value for those two in `env` (a command line command).

**Comment by samphippen** [comment]
Hi @kieraneglin 

Thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks 👍

**Comment by mikegee** [comment]
This issue has almost no chance of being a bug in RSpec. I recommend closing until @kieraneglin can create a reproduction case as requested above.

@kieraneglin if you are still having this problem and can link to your whole application rather than creating a reproduction case, I'm interested in taking a look.

**Comment by benoittgt** [comment]
Thanks, @mikegee for the bump and the help offer. Closing it for now.
