### ISSUE TITLE
Running Rspec on Rake task

### ISSUE THREAD

**Issue by Xosmond** [rspec/rspec-rails#1691]
Is there any way to run all my tests on a rake task?

```
task :runtests=> :environment do
    **HERE RUN RSPEC WITH ALL TESTS AND GET THE RESULT TO A STRING**
    THEN DO SOMETHING WITH TE RESULT
end
```

Thanks.

**Comment by samphippen** [comment]
Hi @Xosmond, we prefer that the RSpec issue tracker is only used for bugs and features. Would you mind re-asking your question over on our mailing list: https://groups.google.com/forum/#!forum/rspec.
