### ISSUE TITLE
user model gone / not recognizing

### ISSUE THREAD

**Issue by anggainlippox** [rspec/rspec-rails#1692]
hi all I've test all model and it works great except the user model, when I go to 
xxxx/coverage/index.html the user model not there. how can I solve this?

Thanks before :)

**Comment by samphippen** [comment]
hi @anggainlippox, this most likely isn't an issue with RSpec. I'd suggest filing this with whatever coverage gem you're using, as most likely it's an issue with that gem.

**Comment by anggainlippox** [comment]
thank for fast respond @samphippen :+1:
