### ISSUE TITLE
Everything in the config is loaded twice when testing using rspec

### ISSUE THREAD

**Issue by inv-joseph** [rspec/rspec-rails#1694]
**Gemlist** for my project is 

```
group :development, :test do
  gem "rails-erd"
  gem 'letter_opener'
  gem 'spring'
  gem 'faker'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end
```

**Spec_helper.rb** has following data

```
require 'factory_girl_rails'

RSpec.configure do |config|
  config.include FactoryGirl::Syntax::Methods
end
```

**group_spec** content is 

```
require 'spec_helper'

require File.expand_path("../../../config/environment", __FILE__)
RSpec.describe Class, :type => :model do
  #pending "add some examples to (or delete) #{__FILE__}"
  before(:each) do
    @my_car=Factory.create(:group, params)
  end
end
```

When I execute command 'bundle exec rspec spec/models/group_spec.rb'. It produces the following error

```
/usr/local/rvm/gems/ruby-2.3.1/gems/airbrake-ruby-1.4.4/lib/airbrake-ruby.rb:102:in `configure': the 'default' notifier was already configured (Airbrake::Error)
    from /path/to/config/initializers/errbit.rb:1:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
    from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
    from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
```

airbrake file is loaded twice. When I remove all data in errbit.rb then showing error that routes are repeatedly loading. Please help to solve this issue

**Comment by JonRowe** [comment]
This line:

`require File.expand_path("../../../config/environment", __FILE__)` 

is probably causing this behaviour, if Rails is also loaded elsewhere it'll cause this behaviour, requires are only idempotent if the file path is the same.

**Comment by myronmarston** [comment]
@JonRowe's probably right...but in general if you want to see what's causing files to get loaded, just put this at the top of the file:

``` ruby
puts "Loading #{__FILE__}. Backtrace:"
puts caller.join("\n")
puts
```

That'll print out the backtrace of the code that led to the file being loaded, and you can see where the sources of multiple requires are.

**Comment by inv-joseph** [comment]
@JonRowe I have replaced all require File.expand_path with require_relative, but still have the same issue. All files in initializers and routes.rb file is loading twice. When I comment routes.rb then can execute 
**bundle exec rspec**   command and test models. As there is no conflict between two routes(When the routes.rb is executed twice there is no routes to raise conflict) .

It is loaded twice when executes the command **Rails.application.initialize!** in environment.rb. It works fine and these files are executed only once when we run the project

@myronmarston  in which file do I place this codes

**Comment by myronmarston** [comment]
In any file in which you want to understand the backtrack at the point it gets loaded.

**Comment by inv-joseph** [comment]
@myronmarston ,  I have added the above given code in config/initializers/assets.rb, which produces same backtrace for both time and the resulted backtrace is 

Loading /home/akhil/test-prjct/test/project/config/initializers/assets.rb. Backtrace:
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.1/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.1/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.1/lib/rails/engine.rb:615:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
/home/akhil/test-soko/test/sokonokado/config/environment.rb:11:in `<top (required)>'
/home/akhil/test-soko/test/sokonokado/spec/rails_helper.rb:4:in `require_relative'
/home/akhil/test-soko/test/sokonokado/spec/rails_helper.rb:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `block in requires='
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `requires='
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:101:in `block in process_options_into'
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:100:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:100:in `process_options_into'
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:22:in `configure'
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:96:in `setup'
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:85:in `run'
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.0.4/exe/rspec:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/rspec:23:in `load'
/usr/local/rvm/gems/ruby-2.3.1/bin/rspec:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by JonRowe** [comment]
Per your backtrace, your loading Rails in your `rails_helper.rb` and your group spec:

```
/home/akhil/test-prjct/test/project/config/environment.rb:11:in `<top (required)>'
/home/akhil/test-prjct/test/project/spec/rails_helper.rb:4:in `require_relative'
```

**Comment by inv-joseph** [comment]
@JonRowe ,I don't understand what you actually meant. As you said I have changed require File.expand_path() to require_absolute. I found that in environment.rb when Rails.application.initialize! is executed all the initializing files are executed twice while running rspec. But when we run the project it is executed only once. So no issue there

**Comment by JonRowe** [comment]
From your initial post:

```Ruby
require 'spec_helper'

require File.expand_path("../../../config/environment", __FILE__)
RSpec.describe Class, :type => :model do
  #pending "add some examples to (or delete) #{__FILE__}"
  before(:each) do
    @my_car=Factory.create(:group, params)
  end
end
```

Remove the require, as `rails_helper.rb` already contains one.

**Comment by inv-joseph** [comment]
yes. I remove require File.expand_path("../../../config/environment", __FILE__) from every *_spec files. But issue is still there the same issue

**Comment by JonRowe** [comment]
Did you try not replacing it with the require_relative? It's recommended to just use `require 'rails_helper'` when you need Rails.

**Comment by inv-joseph** [comment]
files under config contain require_relative. In *_spec files there is only require 'rails_helper'

**Comment by inv-joseph** [comment]
@JonRowe, @myronmarston  : I have found that the issue is when rspec execute lib/mailboxer/engine.rb. When I delete that file the issue is solved .The content of this file is exactly the same as https://github.com/mailboxer/mailboxer/blob/master/lib/mailboxer/engine.rb. What may be the issue. Please give your conclusions

**Comment by soulcutter** [comment]
This issue has grown stale. It sounds like a problem outside of RSpec, so closing for now.

**Comment by braindeaf** [comment]
Did anyone ever find a solution for this I am still seeing this with a Rails 6.1 project (using engines), and latest RSpec.

**Comment by pirj** [comment]
@braindeaf Yes, it's typically an redundate `require` statement in one of the files. You'll pinpoint it by finding a common root of the two backtraces printed by `puts caller` at the beginning of the file that complains that it's loaded twice.

There's apparently nothing that could/should be fixed in RSpec itself, so let's move the further discussion to our mailing list https://rspec.info/help/

**Comment by braindeaf** [comment]
I've just traced it back to here, in Devise::JWT, I guess this is all deliberate

```ruby
config.after_initialize do
  Rails.application.reload_routes!
```
          
 So nothing to do with Rspec, I just hadn't otherwise noticed :) Thank you.

**Comment by thisismydesign** [comment]
In my case, this was caused by an unnecessary `Dotenv.load` call.
