### ISSUE TITLE
method stub doesn't survive a @object.becomes(OtherSTIClass)

### ISSUE THREAD

**Issue by foucist** [rspec/rspec-rails#1728]
Just thought it was amusing to discover this ;)

It's not totally unexpected, since #becomes actually creates a new object and copies the attributes over.   So however the stub hooks into the object is likely not getting copied. 

http://apidock.com/rails/ActiveRecord/Persistence/becomes

example:

```
it "doesn't work" do
  create(:message, sender: sender)
  expect(sender).to receive(:some_method)
  message.call_something
end

def call_something
  message.becomes(OtherMessage)
  message.sender.some_method
end

```

**Comment by myronmarston** [comment]
When you `expect` or `allow` an object to receive a message, that affects _only_ that one object. I know nothing about `becomes` but if it creates a new object instance as you say, there is no reason to think that the returned object would inherit what's been mocked or stubbed from the source object.

OTOH, in your example, you call `message.becomes(OtherMessage)` and ignore the return value, and then you are calling `some_method` on `message.sender` -- which, if I'm understanding correctly, should not be affected by the `becomes` call.

Does `becomes` cause some kind of side effect on `message` or any of its attributes?  The description and source you linked to make it look like `becomes` is side-effect free, so the example you pasted should work.

**Comment by JonRowe** [comment]
Closing as stale
