### ISSUE TITLE
Migrations not automatically being run

### ISSUE THREAD

**Issue by MasterRoot24** [rspec/rspec-rails#1733]
For some reason, `ActiveRecord::Migration.maintain_test_schema!` seems to be broken for me on a new Rails 5 app that I'm currently building ([code here](https://github.com/MasterRoot24/acrm)).

If I push [`3f2355d `][broken-sha] to `master` on GitHub, Travis builds fail with the error:
```
Migrations are pending. To resolve this issue, run:
	bin/rails db:migrate RAILS_ENV=test
```
Build log [here](https://travis-ci.org/MasterRoot24/acrm/builds/171602866).

If I add a `before_script` to Travis that runs `bundle exec rake db:migrate RAILS_ENV=test` the build succeeds. However, it's my understanding that `ActiveRecord::Migration.maintain_test_schema!` (which is in my `spec/rails_helper.rb` file) should remove the need for the manual migration call in the `before_script`.

If I push the commit before that ([`5d81376`][working-sha]) the build succeeds without having to manually run `rake db:migrate` before the build.

Anyone able to offer any reasons why I would need to manually run migrations *after* commit [`5d81376`][working-sha] on the repo above? I don't think this is a bug with `rspec-rails`, but I'm hoping someone here can help.

[working-sha]: https://github.com/MasterRoot24/acrm/commit/5d81376f159325342101b470bebf845033b45d35
[broken-sha]: https://github.com/MasterRoot24/acrm/commit/3f2355ded76ff3a23e0416ec6d2da7fbb0c0917f

**Comment by JonRowe** [comment]
As per the rails documentation, the `ActiveRecord::Migration.maintain_test_schema!` doesn't run migrations automatically, it loads the schema, could that be your issue? You need to have run the migration manually yourself before hand, committed the schema, for this to run.

**Comment by MasterRoot24** [comment]
You can see from [`3f2355d`](https://github.com/MasterRoot24/acrm/commit/3f2355ded76ff3a23e0416ec6d2da7fbb0c0917f) on the source repo, the schema is up to date with the changes in the migration that was added in that commit.

Furthermore, if I checkout that commit locally, and migrate the DB again, there are no changes made to the schema file, proving that the schema is up to date with the migrations.

```
joenyland@Joes-MacBook-Pro ~/Code/acrm $ git checkout 3f2355d
HEAD is now at 3f2355d... Add address to Company model
joenyland@Joes-MacBook-Pro ~/Code/acrm $ rails db:migrate
joenyland@Joes-MacBook-Pro ~/Code/acrm $ git status
HEAD detached at 3f2355d
nothing to commit, working tree clean
joenyland@Joes-MacBook-Pro ~/Code/acrm $ 
```

**Comment by JonRowe** [comment]
I think in the case of Travis you must have to run then manually then, as it has no DB to copy.

**Comment by MasterRoot24** [comment]
> If I push the commit before that ([`5d81376`](https://github.com/MasterRoot24/acrm/commit/5d81376f159325342101b470bebf845033b45d35)) the build succeeds without having to manually run `rake db:migrate` before the build.

Furthermore, I don't have to run migrations manually for other Rails apps on Travis.

**Comment by JonRowe** [comment]
I'm out of ideas sorry, not something RSpec is involved with. Why don't you try asking the Rails devs?

**Comment by MasterRoot24** [comment]
Me too 😞

I assumed it would be batted back to `rspec-rails`. I've contacted Travis "support" too, but no reply... I'll try Rails and see what they say.

Thanks for taking a look at it though 🙂

**Comment by hibaAkroush** [comment]
run: rake db:migrate RAILS_ENV=test 
and then: rspec spec
