### ISSUE TITLE
config.include with type not loading

### ISSUE THREAD

**Issue by fweep** [rspec/rspec-rails#1736]
I'm trying to include a bunch of helpers conditionally based on their `type`, but when I apply a type restriction, none of them load.

I have these in my `rails_config.rb`:

```
config.include Rails.application.routes.url_helpers
config.include Shoulda::Matchers::ActionController
config.include Capybara::DSL
config.include Warden::Test::Helpers
config.include WaitForAjax
```

What I want is:

```
config.include Capybara::DSL, type: :feature
config.include Rails.application.routes.url_helpers, type: :request
config.include Rails.application.routes.url_helpers, type: :feature
```

...and so on.

When I use any `type` restriction, they don't load, and I get undefined method errors. I thought Spring might be to blame, but it happens without Spring.

I'm using type declarations in my specs:

```
RSpec.feature "Employees Feature", type: feature do
```

I'm not sure what the downside is to always including them. I was hoping to speed up my tests.

**Comment by myronmarston** [comment]
Try `type: :feature` instead of `type: feature`.  The latter (which your snippet above has) calls the `feature` method and sets `:type` to whatever the return value is.

You may also want to configure RSpec to disable monkey patching:

``` ruby
RSpec.configure do |config|
  config.disable_monkey_patching!
end
```

That will prevent `feature` from being defined on `main`, which should give you a `NoMethodError` for a mistake like `type: feature`.

**Comment by JonRowe** [comment]
> I'm not sure what the downside is to always including them. I was hoping to speed up my tests.

The downside is you have to have required and loaded all those modules, this can increase time taken to start running your specs (if rails has to be booted that drastically increases that time).

**Comment by fweep** [comment]
Thanks @myronmarston! That was exactly the problem. I didn't even see that; all my other specs use symbols for the type. I must have pasted some boilerplate into my first feature spec and I just kept copy-pasting the `describe` line in new feature specs. I've disabled monkey patches so that this won't bite me again.

**Comment by fweep** [comment]
@JonRowe, it does indeed make a huge difference. It shaved 25% of the time off my test suite, which is a huge win.
