### ISSUE TITLE
I'm having a problem debugging why I my spec_helper.rb doesn't allow me to have spec files in app/

### ISSUE THREAD

**Issue by NullVoxPopuli** [rspec/rspec-rails#1738]
I'm trying out a more 'together' layout of files, like:
![2016-10-31-160615_333x267_scrot](https://cloud.githubusercontent.com/assets/199018/19869750/02dd6798-9f84-11e6-971f-82f981a59f80.png)

But, my spec_helper errors starting with the rspec-ralis require, and gives me all sorts of errors on the Rspec Configuration option like undefined method `fixture_path=`, `use_transactional_fixtures=`, ... etc

I have my changes in this PR of my repo: https://github.com/NullVoxPopuli/aeonvera/pull/910

Here is my spec helper.

https://github.com/NullVoxPopuli/aeonvera/blob/0bb644b9bab1fee4e4b5b18d04d1827c3d813119/spec/spec_helper.rb

I've tried moving a spec file to app in another project of mine, and for some reason it works?

No idea why. Any ideas / gotchyas? Thanks!

**Comment by NullVoxPopuli** [comment]
figured it out: needed `Bundler.require(:default, :test)` at the top of my spec helper. new spec_helper in nthe PR

**Comment by JonRowe** [comment]
This is a very non standard way to structure your tests, what I suspect is happening is a load ordering issue with the specs being loaded when you boot Rails. Your fix is just loading rspec-rails early and solving the issue, but I warn you that it's unlikely be able to seperate your rails specs out using this approach. (A moot point given that your spec_helper does this anyway, no real point in having the rails_helper in your scenario).

**Comment by NullVoxPopuli** [comment]
does rails load _everything_ under app? even if classes/files (like the specs) aren't used?

**Comment by JonRowe** [comment]
If eager loading is turned on definitely, otherwise it at least registers all the files for autoloading with active support. Either way it is very not recommended to store specs in your app folder.

**Comment by NullVoxPopuli** [comment]
well, balls. thanks for the tip!

(alternatively, I wonder if I could change eager_loading to skip files ending in _spec)

**Comment by JonRowe** [comment]
You could, but why do you want to store your test files with you application code?

**Comment by NullVoxPopuli** [comment]
I was just going to try out and see how I felt about having related files next to eachother. I'm already doing it with application files via https://github.com/NullVoxPopuli/rails_module_unification/  

But it might be more effort than it's worth. idk.
