### ISSUE TITLE
Automate testing successful boot of Worker Processes

### ISSUE THREAD

**Issue by joshuamcginnis** [rspec/rspec-rails#1740]
Ruby version: 2.2.4
Sidekiq / Pro / Enterprise version(s): Sidekiq Pro 3.3.3

We've had a couple of issues recently in our Rails 4 app that could have been prevented with a simple check to see that both the main app and a worker process correctly boot up our application.

Our Procfile for Heroku looks like so:
```
web: bundle exec unicorn -p $PORT -c config/heroku/unicorn.rb
sidekiq: bundle exec sidekiq -q high -q medium -q low
```

Right now, we run a very large test suite that takes 30 mins to complete, even when bisecting the suite across 10+ containers.

We use CircleCI and are considering adding a test like follows that simulates the Sidekiq bootup process.

```ruby
require 'spec_helper'

RSpec.describe 'Booting processes' do

  context 'Sidekiq server' do
    it 'loads successfully' do
      boot_sidekiq_sequence = <<-SEQ
        require 'sidekiq/cli'
        Sidekiq::CLI.instance.environment = '#{ENV['RAILS_ENV']}'
        Sidekiq::CLI.instance.send(:boot_system)
      SEQ

      expect(system(%{echo "#{boot_sidekiq_sequence}" | ruby > /dev/null})).to be_truthy,
        "The Sidekiq process could not boot up properly. Run `sidekiq` to troubleshoot"
    end
  end
end
```

The problems I see with this approach are:

* It's not quite a complete test of our application boot process which would require reading from our Procfile (we also want to protect devs from making breaking changes there)
* It's slow and would add approx 30 secs to our test runtime
* It's only testing a specific portion of the overall Sidekiq boot process

What makes testing the Sidekiq boot process in particular challenging is that it will only exit if there is an exception on boot.

Can anyone recommend a better, faster, more thorough approach to automating this kind of test?

**Comment by joshuamcginnis** [comment]
Is there some place else more fitting for the question, if not here?

**Comment by JonRowe** [comment]
Closing because this isn't an RSpec issue per se ;)

All I can suggest to improve that test would be to boot sidekiq in your circle ci setup (hopefully they allow that to be done in parallel) and set bash to exit if it fails (which should fail your ci), failing that given you have a enterprise version of sidekiq request support from them?

We have a mailing list which might be able to help more on this issue: rspec@googlegroups.com

**Comment by joshuamcginnis** [comment]
👍  Thank you kindly.
