### ISSUE TITLE
uninitialized constant ActionDispatch::IntegrationTest::Behavior (NameError) with Rails 5.0.0.beta2

### ISSUE THREAD

**Issue by Oniiko** [rspec/rspec-rails#1741]
When running rspec with Rails version 5.0.0.beta2, I get this NameError and the it fails to run.

https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/example/request_example_group.rb

```
      if ActionPack::VERSION::MAJOR >= 5
        include ActionDispatch::IntegrationTest::Behavior
      end
```
I checked the rails repository (https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb) and the Behavior module isn't bundled with Rails 5.0.0.beta2.

It's available on Rails 5.0.0 and onwards stable releases, so I just upgraded my Rails version to use rspec. Set the issue here in case anyone else has the same problem.

**Comment by JonRowe** [comment]
Given that Rails 5 is now released I suggest upgrading, things may have moved about during the beta.
