### ISSUE TITLE
Rspec 3.5 + factory_girl-preload are not rolling back on each test

### ISSUE THREAD

**Issue by gustavowt** [rspec/rspec-rails#1745]
Hy guys,

This issue was posted on factory_girl-preload [repository](https://github.com/fnando/factory_girl-preload/issues/24) too 

I'm trying to configure the RSpec 3.5 and factory_girl-preload 2.3.1 on Rails 5 as a usually do since Rails 2.

I just realized that something has changed on RSpec 3.5 regarding the option use_transactional_fixtures I've noticed that they are not using savepoint anymore, but are using begin/commit transactions. The problems is that, as I'm using a shared connection, every time that I change something on the database it runs a new begin/commit transaction and I'm suspecting that the rollback is not working for this case, because I'm getting some preloaded factories with different data when I run the whole suite, and the tests are running fine when I run a single suite.

hope someone can help on this one.

Thanks

**Comment by JonRowe** [comment]
`use_transactional_fixtures` delegates to Rails, so it's either FactoryGirl or Rails itself causing this issue. RSpec itself does no handling of your database.
