### ISSUE TITLE
Return response instead of status code in integration tests

### ISSUE THREAD

**Issue by printercu** [rspec/rspec-rails#1746]
Hi!

HDYT about changing return value of `process` method in integration tests? So spec files will get more clear (here are rspec examples, hope similar will be for minitest):

```ruby
# now
subject { get(some_path) && response }
it { should be_ok }
it { should redirect_to }

# after change
subject { get(some_path) }
# same assertions
``` 

I understand that it is not backward-compatible, but it would discourage using magic numbers too:

```ruby
# now
expect(get('/')).to eq 200

# after
expect(get('/')).to be_ok
```

I tried to investigate why rails provides such behaviour. I followed up till some [commit](https://github.com/rails/rails/blame/33030ea7cbfa026b0f9f95a2c5d2dd363a7fe6aa/actionpack/lib/action_dispatch/testing/integration.rb#L380) in 2009, where it already returns status code and gave up.

I've proposed this to rails, but they don't like the idea https://github.com/rails/rails/issues/27039

**Comment by JonRowe** [comment]
`rspec-rails` is a thin wrapper around Rails, we don't control that method and have no intention of doing so.

**Comment by JonRowe** [comment]
You can however implement this yourself very easily with this:

```Ruby
module ReturnStatus
  def process(*args)
    super
    # whatever you want to return
  end
end

RSpec.configuration.include ReturnStatus, type: :feature
```

**Comment by JonRowe** [comment]
> I understand that it is not backward-compatible, but it would discourage using magic numbers too:

> ```Ruby
# now
expect(get('/')).to eq 200
# after
expect(get('/')).to be_ok
```

This would be an undesirable change, in this scenario "be_ok" is the magic, 200 is the standard. Not knowing HTTP response codes is bad practise for a web developer.

**Comment by printercu** [comment]
OK. BTW it can not be done with this simple include, because every http method is defined separately with `define_method` and only `ActionDispatch::Integration::Session` has `process` method.

**Comment by JonRowe** [comment]
If it doesn't work (I didn't try it) use `configuration.prepend` as you definitely can override process, I've done it in test suites to preprocess json bodies.

**Comment by printercu** [comment]
> This would be an undesirable change, in this scenario "be_ok" is the magic, 200 is the standard. Not knowing HTTP response codes is bad practise for a web developer.

RSpec states that spec files can be descriptive as docs. It's not about knowing the standard, it's about readable code. Even if somebody knows what does 422 code means, he still write `render status: :unprocessable_entity`.

**Comment by JonRowe** [comment]
> RSpec states that spec files can be descriptive as docs. It's not about knowing the standard, it's about readable code. Even if somebody knows what does 422 code means, he still write render status: :unprocessable_entity.

Not necessarily, they may find `422` more readable, as it's more specific.

**Comment by printercu** [comment]
Prepend would not work for config to:
```
".../.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/testing/integration.rb:273:in `process'",
".../.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/testing/integration.rb:32:in `get'",
".../.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/testing/integration.rb:346:in `block (2 levels) in <module:Runner>'",
"...project/spec/requests/venue/orders_spec.rb:9:in `block (3 levels) in <top (required)>'",
```

It requires either defining all http methods in module to include or (I use) `ActionDispatch::Integration::Session.prepend SessionHelpers`.

**Comment by printercu** [comment]
`process` appears only in `integration_session` object.

**Comment by JonRowe** [comment]
I was attempting to help by showing how to customise the behaviour, I'm sure you can figure out actual implementation required!

**Comment by printercu** [comment]
However, it's not a problem to not implement it in rspec-rails, because it also requires `Module#prepend` which is not available in old rubies. So them would not have this feature. I'll just add it to my pack of tools.

Status code is just a sample. More complex examples are `it { should redirect_to }`, `its(:body) { should include }`, and so on.

**Comment by printercu** [comment]
Thank you for your time! Happy codding 😃
