### ISSUE TITLE
AJ matchers are no longer work with stubbed objects

### ISSUE THREAD

**Issue by sponomarev** [rspec/rspec-rails#1751]
After all of the improvements during 3.4 -> 3.5 period we can no longer use stubbed objects as arguments for AJ tasks. AJ matchers use `ActiveJob::Arguments.deserialize` and a test is failed because it can't find an object in a database.

The second problem that it tries to hit the database every time. Do you think that it make sense to change this behavior? The only place where we really need job arguments is with block check.

**Comment by JonRowe** [comment]
Apologies that no-one got back to you at the time, but the deserialisation is done to match what rails does, parity with rails was more important as we didn't want to reimplement their code and get it wrong.
I'm closing as stale but please re open if you have something you'd like to fix.
