### ISSUE TITLE
Requiring rails/test_help in rails_helper.rb causes exit 1 when using --color

### ISSUE THREAD

**Issue by olivierlacan** [rspec/rspec-rails#1752]
```
$ bundle exec rspec --color spec/test_spec.rb; echo $?;
Running via Spring preloader in process 12588
/Users/olivierlacan/Development/sandbox/rspec-exit-1-color-flag-test-help-rails-4-2/db/schema.rb doesn't exist yet. Run `rake db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/olivierlacan/Development/sandbox/rspec-exit-1-color-flag-test-help-rails-4-2/config/application.rb to limit the frameworks that will be loaded.
No examples found.


Finished in 0.00061 seconds (files took 2.49 seconds to load)
0 examples, 0 failures


invalid option: --color

minitest options:
    -h, --help                       Display this help.
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /regexp/ or string.
    -e, --exclude PATTERN            Exclude /regexp/ or string from run.

Known extensions: pride
    -p, --pride                      Pride. Show your testing pride!
1
```

I know right?

This took me forever to figure out. So here's the repro app: https://github.com/olivierlacan/rspec-exit-1-color-flag-test-help-rails-4-2

It has a no-op spec which reproduces the issue only when run with `--color` as far as I know. 

[@JonRowe theorized on Twitter][1] that it could have something to do with: 
> @myronmarston @olivierlacan it includes `require "active_support/testing/autorun”`, maybe thats exiting 1 as it doesn’t understand the flag

[1]: https://twitter.com/JonRowe/status/800822342628753417

**Comment by JonRowe** [comment]
I'm pretty certain this is due to `minitest`, see the output mentions

```
invalid option: --color

minitest options:
```

The autorun require is triggering minitest which in turn is erroring because of the --color flag. This is similar to other situations we've seen when minitest is accidentally included into rspec suites.

In general rails test helpers cannot be included into RSpec directly, as they contain an assumption you're using minitest.

**Comment by JonRowe** [comment]
Closing as I believe this is an issue with trying to use minitest with rspec.
