### ISSUE TITLE
Rails 4.2.6/rspec-rails 3.4:  assigns is not working

### ISSUE THREAD

**Issue by imaginationcoder** [rspec/rspec-rails#1757]
Rails 4.2.6/rspec-rails 3.4:  At my controller spec, assigns is always empty though i defined instance  variable at my controller

**Comment by JonRowe** [comment]
We generally ask that people use the mailing list for "ask for help" questions, if you can gist your spec I might be able to help here however.

**Comment by imaginationcoder** [comment]
Hey JonRowe, 
    here is my spec code

require 'rails_helper'

RSpec.describe PostsController, type: :controller do
    it "loads all posts into @posts" do
      post1, post2= Post.create!(content: "123"), Post.create!(content: "123")
      expect(assigns(:posts)).to eq([post1, post2])
    end
  end

**Comment by JonRowe** [comment]
You're not actually calling your controller there

**Comment by JonRowe** [comment]
A quick google came up with this blog post, which might be a good read for you in your controller testing adventure. https://everydayrails.com/2012/04/07/testing-series-rspec-controllers.html

**Comment by imaginationcoder** [comment]
ahh!   

Thanks JonRowe.
