### ISSUE TITLE
Rspec not testing render, won't allow us to stub

### ISSUE THREAD

**Issue by rkentmc** [rspec/rspec-rails#1758]
Rails 5.0.0.1
Rspec 3.5.4
Ruby 2.3.1

We have been trying to provide test coverage for our rails application. We have a rescue in a private method that Rspec is not reaching. 

Rspec:

```
  it 'returns 200 after 404 from GET #edit error' do
     allow(controller).to receive(:getpackage).and_return(URI::InvalidURIError)    
     expect(response.code).to eq(200) # => covers the 200
     expect(response).to render_template('errors/5xx') # => does not read the render
   end

```

Rails:

```
private

def set_package
   @package = PackageServices.getpackage params[:id]
 rescue URI::InvalidURIError
   render 'errors/5xx'
 end
```
Error message:

```
expecting <"errors/5xx"> but rendering with <[]>
./spec/controllers/packages_controller_spec.rb:139:in `block (3 levels) in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'

```

We have tried to assert_template, tried to stub it using stub_template, installed a gem rails-controller-testing (not rspec), but we have run out of ideas and every google link is purple. Is this a bug or are we going about it the wrong way?

**Comment by JonRowe** [comment]
You've setup a stub here:
```Ruby
allow(controller).to receive(:getpackage).and_return(URI::InvalidURIError) 
```
but are calling: `PackageServices.getpackage params[:id]`.

I suspect you need to do: `allow(PackageServices).to receive(:getpackage).and_raise(URI::InvalidURIError)` instead

**Comment by rkentmc** [comment]
It is not reaching the render_template, I have used every syntax that is available. It raises the error and returns 200 fine. Do you have a suggestion for triggering coverage for the render action?

"expecting <"errors/5xx"> but rendering with <[]>"

**Comment by JonRowe** [comment]
Correct, you're not raising an error so the rescue is never reached.

**Comment by rkentmc** [comment]
Your earlier suggestion does not work. Do you have a suggestion for triggering coverage for the render action?

**Comment by JonRowe** [comment]
You're missing a `get :edit` for starters.

**Comment by JonRowe** [comment]
If you changed `allow` for `expect` you would see it's never called.
