### ISSUE TITLE
infer spec type using default-path setting from RSpec

### ISSUE THREAD

**Issue by mockdeep** [rspec/rspec-rails#1759]
We've nested our Rails specs under a sub directory `spec/ruby/`. This seems fine when we add `--default-path spec/ruby` to our `.rspec` file, but `rspec-rails` can no longer infer the spec types, since it looks like it has hard coded the expectation that it will find controllers in `spec/controllers`. It would be great if this aligned with the `--default-path` option and used that as the base directory.

**Comment by JonRowe** [comment]
Thanks for the suggestion @mockdeep but inferring spec types is a legacy hangover, as such its currently kept only for back compatibility, and as such we don't want to expand it. I'd recommend switching to using explicit types.

**Comment by mockdeep** [comment]
So you would do `define_derived_metadata` for all spec types? It seems like a common enough use case that it should be handled by the gem as opposed to having each application define them manually.

**Comment by JonRowe** [comment]
No I'd simply add `type: n` where required, it's a far simpler solution, it's also what's generated by the generators. Transpec can also convert older specs to this format.

**Comment by mockdeep** [comment]
Hmm, okay. I'll give Transpec a look.
