### ISSUE TITLE
Use assert_nil if expecting nil

### ISSUE THREAD

**Issue by Gedrovits** [rspec/rspec-rails#1761]
**rspec-rails** version **3.5.2**

> Use assert_nil if expecting nil from /Users/vgedrovits/.rvm/gems/ruby-2.3.1/gems/rspec-rails-3.5.2/lib/rspec/rails/adapters.rb:212:in `block (2 levels) in define_assertion_delegators'. This will fail in MT6.

Recently received this warning, nothing critical, but do we want to fix that?

**Comment by samphippen** [comment]
@Gedrovits thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by xaviershay** [comment]
This warning is coming from Minitest (MT6 = minitest 6 ... this was non-obvious to me until I did some digging). It occurs when you do something like:

```
expected = nil # possibly a mistake?
assert_equal expected, nil
```

I believe `rspec-rails` enables minitest assertions which is what allows `assert_equal` in RSpec. By default, this is not a method we provide.

This is a legitimate deprecation warning from minitest, and isn't something we would fix in rspec.
