### ISSUE TITLE
REQUEST SPEC: Post to route redirects to Get route

### ISSUE THREAD

**Issue by Herz3h** [rspec/rspec-rails#1766]
Hello,

I have a controller with methods that responds to posts as defined in route : 

`post '/events/create'
`
And i have a Request spec like this : 

```
describe "Event management", :type => :request do 
   context "with access token" do
     it "creates an event"
        post events_create_path, params: {title: "blabla", message: "new event"}
        follow_redirect! # I added this otherwise i get status code of 301 or 307 (redirect)
        expect(response.status).to eq(200)
     end
  end
end
```

But even after adding follow_redirect it says : No routes matches [GET] /events/create

If i change that /events/create to GET in routes and do get in request spect rather than POST it works fine. So i assume this is a bug ?

If not please correct me 

Thanks in advance

**Comment by samphippen** [comment]
hi @Herz3h could you follow these steps:

Thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by Herz3h** [comment]
Ok i've tried to extract only that controller and the create method, then use same Request spec, and same Gemfile and it works... so i have no idea what makes it try to redirect in the other case. Btw i do a post request to an external API in my create action, but that doesn't cause any problem in the isolated rails app i made for test.

**Comment by Herz3h** [comment]
Actually since i was using this project which i've modifed for my need : https://github.com/microsoftgraph/ruby-connect-rest-sample

I just made a new project as you told me and moved all my code, now the bug seems to be gone. not sure why it happened.
