### ISSUE TITLE
Acceptance specs on 1.8.7 are currently skipped.

### ISSUE THREAD

**Issue by JonRowe** [rspec/rspec-rails#1783]
Our 1.8.7 builds seg fault when trying to run acceptance specs, as of #1769 they are skipped to maintain a consistent green build but we'd like to run as much as possible on 1.8.7. This issue has been opened to keep track of that information.

/cc @samphippen @myronmarston

**Comment by samphippen** [comment]
@JonRowe I'm tempted to de-prioritise this one. I'm planning on implementing the rspec-rails 4.0 RFC over my christmas vacation (that is, get drop a version which removes old railses, etc).

**Comment by JonRowe** [comment]
This can be closed when RSpec-Rails goes off pisté :) :+1:
