### ISSUE TITLE
How to run rspec against gem's spec cases

### ISSUE THREAD

**Issue by gamesover** [rspec/rspec-rails#1784]
Hi, if I create a new rails project, I want to run `rspec` for current project `spec` test case, which is very easy, and I want to run rspec against one installed gem's test cases in this gem's `spec` folder.

All in all, I run `rspec`, it checks test cases in spec folder and the desired gem's spec folder. Any  advice is quite welcome. Thanks.

**Comment by JonRowe** [comment]
You'll need to provide the path e.g. `rspec ./spec/ /path/to/gem/spec`

**Comment by gamesover** [comment]
I've worked it out and many thanks! @JonRowe
