### ISSUE TITLE
Scaffold generator in API mode generates tests for new and edit actions

### ISSUE THREAD

**Issue by ppires** [rspec/rspec-rails#1786]
When using the scaffold generator in rails 5 API mode (with rspec-rails), the controller is generated without the `new` and `edit` actions, but the generated tests are testing these actions (and of course they fail since theses actions don't exist!).

**Steps to reproduce:**
1. create new rails app in API mode (`rails new app_name --api`)
2. install the `rspec-rails` gem (add to Gemfile and then `rails g rspec:install`)
3. run the scaffold generator (`rails g scaffold MyModel`)

**Expected behavior:**
The tests generated in `spec/controllers/my_model_controller_spec.rb` don't have tests for the `new` and `edit` actions.

**Actual Behavior:**
The tests generated in `spec/controllers/my_model_controller_spec.rb` DO HAVE tests for the `new` and `edit` actions, and consequently they fail.

**Comment by ppires** [comment]
Forgot to mention that the routing spec are generated with the `new` and `edit` routes as well!

**Comment by adimircolen** [comment]
👍

**Comment by JonRowe** [comment]
Happy to accept a PR to fix this, the api mode is relatively new and I don't think our scaffolds have been modified to reflect this.

**Comment by ppires** [comment]
@JonRowe was checking the code for the PR, and noticed that this is already fixed in the master branch. Probably it will make in the 3.6 release. Will close the issue.
