### ISSUE TITLE
Display warning or error when using `expect(...).to raise_error(...)`

### ISSUE THREAD

**Issue by maikokuppe** [rspec/rspec-rails#1787]
This piece of code 

```
it 'raises an error' do
  expect(raise StandardError).to raise_error(StandardError)
end
```

results in

```
Failure/Error: expect(raise StandardError).to raise_error(StandardError)

StandardError:
  StandardError
```

which does not really help. The correct way is to use a block like this:

```
it 'raises an error' do
  expect{raise StandardError}.to raise_error(StandardError)
end
```

This is really frustrating if you just can't find the mistake (happened to me several times over the past years).

Is there any usecase for using `raise_error` in combination with `expect(...)`? If not (that's what I think), it would make sense to raise an `RSpec::RaiseErrorRequiresExpectBlock` error or something like that.

**Comment by JonRowe** [comment]
We actually issue a warning:
```
Failure/Error: expect(:a).to raise_error(StandardError)
       expected StandardError but was not given a block
```
but you won't see it if your code is already issuing an error due to the way Ruby evalautes code, `expect(raise StandardError)` will raise the error before `raise_error(StandardError)` is even evaluated.

**Comment by maikokuppe** [comment]
That makes sense.
