### ISSUE TITLE
Multiple asserts for a controller spec

### ISSUE THREAD

**Issue by BeRMaNyA** [rspec/rspec-rails#1789]
Let me explain the issue...

I was testing a Rails controller with RSpec and I have one scenario with about 8 asserts..

I don't like to have an "it" with that amount of asserts so what I did was this:

```ruby
RSpec.shared_examples 'successful payment' do |term_type, years|
  let(:surgeon_package) { assigns(:surgeon).reload.last_surgeon_package }
  let(:payment)         { surgeon_package.payments.first }

  before do
    put(:update_account, params)
  end

  it 'package term must be yearly' do
    expect(surgeon_package.payment_term.term).to eq(1)
    expect(surgeon_package.payment_term.term_type).to eq(term_type)
  end

  it 'package payments must be one' do
    expect(surgeon_package.payments.count).to eq(1)
  end

  it '...'
end
```

But as you can see I request the action :update_account on each it.

What do you think is the best way to solve this issue? since I don't want to request /update_account every time.

Global variables? $cache? get the code back to one "it" ? thoughts?

Thanks community

**Comment by JonRowe** [comment]
The accepted practise here (especially given controller specs are soft deprecated in Rails 5) is to treat this as a feature spec, and thus only have one "`it`" (you can use another alias e.g. `specify` or `scenario`), if you want to see the "triangulation" effect of not stopping at the first failure, you could use the `aggregate_failures` feature to run all the expectations and get a summarised report.

Also in future could you please use the mailing list, IRC or one of the many Ruby slack communities to ask this sort of question, we prefer Github issues remain for bug reports and feature requests, not community discussion.
