### ISSUE TITLE
The request.params object doesn't contain information about uploaded file

### ISSUE THREAD

**Issue by thongncvn** [rspec/rspec-rails#1791]
Hi, thanks for spending your time reading this.

I was trying to write a controller spec to check if the uploaded temp file is properly deleted:

```
it 'deletes the temp file' do
  post :create, file: fixture_file_upload("#{Rails.root}/spec/support/data/file.dat")

  # The "expect" part, I don't know what to write here...
end
```

The controller is similar to this:

```
class FilesController < ApplicationController
  def create
    if ProcessTheFile.new(params).execute
      redirect_to ok_path
    else
      redirect_to failed_path 
    end
  end
end
```

The problem is, when I try to inspect `params` from within the controller action, I can get the uploaded temp file with `params[:file].tempfile.path`. However, when I try to get that value from `controller.params` in the spec, `controller.params[:file].tempfile.path` just returns `nil`.

I doubt that this temp file is a fake one. I'm not sure. So I post my case here and hope to be helped. 
Is there another way I can get the right params that can be read from within the controller action? Please help me to know what to do.

Thank you very much and thanks for reading this. :grin:

**Comment by samphippen** [comment]
Thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by thongncvn** [comment]
Hi @samphippen, thanks for your suggestion. While setting up a project to reproduce the issue, I realized that in my code, the temp file has been unlinked before. That is the reason why the parameter changed.

This is my bad, sorry for asking question without thinking carefully.

Following is the project, in case someone might curiously want to know more about this case:
https://github.com/thongncvn/rspec-request-params-case

I still think that it would be cool if from within the spec, we can get the path of the temp file. But that is out of the scope.

Thank you very much, @samphippen!
