### ISSUE TITLE
Weirdness with ActiveModel attributes and expectations

### ISSUE THREAD

**Issue by typeoneerror** [rspec/rspec-rails#1793]
I'm using 3.4.2 so I'm unsure if this is a non-issue, but I'm encountering some weird results with expectations, specifically with ActiveModel attributes. I've written up my account on StackOverflow: http://stackoverflow.com/questions/42682762/how-can-a-ruby-method-not-repond-to-a-method-but-also-call-the-method

**Comment by JonRowe** [comment]
This is slightly counter intuitive but is working as expected, checking that the method is not called, causes the method to be defined by RSpec, which in turn causes the method to be called by your code. You could add an expectation on `respond_to?` to force it to return false, but I would recommend you instead don't assert the method is not called, but assert that no `NoMethodError` error is raised

**Comment by typeoneerror** [comment]
@JonRowe I like the assertion idea, I'll go with that. Appreciate your response even though I closed the issue. You rock.
