### ISSUE TITLE
issue deploying to heroku,   rake aborted! NoMethodError: undefined method `web_console' for #<Rails::Application::Configuration

### ISSUE THREAD

**Issue by Rollson** [rspec/rspec-rails#1794]
please can someone help me. i run into this error when trying to deploy to heroku

remote: sh: 2: Syntax error: Unterminated quoted string
remote: sh: 2: Syntax error: Unterminated quoted string
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     NoMethodError: undefined method `web_console' for #<Rails::Application::Configuration

/language_pack/helpers/rake_runner.rb:102:in `load_rake_tasks!': Could not detec
t rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
remote: ensure you can run `$ bundle exec rake -P` against your app
remote: and using the production group of your Gemfile.
remote: rake aborted!
remote: NoMethodError: undefined method `web_console' for #<Rails::Application::
Configuration

**Comment by samphippen** [comment]
Hi @Rollson, we typically don't use the issue tracker for help requests, only bugs. Would you mind filing your question on our mailing list here: https://groups.google.com/forum/#!forum/rspec

**Comment by Rollson** [comment]
okay, done that. thank you
