### ISSUE TITLE
Matcher inconsistencies

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-rails#1801]
A couple things I'm noticing:

- [x] `be_a_new(model_class)` checks `new_record?`, but is documented as checking `!persisted?`.  These should agree.
- [x] `be_new_record` checks `!persisted?`. It should probably use the same method that `be_a_new` uses. (`new_record?` makes sense to me).
- [ ] `be_a_new(model_class).with(some_attributes)` does not support composable matching by accepting matchers in the `some_attributes` hash.

**Comment by JonRowe** [comment]
#1803 doesn't fix the composable matcher issue

**Comment by myronmarston** [comment]
True. It fixed the part I care more about. Feel free to take a stab at the composable issue :).

**Comment by JonRowe** [comment]
Just wanted to make sure we kept track of the last part :)

**Comment by britnia** [comment]
Hey @myronmarston I'm trying to understand what you mean by 

> be_a_new(model_class).with(some_attributes) does not support composable matching by accepting matchers in the some_attributes hash.

I think you mean something like this but I want to make sure I'm on the same page with you before I start digging in all willy nilly.

`some_attributes = {:about => a_hash_including(:type = 'gerbil', :color => 'brown'), :characteristics => { :some => 'other', :non_matcher => 'stuff maybe'}`
`expect(object).to be_a_new(Animal).with(some_attributes)`

PS - Please be nice to me as I'm new to open source and I find you all terribly intimidating.

**Comment by myronmarston** [comment]
Hey @britnia -- that's definitely an example of what I'm talking about.  Basically, the `be_a_new` matcher allows you to specify record attributes but you can only specify exact values, whereas the [have_attributes](https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/built_in/have_attributes.rb) matcher allows you to specify an attribute value using a matcher, like your `about: a_hash_including` example.

> PS - Please be nice to me as I'm new to open source and I find you all terribly intimidating.

We don't bite, I promise :).  Is there something we can do to be more welcoming?

**Comment by britnia** [comment]
Thanks @myronmarston! That's very helpful. Thanks for being so welcoming! I'm going to try to figure out how to make it happen :)

**Comment by tf** [comment]
#1803 leads to a somewhat breaking change. Surprisingly ActiveRecord (tested with 4.2.6) reports destoyed records as neither `new_record?` nor `persisted?`. So before, it was possible to test that a record has been destroyed by:
```ruby
record.destroy
expect(record).to be_new_record # => used to pass
```
With the new implementation this has to be rewritten as:

```ruby
record.destroy
expect(record).not_to be_persisted
```

**Comment by tf** [comment]
Or, of course, `expect(record).to be_destroyed`. Somehow wasn't aware of `record.destroyed?` so far.

**Comment by myronmarston** [comment]
Thanks for reporting this, @tf!  We definitely didn't mean to break anything, so it's nice to hear about it.

In this case, the change feels more like a bug fix than a breaking change, to me at least (even if it was unintentional).  I don't think a destroyed record is a "new record" in any meaningful sense, so the fact that `expect(destroyed_record).to be_new_record` passed before feels like a bug, IMO.  After all, when the [old yankee stadium](https://en.wikipedia.org/wiki/Yankee_Stadium_(1923)) was destroyed a few years ago, I don't think anyone would say it became a new stadium--that's nonsensical.  It similarly feels nonsensical to say that a destroyed record should pass a `expect(record).to be_new_record` expectation.

**Comment by tf** [comment]
Yes, you are totally right. Thanks for the thoughtful response. I guess, my confusion was caused by the invalid assumption that `persisted?` was defined as `!new_record?`. I hope, I did not derail the conversation here too much.

**Comment by britnia** [comment]
I believe this issue can be closed now.
