### ISSUE TITLE
Controller specs: Cookies values are always converted to string

### ISSUE THREAD

**Issue by Erowlin** [rspec/rspec-rails#1812]
We're currently upgrading our application from Rails 4.2 to Rails 5.0, and I've noticed that there is a weird behaviour with the cookies: 

```ruby
subject {get :new, params: { token: 1 }}
let(:token) {user.referral_token}

it 'sets cookie' do
  subject
  expect(response.cookies['referrer_id']).to eq(referrer.id)
end
```
Rails 4, specs pass
Rails 5, specs fail:        `expected: 1, got: "1"`

When using a `binding.pry` in the controller, right after the cookie is set, the value is an integer, not a string: 

```ruby
     6: def new
     7:   @referrer = User.find_by(referral_token: params[:token])
     8:   if @referrer.present?
     9:     cookies.permanent[:referrer_id] = @referrer.id
    10:     binding.pry
 => 11:     redirect_to new_user_registration_path(show_referral_message: true)
    12:   else
    13:     redirect_to root_path
    14:   end
    15: end

[1] pry(#<ReferralsController>)> @referrer.id
=> 1
[2] pry(#<ReferralsController>)> cookies.permanent[:referrer_id]
=> 1
[3] pry(#<ReferralsController>)> cookies.permanent[:referrer_id].class
=> Integer
[4] pry(#<ReferralsController>)> @referrer.id.class
=> Integer
```

I'm not really sure on what to do here. Is the new behaviour to always have string in the specs? Because I cannot reproduce it in the controller. I didn't find any change in the Changelog also. 

Thank you!

**Comment by JonRowe** [comment]
> When using a binding.pry in the controller, right after the cookie is set, the value is an integer, not a string:

The value is probably a string in the response tho, remember your specs is on the outside of the stack.

**Comment by Erowlin** [comment]
Ah you're right JonRowe, thanks for the explanations. 

Then what changed between Rails 4 and Rails 5 ? I cannot find anything in the changelog. If you could point me to those changes, it would be helpful!

**Comment by JonRowe** [comment]
@Erowlin did you try the Rails change log? `rspec-rails` is a thin wrapper around the Rails test helpers and generally the content is "as is" from them

**Comment by Erowlin** [comment]
I didn't knew that, I will take a look at it. 👍  for pointing me on this.
