### ISSUE TITLE
Stubbing collection methods in Rails 5.0.3

### ISSUE THREAD

**Issue by erikse** [rspec/rspec-rails#1817]
Hi

I've noticed an issue with tests failing in rspec-rails 3.6.0 since upgrading a Rails 5.0.2 app to 5.0.3, released a few days ago.

The failing tests allow a subject's has_many collection to receive .build or .create and substitute the return value with a stub (such as cases where I want set expectations on the return value). Since upgrading Rails, it ignores the stub.

For example, running the code below in [5.0.3](https://github.com/erikse/has-many-expect): 

```ruby
class Episode < ApplicationRecord
  belongs_to :show
end

class Show < ApplicationRecord
  has_many :episodes
end

require 'rails_helper'

RSpec.describe Show, type: :model do

  describe '#episodes' do
    subject! { Show.create(name: 'The Simpsons') }

    it 'mock subject.association_name.build to return ok' do
      allow(subject.episodes).to receive(:build) { 'ok' }

      expect(subject.episodes.build).to eq 'ok'
    end
  end
end
```
results in:
```ruby
Failures:

  1) Show#episodes mock subject.association_name.build to return ok
     Failure/Error: expect(subject.episodes.build).to eq 'ok'
     
       expected: "ok"
            got: #<Episode id: nil, series: nil, number: nil, show_id: 1, created_at: nil, updated_at: nil>
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,8 @@
       -"ok"
       +#<Episode:0x007f9a69c863c8
       + id: nil,
       + series: nil,
       + number: nil,
       + show_id: 1,
       + created_at: nil,
       + updated_at: nil>
       
     # ./spec/models/show_spec.rb:11:in `block (3 levels) in <top (required)>'
```
But passes in [5.0.2](https://github.com/erikse/has-many-expect/commits/downgrade_to_rails_5_0_2).

To get these kinds of tests passing in 5.0.3, saving the association to a variable first, and setting the stub directly on the saved variable, allows the spec to pass:

```ruby
    it 'mocks association_name.build to return ok' do
      association = subject.episodes
      allow(association).to receive(:build) { 'ok' }

      expect(association.build).to eq 'ok'
    end
```

#### Config

```bash
$ rails -v
Rails 5.0.3

$ ruby -v
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin16]

$ rspec -v
RSpec 3.6
  - rspec-core 3.6.0
  - rspec-expectations 3.6.0
  - rspec-mocks 3.6.0
  - rspec-rails 3.6.0
  - rspec-support 3.6.0
```

#### Sample

Rails 5.0.3 [(failing)](https://github.com/erikse/has-many-expect)
Rails 5.0.2 [(passing)](https://github.com/erikse/has-many-expect/tree/downgrade_to_rails_5_0_2)
Rails 5.0.3 [(workaround)](https://github.com/erikse/has-many-expect/tree/save_association_to_mock)

**Comment by samphippen** [comment]
@erikse thanks for providing plenty of detail here. We should be able to fix this without any further info from you 👍

**Comment by erikse** [comment]
Thanks @samphippen, seems like some discussion about it has come up in a [Rails issue](https://github.com/rails/rails/pull/28246). Maybe with https://github.com/rails/rails/commit/5ab742db515e3fdf789edb87d25284ed5ad51aad#diff-674a3ea80616c218e9d7b16f175f7098, we'll no longer get back the same object, and we'll need to change tests like these going forwards?

**Comment by krzysiek1507** [comment]
Very ugly workaround:
```ruby
allow(subject).to receive(:episodes) { subject.episodes }
```

**Comment by aledustet** [comment]
Same error on my side what i did was to mock the message chain like:

```

allow(subject).to receive_message_chain(:episodes, :build) { 'ok' }

```
👍

**Comment by erikse** [comment]
Great, the change has been reverted in rails/rails@d6679affd845c746849f5d3c9e5615c81ed701a0, but seems like we have a few workarounds for now 🛠 🚧 👍

**Comment by maschwenk** [comment]
Appears there is a fix here https://github.com/rails/rails/pull/29098, but when I checked out `v5.1.1` and cherry picked the commit, my specs were still broken. Anyone here want to confirm the same?
https://github.com/maschwenk/rails/tree/5-1-stable-regression-ar-collection

**Comment by erikse** [comment]
@maschwenk - I haven't had a chance to try 5.1, but I'm guessing the suggestions for setting expectations on collections might also work?

Even though the change was reverted in Rails, I think going forward - it's probably safer not to assume the same collection will always be returned on subsequent invocations. Either way, this seems more like an issue in how rspec was used, rather than rspec itself, so closing.
