### ISSUE TITLE
How come the readme emphasizes development group in Gemfile?

### ISSUE THREAD

**Issue by runephilosof** [rspec/rspec-rails#1821]
In the Readme.md it is _emphasized_ that rspec-rails should be in _both_ test and development group.

But I have had no problems only having it in the test group. I can use the generators and rake commands without specifying `RAILS_ENV=test`.

Am I missing some functionality by just having it in the test group (Rails >= 3.2)?

**Comment by JonRowe** [comment]
At one point Rails used groups to load gems based on differing environments, hence this emphasis, it was to ensure the generators and commands were available, if your environment includes all the groups you don't need to do this but the emphasis should probably remain!
