### ISSUE TITLE
Shared examples from other file?

### ISSUE THREAD

**Issue by marcosanfilippo** [rspec/rspec-rails#1823]
Hi, there's a way to recall shared examples from other file?

I already have a shared example in each file, with `shared_example 'my scenario'` and after, I call `it_behaves_like 'my scenario'`.

All is ok. But now I want to import a `shared_example_spec.rb` file instead of replicate its content in each spec file.

Thank you.

**Comment by JonRowe** [comment]
`require 'path/to/shared_examples'` they will now be available in that spec file.

**Comment by marcosanfilippo** [comment]
It doen not work as I expect.

The shared block has the follow operation:

```
before(:all) do
    @full_user = FactoryGirl.create(:entity_user)
  end
```

But in the embedder file I can't find the global `@full_user`. Why? How can I solve it?

**Comment by JonRowe** [comment]
Shared examples define a context, things defined inside the context are only available inside the context thus:

```Ruby
RSpec.shared_examples_for "some scenario" do
  let(:my_value) { 2 }
end
RSpec.describe "something" do
  it_behaves_like "some scenario"
  it "also does this" do
    expect(my_value).to eq 2
  end
end
```

doesn't work, but:

``` Ruby
RSpec.shared_examples_for "some scenario" do
  let(:my_value) { 2 }
end
RSpec.describe "something" do
  it_behaves_like "some scenario" do
    it "also does this" do
      expect(my_value).to eq 2
    end
  end
end

```

does. Please read the [docs](https://relishapp.com/rspec/rspec-core/v/3-6/docs/example-groups/shared-examples) or use irc / mailing list / your local slack group for further discussion, github isn't the best place to seek support, as it just ties up our maintenance time.
