### ISSUE TITLE
View specs for shared partials infer request.path_parameters strangely in rails 4

### ISSUE THREAD

**Issue by tlubz** [rspec/rspec-rails#1828]
View specs seem to be inferring `controller.request.path_parameters` incorrectly for shared partials since rspec-rails v3.5.0.beta1.

we are on rails 4.1.14.1
rspec 3.6.0

repro instructions:

create a partial view under `app/views/shared/_example.html.haml` with e.g.

```haml
#{request.path}
```

create a spec for it under `spec/views/shared/_example.html.haml_spec.rb` with e.g.

```ruby
RSpec.describe 'shared/_example.html.haml' do
  it 'shouldnt act weird' do
    render('shared/example')
    expect(rendered).not_to eq('No route matches {:action=&gt;"index", :controller=&gt;"shared"}')
  end
end
```

seems like a bug that `request.path` evaluates to an error message. it should raise an exception or evaluate to an empty string.

if this doesnt seem like a bug, then it would at least be nice to know what the correct way to set request.path to a sane value would be from within rspec view examples.

**Comment by JonRowe** [comment]
Closing as this is for an unsupported version of Rails for the current `rspec-rails`  and we don't have the capability to fix older rails issues sorry.
