### ISSUE TITLE
the environment variable RAILS_ENV is overwritten to test

### ISSUE THREAD

**Issue by rod-eligible** [rspec/rspec-rails#1830]
In a big project where we have two different environments for testing, we set the environment variable **RAILS_ENV** to something different from **test**, yet whenever we run the specs, the environment variable is hardcoded by **rspec-rails** to **test**.

This may be a design decision on the library and I'll just let a monkey patch on my project, the overwrites happens [here](https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/tasks/rspec.rake#L23)

```
ENV['RACK_ENV'] = ENV['RAILS_ENV'] = 'test'
```

maybe it could be updated to something like...
```
ENV['RACK_ENV'] = ENV['RAILS_ENV'] = (ENV['RAILS_ENV'] || ENV['RACK_ENV'] || 'test')
```

so it will use **RAILS_ENV** if present, or **RACK_ENV** or finally **test** by default

**Comment by JonRowe** [comment]
This is deliberate because Rails doesn't support multiple test environments, so does weird things TM, I would suggest using another ENV variable to delineate between your test setups.
