### ISSUE TITLE
Update generator to avoid requiring the rails-controller-testing gem

### ISSUE THREAD

**Issue by brunofacca** [rspec/rspec-rails#1832]
Controller specs produced by the generator use `assigns` and `assert_template`, which were "deprecated" in Rails 5 (extracted to the [rails-controller-testing](https://github.com/rails/rails-controller-testing) gem).

The [RSpec 3.5 release notes](http://rspec.info/blog/2016/07/rspec-3-5-has-been-released/) say:

> For new Rails apps: we don't recommend adding the rails-controller-testing gem to your application. The official recommendation of the Rails team and the RSpec core team is to write request specs instead. Request specs allow you to focus on a single controller action, but unlike controller tests involve the router, the middleware stack, and both rack requests and responses. This adds realism to the test that you are writing, and helps avoid many of the issues that are common in controller specs. In Rails 5, request specs are significantly faster than either request or controller specs were in rails 4, thanks to the work by Eileen Uchitelle1 of the Rails Committer Team.

Maybe instead of generating controller specs, the generators could produce request specs.

**Comment by JonRowe** [comment]
We  now generate request specs by default.
