### ISSUE TITLE
Use `is_expected` for a custom matcher

### ISSUE THREAD

**Issue by dosuken123** [rspec/rspec-rails#1834]
Currently, I have the following test.

```
# sample_spec.rb file

let(:action) do
  proc do
    get :edit
  end
end

it { expect(action).to be_allowed_for(:admin) }
it { expect(action).to be_allowed_for(:user) }
it { expect(action).to be_allowed_for(:tester) }
...
```

```
# custom_matcher.rb

matcher :be_allowed_for do |role|
  match do |action|
    sign_in_as(role)
    action.call

    response.status == 200
  end
end
```

However, I'd like to use `is_expected`, if possible. So something like,
```
# dog_spec.rb file

subject { get :edit }

it { is_expected.to be_allowed_for(:admin) }
it { is_expected.to be_allowed_for(:user) }
it { is_expected.to be_allowed_for(:tester) }
...
```

But `match do |action|` will feed `ActionController::TestResponse` as action, which is a result of the subject.

How can I execute the subject's block in the `match do |action|`?

**Comment by samphippen** [comment]
@dosuken123 this issue isn't to do with `rspec-rails` but `rspec-core` would you mind re-filing it on https://github.com/rspec/rspec-core?
