### ISSUE TITLE
'includes' is being replaced by 'a hash including' in strings

### ISSUE THREAD

**Issue by RGillett** [rspec/rspec-rails#1835]
```
describe 'RulesController' do
  it 'always returns the list of general rules' do
    get "/partner_setup/rules/1/general_rules"
    rules = JSON.parse(response.body)

    expect(rules).to match(a_hash_including({
      'title' => 'Test',
      'description' => 'a link will not be included in the emails'
    }))

  end

end
```

Running the above test gives this error:

> expected [{"id"=>"1", "title"=>"Test", "description"=>"a link will not be included in the emails"}] to match (a hash including {"title" => "Test", "description" => "a link will not be a hash includingd in the emails"})
> Diff:
> @@ -1,2 +1,4 @@
> -(a hash including {"title" => "Test", "description" => "a link will not be a hash includingd in the emails"})
> +[{"id"=>"1",
> +  "title"=>"Test",
> +  "description"=>"a link will not be included in the emails"}]
>

**Comment by JonRowe** [comment]
Duplicate (and wrong repo for) rspec/rspec-expectations#1116
