### ISSUE TITLE
Show how to assert that a specific layout was rendered in the render_template docs

### ISSUE THREAD

**Issue by brunofacca** [rspec/rspec-rails#1836]
Given that `render_template` can be used to assert that a specific layout was rendered, as in `expect(response).to render_template('layouts/admin')`, I suggest we include this in [the docs](https://github.com/rspec/rspec-rails/blob/master/features/matchers/render_template_matcher.feature). May I submit a PR?

**Comment by xaviershay** [comment]
yes please!

**Comment by brunofacca** [comment]
@xaviershay, please check the PR and let me know if it requires any adjustments.

**Comment by knappe** [comment]
@brunofacca I ran into this today and would love to see this merged.  How can I help push this to the finish line?

**Comment by JonRowe** [comment]
@knappe For the attached documentation PR to work it needs to actually assert the correct layout, or render the correct layout.

**Comment by knappe** [comment]
Okay, I'll see if I can work on this later tonight then.

**Comment by JonRowe** [comment]
Closed as this was done in #2063
