### ISSUE TITLE
[DOCUMENTATION] How important is the semantic distinction between “spec” vs. “test”? (and other tidbits)

### ISSUE THREAD

**Issue by rlue** [rspec/rspec-rails#1840]
Re: the discussion I initiated in #1838, what is the RSpec team's position on distinguishing between ”specs“ and ”tests“? Not to be persnickety, but the README uses language that hints at a distinction:

> Use model specs to describe behavior of models...

> Use controller specs to describe behavior of Rails controllers...

> Use request specs to specify one or more request/response cycles...

In these cases, “specs” cannot be substituted with “tests” (tests **verify** behavior rather than **describing** it). 

Okay. So I know this is terribly persnickety. But as a novice, I can tell you that I'm already drinking from a firehose, and all this verbal gymnastics consumes precious cognitive overhead because before I can put all the pieces in place, I have to constantly guess at how much there is left to learn that I don't know about. 

> [INNER MONOLOGUE]: _Why is it telling me how to **describe** or **specify** things when I'm trying to figure out how to **test** stuff? Are there any intermediate steps between describing/specifying and testing?_

If the distinction is important, can we clarify in the introduction? If not, can we ditch the “describe/specify” phrasing and stick with “test”? I'm happy to submit a PR if any maintainers think it would be an improvement.

---

Also, can we address this phrasing?

> Use [x] to [do y]...

It makes it sound like [x] is a distinct thing in its own right (_e.g.,_ use a pair of scissors to cut paper — you _could_ use it to stir a pot of soup, but that's not a good idea), but that's not true of the various kinds of specs. You cannot use a model spec to do anything other than describing the behavior of models, because if you do, it ceases to be a model spec. My problem with this phrasing is that it left me wondering if there's something else that makes it so (_e.g.,_ a `ModelSpec` class?)

I'd like to propose something like the following instead:

> ### Intro
> 
> rspec-rails is a testing framework for Ruby on Rails. In this framework, “specs” are written in the [RSpec DSL](https://relishapp.com/rspec) to describe how the various components of your application (models, views, controllers, etc.) are expected to behave. Running `rspec` will test your application against these specs and generate a report of where it conforms to (or diverges from) them.
>
> ### Types of Specs
> 
> All specs belong to one of seven types, depending on which kind of applicaton component it describes:
> 
> * model specs
> * request specs
> * controller specs
> * feature specs
> * mailer specs
> * job specs
> * view specs
> 
> Each one has a corresponding folder in the project's `spec` directory (_e.g.,_ `spec/models`), where all specs of that type belong. If you keep any spec outside of its default location, its type must be specified within the file using the `type:` option, like so:
> 
>     # user_spec.rb
>     RSpec.describe User, type: :model do
> 
> ### Model Specs
> 
> A spec for a `User` model might look something like this:
> 
>     require "rails_helper"
> 
>     RSpec.describe User do
>       it "orders by last name" do
>         lindeman = User.create!(first_name: "Andy", last_name: "Lindeman")
>         chelimsky = User.create!(first_name: "David", last_name: "Chelimsky")
> 
>         expect(User.ordered_by_last_name).to eq([chelimsky, lindeman])
>       end
>     end
> 
> Note that the model class (`User`) is passed as an argument to `RSpec::describe`.
> 
> For more information, see [cucumber scenarios for model specs](https://www.relishapp.com/rspec/rspec-rails/docs/model-specs).

Thoughts?

**Comment by mikegee** [comment]
A good next step here would be to move your proposal into a pull request. That would make it simpler to compare it with the current content.

**Comment by JonRowe** [comment]
Specs are just RSpecs word for test, theres no real distinction in use and we only use the word test in the readme to specifically refer to Rails tests helpers, which call them tests. We will always welcome documentation PRs but would prefer as @mikegee an actual PR to discuss changes, closing as this is in itself inactionable, will happily review any PRs
