### ISSUE TITLE
`change` matcher with `(object, :message) syntax not seeing changes to ActiveRecord object

### ISSUE THREAD

**Issue by rlue** [rspec/rspec-rails#1850]
I am observing the following behavior: when expecting a code block to change an ActiveRecord object, 

```
expect { patch user_path(alice), params: { user: { confirmed: true } } }
  .to change ...
```

the `change` matcher only works with curly-brace (_i.e.,_ block) syntax, failing with `(object, :message)` syntax:

```
expect { patch user_path(alice), params: { user: { confirmed: true } } }
  .to change(alice, :confirmed?).from(false).to(true)  # this fails
  .to change { alice.confirmed? }.from(false).to(true) # this works fine
```

Specifically, the former case yields the following output:

```
Failure/Error:
  expect { patch user_path(alice), params: { user: { confirmed: true } } }.to change(alice, :confirmed?).from(false).to(true)

  expected #confirmed? to have changed from false to true, but did not change
```

I asked about this on StackOverflow, and [an answerer guessed](https://stackoverflow.com/questions/45274875/rspec-not-seeing-changes-to-activerecord-object-with-changeobject-message/45277100?noredirect=1#comment77517205_45277100) that this happens because the parenthesis syntax does not reload the ActiveRecord object after the `expect` block runs.

Is this correct? If so, is it deliberate? Is there any way around it, or is it simply advisable to stick to block syntax?

**Comment by pirj** [comment]
As I see from your question on SO, the scenario is a bit different:
```ruby
FactoryGirl.create(:commitment, user: carol,
                                  company: company,
                                  confirmed_by_admin: true)

expect { patch commitment_path(carol.commitments.first) }
  .to change { carol.commitments.first.confirmed?) }.from(false).to(true)
  and.to change(carol.commitments.first, :confirmed?).from(false).to(true)
```

The difference is that `carol.commitments.first` with `change` block syntax is evaluated both before and after `patch`, while with argument syntax it's evaluated once, and not reloaded.
E.g. if it happens that `patch` is loading its own instance of the record and operates on it, this won't be reflected on the record instance instantiated in the example, those will be two distinct objects, and state change of one won't be reflected on the other one.

I'd go with block syntax with request specs.

**Comment by rlue** [comment]
Thanks. I posted this question when I was first getting started with RSpec, and have since learned better.

Sorry for the trouble!

**Comment by pirj** [comment]
You are welcome!
