### ISSUE TITLE
Params Named '_' in Array Move Themselves

### ISSUE THREAD

**Issue by ksylvest** [rspec/rspec-rails#1851]
It appears that rspec (or perhaps rails) is doing something very strange with '_' keys in a hash ordering.

**app/controllers/demos_controller.rb**:

```ruby
class DemosController < ApplicationController
  def update
    raise params.inspect
  end
end
```

**spec/controllers/demos_controller_spec.rb**:

```ruby
require 'rails_helper'

RSpec.describe DemosController, type: :controller do
  describe 'PATCH #update' do
    it '...' do
      patch :update, params: {
        bulk: [
          { id: 'A' },
          { id: 'B', _destroy: true }
        ]
      }
    end
  end
end
```

**Result:**

```
RuntimeError: [<ActionController::Parameters {"id"=>"A", "_destroy"=>"true"} permitted: false>, <ActionController::Parameters {"id"=>"B"} permitted: false>]
```

(notice A gets the '_destroy' instead of B)

**Tested:**

rails: '5.1.2'
rspec-rails: '3.6.0'

The identical code test written in minitest:

```ruby
require 'test_helper'

class DemosControllerTest < ActionDispatch::IntegrationTest
  test 'updating' do
    patch demo_path, params: {
      bulk: [
        { id: 'A' },
        { id: 'B', _destroy: true }
      ]
    }
  end
end
```

```
RuntimeError: [<ActionController::Parameters {"id"=>"A"} permitted: false>, <ActionController::Parameters {"id"=>"B", "_destroy"=>"true"} permitted: false>]
```

(notice B correctly gets the '_destroy' instead of A)

sample project that has this issue: [demo.zip](https://github.com/rspec/rspec-rails/files/1171317/demo.zip)

**Comment by ksylvest** [comment]
sample project that has this issue: [demo.zip](https://github.com/rspec/rspec-rails/files/1171317/demo.zip)

**Comment by mikegee** [comment]
@ksylvest Rack has a hard time with deep structures of hashes and arrays like that. See https://github.com/rack/rack/pull/1058 for instance.

**Comment by JonRowe** [comment]
Closing as this is unlikely to be an `rspec-rails` issue, we pass them through to Rails / Capybara etc and don't modify them in anyway I can think of that would cause this.
