### ISSUE TITLE
Syntax difference between Rails 4/5 on get requests

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [rspec/rspec-rails#1862]
Hello, 

It took me a couple of hours to understand this.
When using `Rails 5` I need to use the following syntax for a `get request`:

`get :edit, params: {id: question}`

but when using `Rails 4`, if I use that request I receive a routing error. Probably the routing error should be substituted with a syntax error, like the one that I receive when using the below syntax in `Rails 5`. This is the correct syntax that I had to use:

`get :show, id: question`

Thanks a lot for the amazing gem 
Fabrizio Bertoglio

**Comment by JonRowe** [comment]
This behaviour is being surfaced from Rails, I suggest "suggesting" that to them :joy:
