### ISSUE TITLE
Rails 5.1 - body or format not supported. `unknown keywords: body, format`

### ISSUE THREAD

**Issue by Rio517** [rspec/rspec-rails#1866]
In rails 5.1, it is not possible to either post raw request bodies or to add a format to a post request. In 5.0, one could use positional arguments, but they are clearly deprecated. 

``` ruby
post '/v1/some_path', body: some_hash.to_json, format: :json
```

Resolving this would also resolve the similar issue: https://github.com/rspec/rspec-rails/issues/1852. This bug also invalidates @JonRowe's recommendation [here](https://github.com/rspec/rspec-rails/issues/1650#issuecomment-230097893).

Please let me know if there is a new approach that I'm overlooking.

**Comment by JonRowe** [comment]
I haven't looked into this in detail so I can't provide an updated recommendation, but you need to match what Rails tells you to do, annoyingly thats not easily searchable for, so it may not even be possible anymore. RSpec doesn't override this behaviour so it's really down to Rails here...

**Comment by Rio517** [comment]
Ah I didn't realize. I assumed the `post` method in this case was a rspec thing and rspec was prepareing the request before handing off to rails. I guess I have to dig into the source and see what I can find. thanks for the pointer.  I'll close this and the related ticket then.

**Comment by adonaldson** [comment]
In case anyone else stumbles across this, I had good fortune with the rspec docs here:

https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec#providing-json-data

Instead of using the `body` keyword, pass your JSON string into `params` (ensuring that your headers correctly identify the content type).

**Comment by acflint** [comment]
If anyone else stumbles across this, as of Rails 5.1 you can set the format using `as:`. For example: `post '/v1/some_path', params: {}, as: :json`
