### ISSUE TITLE
Undefined method `before_filter' for ActionController::Base:Class

### ISSUE THREAD

**Issue by igkyab** [rspec/rspec-rails#1873]
Hi,
I've install `rspec-rails 3.6.1` in a new `Rails 5.1.3` `api` project today.
After execute `bundle install` and `rails g rspec:install`, i execute `bundle exec rspec spec/models` and i have this error : 

> An error occurred while loading ./spec/models/person_spec.rb.
> Failure/Error: require 'rspec/rails'
> 
> NoMethodError:
>   undefined method `before_filter' for ActionController::Base:Class
>
>   Did you mean?  before_action
>  ./spec/rails_helper.rb:7:in `<top (required)>'
>  ./spec/models/person_spec.rb:1:in `require'
>  ./spec/models/person_spec.rb:1:in `<top (required)>'
> No examples found. 

What should i do to resolve this error ? I have not changed  anything on the spec_helper.rb and rails_helper.rb configurations.

Thanks in advance for any help.

**Comment by JonRowe** [comment]
Remove any `before_filter`s from your controllers and replace with `before_action`?

**Comment by igkyab** [comment]
Yes this is my first idea too. But i don't have any `before_filter` in my controllers.

**Comment by JonRowe** [comment]
This error isn't coming from RSpec, but from Rails, either your code has one somewhere, or you're using a gem that does.

**Comment by igkyab** [comment]
Ok, i will do a tour of the gems i use.

Thank you very much!

**Comment by igkyab** [comment]
Problem resolved!

The problem come from the [https://github.com/tbpro/mongoid_userstamp project.](url)

They corrected the problem but did not make a new release of the gem...

Thank you very much for you help @JonRowe
