### ISSUE TITLE
Generator Path

### ISSUE THREAD

**Issue by sunnyrjuneja** [rspec/rspec-rails#1877]
Hi friends at RSpec,

First of all, thank you so much for your hard work. I'm an avid fan and I just picked up the new book.

I wanted to bring to your attention something that been bothering me over the last few days. When I type

```
$ bin/rspec g rspec:feature folder/resource
```

The path of the generated file is

```
#{Rails.root}/spec/features/folder/folder_resource_spec.rb
```

Perhaps I'm not thinking clearly about this but I think I want

```
#{Rails.root}/spec/features/folder/resource_spec.rb
```

I would love to hear your feedback. If you find my proposal to be in agreeance, I would be happy to contribute a PR. If not, I totally understand.

**Comment by JonRowe** [comment]
That does seem like a bug, whats the normal Rails behaviour?

**Comment by sunnyrjuneja** [comment]
Hey Jon,

The normal rails behavior is as following:

```
λ →  bin/rails g model foo/bar
Running via Spring preloader in process 35016
      invoke  active_record
      create    db/migrate/20170929204826_create_foo_bars.rb
      create    app/models/foo/bar.rb
      create    app/models/foo.rb
      invoke    rspec
      create      spec/models/foo/bar_spec.rb
      invoke      factory_girl
      create        spec/factories/foo_bars.rb
```

**Comment by JonRowe** [comment]
Ok! Happy to help review a PR :)
