### ISSUE TITLE
Devise in Rspec API Doc with Rails 5.0 and RSpec 3.6

### ISSUE THREAD

**Issue by 3DEsprit** [rspec/rspec-rails#1878]
The issue is that the Devise helpers are unable to access the **request object** which is needed for Devise's ControllerHelper login. 

I'm calling the login_with method within my before block, and loading the same rails_helper I use with my rspec environment which allows me to access this variable and login with Devise:

```
before(:each) do
    login_with current_user
    header 'Accept', 'text/html'
    header 'Content-Type', 'text/html'
  end
```

**I can access the helper module and call the method, but it always gives an error of not being able to access 'env of nil:NilClass' when using @request, and ' undefined local variable or method `request' ' when using the variable**. 

I have also tried to access request from the helpers, and controller objects, but to no avail. I did try the older solution found in #272 , and after some changes it also had the same issue. Has anyone been able to get this working? Do I need to do something different with my tests to get a accessible request?

**Comment by JonRowe** [comment]
Sounds like Devises test helper is monkey patching Rails and this is broken in Rails 5, try raising an issue with them.

**Comment by 3DEsprit** [comment]
My apologies, that previous issue threw me off to the wrong repo. Thanks!
