### ISSUE TITLE
[DOCUMENTATION] Not clear on one of the cucumber features

### ISSUE THREAD

**Issue by rlue** [rspec/rspec-rails#1881]
There are two scenarios at the end of the “Controller specs > Views are stubbed by default” feature ([controller_specs/isolation_from_views.feature](https://github.com/rspec/rspec-rails/blob/master/features/controller_specs/isolation_from_views.feature)) that I'm having difficulty understanding the purpose of (copied below).

What are these features intended to illustrate? Is the assumption that there is a file at `app/views/custom_action.html.erb`, which is blank in the first scenario and contains the text 'template for a custom action' in the second? Unless I missed something, it doesn't look like these details are specified anywhere on that docs page.

And why does the example in the first scenario use both `controller.prepend_view_path` and `controller.append_view_path` with the same argument, and why is only the former used in the second scenario?

Any insight would be deeply appreciated.

> ### expect empty templates to render when view path is changed at runtime (passes)
> 
> * **Given** a file named "spec/controllers/things_controller_spec.rb" with:
> 
>   ```ruby
>   require "rails_helper"
>   
>   RSpec.describe ThingsController, :type => :controller do
>     describe "custom_action" do
>       it "renders an empty custom_action template" do
>         controller.prepend_view_path 'app/views'
>         controller.append_view_path 'app/views'
>         get :custom_action
>         expect(response).to render_template("custom_action")
>         expect(response.body).to eq ""
>       end
>     end
>   end
>   ```
>   
> * **When** I run `rspec spec` 
>
> * **Then** the examples should all pass 
> 
> ### expect template to render the real template with render_views when view path is changed at runtime
> 
> * **Given** a file named "spec/controllers/things_controller_spec.rb" with:
> 
>   ```ruby
>   require "rails_helper"
>   
>   RSpec.describe ThingsController, :type => :controller do
>     render_views
>   
>     it "renders the real custom_action template" do
>       controller.prepend_view_path 'app/views'
>       get :custom_action
>       expect(response).to render_template("custom_action")
>       expect(response.body).to match(/template for a custom action/)
>     end
>   end
>   ```
> 
> * **When** I run `rspec spec `
>
> * **Then** the examples should all pass

**Comment by JonRowe** [comment]
These scenarios are testing edge cases within the view rendering code, specifically "rendering when the view path is changed at runtime" and the knock on effects of that; They're not great documentation and could be moved to the smoke / unit tests but until they're replaced I guess they stay put! If you'd like to take a stab at moving them to a more appropriate form of test I'd be happy to help review it in a PR.

**Comment by rlue** [comment]
Thanks for the quick reply, @JonRowe! Given [the page's placement](https://relishapp.com/rspec/rspec-rails/v/3-6/docs/controller-specs/views-are-stubbed-by-default) in the organization of the docs, my understanding was that the goal of this particular page was to illustrate features of the Controller spec facility. 

It seems to me that these two scenarios might make more sense on the [Render_views page](https://relishapp.com/rspec/rspec-rails/v/3-6/docs/controller-specs/render-views), rather than the one that they're on? (In fact, I didn't even notice the call to `render_views` in the second scenario until just now.)

**Comment by JonRowe** [comment]
@rlue that entire file is testing view isolation, its not really docs

**Comment by rlue** [comment]
Oh. I was under the impression that the extensive use of Cucumber scenarios throughout the RSpec docs was to illustrate and reinforce the principle that well-written tests double as documentation.

But even if that's not the case — if it's not really docs, then why is it included in the docs?

**Comment by JonRowe** [comment]
Cucumber is both documentation, and tests, these fall into the later. This documents a minor point, and then tests a couple of edge cases. The reason why they are here is *likely* (I don't know for sure) to test a bug fix, and its easier to write a scenario than an extensive unit test. These days we ask contributors to write unit tests and point them in the right direction, however we lack the resources to go back and fix those we deem that could be moved, like I said if you'd like to make an attempt I'll happily help by reviewing the PR. Deleting them without replacement isn't acceptable to us however!

**Comment by rlue** [comment]
Thanks for the explanation. I'll see if I can get a better understanding of how the tests are structured and the role that they play outside of documentation before trying my hand at a PR.
