### ISSUE TITLE
[Question] Skip ActionDispatch::SystemTest integration possible?

### ISSUE THREAD

**Issue by thenoseman** [rspec/rspec-rails#1895]
Hi,
I was wondering if it is currently possible to _skip_ the `ActionDispatch::SystemTest` integration when using Rails 5.1?

Usecase:
Our integrationtests require the server (puma/passenger) to run as a separate process.
The workflow while developing would be to start `bin/rails server` in one terminal tab and run a integration spec in the other.

When I activate rspec-rails 3.7.1 this doesn't work anymore since the ActionDispatch::SystemTest integration start the server itself.

As I understand the Integration is activated when requiring `example.rb` (https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/example.rb#L11) and thus requiring `'rspec/rails/example/system_example_group'`.

Is it possible to skip that to make the old way (two processes) work again?

Thanks!

**Comment by JonRowe** [comment]
Ironically someone had the inverse issue recently, they'd already turned off the inbuilt server and were having process configuration issues. I believe if you set `Capybara.run_server = false` you'll restore the behaviour you want. See #1813
