### ISSUE TITLE
Doc error: assert_template has been extracted to a gem

### ISSUE THREAD

**Issue by lsarni** [rspec/rspec-rails#1896]
I have used Controller Specs before but as it is recommended in the README I switched to Request Specs.
I'm using the examples [here](https://relishapp.com/rspec/rspec-rails/v/3-6/docs/request-specs/request-spec) in the doc.

This test:
```
  it 'creates a shipment' do
      get new_shipment_path
      expect(response).to render_template(:new)
    end
```

Causes this error:
```
Failure/Error: expect(response).to render_template(:new)

     NoMethodError:
       assert_template has been extracted to a gem. To continue using it,
               add `gem 'rails-controller-testing'` to your Gemfile.
```
Should I add that gem or are the examples outdated?

Version: rspec-rails (3.6.1), rails 5.1.4

**Comment by JonRowe** [comment]
As it mentions, you should add the gem. The examples will then work as is.
