### ISSUE TITLE
Don't use block quotes or double quotes in auto-generated spec_helper.rb and rails_helper.rb (make rubocop happy)

### ISSUE THREAD

**Issue by experimatt** [rspec/rspec-rails#1898]
After adding the `gem 'rspec-rails'` to my Gemfile and running `rails generate rspec:install`, rubocop complained about the following:

```
== spec/spec_helper.rb ==
C: 52:  1: Do not use block comments.
== spec/rails_helper.rb ==
C:  6:  7: Prefer single-quoted strings when you don't need string interpolation or special symbols.
```

**Comment by JonRowe** [comment]
The generated files are intended to be edited by you, the block comments can be deleted or uncommented as per your preferences and we actually prefer quote consistency in our own code base so you can either update your rubocop to match or edit the file to your preference ;)

**Comment by experimatt** [comment]
Would you consider the use of double quotes here consistent within the code base?

https://github.com/rspec/rspec-rails/blob/2bd9cd7d2be614f813e6b37f35c085d1c0226143/lib/generators/rspec/install/templates/spec/rails_helper.rb#L6
