### ISSUE TITLE
Bad error message for not having Puma installed.

### ISSUE THREAD

**Issue by kulte** [rspec/rspec-rails#1900]
If I don't have Puma installed, it won't load the SystemTestExample (I know I spelled that class wrong, but hopefully you catch my drift, sorry for being too lazy to look it up 😄), and thus there will be undefined method `driven_by`. That's inferior to a failure which states that you must have puma in your Gemfile, I would think. 

Thanks for your work on SystemSpecs though! 🙏

**Comment by JonRowe** [comment]
We've already taken steps to improve this, just unreleased sorry!
