### ISSUE TITLE
render_views is an undefined method for the config in version 3.7.0

### ISSUE THREAD

**Issue by PCGeekBrain** [rspec/rspec-rails#1918]
Good evening, I was trying to migrate to jbuilder to clean up my projects rendering functions and came across this issue. It seems that the tests crash when I attempt to set or call `render_views`.

For example, here is the configuration I am trying:
```
RSpec.configure do |config|

  # https://github.com/rails/jbuilder/issues/32
  config.render_views
  ...
```
Whenever I run my test suite with this configuration I get the following error: 
```
spec/spec_helper.rb:19:in `block in <top (required)>': undefined method `render_views' for #<RSpec::Core::Configuration:0x005632b4cee1d0> (NoMethodError)
```

What is interesting that it still works in the single test environment. For example:
```
RSpec.describe CallsController, type: :controller do
  render_views
  ...
```

Any idea why this function might not be working in the global context?

**Comment by joeltaylor** [comment]
@PCGeekBrain AS of RSpec 3.X, you should have two helper files: `spec_helper.rb` and `rails_helper.rb`. The `spec_helper` is intended to be lightweight and doesn't include the `rspec/rails` gem, which gives you that global config. Relocating `config.render_views` to your `rails_helper` should do the trick.

**Comment by PCGeekBrain** [comment]
Thanks it worked!
