### ISSUE TITLE
render_template with partial option requiring filename extension?

### ISSUE THREAD

**Issue by justin-capalbo** [rspec/rspec-rails#1923]
Here is the [gist](https://gist.github.com/justin-capalbo/f50ce288ed3302963d26dde907165c98).

I am working on a site with the following [bug branch](https://github.com/justin-capalbo/powerful-ally/tree/guild-flow).  I'm brand new to RSpec and liking it so far.  I'm just trying to understand why this test is failing.  Every example I've found of "expect response to render template" with partial option specifies just the name of the partial with the leading underscore.  However, I'm getting failed tests with the above code.

In the error detail, it looks like the array is actually holding the value of the partial **with** the filename extension, which is how I thought to simply add the extension, which did fix it.  Contrary to the "if it ain't broke", or "if it hurts, don't do that" mantras, I'm looking to actually understand why I'm wrong here.  Can anyone shed some light?  On the off chance that this is a bug... I'm happy to have discovered it, but I doubt that's the case.

I also have the shoulda_matchers gem installed if that matters.  I thought it was part of native Rspec though.  If this is in the wrong place, I'll gladly move it.

**Comment by JonRowe** [comment]
As I tried to explain on rspec/rspec-dev#192 this matcher delegates to Rails own `assert_template`. The options accepted by it and used by it are subject to Rails conditions. Please see their documentation.
