### ISSUE TITLE
Controller tests still use deprecated Rails 4 test helpers in Rails 5

### ISSUE THREAD

**Issue by Widdershin** [rspec/rspec-rails#1926]
Hello,

I have encountered an issue that I believe is a bug. In short, in a controller test in Rails 5, the `get` and `post` helpers are included from the deprecated `ActionController::TestCase::Behavior` when they should be included from the modern `ActionDispatch::Integration::Behaviour`.

Steps to reproduce:

* Create a new Rails project, without TestUnit. In my repro, I used `v5.1.4`.
* Add `gem 'rspec-rails', '~> 3.7.2'` to dev/test group in Gemfile
* `bundle install`
* Install with `rails g rspec:install`
* Create a controller + spec using `rails g controller books`
* In `spec/controllers/book_spec.rb`, add the following test:

```ruby
  it "works" do
    puts method(:get)
  end
```
 
* Run with `rspec spec/controllers/books_controller_spec.rb`

Expected result:

`rspec` should print `#<Method: RSpec::ExampleGroups::BooksController(ActionDispatch::Integration::Runner)#get>`

Actual result:

`rspec` prints `#<Method: RSpec::ExampleGroups::BooksController(ActionController::TestCase::Behavior)#get>`

This is a problem because the documentation for Rails 5 tells users to switch from `get :index` to `get book_index_path`. This means that users encounter a cryptic error from Rails stating that the route cannot be resolved.

Searching the codebase for `ActionDispatch::IntegrationTest::Behavior` shows two places where `rspec-rails` includes this module.

I was able to fix this issue by including this module in `ControllerExampleGroup`, like so:

`lib/rspec/rails/example/controller_example_group.rb`
```diff
 module ControllerExampleGroup
   extend ActiveSupport::Concern
   include RSpec::Rails::RailsExampleGroup
   include ActionController::TestCase::Behavior
   include RSpec::Rails::ViewRendering
   include RSpec::Rails::Matchers::RedirectTo
   include RSpec::Rails::Matchers::RenderTemplate
   include RSpec::Rails::Matchers::RoutingMatchers
   include ControllerAssertionDelegator
 
+  if ActionPack::VERSION::MAJOR >= 5
+    include ActionDispatch::IntegrationTest::Behavior
+  end
+
   # Class-level DSL for controller specs.
```

I have not created a pull request as I do not have the time to understand the surrounding context and ensure that this is the appropriate solution.

I hope this is enough information to go on. Happy to answer any questions.

Cheers 😄
Nick

**Comment by JonRowe** [comment]
Controller tests are deprecated full stop in Rails 5, you need to add the `rails-controller-tests` gem to use them. You can use the Rails 5 `ActionDispatch::IntegreationTest::Behaviour` via using system tests (`type: :system`)

**Comment by JonRowe** [comment]
Its not a deliberate behaviour, it could be improved to be conditional dependent on the presence of gem I guess

**Comment by swrobel** [comment]
FYI, @JonRowe I believe you stated incorrectly that System specs are equivalent to integration tests. The docs for [Request specs](https://relishapp.com/rspec/rspec-rails/v/3-7/docs/request-specs/request-spec) indicate that they use Rails integration tests under the hood. [System specs](https://relishapp.com/rspec/rspec-rails/v/3-7/docs/system-specs/system-spec) are actually a wrapper around the new [Rails 5.1 System Test feature](http://guides.rubyonrails.org/5_1_release_notes.html#system-tests).

**Comment by JonRowe** [comment]
@swrobel Rails 5.1 system tests are a form of integration test, as such they use the module called `ActionDispatch::IntegrationTest::Behaviour` under the hood. This is what I was referring to. They are the "new" way of doing what the OP was attempted to test.

**Comment by swrobel** [comment]
So much different terminology for the same things. Pardon my confusion ¯\_(ツ)_/¯
