### ISSUE TITLE
Tests run in individual test, but not within the whole suite

### ISSUE THREAD

**Issue by benjii** [rspec/rspec-rails#1931]
Hi everyone,

I have a funny problem with rspec... as my title says, I have tests that will pass when run individually, but not when run within the entire test suite.

So this:

`rspec ./spec/api/api_v2/deposits_spec.rb`

gives this as output:

````
Finished in 2.6 seconds (files took 4.32 seconds to load)
10 examples, 0 failures
````

Whereas this:

`rspec`

gives the following output:

````
rspec ./spec/api/api_v2/deposits_spec.rb:19 # APIv2::Deposits GET /api/v2/deposits should require deposits authentication
rspec ./spec/api/api_v2/deposits_spec.rb:24 # APIv2::Deposits GET /api/v2/deposits login deposits
rspec ./spec/api/api_v2/deposits_spec.rb:29 # APIv2::Deposits GET /api/v2/deposits deposits num
rspec ./spec/api/api_v2/deposits_spec.rb:34 # APIv2::Deposits GET /api/v2/deposits should return limited deposits
rspec ./spec/api/api_v2/deposits_spec.rb:39 # APIv2::Deposits GET /api/v2/deposits should filter deposits by state
rspec ./spec/api/api_v2/deposits_spec.rb:51 # APIv2::Deposits GET /api/v2/deposits deposits currency cny
rspec ./spec/api/api_v2/deposits_spec.rb:58 # APIv2::Deposits GET /api/v2/deposits should return 404 if txid not exist
rspec ./spec/api/api_v2/deposits_spec.rb:63 # APIv2::Deposits GET /api/v2/deposits should return 404 if txid not belongs_to you 
rspec ./spec/api/api_v2/deposits_spec.rb:68 # APIv2::Deposits GET /api/v2/deposits should ok txid if exist
rspec ./spec/api/api_v2/deposits_spec.rb:75 # APIv2::Deposits GET /api/v2/deposits should return deposit no time limit 
````

with specific failures telling me that it can't find routes:

````
  1) APIv2::Deposits GET /api/v2/deposits should require deposits authentication
     Failure/Error: get '/api/v2/deposits', :params => { token: token }
     
     ActionController::RoutingError:
       No route matches [GET] "/api/v2/deposits"
     # ./spec/api/api_v2/deposits_spec.rb:20:in `block (3 levels) in <top (required)>'
````

So I guess my question is... how come rspec can find routes when running in the first mode, but not the second?

Have I missed some configuration perhaps?

Thanks in advance,
Ben

**Comment by JonRowe** [comment]
There is something in your environment or other spec files interfering at some point, try using `rspec --bisect` to find the minimal failure combination that is causing this.

**Comment by samphippen** [comment]
This is likely not an RSpec bug, but rather a user spec ordering issue. @benjii if you confirm this is *not* an issue in your app, please re-open.

**Comment by jamieorc** [comment]
Oh, man. `rspec --bisect ...` to the rescue!

**Comment by jamieorc** [comment]
`rspec --bisect` narrowed down the problem, but it still took me an hour and half to figure out how to fix it. Difference between RapidScreen models and settings and non-RapidScreen apps.
