### ISSUE TITLE
Request Spec not Enqueuing Delayed Job

### ISSUE THREAD

**Issue by musiaht** [rspec/rspec-rails#1948]
Hi All,

I am having some trouble with Request Spec and Delayed Job. Currently I have an endpoint that is supposed to enqueue a job; but when triggering this through Request Spec, the job doesn't seem to be enqueued. When I try a similar test using a Controller Spec, the job is enqueued.

For example in my controller, I am enqueuing a job on a POST like follows...

```ruby
module V1
  class MyController < ApplicationController
    def create
      MyJob.perform_later(params[:name])
    end
  end
end
```

On a Controller Spec, this passes; I simply check to see if the job queue increments to 1.

```ruby
require 'rails_helper'

RSpec.describe V1::MyController, type: :controller do
  let(:valid_post) { {name: 'asdf'} }
  let(:valid_session) { {} }

  describe 'POST #create' do
    it 'enqueues a job' do
      post :create, params: valid_attributes, session: valid_session
      expect(Delayed::Job.count).to eq(1)
    end
  end
end

```

But on Request spec, the job count is 0 and seemingly, the job is not enqueued

```ruby
require 'rails_helper'

RSpec.describe '/my-endpoint', type: :request do
  let(:valid_post) { {name: 'asdf'} }

  describe 'POST #create' do
    it 'enqueues a job' do
      post '/my-endpoint', params: valid_attributes
      expect(Delayed::Job.count).to eq(1)
    end
  end
end
```

Is there any setting that would cause a difference in between Controller and Request Specs?

Thanks for your help.

**Comment by JonRowe** [comment]
If you're request specs are using a threaded server is possible your delayed jobs are not in the same thread...

**Comment by musiaht** [comment]
Hi @JonRowe,

Thanks for the tip! The intent of the test was to check to the database to see if the job had been enqueued on the "delayed_jobs" table; to my best understanding, Delayed::Job.count was only supposed to query the database. There shouldn't have been any need to inspect of the job on the job runner or worker. Again, this should have been only database related and no jobs were actually performed.

I did do some googling around on threading and I did find something remotely similar to the problem I am experiencing; https://github.com/thoughtbot/capybara-webkit/issues/569. I am finding that if I were to run the spec independently, the tests would pass as expected; but when executing the whole suite, I would get the failure with not jobs on the table. I'll have to sort out to see what some of the other tests are doing; how they might be rolling back the database as per that issue I found.

In any case, thanks again for your help.

**Comment by jaynetics** [comment]
there is an age-old rails bug that makes request specs use a different test adapter than the configured one. 

https://github.com/rails/rails/issues/37270

it is only now being fixed. the thread contains workarounds, too. it was probably not the root cause for the situation described above, but it has the same effect, and maybe someone stumbles upon this while googling like me.
