### ISSUE TITLE
Request test with devise_token_auth

### ISSUE THREAD

**Issue by zerobatu** [rspec/rspec-rails#1952]
Hi, I have a project in API Rails and I'm trying to test the requests

It's a simple test but the controller have authentication and a can't sign in or add a token in the headers
```Ruby
describe "GET /offices" do
  it "authentication test" do
    headers = FactoryBot.create(:executive).create_new_auth_token
    get offices_path
    expect(response).to have_http_status(200)
  end
end
```
In the controllers test I added this and works

```Ruby
before(:each) do
  request.headers.merge!  FactoryBot.create(:executive).create_new_auth_token
end
```

I read this rspec documentation but doesn't works
https://relishapp.com/rspec/rspec-rails/v/3-7/docs/request-specs/request-spec

I'm using 
rails 5.1.4
rspec 3.7
devise_token_auth 0.1.42

**Comment by JonRowe** [comment]
`headers = FactoryBot.create(:executive).create_new_auth_token` just assigns a local variable called `headers`. Hence why `request.headers.merge!` works.
