### ISSUE TITLE
request from the specific controller's spec to another controller

### ISSUE THREAD

**Issue by majioa** [rspec/rspec-rails#1954]
I have a spec to test the controller data. I use `json` request to get CSRF token and then access to method on another controller:

    RSpec.describe Api::V1::Lp::PhonesController, type: :controller do

currently I can't get CSRF as follows:

    post :auth, params: auth_attributes

since the access is going to the absent route, therefore it is present for another controller only. So is there a way to make a post request from the specific controller's spec to another controller? Or get te CSRF token with any other way inside the controller spec space?

**Comment by JonRowe** [comment]
You either need a full integration test for this, or you can generate a token in the spec and pass it in that way.
