### ISSUE TITLE
undefined private method  'fixture_path'

### ISSUE THREAD

**Issue by sithara** [rspec/rspec-rails#1956]
Hi
 
We recently had a ruby upgrade from 1.9 to 2.3.5 and rails to 3.2.22.Since then when we try executing `bundle exec rspec` we get the following error(Rspec version:  2.12.1)

private method `fixture_path' called for #<RSpec::Core::Configuration:0x00005600b187ec38> (NoMethodError)
Did you mean?  fixture_path=

It points to the describe statement:
	vendor/bundle/ruby/2.3.0/gems/rspec-core-2.12.1/lib/rspec/core/example_group.rb:230:in `describe'
	vendor/bundle/ruby/2.3.0/gems/rspec-core-2.12.1/lib/rspec/core/dsl.rb:18:in `describe
I tried commenting off all fixture thingys from spec_helper.rb but still getting the same error.

Request your help in fixing the same 

Thanks much
Sithara

**Comment by JonRowe** [comment]
Please update RSpec to a supported version, `2.12` is very old and likely doesn't support Rails `3.2`, you can upgraded to `2.99` which will provide you with a stable upgrade path to `3.x`, after that please use `~> 3.7`.

**Comment by sithara** [comment]
Thanks much @JonRowe  for the great support 👍

**Comment by mustmodify** [comment]
I gotta say, this is another example of the one thing I dislike about the Ruby community. Instead of helping people, you say "Upgrade now!". If you are new to this community, that might be easy OR it might be really painful. Other options include:

* "Oh I see they someone else changed something, we should issue a point release" or just "here's a quick fix but you might consider upgrading for these reasons."

**Comment by benoittgt** [comment]
Hello @mustmodify 

Here you can have a fast an easy way to resolve your issue by simply upgrading the gem. That's a gift! 🎁 

Also as mention, this is an old version. Maintaining open source project take time, here the issue get resolve after one day for free. 
Feel free to answer to the point you provide.

Bye

**Comment by JonRowe** [comment]
@mustmodify I'm afraid we don't have the resources (as volunteers) to back port support for newer versions of rails to older versions of RSpec. The OP upgraded their Rails without RSpec, and it was a simple fix to upgrade RSpec to a version that supports their version of Rails. We fully support semver and made our last major upgrade process as simple as it could be (including a full transitional release that helped with anything that was a breaking change, and with the aid of another project an automatic conversion tool). So in our case "upgrade" *is* the easy fix. For reference RSpec 3 was released 4 years ago, and every version since since is a fully backwards compatible "point release"

**Comment by mustmodify** [comment]
I use rspec by default in my projects. I have a great deal of respect for it and I appreciate the time you have spent on it. 

That there is tremendous value in our community and its behaviors should not prevent us from considering how we might grow further. I feel like one area for growth is in our tendency to prioritize new versions, often explicitly deprioritizing maintenance. That seems unhealthy to me.

**Comment by JonRowe** [comment]
You are picking the wrong project to make your point, the RSpec policy is not one that prioritises new versions over maintenance. In fact we prioritise maintenance over new features heavily.

We follow semver, bug fixes are released under patch releases as we find and fix them. Often we get new features contributed which forces us to release minor versions to be semver compliant, these releases will often contain bugfixes as well, and are entirely backward compatible, making them as seamless as a patch release to upgrade.

Obviously we cannot re-release versions with fixes in them, so an update to at least a patch version will always be required. We recommend that people pick their RSpec version based off `~> major.minor` and ignore patch level, that way a `bundle update` or similar will always pick the current version of RSpec regardless of minor or patch level increases.

We could back-port fixes to older minor versions, and in some cases major versions, but that is an extremely large overhead we just do not have the time to do. So this is not about deprioritising maintenance at all, but actually about prioritising the health of RSpec as a whole.

**Comment by arosalesheiskell** [comment]
Hi there, I'm having a similar issue with the `fixture_path` method.

I'm currently on rspec-rails 2.8.1 and trying to upgrade to 2.99 and doing so gets me the error message "Could not find gem 'rspec-rails (~> 2.99)' in any of the gem sources listed in your Gemfile." when i try to run `bundle install`.

**Comment by pirj** [comment]
@arosalesheiskell Not sure if it is somehow related. Here it is https://rubygems.org/gems/rspec-rails/versions/2.99.0
You may as well point to Github directly if your version of Bundler allows for that:
```ruby
gem 'rspec-rails', github: `https://github.com/rspec/rspec-rails.git`, tag: 'v2.99.0'
# or
gem 'rspec-rails', github: `rspec/rspec-rails`, tag: 'v2.99.0'
```

**Comment by arosalesheiskell** [comment]
> ```ruby
> gem 'rspec-rails', github: `https://github.com/rspec/rspec-rails.git`, tag: 'v2.99.0'
> # or
> gem 'rspec-rails', github: `rspec/rspec-rails`, tag: 'v2.99.0'
> ```

Unfortunately adding either line to this resulted in a Gemfile parsing error. Trying to set the rspec-rails gem version to 2.99.0 in my gemfile also didn't work and showed a "Could not find gem 'rspec-rails (~> 2.99.0)' in any of the gem sources listed in your Gemfile." error message. 

Would you recommend opening up a new issue for this?

**Comment by pirj** [comment]
@arosalesheiskell Let's move this discussion to https://groups.google.com/forum/#!forum/rspec
