### ISSUE TITLE
Wrong negative expectation with once

### ISSUE THREAD

**Issue by SergiyYarinovskiy** [rspec/rspec-rails#1963]
Hello. I have such tests:
```ruby
  class A; end
  it 'calls new' do
    expect(A).to receive(:new).once
    A.new
  end
```
It finishes successfully. Next one:
```ruby
  class A; end
  it 'calls new' do
    expect(A).not_to receive(:new)
    # A.new
  end
```
Also fine. But if I combine `.not_to` with `.once` it behaves like it expects **to receive**:
```ruby
  class A; end
  it 'calls new' do
    expect(A).not_to receive(:new).once
    # A.new
  end
```
```
     Failure/Error: expect(A).not_to receive(:new).once
     
       (A (class)).new(*(any args))
           expected: 1 time with any arguments
           received: 0 times with any arguments
```
I am not sure if this is a bug. I would expect that `.once` will be ignored and last test passes
`rspec-rails (3.7.2)`

Thank you

**Comment by JonRowe** [comment]
This is a bug in `rspec-mocks` if you could reopen this there we'd be grateful.
