### ISSUE TITLE
Use transactional tests

### ISSUE THREAD

**Issue by szpasztor** [rspec/rspec-rails#1964]
In March 2015, [rails introduced a change](https://github.com/rails/rails/pull/19282) renaming `use_transactional_fixtures` to `use_transactional_tests`. However, it looks like in rspc 3.7.0 this change is still not implemented and the gem is using the deprecated key. This is evidenced by the following attempt to use the new name:
```
NoMethodError:
  undefined method `use_transactional_tests=' for #<RSpec::Core::Configuration:0x00007fc741859070>
  Did you mean?  use_transactional_fixtures=
```

The change should be as simple as renaming current usages in the repo.

**Comment by JonRowe** [comment]
The RSpec setting is `use_transactional_fixtures` it talks to the correct method under the hood in Rails for you.
