### ISSUE TITLE
Errno::ENAMETOOLONG on system test screenshot

### ISSUE THREAD

**Issue by oniofchaos** [rspec/rspec-rails#1976]
### Steps to reproduce

Have a sufficiently long series of describes/contexts such that their combined name causes the error. One example from my app is 
```
Errno::ENAMETOOLONG:
              File name too long @ rb_sysopen - /home/circleci/project/tmp/screenshots/failures_r_spec_example_groups_client_exports_a_csv_of_exceptions_by_visiting_the_exception_report_page_and_clicking_export_to_csv_and_filling_out_the_export_form_with_valid_information_and_clicking_download_downloads_a_file_named_"exception_report_csv"_599.png
```

### Expected behavior

Screenshot should save successfully in some fashion without error - maybe by truncating the name?

### Actual behavior

`Errno::ENAMETOOLONG` error and no screenshot saved.

### System configuration
**Rails version**: 5.1.5

**Ruby version**: 2.5.0

See https://github.com/rails/rails/issues/32346

**Comment by JonRowe** [comment]
As a workaround please use less contexts, will update rails/rails#32346

**Comment by samphippen** [comment]
@JonRowe  I'm going to make this truncate on our end.
