### ISSUE TITLE
SourceAnnotationExtractor moved in edge Rails causing error

### ISSUE THREAD

**Issue by jasnow** [rspec/rspec-rails#1984]
**Steps to Reproduce**

 1. Clone repo: https://github.com/jasnow/show-me-the-food5edge
 2. Run "bundle ; rake" (all green)
 3. Run "bundle update ; rake" and get this error:
```
Bundler::GemRequireError: There was an error while trying to load the gem 'rspec-rails'.
Gem Load Error is: Rails::SourceAnnotationExtractor is not a class/module
Backtrace for gem load error is:
```
 4. Think this is caused by this code change:    https://github.com/rails/rails/commit/0ec23effa74e8e9da6ebb14afbd335bea470ab3e
 5. Feel free to add comment for more information if needed.

Rails:   6.0.0.alpha
Ruby:   2.6.0-preview1

**Comment by jasnow** [comment]
Checked today and it affects 4 of my "canary"/edge Rails repos.

**Comment by nbulaj** [comment]
The same problem [here](https://travis-ci.org/doorkeeper-gem/doorkeeper/jobs/366415756). Even for all the RSpec stack from the `master`.

**Comment by jasnow** [comment]
@JonRowe - Is there anything else you need from me regarding this issue?

**Comment by JonRowe** [comment]
Try out #1989 and see if that fixes it for you, really someone should tell the Rails team about this too as the intent is to deprecate the class not break it.

**Comment by jasnow** [comment]
I did the following:
 1. Changed Gemfile to use
```
gem 'rspec-rails', git: 'https://github.com/rspec/rspec-rails'
```
 2. Ran "bundle update" and got lots of dependency errors.

**Comment by jasnow** [comment]
@JonRowe - Added a comment to Gitter. Can't cut/paste into Google Group and did not yet want to delete rails/rails issue template.

**Comment by nbulaj** [comment]
I'm using master branch of Rspec with Rails master and still see this error:

https://travis-ci.org/doorkeeper-gem/doorkeeper/jobs/380759360
