### ISSUE TITLE
NoMethodError: undefined method `receive'

### ISSUE THREAD

**Issue by ianaverno** [rspec/rspec-rails#1991]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.2.8
Rails version: 4.2.7
Rspec version: 3.5.4

## Observed behaviour

running
`expect(PinMailer).to receive(:pin_approval).with(instance_of(CommunityPost), community_owner.user.email)`

results in 
```
NoMethodError:
       undefined method `receive' for #<RSpec::ExampleGroups::ApiV1CommunityPostsController::ControllerActions::POSTCreate::WhenApprovalIsRequired:0x007fadb7d29bc0>
```

## Expected behaviour

Should check that the method is run with the provided parameters

**Comment by JonRowe** [comment]
Have you got the expect syntax turned on?

**Comment by samphippen** [comment]
@ianaverno 
Thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by samphippen** [comment]
@ianaverno I'm going to go ahead and close this issue because it seems this is specific to your use case. If you can provide us with a reproduction case I'm very happy to re-open. Thanks!
