### ISSUE TITLE
Method destroy don't run

### ISSUE THREAD

**Issue by jujulisan** [rspec/rspec-rails#1994]
I upgraded my application for Rails 5.1.6, ruby 2.5.1 and rspec 3.7.2.
This application has a test it verify if the callback was called. When I debbug de test and run manually the line with destroy, the test pass. But if I run the test normally, the test fail.

Ruby version:2.5.1
Rails version:5.1.6
Rspec version:3.7.2

Code

```
     before do
        allow(Module::Class).to receive(:method)
        object.destroy # I need run this line mannualy for test works
        object.run_callbacks(:commit)
      end

      it 'callback was called' do
        expect(Module::Class).to have_received(:method).at_least(:once)
      end
```

Failure/Error: expect(Module::Class).to have_received(:method).at_least(:once)
     
       (Module::Class (class)).method(*(any args))
           expected: at least 1 time with any arguments
           received: 0 times with any arguments

Before the upgrade, my test was passing. And if I run the line object.destroy with a binding.pry, and then I continue the test, it pass.

**Comment by JonRowe** [comment]
We don't do anything special with callbacks, are you upgrading Rails or RSpec? If you're upgrading both try just upgrading RSpec first, and if the test still fails then there might be an issue with our integration with system specs, which changed how Rails handles transactions, otherwise it's an issue with Rails.

**Comment by jujulisan** [comment]
Yes, I upgrade both, I'll upgrade rspec first.

**Comment by jujulisan** [comment]
Sorry about that, this really is an issue with Rails. I'll this issue.
