### ISSUE TITLE
Controller tests - state is propagated between multiple requests within the same example

### ISSUE THREAD

**Issue by alisnic** [rspec/rspec-rails#2006]
## What Ruby, Rails and RSpec versions are you using?

ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
Rails 4.2.8
RSpec 3.5.4

## Observed behaviour

When doing controller tests, controller state is propagated between multiple requests within the same example

## Expected behaviour

Controller state should not be propagated between requests, as it happens in real world

## Can you provide an example app?

I wrote a failing spec for that

```ruby
Scenario: state does not propagate between requests
  Given a file named "spec/controllers/widgets_controller_spec.rb" with:
    """ruby
    require "rails_helper"

    class WidgetsController < ::ActionController::Base
      def index
        @counter ||= 0
        @counter += 1
        render plain: @counter.to_s
      end
    end

    RSpec.describe WidgetsController, :type => :controller do
      describe "GET index" do
        it "does not accumulate state between requests" do
          get :index
          get :index
          expect(response.body).to eq("1")
        end
      end
    end
    """
  When I run `rspec spec`
  Then the example should pass
```

**Comment by alisnic** [comment]
It seems that the problem is in Testing::Functional from Rails, nothing to do with Rspec-rails  https://github.com/rails/rails/blob/v4.2.8/actionpack/lib/action_controller/test_case.rb#L618

**Comment by JonRowe** [comment]
Thanks for checking in to that further for us!
