### ISSUE TITLE
Scaffold controller spec template uses deprecated 'success?` method

### ISSUE THREAD

**Issue by composerinteralia** [rspec/rspec-rails#2009]
When creating a resource with `rails generate scaffold`, we use this template for the rspec controller specs:
https://github.com/rspec/rspec-rails/blob/master/lib/generators/rspec/scaffold/templates/controller_spec.rb#L67

But the `success?` method on the response was deprecated:
https://github.com/rails/rails/blob/20c91119903f70eb19aed33fe78417789dbf070f/actionpack/lib/action_dispatch/testing/test_response.rb#L23

This may be as simple as changing the controller spec template to use `be_successful` instead of `be_success`. I can make a PR for this next week if nobody else does.

You can see the deprecation warning by running the specs here: https://github.com/composerinteralia/rspec-deprecated-method-app

Ruby version: 2.5.1
Rails version: 5.2.0
Rspec version: 3.7

**Comment by benoittgt** [comment]
Hello @composerinteralia 

Thanks for the comment. Feel free to open a PR to address this warning.

🎉
