### ISSUE TITLE
Disable making specs a dependency of the default rake task?

### ISSUE THREAD

**Issue by joshuapinter** [rspec/rspec-rails#2016]
By default, this library sets the default rake task to depend on `:spec`, as can be seen in this line: 

```ruby
task :default => :spec
```

https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/tasks/rspec.rake#L6

We want to run a few things before running the specs when we call `bundle exec rake`. But with this line setting the default rake task to depend on `:spec`, we can't redefine the default rake task without first clearing it out, which is not obvious. You're required to do something like this: 

```ruby
Rake::Task[ :default ].clear

task default: :environment do
  # Preparatory tasks.

  Task::Task[ :rspec ].invoke

  # Closing tasks.
end
```

Is there a way of making this configurable so that you can not set the default rake task to depend on `:spec`?

I can issue a PR if this is something that's of interest to you. 

Thanks.

**Comment by JonRowe** [comment]
To be honest opting out via `task(:default).clear` is going to be more concise than creating a setting somewhere, especially as it would have to load in rake and not in RSpec.

We could change this in the next major version, but we'd have to go down the "generate" a rake task file route, and have it in there, so it could be just deleted, would require deprecation, changeover, all sorts, to be honest given you're the first person to ever even suggest this, I'm kind of inclined to think its too much effort!

**Comment by joshuapinter** [comment]
Thanks for the reply, @JonRowe. If I'm the only one then, yeah, definitely not worth the effort. Haha.

Quick question, though: Is this normal practice for a test suite to make the default rake task depend on it and automatically run it? What was the thinking around doing this in the first place? I find it a little surprising, but it seems I'm the only one that thinks so. 😄

Thanks!

**Comment by JonRowe** [comment]
We only do this because Rails does this, it would be very surprising to run
'rake' and get minitest when you're an RSpec user!

The main RSpec gems don't do this as they're a bit more diy

**Comment by joshuapinter** [comment]
![well there it is](https://user-images.githubusercontent.com/180819/43656243-ee53f2e0-970e-11e8-99cf-d6958974eef3.gif)

See, and that makes perfect sense. I didn't realize Rails does this. Mystery solved. I'll stop my whining. :)
