### ISSUE TITLE
having a problem with=>  rails g rspec:install  

### ISSUE THREAD

**Issue by bottles9** [rspec/rspec-rails#2018]
## What Ruby, Rails and RSpec versions are you using?

Ruby version:
Rails version:
Rspec version:

**Comment by bottles9** [comment]
[livechat.zip](https://github.com/rspec/rspec-rails/files/2289936/livechat.zip)
 this the project i am working on Please

**Comment by JonRowe** [comment]
This isn't an RSpec issue, but a problem in your `C:/Sites/livechat/config/application.rb`, comment out the line with `load_defaults` on it, (line 95). It seems that something is wrong with your Rails install.
