### ISSUE TITLE
Rspec command does not work for 2.4.2 ruby version ?

### ISSUE THREAD

**Issue by sapnaSpaceo** [rspec/rspec-rails#2019]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.4.2
Rails version: 5.4.1
Rspec version: 3.8.0

## Observed behaviour

 bundle exec rspec command works fine when my ruby version is 2.3.1 but it throws error when I use this command for ruby version 2.4.2 it gives below error.

rbenv: rspec: command not found

The `rspec' command exists in these Ruby versions:
  2.3.1

## Expected behaviour

 bundle exec rspec command should work for latest versions of ruby

**Comment by JonRowe** [comment]
I'm afraid we can't debug why you don't have RSpec installed after upgrading, Ruby. I recommend try reinstalling RSpec in your new gem environment.  e.g.

* Running `bundle install` afresh
* Running `gem install rspec`
* Checking your PATH includes the location of your gem installations, which has probably changed.

**Comment by sapnaSpaceo** [comment]
yes it worked. thank you.
