### ISSUE TITLE
Getting sporadic Net::ReadTimeout when using file fixtures along with Capybara and Capybara-webkit

### ISSUE THREAD

**Issue by mhluska** [rspec/rspec-rails#2029]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.4.2
Rails version: 5.2.1
Rspec version: 3.8.0

Capybara version: 3.8.2
Capybara-webkit version: 1.15.0
Chrome version: 69.0.3497.100

## Observed behaviour

Load a file fixture, e.g. `fixtures :all`, use Capybara::DSL and do `visit('/')` in a spec, notice hang with eventual Net::ReadTimeout. The issue is sporadic. Maybe 1 in 10 attempts will succeed.

The issue only happens on my specs that use file fixtures. The others pass 100% of the time. I'm not sure whether this is more likely to be a Selenium issue but I've been debugging it for days and I figure I'd ask here first.

## Expected behaviour

Should be able to use `visit('/')` without hanging.

## Redacted example

```rb
describe 'the feature', :vcr, type: :system do
  fixtures :all

  before do
    Capybara.session_name = :a_user
    visit('/') # This hangs, ends with `Net::ReadTimeout` sometimes.
    ..
  end

  it 'can use the feature' do
    ..
  end
end
```

**Comment by mhluska** [comment]
I may have fixed this by upgrading to Ruby 2.5.1. It's possible it was caused by [aws-sdk-ruby monkey patching Net::HTTP](https://github.com/aws/aws-sdk-ruby/issues/1752)

**Comment by JonRowe** [comment]
Its unlikely this is an `rspec-rails` issue, as its capybara timing out trying to access your web app. Does it happen if you remove the `fixtures :all` line? Or use a more limited fixture subset? You should also check your application boot time in this scenario

**Comment by mhluska** [comment]
@JonRowe this seems to be more likely due to [Ember FastBoot](https://stackoverflow.com/questions/52632353/capybara-selenium-webdriver-netreadtimeout-when-using-rspec-file-fixtures-fa). Going to close.
