### ISSUE TITLE
Feature Request: check if an email is in delivery queue and has certain properties

### ISSUE THREAD

**Issue by tansaku** [rspec/rspec-rails#2030]
I was just thinking it would be great to have a custom matcher to check if an email is in delivery queue and has certain properties

We're just working on modifying the following code to work with any email in the delivery queue:

```rb
    expect(ActionMailer::Base.deliveries[0].subject).to include(subject)
    expect(ActionMailer::Base.deliveries[0].body).to include(body) unless body.nil?
    expect(ActionMailer::Base.deliveries[0].to).to include(email) unless email.nil?
```
have been playing around with things like:

```rb
expect(subjects).to include an_object_having_attributes(unparsed_value: subject)
```
which doesn't seem to work and would have inconsistencies even if it did - anyone ever worked on this kind of thing before?

**Comment by JonRowe** [comment]
Checkout https://github.com/email-spec/email-spec

**Comment by benoittgt** [comment]
@tansaku feel free to close the issue if the gem fits your need. 🙂

**Comment by tansaku** [comment]
thanks @benoittgt - I need to review - the gem has lots of handy features, but not sure it helps with my specific issue - at least I can't immediately see that it does ...

**Comment by JonRowe** [comment]
@tansaku I think it should do, as it asserts on various properties of delivered emails, which in test mode is the queue, you can check subject and bodies of emails easily with email_spec. 

RSpec Rails is a thin wrapper over the Rails test helpers so we try to encourage the use of external gems for everything else.

**Comment by JonRowe** [comment]
A given email / one of the emails in the queue should be the same thing, I believe this, with `email_spec` would do what you want:

```
expect(
  ActionMailer::Base.deliveries[0]
).to have_subject(subject).and(have_body_text(body)).and(deliver_to(email))
```

**Comment by tansaku** [comment]
thanks @JonRowe - that looks nice, but we don't want to assume that the email with those properties is the first one in the queue, but maybe we can combine with `to include an_object_having_attributes` to achieve the effect we want?

```rb
expect(
  ActionMailer::Base.deliveries
).to include an_object_that_has_subject(subject).and(has_body_text(body)).and(delivers_to(email))
```

**Comment by JonRowe** [comment]
Quite possibly, feel free to experiment wth composition of matchers, I think you could just use `include` with the above

**Comment by JonRowe** [comment]
I'm going to close this as I don't feel it's `rspec-rails` job to provide anything here, there are as demonstrated 3rd party solutions that can be combined to do this.

**Comment by JonRowe** [comment]
Have you seen that you can [define custom matchers](https://relishapp.com/rspec/rspec-expectations/v/3-8/docs/custom-matchers/define-a-custom-matcher)?

**Comment by tansaku** [comment]
oh that's a good idea - thanks @JonRowe :-)

**Comment by JonRowe** [comment]
I believe you should be able to define a custom matcher such that you can compose it with include

**Comment by tansaku** [comment]
ah maybe so, in the first instance I just went for:

```rb
class HaveEmailWithMatcher
  def initialize(subject, body, to)
    @subject = subject
    @body = body
    @to = to
  end

  def matches?(emails)
    matches.include? [true, true, true]
  end

  def matches
    emails.map do |mail|
      [mail.subject == @subject,   
      body_match = @body.nil? ? true : mail.body == @ody,
      email_match = mail.to.include?(@to)]
    end
  end

  def failure_message
    "Expected email with #{@subject} #{@body} #{@to} but only got these matches:\n" +
    matches
  end

  def failure_message_when_negated
    "Expected not to find email with #{@subject} #{@body} #{@to} but got these matches:\n" +
    matches
  end
end
```
haven't checked it works - will have to play with it later - other stuff to do now :-)
