### ISSUE TITLE
undefined method `delete' for #<RSpec::Examp

### ISSUE THREAD

**Issue by dheenaINDIAN** [rspec/rspec-rails#2031]
When i try to add spec for destroy method, it throws errors. User has many projects.

Trying to create a project for a user. Then deleting the project of that particular user throws error.

I have tried as,

```
feature 'Destroy', :project do

  scenario 'project get removed after delete' do
    user = FactoryBot.create(:user)
    project = user.projects.create(FactoryBot.attributes_for(:project))
     signin(user.email, user.password)
     visit projects_path
     delete :destroy, :id => project.id
     expect(response.status).to eq 200 
  end 
end

```
Getting error as 

```
NoMethodError:
   undefined method `delete' for #<RSpec::ExampleGroups::Destroy:0x00000005cff620>

```

**Comment by JonRowe** [comment]
Feature specs are provided by capybara, which emulates the browser, you won't have access to the request helpers in this fashion, you'll need to click a delete link or switch to controller/request tests etc
