### ISSUE TITLE
Selenium::WebDriver::Error::UnknownError:        permission denied

### ISSUE THREAD

**Issue by mariyajolly** [rspec/rspec-rails#2060]
Hi,

I am trying to run ruby scripts through Jenkins. Ruby version used is 2.0.0 , watir-webdriver version is 0.9.9 ,selenium-webdriver version 3.13.0 and geckodriver-v0.23.0-win64. When i run  the scripts I am getting the following error.

```
Failure/Error: Unable to find matching line from backtrace
     Selenium::WebDriver::Error::UnknownError:
       permission denied
     # C:/Jenkins/Ruby200-x64/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
     # C:/Jenkins/Ruby200-x64/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
     # C:/Jenkins/Ruby200-x64/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
     # C:/Jenkins/Ruby200-x64/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
     # C:/Jenkins/Ruby200-x64/lib/ruby/gems/2.0.0/gems/selenium-webdriver-
```

.

**Comment by samphippen** [comment]
Hi @mariyajolly, I see that this is an error from selenium, and that you are using windows.

Are you using `system` or `feature` tests?

Would you mind pasting a copy of `Gemfile` and `Gemfile.lock` in a [gist](gist.github.com) so that we can take a look at all your dependencies?

I will note that we don't really develop against windows, and that this is likely a rails issue, but we can triage it for you first.

**Comment by mariyajolly** [comment]
> Hi @mariyajolly, I see that this is an error from selenium, and that you are using windows.
> 
> Are you using `system` or `feature` tests?
> 
> Would you mind pasting a copy of `Gemfile` and `Gemfile.lock` in a [gist](gist.github.com) so that we can take a look at all your dependencies?
> 
> I will note that we don't really develop against windows, and that this is likely a rails issue, but we can triage it for you first.
