### ISSUE TITLE
Document format issue in Directory Structure

### ISSUE THREAD

**Issue by lanzhiheng** [rspec/rspec-rails#2065]
![image](https://user-images.githubusercontent.com/8858472/50915738-684ab880-1474-11e9-9775-0f165a70403e.png)

It seems that we have the formatted issue in the document, but I can not find any issue in the [source file](https://github.com/rspec/rspec-rails/blob/master/features/directory_structure.feature#L6). I am not sure why It could not render correctly

**Comment by JonRowe** [comment]
Hmm @mattwynne if I may intrude, any ideas why Relish is formatting this so?

**Comment by mattwynne** [comment]
Dunno, that's annoying eh. Is it possible the source file uses some kooky newline characters?

We've got a [long-standing issue](https://github.com/rspec/rspec-dev/issues/199#issuecomment-368155174) that's with me to trial out migrating your docs to https://app.cucumber.pro which might solve this - I'm sure we're using a much more modern markdown renderer in there.

**Comment by lanzhiheng** [comment]
@mattwynne Sounds good,  https://app.cucumber.pro  looks comfortable than Relish.

**Comment by samphippen** [comment]
@JonRowe WDYT about doing this move?

On the one hand, better rendering, on the other the RSpec documentation has canonically been in relish for so long it seems like it might hurt our google juice to move it for quite a while

**Comment by JonRowe** [comment]
If the old documentation could be redirected to cucumber pro the google juice should transfer, @mattwynne would that be possible?

**Comment by mattwynne** [comment]
Yes, we can set up redirects for sure, and we won't force you to move over until you're happy with the new platform. You're guests of honour!

**Comment by samphippen** [comment]
@JonRowe ok, I'm pretty happy to go ahead and try this as part of the 4.xx release for RSpec rails. Is that good for you?

**Comment by benoittgt** [comment]
@samphippen I think it's a good idea. Thanks @mattwynne

**Comment by pirj** [comment]
Do you mind guys if we close this?
The issue seems to be minor, and the effort needed to fix is enourmous. I believe we have more important things to address.

**Comment by lanzhiheng** [comment]
@pirj done
