### ISSUE TITLE
Rails.env returns development

### ISSUE THREAD

**Issue by lethunder** [rspec/rspec-rails#2079]
Hello,
when i run tests on my app i don't want for instance to send welcome text message to user after creating them (because it is for testing purposes and because it costs :) )

So in my model i have something like
```
    unless Rails.env.test?
      client = Twilio::REST::Client.new
      client.messages.create(
        from: Rails.application.credentials[Rails.env.to_sym][:twilio][:phone_number],
        to: Rails.env.development? ? Rails.application.credentials[Rails.env.to_sym][:twilio][:phone_number_for_dev] : recipient.phone,
        body: message
      )
    end
```
but it keeps sending sms because Rails.env returns development.
i tried to change in rails_helper ENV['RAILS_ENV'] ||= 'test' => ENV['RAILS_ENV'] = 'test'
it does not change behaviour. Any idea?
Thanks in advance

**Comment by JonRowe** [comment]
`Rails.env` is entirely controlled by Rails, so this is not an RSpec issue (and we prefer to keep Github issues for bugs and not for help on your specs, thats what the mailing is and/or stackoverflow is for) but looking at your code you evidently have something seeing `ENV['RAILS_ENV']` or `ENV['RACK_ENV']` to `development` (possibly rake).

In your `rails_helper.rb` or `spec_helper.rb` you should be able to override this depending on when your code is run, but you currently have `||=` which won't "force" it, just set it if not already present. Changing this to `=` may work around this issue but you should probably find whats setting it.
