### ISSUE TITLE
How to include params inside the body.

### ISSUE THREAD

**Issue by sunilb0575** [rspec/rspec-rails#2080]
Rspec spec fails on the following test case. Can anyone please help me with sending params inside the body?

**Test case:**

``` 
  describe 'POST search' do
    it 'renders search' do
      request.headers['Content-Type'] = 'application/json'
      request.headers['Accept'] = 'application/json'

      post :search, body: {name: {query_type: 'match', value: ['xy']} }.to_json

      expect(response.status).to eq(200)
      expect(response.body.include?('TWEEDLE'))
    end
  end
```

**Controller:**

```
def search
    page_params = pagination_params
    
    query_hash = QueryPreprocessor.params_to_query_with_types(JSON.parse(request.body.read).deep_symbolize_keys)
    logger.info "query_hash: #{query_hash}"
    es_query_json = Elastic::QueryBuilder.facility_search_v1(query_hash, page_params).to_json
    logger.info "es query: #{es_query_json}"

    facilities = facility_helper.search es_query_json
    json_response build_facilities_response(facilities)
  rescue ApiError => e
    render json: e.response, status: e.status
  end
```

and these are the params which I want to include inside the body, which is being called in the controller:

```
def pagination_params
    page_params = {}
    page_params['size_params'] = params[:size] || 50
    page_params['from_params'] = params[:from] || 0
    page_params['sort_params'] = params[:sort]
    page_params['order_params'] = params[:order]
    page_params
  end
```

**Comment by JonRowe** [comment]
Closing as duplicate issue, picking how to send params depends on your version of Rails. Check the documentation for your version of Rails as to how `post` works (its not RSpec functionality), and then make sure you're using the right kind of spec (which is documented but not mentioned here).

**Comment by martinBlacklane** [comment]
I strongly disagree here. Rails works as expected, RSpec-Rails works unexpected. Sending a request body is standard rest, and also supported in RSpec-Rails. But the behaviour of the `post :query_insurances, body: { definition: { corporation_id: 17, currency: "EUR" } }` differs from the real-life curl example. 
As said, this is not about how to add params inside the body.

**Comment by JonRowe** [comment]
`rspec-rails` is a thin wrapper around the Rails test helpers, `post` is one of these methods, we don't modify its original Rails behaviour in any way, that Rails has different behavious between your usage of `post` and how curl invokes the controller is down to how Rails test helpers don't replicate the full stack but instead simulate it, hence why I refer to checking the Rails documentation
