### ISSUE TITLE
 NoMethodError:  undefined method `merge' for nil:NilClass

### ISSUE THREAD

**Issue by adrienpoly** [rspec/rspec-rails#2098]
## Observed behaviour

All of my tests that are using a `path` will fail with one of the two following message

```
Failure/Error: Rails.application.routes.url_helpers.story_chapter_path
     NoMethodError:
       undefined method `merge' for nil:NilClass
```

or 

```
Failure/Error: <%= link_to root_path, class: "navbar-brand mr-sm-3" do %>
      ActionView::Template::Error:
        undefined method `empty?' for nil:NilClass
```

## what I have done so far:
- It used to work great and can't find what changed???  looked at the diff but can find anything relevant. must be missing something obvious!

- I looked for `empty?` and `merge` in my code base but none are being used when running a failling test

- in my file rails_helper.rb I do have the following line:

```ruby
  config.include Rails.application.routes.url_helpers
``` 

## What Ruby, Rails and RSpec versions are you using?

```
ruby 2.4.2
rails 5.2.2
RSpec 3.8
  - rspec-core 3.8.0
  - rspec-expectations 3.8.2
  - rspec-mocks 3.8.0
  - rspec-rails 3.8.2
  - rspec-support 3.8.0
```

**Comment by JonRowe** [comment]
:wave: You mention this "used to work great", what did you change? Rails? RSpec-Rails? Config?

**Comment by benoittgt** [comment]
Do you think you can provide a reproduction script?

**Comment by adrienpoly** [comment]
I am back working on it today. This happened while I was away from the project for a few weeks. I need to look into what has changed. My first look at it, I couldn't see any change in the rspec configuration. I ll look into the versions of the different gems (Capybara, webpacker etc)

Will post back today if I find something or if I can extract a failing example

**Comment by JonRowe** [comment]
Closing until theres something actionable here
