### ISSUE TITLE
Is there a way to stub Rails credential key?

### ISSUE THREAD

**Issue by olimart** [rspec/rspec-rails#2099]
Similar to stubbing environment variable, can we stub Rails credential key?

## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.6.1
Rails version: 5.2.2
Rspec version: 3.8

## Observed behaviour

`allow(Rails.application.credentials).to receive(:my_token).and_return('')`

## Expected behaviour

```
allow(Rails.application.credentials).to receive(:[]).with(:my_token).and_return('123')
Rails.application.credentials.my_token
=> '123'
```

**Comment by JonRowe** [comment]
As `credentials` is an object you have to stub what you wish to retrieve. So:
```
allow(Rails.application.credentials).to receive(:my_token).and_return('123')
Rails.application.credentials.my_token
# => 123

allow(Rails.application.credentials).to receive(:[]).with(:my_token).and_return('345')
Rails.application.credentials[:my_token]
# => 345
```

It'd be better to use it as designed and setup a test environment set of credentials.

**Comment by olimart** [comment]
Thanks @JonRowe I edited the post to actually focus on the issue (described in your first example).

`my_token` is already defined in `credentials.yml.enc` but I need to override the value in my specs.

I tried indeed the following but it keeps the value defined in `credentials.yml.enc`.

```
allow(Rails.application.credentials).to receive(:my_token).and_return('123')
Rails.application.credentials.my_token
# => 123
```

**Comment by benoittgt** [comment]
I just did a test on a [fresh_app](https://github.com/benoittgt/rspec_credentials_test/blob/master/spec/credentials_spec.rb)

And I add no issue.

My credentials file look like this:
```yml
 aws:
  access_key_id: 123
  secret_access_key: 345
olimart: 'from_config'

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: xxxx
```

```ruby
require 'rails_helper'

describe 'Credentials' do
  it 'stubs credentials' do
    allow(Rails.application.credentials).to receive(:olimart).and_return('123')
    expect(Rails.application.credentials.olimart).to eq('123')
  end
end
```

no issues.

**Comment by olimart** [comment]
@benoittgt What's your master key?

Amazing. The exact same code fails on my end. I appreciate your help.

**Comment by JonRowe** [comment]
@benoittgt I'll leave it up to you to decide if this should be reopened :)

**Comment by olimart** [comment]
> I'll leave it up to you to decide if this should be reopened :)

don't think so. Just need to find out why but in the meantime we came up with a workaround.

**Comment by Uelb** [comment]
Actually, I have the exact same issue, and I cannot figure out why, @olimart, what is the workaround you implemented ?

**Comment by olimart** [comment]
@Uelb 

```ruby
shared_context 'encrypted configuration' do
  def stub_credential(key, value)
    allow(Rails.application).to receive(:credentials).and_return(OpenStruct.new(key.to_sym => value))
  end
end

# usage
stub_credential(:my_credential, 123)
```

**Comment by jcquarto** [comment]
how is this done for a deeper structure, for example if the credentials.yml file has

`test:
     level
         MY_DEEP_ENV_VAR: 12345`

**Comment by pirj** [comment]
```ruby
  allow(Rails.application).to receive_message_chain(:test, :level, :MY_DEEP_ENV_VAR => 67890)
```

**Comment by Petercopter** [comment]
Rubocop was complaining about `receive_message_chain`, so I think I'm going to go with

```
allow(Rails.application).to receive(:credentials).and_return(JSON.parse({ checkr: { secret: 'super duper secret' } }.to_json, object_class: OpenStruct))
```

**Comment by beano-digital** [comment]
This worked for me - note the use of `deep_merge`

```ruby
allow(Rails.application).to receive(:credentials).and_return(Rails.application.credentials.deep_merge(test: { stripe: { trial_periods: { standard_monthly_uk: 30 } } }))
```

**Comment by paulodeon** [comment]
This worked for me, note the use of `deep_merge`:

```ruby
allow(Rails.application).to receive(:credentials).and_return(Rails.application.credentials.deep_merge(test: { stripe: { trial_periods: { standard_monthly_uk: 30 } } }))
```

**Comment by prpetten** [comment]
I have a class:

````ruby
class Vendor::Connection
  VENDOR_CLIENT_ID = Rails.application.credentials.vendor_api[:client_id].freeze
  VENDOR_CLIENT_SECRET = Rails.application.credentials.vendor_api[:client_secret].freeze

  # ...

  def token_body
    {
      client_id: VENDOR_CLIENT_ID,
      client_secret: VENDOR_CLIENT_SECRET,
    }
  end
end
````

When I attempt to mock the credentials using any of the above methods
````ruby
require 'rails_helper'

describe Vendor::Connection do
  before do
    allow(Rails.application.credentials).to receive(:vendor_api).and_return({ client_id: '123' })
  end

  it 'works' do
    expect(true).to eq(true)
  end
end
````

I receive:
````
Failure/Error: VENDOR_CLIENT_ID = Rails.application.credentials.vendor_api[:client_id]

NoMethodError:
  undefined method `[]' for nil:NilClass
````

I also tried a before block of:
````ruby
  before do
    stub_const('Vendor::Connection::VENDOR_CLIENT_ID', '123')
    stub_const('Vendor::Connection::VENDOR_CLIENT_SECRET', '456')
    stub_const('Vendor::Connection::VENDOR_PARTNER_ID', '789')
  end
  ````
  
  I still receive:
````
Failure/Error: VENDOR_CLIENT_ID = Rails.application.credentials.vendor_api[:client_id]

NoMethodError:
  undefined method `[]' for nil:NilClass
````

I tried: 
````ruby
shared_context 'credentials' do
  before do
    allow(Rails.application).to receive(:credentials).and_return(OpenStruct.new(vendor_api: {client_id: '123', client_secret: '456', partner_id: '789'}))
  end
end

describe Uhc::Connection do
  include_context 'credentials'

  it 'works' do
    expect(true).to eq(true)
  end
end
````

Which also returned:
````
Failure/Error: VENDOR_CLIENT_ID = Rails.application.credentials.vendor_api[:client_id]

NoMethodError:
  undefined method `[]' for nil:NilClass
````

I also attempted to put a `binding.pry` as the first line in the `before` block, but it fails before getting to do the `binding.pry`

Any help would be greatly appreciated

**Comment by pirj** [comment]
We reserve our issue tracker for features and bugs.
I suggest seeking help using resources outlines in https://rspec.info/help
Thanks for understanding.

**Comment by JonRowe** [comment]
You will find it hard to mock out things in class definitions, RSpec doesn't control the loading of classes (this is typically something Rails does for you) so by the time the class is loaded the constant is already set, you can use the `stub_const` approach but the error is because in your test environment you don't have a vendor_api set, you need a fake credential set for the class to load, then you can stub the constant.

**Comment by prpetten** [comment]
@pirj My bad, I'll remove the comment

**Comment by prpetten** [comment]
@JonRowe Thanks
