### ISSUE TITLE
transactional_fixtures not working

### ISSUE THREAD

**Issue by Kutomore** [rspec/rspec-rails#2124]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.5.1
Rails version: 5.2.2
RSpec version: 3.8

## Observed behaviour

Test database data is persisting even with `config.use_transactional_fixtures = true` set in the rails_helper

## Expected behaviour

The data of each test should not persist, the database should clean itself up

I don't think it's an gem issue, most likely an messd up config maybe? No errors show up, I found it out by accident and it's driving me crazy. It was set to false for some reason, then I set it to true, recreated the dbs, and tested again, the data still persists.

**Comment by mikegee** [comment]
I'll think other folks would need to be able reproduce the problem to have any hope solving it. Do you think you could create a public repo exhibiting this behavior?

**Comment by Kutomore** [comment]
Weirdly enough, on a different pc it worked just by enabling transactional fixtures. I guess it was an enviroment issue. Thanks for the attention tho.

**Comment by jakeonfire** [comment]
is this behavior not by design? https://discuss.rubyonrails.org/t/fixtures-all-or-nothing/82862/11
