### ISSUE TITLE
RSpec issue in join query 

### ISSUE THREAD

**Issue by Harrymsys** [rspec/rspec-rails#2128]
Hi Team,

We are facing the issue in executing the join query via Rspec where the same code works fine when used directly. 

Sample Query : 
```
SELECT  `datavalue` FROM `TestTable` INNER JOIN `anothertable` ON `table_id` = `somevalue` WHERE `is_available` = TRUE`
```
As per this query, We are fetching the 'datavalue' from the 'testtable' where the 'table_id' should match the two tables - 'testtable' and 'anothertable' in the foreign key relation. 

1) It works fine in the rails console too. 
2) It works fine in the Ruby code, If called seperately 

        TestTable.where( is_available: true ).joins( :anothertable )

3) It is not working when I called from the same method from the RSpec. 

    NOTE : Only Joins is not working in the RSpec. 

Please check on this to resolve it. 

Thanks,
Hari

**Comment by JonRowe** [comment]
Hi, RSpec and RSpec Rails (which I'm assuming your using) has no effect on database access. Rails does have seperate databases for the dev and test environments so its possible your out of sync between the two, check your migrations and try again.

Closing as this is unlikely a bug in either rspec or rspec-rails.
