### ISSUE TITLE
[ANN] RSpec 'master' docs available

### ISSUE THREAD

**Issue by MSP-Greg** [rspec/rspec-rails#2129]
Using code that enhances YARD, I have a site with Ruby and several gems doc'd.  The site is updated at least daily...

The docs for Rspec are here:
https://msp-greg.github.io/rspec/

I combined docs for the following repos together, which may simplify reviewing them:
rspec/rspec
rspec/rspec-core
rspec/rspec-expectations
rspec/rspec-mocks
rspec/rspec-rails
rspec/rspec-support

Home page with all the repos is here:
https://msp-greg.github.io/

**Comment by JonRowe** [comment]
An interesting project! Thanks for highlighting, how are you combining our docs?

**Comment by MSP-Greg** [comment]
It needs all the repos in a defined structure, and I've got all of them locally.  The equivalent section of the `.yardopts' file is:

```
rspec/lib/**/*.rb
rspec-core/lib/**/*.rb
rspec-expectations/lib/**/*.rb
rspec-mocks/lib/**/*.rb
rspec-rails/lib/**/*.rb
rspec-support/lib/**/*.rb
-
rspec/README.md
rspec-*/README.md
rspec-*/Changelog.md
rspec-core/Filtering.md
rspec-expectations/Should.md
```

The project started as a 'I just want to review code/docs on my tablet' issue, and then continued.  Adding reasonable Ruby parsing was a large addition, followed by Rails DSL stuff...

A long time ago I had Rspec docs in separate folders locally, and it drove me nuts.  YMMV

**Comment by JonRowe** [comment]
Interesting, I wonder if its worth combining them on our official docs over on `rspec.info`
