### ISSUE TITLE
Switch to new issue templates.

### ISSUE THREAD

**Issue by JonRowe** [rspec/rspec-rails#2136]
Rather than using the old issue template markdown template, we should setup a couple using the new format Github have setup, maybe one for bugs and one for feature requests?

https://help.github.com/en/articles/about-issue-and-pull-request-templates#issue-templates

**Comment by benoittgt** [comment]
I think this is a good idea!

**Comment by mbirman** [comment]
Perhaps the issue can be closed? The PR pretty much nailed it.
