### ISSUE TITLE
invalid option: --format

### ISSUE THREAD

**Issue by coding-bunny** [rspec/rspec-rails#2137]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.3.0
Rails version: 5.0.7.2
RSpec version: 3.8.0

## Observed behaviour

We are using CircleCI, and running the tests in parallel using their workers.
As soon as we add the `--format` option to our `bundle exec` command, the tests pass, but RSpec keeps exiting with error code 1 and complains about the invalid option.

Running `bundle exec rspec` without options works just fine.

## Expected behaviour

I expect the arguments to work

## Can you provide an example app?
I can't at the moment, but I noticed something else:

* Manually adding a step to uninstall the test-unit gem solves the --format issue
* However then I get `invalid option: --require`

It seems that not a single argument is accepted by RSpec in our situation.
`minitest` and `unit-test` are both installed on the system, and are dependencies of gems we use.

This is the full command we are using:
```
bundle exec rspec --require rspec_junit_formatter --format RspecJunitFormatter --out ./tmp/test-results/rspec/results.xml --format progress $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
```

And to demonstrate that the specs actually work:
```
Warning: NLS_LANG is not set. fallback to US7ASCII.
WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.
WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.
Run options:
  include {:focus=>true}
  exclude {:broken=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 25995
....................................

Finished in 7 minutes 45 seconds (files took 9.3 seconds to load)
36 examples, 0 failures

Randomized with seed 25995


invalid option: --require

minitest options:
    -h, --help                       Display this help.
        --no-plugins                 Bypass minitest plugin auto-loading (or set $MT_NO_PLUGINS).
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /regexp/ or string.
    -e, --exclude PATTERN            Exclude /regexp/ or string from run.

Known extensions: rails, pride
    -b, --backtrace                  Show the complete backtrace
    -d, --defer-output               Output test failures and errors after the test run
    -f, --fail-fast                  Abort test run on first failure or error
    -c, --[no-]color                 Enable color in the output
    -p, --pride                      Pride. Show your testing pride!
Coverage report generated for RSpec to /home/circleci/mms/coverage. 1310 / 6122 LOC (21.4%) covered.
Exited with code 1
```

**Comment by JonRowe** [comment]
:wave: Hi, you have mini test activated somewhere in your stack, as evidenced by:

```
minitest options:
```

As minitest doesn't have a format option it is exiting with 1 for you. This is out of RSpecs hands, so you need to find where it's being activated from and remove the require. I suggest searching for "minitest" in your codebase, and failing that, removing requires one by one from your test setup until you find the culprit inclusion path.

**Comment by coding-bunny** [comment]
Will try and see if I can find anything.
My guess it's going to be in one of our custom gems most probably.
Thanks for pointing me in the right direction!

**Comment by JonRowe** [comment]
Please note it's ok (and somewhat expected) that minitest is installed, what matters is that somewhere you, or a dependency, are requiring it as a runnable item. I think this will take the form of `minitest/autorun` but I'm sure there are other invocation paths.

**Comment by coding-bunny** [comment]
yeah I found it, there was a `require rails/test_help` in the spec,
removing that resolved it
