### ISSUE TITLE
Consider removing rubocop in favour of standardrb (and eventually rubyformat)

### ISSUE THREAD

**Issue by penelopezone** [rspec/rspec-rails#2139]
Hi Y'all,

Of late I've found that rubocop's rules are very unstable for us in particular, it looks like Rubocop routinely breaks our build because we don't have it pinned to an exact version, and they make "breaking changes" between, minors.

I'd like to propose we move to [standardrb](https://github.com/testdouble/standard) which promises to be more stable (also I am collaborating on it with searls). And eventually move to rubyformat (which promises to be extremely semver stable.

Thoughts on the back of a comment :)

**Comment by JonRowe** [comment]
Standardrb isn't configurable and our rubocop config differs from it, we defined our rubocop format to meet our conventions so I'm a no vote on changing for change sake.

**Comment by benoittgt** [comment]
What about pining Rubocop version?

**Comment by pirj** [comment]
We get 2325 offences with `standardrb` and 602 with `rubocop` with our configuration.

RuboCop [is going to become stable once it hits 1.0](https://github.com/rubocop-hq/rubocop/pull/7184#issuecomment-506492606), chances are this will happen soon.

**Comment by JonRowe** [comment]
Yeah I'm going to close for now.
