### ISSUE TITLE
Rails 3.2.22.1 controller tests call application controller method multiple times

### ISSUE THREAD

**Issue by programatologist** [rspec/rspec-rails#2142]
Ruby version: ruby-2.3.7
Rails version: 3.2.22.1
RSpec version: 308

running a controller spec calls the application controller method multiple times.
I have a methods 

```
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def self.something_to_do_for(role)
    puts "I am doing something specific for #{role}"
  end
end
```
```
 # app/controllers/staff_controller.rb
class StaffController < ApplicationController
  something_to_do_for :staff
end

```
```
# app/controllers/admin_controller.rb
class AdminController < ApplicationController
  something_to_do_for :admin
end

```

```
# spec/controllers/staff_controller_spec.rb
require 'rails_helper'

RSpec.describe StaffController, :type => :controller do

end

```

When I run

`rspec spec/controllers/staff_controller_spec.rb`

I get the result

```
I am doing something specific for admin
I am doing something specific for staff
No examples found
Finished in 0.00387 seconds (files took 0.728 seconds to load)
0 examples, 0 failures
```

The application controller method is called two times, each for one controller(expected to call once)

I have added the application here:
https://github.com/programatologist/rspec-testing

My real app in tests have much more complicated logic than this, I have added lighter version of the application to point out the specific issue

**Comment by JonRowe** [comment]
:wave: RSpec isn't doing anything here, its the code loading, if you run `rails console` with your example the same output will be produced. Class level methods used like that are invoked on loading a file.
