### ISSUE TITLE
rails g rspec:install failed to run with bundler 2

### ISSUE THREAD

**Issue by syafiqfaiz** [rspec/rspec-rails#2144]
Ruby version: ruby 2.5.0p0
Rails version: Rails 5.1.4
RSpec version: RSpec 3.8
                            - rspec-core 3.8.2
                            - rspec-expectations 3.8.4
                            - rspec-mocks 3.8.1
                            - rspec-rails 3.8.2
                            - rspec-support 3.8.2
Bundler version: 2.0.2

## Observed behaviour

I wanted to start testing on an existing application, when running the generator
`rails g rspec:install`, it return  `You must use Bundler 2 or greater with this lockfile.`

As a workaround, I have to downgrade bundler to version 1.17.3. 

## Expected behaviour
I was expecting rspec to generate all the files needed for rspec

**Comment by JonRowe** [comment]
:wave: `rails` is a command belonging to rails, the warning message you describe is from bundler. Neither of these are RSpecs responsibility. I suggest you open an issue with one of those projects.
