### ISSUE TITLE
JRuby tests fail because some --add-opens are missing

### ISSUE THREAD

**Issue by olleolleolle** [rspec/rspec-rails#2147]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: JRuby (head, for example)
Rails version: 6-0-stable
RSpec version: master

## Observed behaviour

Travis JRuby tests fail because some `--add-opens` are missing.

<details>

```
2019-06-18T14:50:01.909Z [main] WARN FilenoUtil : Native subprocess control requires open access to sun.nio.ch
Pass '--add-opens java.base/sun.nio.ch=org.jruby.dist' or '=org.jruby.core' to enable.
binstub
0.00sChecking required binstubs
/home/travis/build/rspec/rspec-rails/bin/rspec
2019-06-18T14:50:04.640Z [main] WARN FilenoUtil : Native subprocess control requires open access to sun.nio.ch
Pass '--add-opens java.base/sun.nio.ch=org.jruby.dist' or '=org.jruby.core' to enable.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.ext.openssl.SecurityHelper (file:/home/travis/.rvm/rubies/jruby-head/lib/ruby/gems/shared/gems/jruby-openssl-0.10.2-java/lib/jopenssl.jar) to constructor java.security.cert.CertificateFactory(java.security.cert.CertificateFactorySpi,java.security.Provider,java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.jruby.ext.openssl.SecurityHelper
```

<summary>Output in test, which disturbs some output tests</summary>

</details>

## Expected behaviour

Tests should pass, JRuby ought to be configured.

## Can you provide an example app?

Here is a link to a failing build: https://travis-ci.org/rspec/rspec-rails/jobs/547274050/

**Comment by JonRowe** [comment]
JRuby is flakey as all hell atm due to Travis issues...

**Comment by olleolleolle** [comment]
@JonRowe Ah, right, that might prove difficult to try out, successfully, then.

**Comment by olleolleolle** [comment]
Heey, it ran, without a single warning on --add-opens. I will add this chunk to the other JRuby, too.

**Comment by pirj** [comment]
@olleolleolle Is there anything left that needs to be done in the scope of this ticket?

**Comment by JonRowe** [comment]
I don't think there is, closing but if there is please re open :)
