### ISSUE TITLE
 `EmptyTemplateHandler::call` wrong number of arguments (2 for 1)

### ISSUE THREAD

**Issue by feixionglee** [rspec/rspec-rails#2161]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
Rails version: 6.0.0
RSpec version: 3.8
  - rspec-core 3.8.2
  - rspec-expectations 3.8.4
  - rspec-mocks 3.8.1
  - rspec-rails 3.8.2
  - rspec-support 3.8.2

## Observed behaviour

```
ActionView::Template::Error:
       wrong number of arguments (given 2, expected 1)
# ~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-rails-3.8.2/lib/rspec/rails/view_rendering.rb:105:in `call'
```

## Expected behaviour

The specs should all pass, (all pass with rails 5.2.3)

## Investigation

It failed on this method `EmptyTemplateHandler::call`
https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/view_rendering.rb#L105
```
class EmptyTemplateHandler
    def self.call(_template)
        ::Rails.logger.info("  Template rendering was prevented by rspec-rails. Use `render_views` to verify rendered view contents if necessary.")

        %("")
    end
end
```

There are arguments changes from rails
https://github.com/rails/rails/commit/28f88e0074f473f58c2d3fd54cb3daff81027c12#diff-562906215bf781788ec5aaf37e958cb8L307

```
-  code = @handler.call(LegacyTemplate.new(self, source)) 
+  code = @handler.call(self, source)
```

**Comment by JonRowe** [comment]
:wave: I this is fixed on the `4-0-dev` branch and released in the beta. See #2089
