### ISSUE TITLE
Resetting request cookie during a test does not persist

### ISSUE THREAD

**Issue by Rheisen** [rspec/rspec-rails#2167]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.6.3
Rails version: 6 rc2
RSpec version: 3.8.2

## Observed behaviour

https://stackoverflow.com/questions/57648988/ror-rspec-request-cookie-change-not-persisting-when-changed-in-test-case

## Expected behaviour

Setting a request cookie uses that cookie value in the next request.

## Can you provide an example app?

Not easily

**Comment by JonRowe** [comment]
There are some oddities with how cookies are set, its all controlled by rails / rack-test and not us though, I'm guessing from the closed issue you got an answer on SO?
