### ISSUE TITLE
Rails 6 Rspec throws “ActiveModel::MissingAttributeError” on Carrierwave uploader when in Concern

### ISSUE THREAD

**Issue by jathayde** [rspec/rspec-rails#2168]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.6.3
Rails version: 6.0.0
RSpec version: 3.8.0
RspecRails 4.0.0.beta2

## Observed behaviour

Upon running `rspec` the factory fails:
```
Failure/Error: let(:lodge) { FactoryBot.create(:lodge) }

     ActiveModel::MissingAttributeError:
       can't write unknown attribute `checklist`
```

## Expected behaviour

The factory should be valid (it is in Rails 5.2.x).

The failure is caused by a carrierwave mounter being called in the `included` block in a concern. If the mounter is called in the `lodge.rb` file alone, it works as expected.

## Can you provide an example app?

I can add someone to the private repo.

**Comment by benoittgt** [comment]
Hello @jathayde 

Thanks for the issue. Could you provide a fresh rails app with a reproducing issue. This will help us to identify the problem.

Thanks

**Comment by JonRowe** [comment]
@jathayde this seems like a factory bot issue...

**Comment by jathayde** [comment]
Thanks, Jon. Do you want me to file it on the FactoryBot issues instead? If not I can work this week/end on replicating in a new minimal app.

**Comment by JonRowe** [comment]
I suggest you do!

**Comment by JonRowe** [comment]
Closing for now, feel free to reopen if theres something we can help with
