### ISSUE TITLE
Request: Close finished GitHub Issues Milestones

### ISSUE THREAD

**Issue by olleolleolle** [rspec/rspec-rails#2179]
**Problem description**:

Noting a few Open milestones here, with 0 outstanding issues, I request they be closed:

https://github.com/rspec/rspec-rails/milestones

When I browse the repository to know what's being worked on for the next release, Milestones can help with knowing how much is remaining.

**Comment by pirj** [comment]
Thanks for bringing this up. Closed finished milestones.
