### ISSUE TITLE
Version 3.8.3?

### ISSUE THREAD

**Issue by aried3r** [rspec/rspec-rails#2182]
What then became #2181 was initially meant to correct the changelog. There is no version 3.8.3 released, although a [changelog entry](https://github.com/rspec/rspec-rails/blob/master/Changelog.md#383--2019-10-03) exists. This also means that the links to the full changelog lead nowhere:

http://github.com/rspec/rspec-rails/compare/v3.8.2...v3.8.3
http://github.com/rspec/rspec-rails/compare/v3.8.3...v3.9.0

Will there be a 3.8.3 or should this be merged into 3.9.0?

**Comment by JonRowe** [comment]
:wave: There is a 3.8.3, it exists as a tag and on `3-8-maintenance` but somehow it didn't get pushed to rubygems, fixed.
