### ISSUE TITLE
Testing Mounted Engine request.path_info Improperly Set

### ISSUE THREAD

**Issue by jonmchan** [rspec/rspec-rails#2197]
Ruby version: ruby 2.6.3p62
Rails version: rails 5.2.3
RSpec version: RSpec 3.9

## Observed behaviour

When testing mounted engines in an application:

application's config/routes.rb:
```
Rails.application.routes.draw do
  mount PseudoKiosk::Engine => "/test"
end
```

engine's config/routes.rb:
```
PseudoKiosk::Engine.routes.draw do
  namespace :pseudo_kiosk do
    get 'authentication/unlock'
  end
end
```

I am creating controller and request specs:

```
# this is a controller inside the engine
RSpec.describe PseudoKiosk::AuthenticationController, type: :controller do
  routes { PseudoKiosk::Engine.routes } 

  describe "GET #unlock" do
    it "returns http success" do
      get :unlock, params: {}
      expect(response).to have_http_status(:success)
    end
  end
end
```

In the app, when I check for `request.path_info`, I get: `/pseudo_kiosk/authentication/unlock`.

## Expected behaviour

I expect to be getting the engine properly namespaced through the mount syntax, but I am not receiving the expected `/test/pseudo_kiosk/authentication/unlock` for the `request.path_info` within the controller.

## Can you provide an example app?

https://github.com/jonmchan/pseudo_kiosk/blob/8600321a702c9c6b0d418f04064099cc5e29bc72/spec/controllers/pseudo_kiosk/authentication_controller_spec.rb

You can utilize the pry breakpoint at https://github.com/jonmchan/pseudo_kiosk/blob/8600321a702c9c6b0d418f04064099cc5e29bc72/lib/pseudo_kiosk/controller.rb#L18 and inspect the `request.path_info` to view the issue.

As a current workaround, I am `mount PseudoKiosk::Engine => "/"` to get around the issue and make my tests pass.

**Comment by JonRowe** [comment]
I think you'll find your issue is this:

`routes { PseudoKiosk::Engine.routes }`

If your engine is installed in your app, your apps routes will contain the engines routes, and thus you don't need to override them.

**Comment by jonmchan** [comment]
@JonRowe Thanks for your reply. I had to add that line in because it couldn't find the routes when I ran the test without it:

```
ActionController::UrlGenerationError:
       No route matches {:action=>"process_submit", :controller=>"pseudo_kiosk/authentication", :passcode=>"swordfish"}
```

However, my `bin/rails app:routes` show:

```
$ bin/rails app:routes
                                          Prefix Verb URI Pattern                                                                              Controller#Action
...
                             pseudo_kiosk_engine      /                                                                                        PseudoKiosk::Engine
...

Routes for PseudoKiosk::Engine:
        pseudo_kiosk_authentication_unlock GET  /authentication/unlock(.:format)         pseudo_kiosk/authentication#unlock
pseudo_kiosk_authentication_process_submit POST /authentication/process_submit(.:format) pseudo_kiosk/authentication#process_submit
```

**Comment by JonRowe** [comment]
Basically when you override the routes, you need to use the sub route to get it to match, if you don't, you need to provide the context in which it is mounted to get it to match. I'm not sure how rails expects you to provide the later, but I suggest you use the former and not worry about what the path shows in the tests (which are now independant of where they are mounted).

If you truely need integrations tests for your engine within your app, then remove the route override, and use `get "/path/to/controller"` rather than trying to autogenerate.

**Comment by jonmchan** [comment]
@JonRowe the issue I am having is the engine I am creating is a security gem which checks endpoints against a whitelist. Somehow, the code in working within the engine to generate the whitelist using the proper named routes ( `PseudoKiosk::Engine.routes.url_helpers.pseudo_kiosk_authentication_unlock_path` generates  `/pseudo_kiosk/authentication/unlock` ), however the `request.path_info` populated by rspec is (/authentication/unlock). My gem sees that as an endpoint not in the whitelist and blocks that route.

I am not trying to test the engine in an app, I solely am trying to use a dummy app within the spec folder mount the engine and properly test the engine.

**Comment by jonmchan** [comment]
Trying to manually specify the route still won't work:

```
Failure/Error: get '/pseudo_kiosk/authentication/unlock'
     
     ActionController::UrlGenerationError:
       No route matches {:action=>"/pseudo_kiosk/authentication/unlock", :controller=>"pseudo_kiosk/authentication"}
```

**Comment by JonRowe** [comment]
Ah that might only be available in a proper integration / request spec rather than a controller spec. Controller tests are soft-deprecated by the Rails team and this is one of the reasons why.

**Comment by jonmchan** [comment]
@JonRowe that's important to note... if I was to convert all these tests to request specs, the issue I was running is I don't have direct access to the session. Is there a recommended workaround for that or am I to be making getter and setter endpoints to read and write to the session variables I need? Seems sorta clunky, especially since I would have to make sure everything can be serialized/deserialized properly.

Thanks for your input - I appreciate it.

**Comment by JonRowe** [comment]
If you're happy with controller tests I suggest going back to your original configuration and accepting that the path will be the subpath and not the full path. Engines shouldn't depend on their mount points anyway?

**Comment by JonRowe** [comment]
Closing because this is a "configuring Rails" issue we're not able to do much about, happy to get providing help here.

**Comment by jonmchan** [comment]
>>> accepting that the path will be the subpath and not the full path

That's hard for me to do because it fails in checking if the endpoint is on the whitelist.

See:
https://github.com/jonmchan/pseudo_kiosk/blob/3b01585027cb7a01c6ed06fd84e61fede7dc42ee/lib/pseudo_kiosk/controller.rb#L24-L35

The engine generated urls does not match the path_info from the request.

The workaround I have achieved is setting the engine mount point to be / so subpath and full path are equal. 

I opened an issue here because I feel this issue makes controller testing engine mounted controllers impossible if the mounted controller does any calculations with the pathinfo. It sounds like this can't be fixed directly in rspec-rails but has to addressed by the underlying rails controller. Since controller testing is soft-deprecated, I'll just leave all this information here in case someone else runs into this issue.

**Comment by JonRowe** [comment]
I think you have overlooked something here, its possible to mount an engine multiple times at different endpoints, so you need to account for that which would also fix this for you. I'm not sure you should be trying to introspect the path in this fashion, if you are trying to secure various controller/action combos you are better off using those parts rather than the string url. Just my 2¢.

**Comment by jonmchan** [comment]
Good point, I'll secure these engine endpoints by controller and action. Thanks!
