### ISSUE TITLE
Order for helpers

### ISSUE THREAD

**Issue by jonmchan** [rspec/rspec-rails#2204]
I believe it is suboptimal/confusing for `.rspec` to by default be defined as `--require spec_helper`. This is especially confusing because all the spec files by default are set to `require 'rails_helper'` and not `require 'spec_helper'`. I understand this is because it inherits from rspec-core, but I feel that behavior is confusing.

To the average developer, they would believe that `rspec_helper` is loaded before `spec_helper` and that everything in spec_helper should read from `rspec_helper` because the only require they see is in their files. This is not the case. `spec_helper` actually is loaded first before `rspec_helper` because rspec loads the `--require spec_helper` file first.

This leads to all sort of issues when trying to set flags in `rails_helper.rb` or expecting for dependencies to be loaded in `rails_helper` before `spec_helper.rb` is loaded and being puzzled when trying to trace your code and thinking the order that it runs is `my_spec.rb` => `require 'rails_helper'` => `require 'spec_helper'` when in fact it is `require 'spec_helper'`, then `my_spec.rb` => `require 'rails_helper'` => `require 'spec_helper'`.

I propose to make the default generator for .rspec to be just `--require rails_helper` to be consistent with the require in all the spec files.

**Comment by pirj** [comment]
Just to make things clear, you refer to `rspec_helper`, do you mean `rails_helper`?

Can you please elaborate on where this confusion may come from?
In [`rails_helper` template](https://github.com/rspec/rspec-rails/blob/master/lib/generators/rspec/install/templates/spec/rails_helper.rb#L2) `spec_helper` is explicitly required. So, when the spec file is loaded, it doesn't really matter if it explicitly requires `rails_helper`, or if `.rspec` specifies to `--require rails_helper`, `spec_helper` is evaluated first.

It wouldn't be efficient in some cases to always load `rails_helper`, since a Rails project may have specs for locally-defined RuboCop cops, or RSpec matchers, or any arbitrary code that doesn't need/depend on Rails, and that would significantly impact spec loading time.

**Comment by JonRowe** [comment]
👋 so this is done for another good reason, `spec_helper.rb` does not load rails. Thus any specs not running rails, e.g. plain ruby specs can run  quickly without the large boot time penalty of rails. Of course any specs touching rails code need rails, so they load `rails_helper.rb`. This shortens the feedback cycle drastically when working on PORO specs, whilst still allowing integration testing with Rails in full suite tuns.

**Comment by jonmchan** [comment]
> Just to make things clear, you refer to rspec_helper, do you mean rails_helper? 

How embarrassing, don't know how I started typing that! Yes, I mean `rails_helper`.

@JonRowe 

> wave so this is done for another good reason, spec_helper.rb does not load rails. Thus any specs not running rails, e.g. plain ruby specs can run quickly without the large boot time penalty of rails. Of course any specs touching rails code need rails, so they load rails_helper.rb. This shortens the feedback cycle drastically when working on PORO specs, whilst still allowing integration testing with Rails in full suite tuns.

That makes perfect sense. Is this documented anywhere? I see the error in my code is that I'm including stuff that loads rails in `spec_helper` when they only should be in `rails_helper`, such as:

```
  config.include ::PseudoKiosk::TestHelpers::Internal
  config.include ::PseudoKiosk::TestHelpers::Internal::Rails
```
https://github.com/jonmchan/pseudo_kiosk/blob/master/spec/spec_helper.rb#L50

That should goes in `rails_helper`, correct?

**Comment by pirj** [comment]
You are welcome!

I highly encourage you to send a doc update to clarify this in the README.
It's briefly mentioned [here](https://relishapp.com/rspec/rspec-rails/v/3-9/docs/directory-structure), but oddly enough `require 'spec_helper'` line is present; also [here](https://relishapp.com/rspec/rspec-rails/v/3-9/docs/upgrade).
This distinction should be on the forefront.

**Comment by JonRowe** [comment]
> That makes perfect sense. Is this documented anywhere? 

As @pirj mentions it is in the relish docs for upgrading, but not for installing / getting started, nor in the helpers themselves if you fancy a quick PR to rectify that? 

> I see the error in my code is that I'm including stuff that loads rails in spec_helper when they only should be in rails_helper, such as: <snip> That should goes in rails_helper, correct?

Yep

> It'd be great to advise caution for including any code in spec_helper that is rails related.

I would happily welcome a PR to add a warning to the generated spec_helper to that effect (when generated by rspec-rails).
