### ISSUE TITLE
approximate at for activejob

### ISSUE THREAD

**Issue by mkamensky** [rspec/rspec-rails#2205]
I queue an email to be sent 24 hours after a certain controller action. When I try to test it, I currently have

```
expect { commit }.to have_enqueued_mail(...).at(Time.now + 24.hours)
```
The problem is that `Time.now + 24.hours` is not precisely equal to what it was during `commit`, when the job was created, so the test fails.

What I would hope to have is something like
```
expect { commit }.to have_enqueued_mail(...).approx_at(Time.now + 24.hours, err)
```
which passes if the given time is within `err` from the job time (perhaps with some default value for `err`).

As a more general alternative, it would perhaps be useful if one could easily override the class used by the matchers, say by a derived class, and then I could implement it myself (but I think the feature I suggest could be useful in general)

**Comment by mkamensky** [comment]
PS., not really related, but the page that seems to be the [official docs](https://relishapp.com/rspec/rspec-rails/v/3-9/docs/matchers) does not mention `have_enqueued_mail` at all, and the links to the activejob matchers on the [jobs spec](https://relishapp.com/rspec/rspec-rails/v/3-9/docs/job-specs/job-spec) page seem to be broken

**Comment by mkamensky** [comment]
I now have the following in `rails_helper.rb`:

```ruby
module RSpec
  module Rails
    module Matchers
      class HaveEnqueuedMailApproximately < HaveEnqueuedMail
        def approx_at(tim, err = 1.minute)
          @approx_at = tim
          @approx_err = err
          self
        end

        def approx_at?(job)
          @approx_at.nil? || (job[:at] - @approx_at.to_f).abs < @approx_err
        end

        def other_attributes_match?(job)
          approx_at?(job) && super
        end

        def base_message
          res = super
          res.gsub!(' but enqueued', " approx. at #{@approx_at.inspect} (with error #{@approx_err.inspect}), but enqueued") if @approx_at.present?
          res
        end

      end

      def have_enqueued_mail(mailer_class = nil, mail_method_name = nil)
        HaveEnqueuedMailApproximately.new(mailer_class, mail_method_name)
      end
    end
  end
end
```

**Comment by pirj** [comment]
Wondering if the following works:
```ruby
expect { commit }.to have_enqueued_mail(...).at(a_value_within(1.minute).from(24.hours.from_now))
```

Another option would be to use https://api.rubyonrails.org/classes/ActiveSupport/Testing/TimeHelpers.html#method-i-freeze_time

**Comment by mkamensky** [comment]
> Wondering if the following works:
> 
> ```ruby
> expect { commit }.to have_enqueued_mail(...).at(a_value_within(1.minute).from(24.hours.from_now))
> ```

Doesn't work directly, since the serialization calls `to_f` on the argument of `at`, but this is a much better solution, thanks! I will try to change the `active_job` matcher to skip the `to_f` if it can't be applied.

(also, `from` should be replaced with `of` above)

**Comment by mkamensky** [comment]
Ok, I changed https://github.com/rspec/rspec-rails/blob/e50def6ad42a5d5a648d1ee7854966407bb6f4c4/lib/rspec/rails/matchers/active_job.rb#L163 to
```ruby
         @at == :no_wait ? nil : @at.try(:to_f) || @at
```
(possibly this should be replaced by something more sophisticated, since one might wish to keep `@at` even when it does respond to `to_f`) but also had to change https://github.com/rspec/rspec-rails/blob/e50def6ad42a5d5a648d1ee7854966407bb6f4c4/lib/rspec/rails/matchers/active_job.rb#L152 to
```ruby
         serialized_attributes.all? { |key, value| Support::FuzzyMatcher.values_match?(value, job[key]) }
```

With these, the slightly modified version
```ruby
expect { commit }.to have_enqueued_mail(...).at(a_value_within(1.minute).of(24.hours.from_now.to_f))
```

Slightly annoying that the `to_f` is required there, but it's a minor nuisance. From my point of view, this is the preferred way, thanks!

**Comment by JonRowe** [comment]
@pirj's solution is one I would expect to work and would recommend, if it doesn't lets fix it!

**Comment by pirj** [comment]
@mkamensky Broken matcher link in the docs can be fixed in `features/job_specs/job_spec.feature` like this:
```ruby
-  [`have_been_enqueued`](matchers/have-been-enqueued-matcher) and
-  [`have_enqueued_job`](matchers/have-enqueued-job-matcher) for more
+  [`have_been_enqueued`](../matchers/have-been-enqueued-matcher) and
+  [`have_enqueued_job`](../matchers/have-enqueued-job-matcher) for more
```

Not exactly sure, but I suggest it is both applied to `3.9-maintenance` and `master`.

**Comment by mkamensky** [comment]
Thanks! Will try to do both in a few days

**Comment by pirj** [comment]
@mkamensky A friendly reminder about doc update pull request.

**Comment by mkamensky** [comment]
> @mkamensky A friendly reminder about doc update pull request.

Just did, not sure if there is any tests or anything beyond just fixing the links. Thanks.
