### ISSUE TITLE
Wrong rspec libraries for beta versions

### ISSUE THREAD

**Issue by wacko** [rspec/rspec-rails#2209]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.6.5
Rails version: 6.0.1
RSpec version: 3.9.0 & 4.0.0.beta3

## Observed behaviour

Looking at Rubygems, rspec-rails 3.9.0 depends on rspec-core ~> 3.9.0
But rspec-rails 4.0.0.beta3 depends on rspec-core ~> 3.8
(Idem for rspec-expectations, rspec-mocks, rspec-support)

https://rubygems.org/gems/rspec-rails/versions/3.9.0
https://rubygems.org/gems/rspec-rails/versions/4.0.0.beta3

## Expected behaviour

I expect rspec-rails 4.0.0 (beta) to depend on rspec-core ~> 3.9.0

**Comment by JonRowe** [comment]
:wave: Hello, thanks for taking the time to start this discussion, prior to `rspec-rails` 4,`rspec-rails` was pinned to the same version of the core RSpec gems, so 3.8 depended on 3.8, 3.9 depends on 39.9 etc etc. However `rspec-rails` 4 is now not locked to the core gems, so actually it makes sense for it to depend on the minimum supported version, which is 3.8 given thats what it was developed against. 

Come the release of RSpec core 4 we will have to add additional tests and checks to make sure it supports that version, at which point it will become > 3.8 etc.
