### ISSUE TITLE
Unable to install rspec-rails using README.md instructions

### ISSUE THREAD

**Issue by JoeNyland** [rspec/rspec-rails#2218]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]`
Rails version: `Rails 5.2.3`
RSpec version: `RSpec 3.9`

## Observed behaviour

* As per the [README.md](https://github.com/rspec/rspec-rails/blame/d0f81dfccf92df655caeacfd1ce0ba1808779f99/README.md#L31) I made this change:

```diff
diff --git a/Gemfile b/Gemfile
index 0fc37a4..4e8b9d3 100644
--- a/Gemfile
+++ b/Gemfile
@@ -39,6 +39,7 @@ group :development, :test do
   gem 'byebug'
   # Use sqlite3 as the database for Active Record
   gem 'sqlite3', '~> 1.3.6'
+  gem 'rspec-rails', '~> 4.0'
 end
 
 group :test do
```

* Then install:

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'rspec-rails (~> 4.0)' in any of the gem sources listed in your Gemfile.
```

## Expected behaviour

* `rspec-rails` installs without errors

## Can you provide an example app?

* N/A as this is easily reproduced in any repo

## My research into the issue

Currently, 3.9.0 seems to be the latest available non-prerelease version released:

```
$ gem search -qre --no-prerelease rspec-rails
rspec-rails (3.9.0)
```

The [pessimistic version constraint](https://guides.rubygems.org/patterns/#pessimistic-version-constraint) won't include prerelease versions of gems, so Bundler is unable to find a version of the gem that matches the version constraint that we're advising users to use in the README.

Assuming that we don't want users to install prerelease versions by default, I think the [README has been updated a bit too soon](https://github.com/rspec/rspec-rails/commit/a76a34637efd3a605c85d470978790e1046baaa7), and until 4.0 is released, the README should instruct users to add `gem 'rspec-rails', '~> 3.9'` to their Gemfiles.

I'm happy to patch this in a PR, if desired 🙂

**Comment by JonRowe** [comment]
:wave: `README.MD` is for the 4.0.0 series / master branch, it is installable as `4.0.0.beta3` although we are hoping to have the final release out soon. The 3.9 branch refers to 3.9 etc in the readme, and if you look on Rubygems you'd get the right readme.
