### ISSUE TITLE
DEPRECATION WARNING: Initialization autoloaded the constant

### ISSUE THREAD

**Issue by damienlethiec** [rspec/rspec-rails#2219]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.6.5
Rails version: 6.0.0
RSpec version: 3.9.0

## Observed behaviour

When I run my test, I got a deprecation warning:
```
DEPRECATION WARNING: Initialization autoloaded the constant Shop.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Shop, for example,
the expected changes won't be reflected in that stale Class object.

This autoloaded constant has been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from block in <main> at /Users/damienlethiec/code/damienlethiec/ProjetsPros/AventureBio/Consulting/Ensovo/ensapp/config/environment.rb:8)
```

Line 8 in my environment.rb is `Rails.application.initialize!`

## Expected behaviour

No deprecation warning !

Thanks so much in advance,
Damien

**Comment by JonRowe** [comment]
This is a problem within your codebase:

> DEPRECATION WARNING: Initialization autoloaded the constant Shop.

This means that somewhere in your boot process you are referencing `Shop` without a require for it first. This process uses code in `config` and `config/initializers`, which is where you will likely find the suspect code.

**Comment by damienlethiec** [comment]
Thanks ! I tried to look for it but cannot fin any reference... I will try more

**Comment by damienlethiec** [comment]
Found it ! Sorry for the issue ! It can be closed ! Thanks so much
