### ISSUE TITLE
Request spec - cannot use params and headers args at the same time

### ISSUE THREAD

**Issue by Yorkshireman** [rspec/rspec-rails#2243]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: `2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]`
Rails version: `6.0.2.rc1`
RSpec version: 
```
RSpec 3.9
  - rspec-core 3.9.0
  - rspec-expectations 3.9.0
  - rspec-mocks 3.9.0
  - rspec-rails 3.9.0
  - rspec-support 3.9.0
```

## Observed behaviour
Request spec:
```
     params = {
        wordlist_entry: {
          word: 'dog',
          description: 'A hairy animal of varying size.'
        }
      }

      headers = {
        'Authorization' => "Bearer #{token}",
        'CONTENT_TYPE' => 'application/vnd.api+json'
      }

      time_now = Time.now
      post '/wordlistentries', params: params # add `, headers: headers` here and neither the params nor the headers get through to the controller - I need both
```

## Expected behaviour
The headers and the params should appear in the controller as headers and request body respectively.

## Can you provide an example app?
https://github.com/Yorkshireman/my_wordlist_resources/blob/bbdbdc7302e864d2eba53e6343dccd3ec88e3b80/spec/requests/create_wordlist_entry_spec.rb#L31

**Comment by JonRowe** [comment]
Apologies for the confusion here, by post is not part of `rspec-rails`, its actually one of rails test methods, I suggest you raise this with them.
