### ISSUE TITLE
Controller tests do not get session.id set correctly

### ISSUE THREAD

**Issue by ianneub** [rspec/rspec-rails#2255]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
Rails version: Rails 5.2.4.1
RSpec version: RSpec 3.9

## Observed behaviour

Rspec does not seem to be setting up controller specs with the new `Rack::Session::SessionId` class. See https://github.com/rails/rails/issues/38039 and https://github.com/rack/rack/issues/1432#issuecomment-571688819

Using my test app running the `rspec` command results in a failure of the one spec. However, this controller works fine in a web browser.

## Expected behaviour

Rspec should "set the controller up" in such a way as the `session.id` used in the controller returns a `Rack::Session::SessionId` class object or `nil` when no existing session exists.

The spec should pass and the `rspec` command should return a 0 exit code.

## Can you provide an example app?
Example app: https://github.com/ianneub/rspec-session-id-issue
Changes from default rails install: https://github.com/ianneub/rspec-session-id-issue/commit/29bfef501864d3fe14a03faa90556504f446e6ed

**Comment by JonRowe** [comment]
If you change your test to a request spec it should work, Rails deprecated controller tests (and thus specs) for this reason, they don't run the full request cycle. We don't actually "set the controller up" in `rspec-rails` we just integrate the rails testing helpers into RSpec.
