### ISSUE TITLE
cookies != response.cookies

### ISSUE THREAD

**Issue by ChrisCPO** [rspec/rspec-rails#2273]
Ruby version: 2.6.5p114
Rails version: 5.2.3
RSpec version: 3.8

When testing a controller that deletes a cookie.
The cookie is removed from the response but not the cookies object.
Is this possibly something we are doing wrong in our app?

```
pry in test after subject is called
[3] pry(#<RSpec::Matchers::DSL::Matcher>)> cookies
=> #<ActionDispatch::Cookies::CookieJar:0x00007ff11de14478
 @committed=false,
 @cookies={"foo"=>"encrypted_string"},
 @delete_cookies={},
 @request= <...omitted...>
[4] pry(#<RSpec::Matchers::DSL::Matcher>)> response.cookies
=> {"foo"=>nil}
```

## Expected behaviour

cookies == request.cookies

## Can you provide an example app?
```
class FoosController < ApplicationController
  def show
    cookies.delete(:foo)

    render plain: "foo"
  end
end

describe FooController do
  describe "#show" do
    subject { -> { get :show } }

    context "when a foo cookie is present" do
      before { cookies[:foo] = "encrypted_string" }

      it { subject.call; expect(response.cookies[:foo]).to eq(nil) } #passes
      it { subject.call; expect(cookies[:foo]).to eq(nil) }          #fails
    end
  end
end
```

**Comment by pirj** [comment]
If you set a breakpoint somewhere where `cookies` are defined, and `show-source cookies` (pry), where is it defined and how exactly?

**Comment by ChrisCPO** [comment]
ahh right
```
[1] pry(#<RSpec::ExampleGroups::QueriesController::Show::WhenTheFormatIsHtml::WhenAInboundDocumentIsPresent>)> show-source cookies

From: /Users/chrisCPO/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/testing/test_process.rb @ line 42:
Owner: ActionDispatch::TestProcess
Visibility: public
Number of lines: 3

def cookies
  @cookie_jar ||= Cookies::CookieJar.build(@request, @request.cookies)
end
```
---

This looks like I misread the rspec documentation. 
https://relishapp.com/rspec/rspec-rails/v/3-8/docs/controller-specs/cookies

**Comment by pirj** [comment]
The documentation for 3.8/3.9 looks outdated, and the whole section has disappeared from `master`.
Are you up to send a pull request to bring back the following section to `features/controller_specs/cookies.feature`?
```
### Recommended guidelines

  * Access cookies through the `request` and `response` objects in the spec.
    * Use `request.cookies` before the action to set up state.
    * Use `response.cookies` after the action to specify outcomes.
  * Use the `cookies` object in the controller action.
```

**Comment by JonRowe** [comment]
:wave: As the documentation points out `cookies` is a Rails method, rails deprecated controller tests in version 5 in favour of request tests, thus the same applies to specs.

I believe `cookies` refers to the request cookies which are not automatically changed on a response until the next request, you can try `response.cookies` but either way this behaviour is dictated by Rails so check their docs.

As`rspec-rails` is a thin wrapper around standard rails behaviour (to the point where there isn't even a mention of `cookies` in our `lib` folder) we don't control this behaviour, but if you can think of a way to improve the docs you are welcome to open a PR.
