### ISSUE TITLE
Custom ActionMailer delivery method changed by Mailer specs

### ISSUE THREAD

**Issue by travisp** [rspec/rspec-rails#2274]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.0
Rails version: 6.1.0alpha
RSpec version: 3.9.0
rspec-rails version: 4.0.0.beta4

## Observed behaviour

Set a different delivery method in `config/environments/test.rb` such as `:custom_test`

I use a custom delivery method that better mimics the delivery method used in my production environment (sendgrid-actionmailer) where no SMTP To address is required (the default test delivery method requires one) and can instead be provided in an alternate way.

When using a mailer spec, rspec-rails changes the delivery method back to :test

Suprisingly, even setting a global
```ruby
  config.before(:each) do
    ActionMailer::Base.delivery_method = :custom_test
  end
```
does not work, only if the before block is provided in the individual Mailer spec itself

## Expected behaviour

rspec-rails maintains the delivery method set in test environment configuration. It does do this for system tests, but not mailer tests for some reason

## Can you provide an example app?

https://github.com/travisp/sample-rspec-mailer-app

There are two specs that will be run by `bundle exec rspec`, a system test and a mailer test. The system test maintains the `:custom_test` delivery method set in the rails test environment configuration, while the mailer test does not.

**Comment by pirj** [comment]
> rspec-rails changes the delivery method back to :test

Have you had a chance to pinpoint that to a specific line of code?

**Comment by JonRowe** [comment]
:wave: This is a Rails issue, we don't call this method anywhere, `rspec-rails` is a thin wrapper integrating Rails test helpers into `rspec`, as such behaviour exhibited by the Rails test helpers will be exhibited within rspec.

**Comment by travisp** [comment]
@JonRowe You're right, sorry about the wrong report.

**Comment by JonRowe** [comment]
Don't worry about it! I just don't think we can help :)
