### ISSUE TITLE
Can't override rspec generator templates in latest

### ISSUE THREAD

**Issue by jamesst20** [rspec/rspec-rails#2278]
Ruby version: 2.6.3
Rails version: 6.0
RSpec version: 4.0.0 beta4

**What I did**
I added my overriden template file in `lib/templates/rspec/scaffold/controller_spec.rb`.

**What happened**
Running the command `rails g scaffold MyModel attribute_name:string` completly ignores it and use the default generator.

**What was expected**
I expected the scaffolding to use my rspec generator

**Comment by jamesst20** [comment]
My project is using API controller, the right file name should have been api_controller_spec.rb.

Sorry !

**Comment by nicoalonsop** [comment]
I have checked and it is working for me.
