### ISSUE TITLE
Capybara spec is stuck with Ruby 2.7.0

### ISSUE THREAD

**Issue by vitalinfo** [rspec/rspec-rails#2279]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.0
Rails version: 6.0.2.1
RSpec version: 4.0.0.beta3 (doesn't work for 4.0.0.beta4 as well)

## Observed behaviour
I have a problem that rspec process is stuck when runs capybara spec with some specific case.
f.e.

```
RSpec.describe 'Test', type: :feature, js: true do
  subject { page }
  let(:teacher) { create :user }
  let(:article) { create :article }

  before { login_as(teacher, scope: :user, run_callbacks: false) }

  # pass
  context 'when visit root' do
   before do
      article.destroy
      visit root_path
   end

   it { expect(subject).to have_text('Hello user') }
  end

  # freeze
  context 'when visit root' do
   before do
      visit root_path
      article.destroy
   end

   it { expect(subject).to have_text('Hello user') }
  end
end
```

as I've found, that very important that object destroyed/created before `visit`.
It does work with Ruby 2.6.5.

**Comment by pirj** [comment]
Just a random thought - can you try against `master` `rspec-rails`, there are [115 commits](https://github.com/rspec/rspec-rails/compare/v4.0.0.beta4...master) since `4.0.0.beta4`.

**Comment by JonRowe** [comment]
You might want to take a look in your test log, this is more likely a rails issue than an rspec-rails one

**Comment by vitalinfo** [comment]
@JonRowe could be a rails problem, in logs nothing helpful, just lats command with object destroy

**Comment by vitalinfo** [comment]
@pirj thanks for advice, but result the same

**Comment by pirj** [comment]
Wondering at which stage it hangs.
Can you put breakpoints here and there to figure this out?
```ruby
# freeze
context 'when visit root' do
  it do
    visit root_path
    article.destroy
    expect(subject).to have_text('Hello user')
  end
end
```

If it hangs on `subject`, mind setting up breakpoints in your controller?

**Comment by pirj** [comment]
Ping

**Comment by vitalinfo** [comment]
@pirj sorry for delay

I've investigated a little bit and what I found:
- my case a little bit complex than I explain from the beginning 
- I have SPA and load some data on demand 
- it doesn't freeze on initial controller action
- it does freeze on processing XHR request afterwards 
- if I add any sleep (wait precessing of all requests from the page) before destroy, like
```
context 'when visit root' do
  it do
    visit root_path
    sleep 1
    article.destroy
    expect(subject).to have_text('Hello user')
  end
end
```
it does work as well

**Comment by pirj** [comment]
Freezing is still a strange problem.
What is the [default waiting time](https://rubydoc.info/github/teamcapybara/capybara/master#Asynchronous_JavaScript__Ajax_and_friends_) in your configuration?

Just to confirm that it's Capybara stuck in endless wait: if you Ctrl-C that process, does it show its backtrace?

Is "Hello user" text delivered with `root_path` load, or with an XHR request?

**Comment by vitalinfo** [comment]
`Capybara.default_max_wait_time = 10`

yes, it stuck forever, if press Ctrl-C it doesn't have any backtrace

doesn't really matter where the `Hello user` is

**Comment by pirj** [comment]
I'm afraid we've left with two options here, one is to use `sleep 1` which doesn't seem too reliable in the long run, and to debug it deeper.

Can you drop a `binding.pry` (install `pry-byebug`) breakpoint somewhere before `have_text` (without `sleep 1`), wait for a second and then Ctrl-D? Wondering if it will still hang.

If it will, change it to:
```diff
- expect(subject).to have_text('Hello user')
+ page.has_text?('Hello user) # this is the usual suspect, removing `subject` to avoid doing extra steps
```
run `step` in `pry` to dive into `page`'s `has_text?` method.
Use `step`/`next` (and `help` if you need to) to get to the point where it hangs.

Please share your results.

**Comment by JonRowe** [comment]
I mean if a sleep fixes it I'm wondering if its a deadlocking issue in a thread somewhere, if you add a timeout to the spec:
```Rspec
context 'when visit root' do
  around do |example|
    Timeout.timeout(15) do
      example.call
    end
  end

  it do
   # your spec
  end
end
```
It should stop it freezing, and the backtrace from the error should reveal where its stuck...

**Comment by pirj** [comment]
Please feel free to reopen if you are still experiencing the problem.
If you happened to solve it, please share your solution.
