### ISSUE TITLE
DEPRECATION WARNING: Initialization autoloaded the constant BadgeLabelHelper

### ISSUE THREAD

**Issue by lsarni** [rspec/rspec-rails#2284]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.0
Rails version: 6.0.2.1
RSpec version: 3.9.0

## Observed behaviour

When I run `rspec` I get this warning:

```
DEPRECATION WARNING: Initialization autoloaded the constant BadgeLabelHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload BadgeLabelHelper, for example,
the expected changes won't be reflected in that stale Module object.

This autoloaded constant has been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.

```
I saw this similar [closed issue](https://github.com/rspec/rspec-rails/issues/2219), but in this case it doesn't seem to be related to my code since I'm not using this constant `BadgeLabelHelper`

The tests run just fine.

**Comment by pirj** [comment]
Let's try to track this down. Use [this](https://gist.github.com/pirj/0604fa90fb6a21849e6d) (I hope it still works), replace `annoying` with `Initialization autoloaded the constant BadgeLabelHelper`.
In Pry's REPL that pops up see `caller` and post the backtrace here with the code from files from yoyr Rails init phase.

**Comment by JonRowe** [comment]
Its the same problem, but its likely the helper is being autoloaded as `helper :badge_label` in a controller or view etc. Debug your initialisation to find whats causing it.

**Comment by Fornacula** [comment]
There is no presence of `badge_label` nor `BadgeLabel` or `BadgeLabelHelper` in my project. Tried also the script for debugging what @JonRowe linked but couldn't get anything useful out of it unfortunatelly. I'm using `ruby 3.0.0p0` and `Rails 6.1.1`. RSpec libraries are the following:

```
rspec-core (3.10.1)
rspec-expectations (3.10.1)
rspec-mocks (3.10.2)
rspec-rails (4.0.2)
rspec-support (3.10.2)
```

Problem still up.

**Comment by JonRowe** [comment]
This is still a rails issue, we do not do any auto loading in RSpec, we just boot your Rails app. Somewhere in your application code or dependencies you are using this helper, its not a constant within RSpec. If this file is not present within your app then remove any engines and gems in use until it goes away.

**Comment by coding-bunny** [comment]
I am having the exact same error message, and nowhere in my code do I have a reference to this `BadgeHelper`.
This is on a fresh Rails project with 1 controller, and 1 model and this error still pops up when using `rspec-rails`
Does't happen for example with `minitest`

**Comment by coding-bunny** [comment]
Actually the only gem I can find that uses the `BadgeLabelHelper` seems to be `twitter-bootstrap-rails`

**Comment by paxer** [comment]
until twitter-bootstrap-rails gem will fix it - the solution could be to add `config/initializers/twitter_bootstrap_rails.rb` with

```
gem_dir = Gem::Specification.find_by_name("twitter-bootstrap-rails").gem_dir
require "#{gem_dir}/app/helpers/badge_label_helper"
```
