### ISSUE TITLE
expect to enqueue job at time fails with 4.0.0, worked with 3.9.1

### ISSUE THREAD

**Issue by doits** [rspec/rspec-rails#2299]
## What Ruby, Rails and RSpec versions are you using?

ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
Rails 6.0.2.2
RSpec 3.9
  - rspec-core 3.9.1
  - rspec-expectations 3.9.1
  - rspec-mocks 3.9.1
  - rspec-rails 4.0.0
  - rspec-support 3.9.2

## Observed behaviour

I check that a job is correctly enqueued, which comes down to something like this (simplified): 

```rb
it 'enqueues at correct time' do
  correct_time = 1.day.from_now
  mail_task = FactoryBot.create(:mail_task)
  expect { SendMailTaskJob.set(wait_until: correct_time).perform_later(mail_task) }
    .to enqueue_job.at(correct_time)
end
```

It passed with rspec-rails 3.9.1. After update to 4.0.0 it fails with this message:

```
expected to enqueue exactly 1 jobs, at Mon, 30 Mar 2020 20:43:59 CEST +02:00, but enqueued 0
Queued jobs:
SendMailTaskJob job with [#<MailTask ...>], on queue default, at 2020-03-30 20:43:59 +0200
```

The time looks right for me, or do I miss something?

## Can you provide an example app?

Edit: See https://github.com/rspec/rspec-rails/pull/2301

**Comment by doits** [comment]
I found out it does not work with `Time`. I added a failing spec to rspec-rails, see #2301. Not sure if it is something rspec-rails has to fix or the caller, but it worked before so ...

**Comment by doits** [comment]
Another observation: It seems to be some kind of precision error.

When printing out the values it tries to compare in https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/matchers/active_job.rb#L157-L163 I get:

```rb
          def at_match?(job)
            return true unless @at
            return job[:at].nil? if @at == :no_wait
            return false unless job[:at]

            pp "Comparing #{job[:at]} to expected #{@at.to_i}"

            values_match?(@at, Time.at(job[:at]))
          end

# => "Comparing 1585258594.9301639 to expected 1585258594"
```

It can be worked around by doing `values_match?(@at.to_i), Time.at(job[:at]))`, but this rather looks ugly and maybe the root cause is somewhere else?

**Comment by doits** [comment]
My last comment was totally wrong, sorry for the noise. It must be something else.

**Comment by syakovyn** [comment]
The workaround I have is to wrap `at` expectation into `Time.at`. E.g. `.at(t)` transform into `.at(Time.at(t))`.
