### ISSUE TITLE
Allow rails test to hook into bundle exec rspec

### ISSUE THREAD

**Issue by jamesla** [rspec/rspec-rails#2318]
I have had a search and this doesn't seem to be possible but it would be a great small and easy feature if it was possible to make rails test compatible with rspec. 

IE `rails test` would alias to `bundle exec rspec`

**Comment by JonRowe** [comment]
I think you'll need to open an issue with Rails to make this configurable sadly as its hard coded to Rails test_unit integration

**Comment by pirj** [comment]
Can you write a test that fails, get a full backtrace, and see if `rake` is involved anywhere, maybe you can override some Rails test task.
Anyway, this seems to be out of scope of what we want to do in `rspec-rails`.

**Comment by JonRowe** [comment]
No it's hardcoded here: https://github.com/rails/rails/blob/master/railties/lib/rails/commands/test/test_command.rb

**Comment by benoittgt** [comment]
I am tempted to make a patch for rails to be able to change that. Maybe rely on rails initialize or simply detect and prioritize the test lib you want to use? 🧐
