### ISSUE TITLE
ActionView is not listed among dependencies

### ISSUE THREAD

**Issue by voxik** [rspec/rspec-rails#2322]
It seems that rspec-rails has grown dependency on ActionView [[1]], while this dependency is not listed as a runtime dependency.

[1]: https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/view_rendering.rb#L1

**Comment by voxik** [comment]
Actually, this should be loaded transitively via ActionPack, so the issues is different. Probably #1690. Sorry for the noise :innocent:

**Comment by JonRowe** [comment]
Is this causing you a specific issue? I mean we require rails so its usually available, but we have context flagging around various features already so we're happy to accept more in a similar line if it is.
