### ISSUE TITLE
`it_behaves_like` in tagged spec do not trigger requiring support files

### ISSUE THREAD

**Issue by ToTenMilan** [rspec/rspec-rails#2326]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.4.10p364
Rails version: 5.0.7.2
RSpec version: 3.9
  - rspec-core 3.9.1
  - rspec-expectations 3.9.1
  - rspec-mocks 3.9.1
  - rspec-rails 4.0.0
  - rspec-support 3.9.2

## Observed behavior
 Given a spec that is tagged as `:articles` in order to require only specific support files,
 `it_behaves_like` is not triggering support files loading when placed as first test. This test is passing only when placed after `it` block that triggers support files loading.

## Expected behavior
 `it_behaves_like` triggers loading of support files based on spec tag

## Example
```
# spec/spec_helper.rb
config.when_first_matching_example_defined(:articles) do
  require_relative 'support/shared/articles/some_shared_spec.rb'
end
```

```
# spec/support/articles/some_shared_spec.rb
RSpec.shared_examples "some shared spec" do
  # ...
end
```

This spec:

```
# spec/models/article.rb
RSpec.describe Article, :articles do
  it_behaves_like "some shared example"
end
```

is raising error:

```
$ rspec spec/models/article.rb
ArgumentError:
  Could not find shared examples "some shared spec"
```

This spec is passing:

```
RSpec.describe Article, :articles do
  it "..." do
    # ...
  end

  it_behaves_like "some shared example"
end
```

**Comment by JonRowe** [comment]
You example has a typo, `"some shared example"` for `"some shared spec"` but I gather this is probably irrelevant, the key is in `when_first_matching_example_defined(:articles)`, if no example is defined, that hook doesn't fire, so these two examples are to be expected.
