### ISSUE TITLE
comparing TrueClass fails

### ISSUE THREAD

**Issue by antarr** [rspec/rspec-rails#2330]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.6.5
Rails version: 4.2.11.1
RSpec version: 3.9.2

## Observed behavior

Expectation is failing when comparing values. I have a spec that is failing even though the value is as expected. This only happens when the `name` param is set to `''` or` ' '`. When printing the response to the console it prints true but `expect(response).to be_truthy` fails. I've tried `expect(response).to eq(true)` as well as `expect(response).to be(true)`

## Can you provide an example app?

```ruby
'Carmen Jones', ' '].each do |name|
          it "return true for common_name: #{name}" do
            data = { subject_dn: {
              country_name: 'US',
              state_or_providence: 'CA',
              locality_name: 'Pasenda',
              organization_name: 'Random Corporation',
              organizational_unit_name: 'Information Technology Department',
              postal_code: '91001',
              street_address: '3000 Pasadena Blv',
              given_name: 'Marcus',
              sur_name: 'Meredith',
              common_name: name
            } }
            response = described_class.new(JSON.dump(data)).call
            puts "response -> #{response.class}:#{response}"
            expect(response).to be_truthy
          end
        end
```

**Comment by JonRowe** [comment]
Hopefully you figured it out but `be_truthy` generally means "not nil or false" in Ruby. So any other value will pass `be_truthy` whilst `eq(true)` means it must return true when compared using `==` etc and `be true` means it must actually be the value `true`.

Theres not enough information here to help further so hopefully you sorted it.
