### ISSUE TITLE
Add documentation for ActionMailbox

### ISSUE THREAD

**Issue by benoittgt** [rspec/rspec-rails#2341]
Hello

While working on https://github.com/rspec/rspec.github.io/pull/143 I noticed that we do not have any documentation for `action_mailbox`.

PR for `action_mailbox` on `rspec_rails` https://github.com/rspec/rspec-rails/pull/2119

I looked at a way to add it to our generated app. Is the best way to do it, to use a separate file like for https://github.com/rspec/rspec-rails/blob/master/example_app_generator/generate_action_mailer_specs.rb? (cc @JonRowe)

Any tips to do it properly welcome.

`action_mailbox` requires `active_storage`. I wrote [a minimal bug report template](https://github.com/rails/rails/pull/39367/files) to use `action_mailbox` and help me to tackle this issue on `rspec-rails`

Thanks

**Comment by JonRowe** [comment]
Seems like what you have in your bug report is similar to what we'd want in our spec generator? We typically scaffold a thing and make sure the scaffold tests work, so we'd want something similar
