### ISSUE TITLE
Is it possible to set before/after hooks per step?

### ISSUE THREAD

**Issue by mileslane** [rspec/rspec-rails#2363]
I'd like to be able to accomplish what I have in my spinach tests:
```
Spinach.hooks.before_step do
  $starting_step = Process.clock_gettime(Process::CLOCK_MONOTONIC)
end
```
```
Spinach.hooks.after_step do
  ending_step = Process.clock_gettime(Process::CLOCK_MONOTONIC)
  elapsed_step = ending_step - $starting_step
  puts "       Elapsed step time: #{elapsed_step.truncate(1)} seconds" if elapsed_step >= 10
end
```

**Comment by JonRowe** [comment]
Steps don't exist in RSpec, they're a spinach thing, if each step is a test, sure, if its a thing inside a test no, RSpec has no knowledge of them (or anything else that happens inside your test blocks), you could ask the Spinach team how best to achieve this.

**Comment by pirj** [comment]
I'm not aware of what Spinach is and what is a step, but I guess if you want to measure the speed of several consecutive examples, you can:
```ruby
describe "several steps" do
  before(:context) do
    $starting_step = Process.clock_gettime(Process::CLOCK_MONOTONIC)
  end
  before(:example) do
    ending_step = Process.clock_gettime(Process::CLOCK_MONOTONIC)
    elapsed_step = ending_step - $starting_step
    puts "       Elapsed step time: #{elapsed_step.truncate(1)} seconds" if elapsed_step >= 10
  end
  specify "step 1" do
    ...
  end
  specify "step 2" do
    ...
  end
end
```

**Comment by mileslane** [comment]
Thanks for your suggestions!

**Comment by pirj** [comment]
Welcome to the world of RSpec!
By the way, RSpec has a `--profile` option, it will print 10 (by default if I recall it correctly) slowest examples.
