### ISSUE TITLE
Deprecate IntegrationGenerator

### ISSUE THREAD

**Issue by klyonrad** [rspec/rspec-rails#2374]
**Is your ticket related to a problem? Please describe.**

There is a IntegrationGenerator class and the code comments mention something about "deprecation for this class before rspec-rails 4". I read the commit message and I don't quite understand if it is technically necessary or not? That's why I am opening this ticket for discussion/explanation 🤔 

Maybe if we delete the class (and the shared examples) we could reduce the development complexity about generators a bit.

From a user perspective I would say that having that integration generator options is just a bit confusing.

**Additional context**

https://github.com/rspec/rspec-rails/pull/1378

**Comment by JonRowe** [comment]
We can't delete it now it's made it into `rspec-rails` `4.0.0` but we should deprecate it and remove it in `rspec-rails` `5.0.0`
