### ISSUE TITLE
Net::ReadTimeout Error when running system specs with chrome/firefox drivers

### ISSUE THREAD

**Issue by fedegl** [rspec/rspec-rails#2383]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.1
Rails version: 6.0.3.3
RSpec version: 3.9

## Observed behaviour

When I run `rails test:system` the system test is run successfully using selenium and chrome

When I run `rspec spec/system` I get a `Net::ReadTimeout with #<TCPSocket:(closed)>` error.

## Expected behaviour

To successfully be able to run system tests on a real browser using selenium.

## Can you provide an example app?

Yes. https://github.com/fedegl/example_app

All I did is create a brand new app, then I installed Rspec and created both a minitest system test and a rspec system test that the only thing they do is check for the H1 text in the root url.

The rails default system tests ran fine by opening up the browser and displaying the root url and then closing the browser.

The Rspec system tests opens the browser but it always shows a blank page. The root url is never loaded. On the terminal after a few minutes I get a `Net::ReadTimeout with #<TCPSocket:(closed)>` error

Thanks!

**Comment by fedegl** [comment]
<img width="754" alt="Screen Shot 2020-09-16 at 12 48 53" src="https://user-images.githubusercontent.com/17049/93385350-016dcd00-f81b-11ea-84f5-2a3dc32df2fe.png">

**Comment by benoittgt** [comment]
Hello @fedegl 

We reuse the same `driven_by` than rails, so Selenium webdriver config is the same (we set default to selenium).

I think the error is somewhere else on your app.

```diff
--- a/spec/system/home_spec.rb
+++ b/spec/system/home_spec.rb
@@ -2,7 +2,7 @@ require 'rails_helper'

 RSpec.describe 'Home', type: :system do
   it 'invited user sets password and creates first order' do
-    visit root_url
+    visit '/'

     expect(page).to have_content 'Hola'
   end
```
And no more timeout, green test suite.

Closing because it is not related to rspec-rails itself.

😊

**Comment by fedegl** [comment]
Thanks, for the quick response!

Indeed, changing `root_url` to `/` made it work. So does that mean I can't use rails routes helpers?

I also didn't understood your comment regarding the reuse of the `driven_by` method. What impact does that have in this case?

With the rails default system tests, I am able to use the route helpers.

**Comment by benoittgt** [comment]
Hello

At the moment we do not load `url_helpers` in system specs. We want the developer to test all layers, including urls and routing.

> Request specs provide a thin wrapper around Rails' integration tests, and are designed to drive behavior through the full stack, including routing
_[source](https://relishapp.com/rspec/rspec-rails/v/4-0/docs/request-specs/request-spec)_

In `feature` (routing, and view also) specs it should work. https://github.com/rspec/rspec-rails/blob/main/lib/rspec/rails/example/feature_example_group.rb#L15

For `driven_by` you should not be impacted. By default we reuse what has been done in Rails `ActionDispatch::SystemTestCase` https://github.com/rspec/rspec-rails/blob/main/lib/rspec/rails/example/system_example_group.rb#L100

**Comment by fedegl** [comment]
Thanks again, really appreciated! 😄

**Comment by JonRowe** [comment]
> Indeed, changing root_url to / made it work. So does that mean I can't use rails routes helpers?

`root_url` is subject to configuration for where the server is, and we don't know that, it may be that Rails is doing some dynamic configuration that we are not.

`root_path` should work, as it requires no endpoint configuration.
