### ISSUE TITLE
rspec run_callbacks(:commit)  for create action is not working ?

### ISSUE THREAD

**Issue by cis-sourabh** [rspec/rspec-rails#2395]
I am writing a test case for `after_commit` callback:

```
after_commit :notify_user, :on => :create
```

When I am executing test case without putting condition `:on => :create`, it works. But when try to run with condition `:on => :create` then `after_commit` callback is not executing, it skipped. 

**Here below is the testcase which is not working**

```
describe "after commit" do
 after do
   subject.run_callbacks(:commit)
 end
 it "should receive notify_user when created" do
   subject.should_receive(:notify_user)
 end
end
```

**Comment by pirj** [comment]
And which version of RSpec?
I can't remember if we have `should_receive`, is this coming from Mocha?

**Comment by nandini-klocrix** [comment]
I am using Rails 4.2.8.

**Comment by nandini-klocrix** [comment]
RSpec 3.9

**Comment by pirj** [comment]
I'd say give `test_after_commit` a shot.
Provide a snippet of the model/spec.
Anyway, this question is more suitable for StackOverflow, not our bug tracker.

**Comment by nandini-klocrix** [comment]
Yes, it worked with them gem. Thanks for your time!!
