### ISSUE TITLE
undefined method `file_fixture_path' for RSpec::Rails::FixtureFileUploadSupport::RailsFixtureFileWrapper:Class

### ISSUE THREAD

**Issue by ramonpm** [rspec/rspec-rails#2419]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.6.6
Rails version: 6.1.0
RSpec version: 
```
RSpec 3.10
  - rspec-core 3.10.0
  - rspec-expectations 3.10.0
  - rspec-mocks 3.10.0
  - rspec-rails 4.0.1
  - rspec-support 3.10.0
```

## Observed behaviour

I'm upgrading to latest Rails and rspec-rails versions, and now all my tests that were using `fixture_file_upload` method are now failing with the error
```
undefined method `file_fixture_path' for RSpec::Rails::FixtureFileUploadSupport::RailsFixtureFileWrapper:Class
```

I see the `RailsFixtureFileWrapper` class has `fixture_path` but no `file_fixture_path`, so maybe that's why... I wonder if it was removed.

## Expected behaviour

No errors.

## Can you provide an example app?

I'll provide an example if it proves necessary. I have a felling someone here knows about the solution, which I couldn't find.

**Comment by pirj** [comment]
We are going to release 4.1.0 with full support for Rails 6.1.
Please try this approach meanwhile https://github.com/rspec/rspec-rails/issues/2402#issuecomment-737625958
