### ISSUE TITLE
fixture_file_upload broken in rails 6.1

### ISSUE THREAD

**Issue by woto** [rspec/rspec-rails#2430]
Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
Rails version: Rails 6.1.0
RSpec version: 
RSpec 3.10
  - rspec-core 3.10.0
  - rspec-expectations 3.10.0
  - rspec-mocks 3.10.0
  - rspec-rails 4.0.1
  - rspec-support 3.10.0

---

After updating from rails 6.0 to 6.1 `fixture_file_upload` stopped to work.

Seems the problem in that there is some changes in test_process.rb which tries call `RSpec::Rails::FixtureFileUploadSupport::RailsFixtureFileWrapper.file_fixture_path` and fails with exception because it is absent
https://github.com/rspec/rspec-rails/blob/dc94a1d9de2178ae20d123ebc7d96e29252c403a/lib/rspec/rails/fixture_file_upload_support.rb

Rails 6.1
https://github.com/rails/rails/blob/05386297f28580efc0686dff383759ced00e0031/actionpack/lib/action_dispatch/testing/test_process.rb#L25

Rails 6.0 didn't include that call
https://github.com/rails/rails/blob/9624a60caf19f15df62a9ce31218ff8f9fdd79cc/actionpack/lib/action_dispatch/testing/test_process.rb#L17

Am I doing something wrong. Or that is true that this feature now incompatible with Rails 6.1?

**Comment by JonRowe** [comment]
Rails 6.1 support is in the `rails-6-1-dev` branch but is not yet released.

**Comment by woto** [comment]
@JonRowe Damn. I checked main branch. Didn't know about dev branch. Thank you!

**Comment by woto** [comment]
For those who are not yet ready to switch to dev branch here is temporary solution:
Replace 

```
fixture_file_upload('files/avatar.png')
```
with
```
Rack::Test::UploadedFile.new(file_fixture('avatar.png'))
```

**Comment by JonRowe** [comment]
@woto It's always worth searching through closed issues as well as open ones for things that have already been fixed, theres quite a few mentioning this 😂

**Comment by woto** [comment]
Yeah. Something went wrong )
