### ISSUE TITLE
request spec post -> ArgumentError: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by dennyluan** [rspec/rspec-rails#2431]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.0.0
Rails version: 6.1.0
RSpec version: 3.10.0
Also:
  - rspec-core 3.10.0
  - rspec-expectations 3.10.0
  - rspec-mocks 3.10.0
  - rspec-rails 4.0.2
  - rspec-support 3.10.0

`rspec-rails` version is 4.0.2

## Observed behaviour

```ruby
RSpec.describe "Comments", :type => :request do
  it 'test' do
    post '/login', params: { user: { guest: true }, format: 'json' }
  end
end
```

returns a failing test with a failure below, when with ruby 2.7.2 the test passes.

```
  1) Comments guest user commenting creates a comment
     Failure/Error: post '/login', params: { user: { guest: true }, format: 'json' }

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
```

Also is breaking for controller specs too.

**Comment by pirj** [comment]
Please provide a more detailed backtrace. Feel free to obfuscate it a bit.

**Comment by dennyluan** [comment]
Sorry, there's no backtrace for it since it's just that the tests fail, where an app on ruby 2.7.2 the tests pass as they should.

**Comment by JonRowe** [comment]
Given we're a wrapper around rails here, a good check would be to see if the same problem is exhibited in minitest, or wether we are delegating in a way thats broken

**Comment by dennyluan** [comment]
Had a feeling this was related to the other issue: https://github.com/rspec/rspec-rails/issues/2436, including `rexml` gem fixed this.

The project where this was breaking unrelated to `rexml` missing also was fixed by updating `rails-controller-testing` to 1.0.5 as well.

**Comment by JonRowe** [comment]
Thanks for reporting back, @benoittgt @pirj it might be worth noting that in our docs for Rails 6.1 WDYT

**Comment by benoittgt** [comment]
Good idea Jon. I will open a PR or maybe @dennyluan you want to do it? :)
