### ISSUE TITLE
ActiveRecord::ReadOnlyError not getting raised in rails 6.1 with use_transactional_fixtures set to true

### ISSUE THREAD

**Issue by ritikesh** [rspec/rspec-rails#2434]
With rails 6.1, inserts or updates on replica databases are no longer raising the `ActiveRecord::ReadOnlyError` exception when `use_transactional_fixtures` is set to `true`. However, the same when tried in rails console or with `use_transactional_fixtures` set to `false`, raises the exception as expected. With

**Comment by benoittgt** [comment]
Hello @ritikesh 

Did you tried to use rails-6-1-dev branch? https://github.com/rspec/rspec-rails/tree/rails-6-1-dev

You can follow this comment https://github.com/rspec/rspec-rails/issues/2419#issuecomment-747004546

If the problem still happens can we add a basic rails app to reproduce the issue?

**Comment by ritikesh** [comment]
Hey @benoittgt, yes, I did try this on the rails-6-1-dev branch and the issue persists. I can try sharing a basic rails app to reproduce this issue.

**Comment by JonRowe** [comment]
Given we're a wrapper around Rails helpers here, it's worth seeing if this happens in minitest too and if so raising an issue with rails instead.

**Comment by ritikesh** [comment]
Hello @JonRowe, you're right, this happens in Rails test cases(which internally uses minitest) too. I will report it on the rails repo. Because it is working alright in rails console, I was led to believe that this had something to do rspec. Thanks.

**Comment by benoittgt** [comment]
Thanks for the following @ritikesh
