### ISSUE TITLE
[Question] multipart/form-data content type in request specs

### ISSUE THREAD

**Issue by PericlesTheo** [rspec/rspec-rails#2447]
Good morning you magnificent humans (and bots).

I am using Rails 6.1 in API mode and I am receiving on an endpoint an incoming email from SendGrid in a multipart/form-data. You can see an [example of the payload](https://github.com/sendgrid/sendgrid-ruby/blob/main/lib/sendgrid/helpers/inbound/sample_data/default_data.txt). SendGrid in their official repository also provide an example of an incoming request. You can [find the send method](https://github.com/sendgrid/sendgrid-ruby/blob/main/lib/sendgrid/helpers/inbound/send.rb#L14-L22) that simply reads the file mentioned above and the sends a request with the right content type.

I've hooked up ngrok and fired a test from Sendgrid, and the data are passed correctly in development (as expected)

However, I am trying to write some basic request tests but I cannot get the parsing to work. More information and code example can be find in the example repo I created  https://github.com/PericlesTheo/rails_6_rspec_multipart_form_data

One thought (from the help of someone) is that I may need to define my own encoder class (I hope we are wrong 🤞) https://github.com/rails/rails/blob/v6.1.1/actionpack/lib/action_dispatch/testing/integration.rb#L221
https://github.com/rails/rails/blob/v6.1.1/actionpack/lib/action_dispatch/testing/request_encoder.rb

Cheers!

**Comment by conzett** [comment]
I don't think there's anything in RSpec preventing multipart/form-data requests from working, I have an application where I've written this kind of spec and they seem to work fine. Multipart/form-data requests are pretty strict though. Have you checked the following:

- Boundary value is included in the content type e.g.`'multipart/form-data; boundary=example'`
- Boundary value matches POST body
- All newlines in the POST body are properly terminated as CLRF

**Comment by pirj** [comment]
Thanks for reporting!

I see the request body is sent if you `request.body.rewind && request.body.read`, but `params` have no traces of parsed parts. Wondering where did it go?

For some reason, docs suggest setting the header as `CONTENT_TYPE` https://github.com/rspec/rspec-rails/blame/main/features/request_specs/request_spec.feature#L106, not `Content-Type`, but it doesn't seem to make any difference.

Rails's own example test uses file fixtures for uploading parts of the multi-part, and I could only find an example with just one file uploaded https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/actionpack/test/controller/integration_test.rb#L1231

https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/actionpack/lib/action_dispatch/testing/integration.rb#L197 suggests that passing an already encoded String is legit.

Putting parts separately to `spec/fixtures/files` and attaching them as:
```ruby
      post "/sendgrid_emails",
        params: {
          dkim: file_fixture('dkim').read,
          to: file_fixture('to').read,
          email: file_fixture('email').read
        }
```
does the job, `params[:email]` in the controller evaluates to `"MIME-Version: 1.0\nReceived: by 0.0.0.0 with HTTP; Wed, 10 A...`.

I believe it's not what you want, as you are recording the whole request from SendGrid.

One observation is that in this case:
```
> request.headers['action_dispatch.request.content_type']
=> #<Mime::Type:0x00007fc58d6e3458
 @hash=943355308254731288,
 @string="application/x-www-form-urlencoded",
 @symbol=:url_encoded_form,
 @synonyms=[]>
```
`x-www-form-urlencoded`, not `multipart/form-data`.

https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/actionpack/lib/action_controller/metal/params_wrapper.rb#L19 suggests to explicitly allow `multipart/form-data` in the controller:
```ruby
class UsersController < ApplicationController
  wrap_parameters format: [:json, :xml, :url_encoded_form, :multipart_form]
end
```

and after making this addition to the controller (and setting a String loaded from a single file to `params:`), there's this error:
```
  Failure/Error: post "/sendgrid_emails", params: incoming_email_body, headers: {"Content-Type" => "multipart/form-data; boundary=xYzZY"}

     EOFError:
       EOFError
     # /Users/pirj/.rvm/gems/ruby-3.0.0@rails-tmp/gems/rack-2.2.3/lib/rack/multipart/parser.rb:359:in `handle_empty_content!'
     # /Users/pirj/.rvm/gems/ruby-3.0.0@rails-tmp/gems/rack-2.2.3/lib/rack/multipart/parser.rb:186:in `on_read'
```

So it seems that now it's properly parsing `multipart/form-data`. Something is missing from the fixture, can't quickly tell what exactly.

Are you sure though that your controller was able to handle `multipart/form-data` without `wrap_parameters`?

In any case, please feel free to share your findings here, and to send a pull request to update the documentation (add a feature test) on how to deal with multi-part uploads.

**Comment by PericlesTheo** [comment]
@pirj thanks for that! @conzett's

> All newlines in the POST body are properly terminated as CLRF

made me realise that maybe there is something wrong with the file. so I cloned https://github.com/sendgrid/sendgrid-ruby/blob/main/lib/sendgrid/helpers/inbound/sample_data/default_data.txt, run the test again and worked! 🎉  🥳 

I've updated the skeleton if you want to have another look.

> Are you sure though that your controller was able to handle multipart/form-data without wrap_parameters?

Yes absolutely which is relatively strange based on your findings.

> For some reason, docs suggest setting the header as CONTENT_TYPE https://github.com/rspec/rspec-rails/blame/main/features/request_specs/request_spec.feature#L106, not Content-Type, but it doesn't seem to make any difference.

I saw that as well but evidently `Content-Type` works just fine.

I will open a PR tomorrow for a test and documentation. Very excited for my first contribution to rspec-rails!
