### ISSUE TITLE
Cannot set classic autoload for rspec

### ISSUE THREAD

**Issue by maurobender** [rspec/rspec-rails#2450]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.6
Rails version: 6.1
RSpec version: 3.10
  - rspec-core 3.10.1
  - rspec-expectations 3.10.1
  - rspec-mocks 3.10.1
  - rspec-rails 4.0.2
  - rspec-support 3.10.1

(also tested with branch rails-6-1-dev)

## Observed behaviour

I have configured `autoload = :classic` for the rails app but rspec still uses zeitwerk new autoload causing errors when loading classes.

## Expected behaviour

rspec to autoload the classes correctly using the classic autoloader

**Comment by pirj** [comment]
Can you please provide a reproduction example repository?

My first thought is that RSpec doesn't do anything that would affect the loader.
Are you sure that you are configuring `autoloader=` in your `config/application.rb`, not `config/environments/*`?

Are you setting `config.autoload = :classic`?
It should be `config.autoloader = :classic`.

**Comment by maurobender** [comment]
Hi @pirj! Thanks for the quick response!

I can't believe it but it was that, I was dealing with this for hours and it was just that! Sorry for the pointless issue and thank you so much for pointing this out! :)

**Comment by pirj** [comment]
No worries and you're welcome!
