### ISSUE TITLE
No support in docs for rails 3.x

### ISSUE THREAD

**Issue by akcrono** [rspec/rspec-rails#2452]
Following the directions in the [link for rails earlier than 5.0](https://github.com/rspec/rspec-rails/tree/3-9-maintenance) results in a a bundler error:

```
    rails (~> 3.2.0) was resolved to 3.2.22.5, which depends on
      actionpack (= 3.2.22.5)

    rspec-rails was resolved to 4.1.0.pre, which depends on
      actionpack (>= 4.2)
```

The docs should be updated to replace `'master'` with the correct maintenance branch name

**Comment by pirj** [comment]
What is the problem you're experiencing with the following exactly?
```ruby
group :development, :test do
  gem 'rspec-rails', '~> 3.9'
end
```

**Comment by akcrono** [comment]
That the other gems it depends on are not also current

**Comment by pirj** [comment]
Can you please elaborate?

**Comment by pirj** [comment]
I suggest you to skip declaring the version constraint, and let Bundler install the correct version of `rspec-rails` and dependent gems basing on the Rails version you use.

It's clearly a miss in the documentation, along with mentioning the now non-existent `master` branch (we're using `main`).
However, we're not too interested in keeping it up to date with other priorities in sight.

To keep you out of dependency conflicts, just keep in mind that `main` is 4.x now, and the most recent development in general. With an older version of Rails to work with, pick an earlier release from RubyGems.

You're welcome to send a PR to `main` and optionally to `rails-6-1-dev` branches to add

> Use rspec-rails 3.x for Rails 3 and 4.

next to

> Use rspec-rails 1.x for Rails 2.x.

**Comment by JonRowe** [comment]
@pirj The issue is we link to the 3-9-maintenance readme from the `main` readme. So we should update that one to reflect correct instructions...

**Comment by akcrono** [comment]
Skipping the version constraint results in a bundler error.  The only way I can update rspec for rails 3.2 is to explicitly define the maintenance branch via the block gem declaration.

And if it's clearly a miss in the documentation, then the request to update the documentation seems like a reasonable change to make.

**Comment by JonRowe** [comment]
> The only way I can update rspec for rails 3.2 is to explicitly define the maintenance branch via the block gem declaration.

Surely not, this should work:

```
gem "rspec-rails", "~> 3.9.0"
```

**Comment by akcrono** [comment]
It surely doesn't:

```Bundler could not find compatible versions for gem "rspec-mocks":
  In snapshot (Gemfile.lock):
    rspec-mocks (= 2.14.6)

  In Gemfile:
    rspec-sidekiq was resolved to 1.1.0, which depends on
      rspec (~> 2.0) was resolved to 2.14.1, which depends on
        rspec-mocks (~> 2.14.0)

    rspec-rails (~> 3.9.0) was resolved to 3.9.1, which depends on
      rspec-mocks (~> 3.9.0)```

Again, I really don't see the issue in simply updating the docs to be accurate.

**Comment by pirj** [comment]
Have you tried running
```
bundle update --conservative rspec-rails rspec-mocks rspec-core rspec-expectations rspec-support rspec-sidekiq
```
What would be the output?

**Comment by JonRowe** [comment]
As per the PR I'm happy to update the old docs on this occasion, as it does help people using older versions, it's just there is no difference between the code in that branch and the releases on rubygems and thus won't help your issue. You've run into a common problem with (older at least) bundler where you have locked versions of gems and are trying to install a newer version, as @pirj suggests you need to update all the gems, theres nothing we can do about that and the git branch shouldn't help you there.

**Comment by akcrono** [comment]
Yes, the bundle update command also works since it updates all the rspec gems, but the whole point was that the current docs as they exist are not accurate for their intended use case, and we've already spent far more time arguing about this than it would have taken to update two lines in the readme to be more accurate.

**Comment by JonRowe** [comment]
I have taken the extra time to try to help you, and future people who may come across this. The documentation pointing to the branches was outdated, but its also the wrong solution for your issue. The problem was the `~> 3.9` which tries to load 4.0.x and Bundler gets terrible confused.

I've now improved this further and pointed out the end of life issues, and provided hopefully clearer instructions.

Thank you for bring this to our attention.
