### ISSUE TITLE
Is it good or bad practice to use assert in rspec environments?

### ISSUE THREAD

**Issue by krtschmr** [rspec/rspec-rails#2457]
We came across some code today in a big RSpec environment.

```
    it "can invite another user " do
      assert policy.create?
    end
```

The question that occurred is simple: Is it good or bad , okay or not okay, to use `assert` in an rspec environment. We would love the input of the community on this.

**Comment by krtschmr** [comment]
I would say it's good. It keeps simple boolean assertions very short to read and quick to write.

**Comment by pirj** [comment]
If it works for you, just do it.

Let's continue the discussion in our mailing list. https://rspec.info/help/

**Comment by JonRowe** [comment]
Its not a typical practise for us, because `assert` comes from minitest and we would write that test as:
```
it "can invite another user " do
  expect(policy).to be_create
  # or
  expect(policy.create?).to eq true
end
```

However we support minitest assertions when included as the expectation library, so it's not bad practise either, as Phil says, if it works for you 👍
