### ISSUE TITLE
rspec is mixing nested attributes

### ISSUE THREAD

**Issue by yalmasri** [rspec/rspec-rails#2459]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.1
Rails version: 6.1.1
RSpec version:
RSpec 3.10
  - rspec-core 3.10.1
  - rspec-expectations 3.10.1
  - rspec-mocks 3.10.1
  - rspec-rails 4.0.2
  - rspec-support 3.10.1

## Observed behaviour

Trying to create a new record with nested attributes and rspec is mixing objects:

## Expected behaviour

Controller should receive params as been declared in the spec file.

## Can you provide an example app?

rspec params defined in `let` spec file:

```ruby
{
                      :user_id => 820,
                      :city_id => 449,
                  :platform_id => 510,
            :exchangeable_type => "Game",
              :exchangeable_id => 572,
                    :aestetics => 7,
                   :negotiable => true,
    :exchange_seeks_attributes => [
        {
                  :game_id => 573,
            :exchange_type => "product",
              :platform_id => 510
        },
        {
                    :price => 250,
            :exchange_type => "money"
        }
    ]
}
```

strong params received in the controller:
```ruby
{
                      "city_id" => "449",
              "exchangeable_id" => "572",
                    "aestetics" => "7",
                   "negotiable" => "true",
                  "platform_id" => "510",
    "exchange_seeks_attributes" => [
        {
                  "game_id" => "573",
            "exchange_type" => "product",
                    "price" => "250",
              "platform_id" => "510"
        },
        {
            "exchange_type" => "money"
        }
    ],
                      "user_id" => 820,
            "exchangeable_type" => "Game"
}
```

**Comment by pirj** [comment]
Is
```ruby
[
        [0] {
                  :game_id => 573,
            :exchange_type => "product",
              :platform_id => 510
        },
        [1] {
                    :price => 250,
            :exchange_type => "money"
        }
```
a valid Ruby syntax?

Are you certain that the same code works if you write a Minitest Rails test? `rspec-rails` is a wrapper around Rails testing, and is suffers from underlying bugs.

Please provide a runnable reproduction example.

**Comment by yalmasri** [comment]
@pirj sorry, I have updated the issue.

**Comment by yalmasri** [comment]
@pirj I don't have Minitest configured for this project, I will try to provide an example project.

**Comment by pirj** [comment]
You may see that almost nothing you use is actually provided by RSpec:
 - https://github.com/rspec/rspec-rails/blob/main/lib/rspec/rails/example/request_example_group.rb
 - https://github.com/rspec/rspec-rails/blob/4fcb7906e09f41887889c704a3f7f8a79f62fd5f/lib/rspec/rails/example/rails_example_group.rb#L9

You may set a breakpoint with `binding.pry` and dive deep (I suggest using `pry-byebug` gem) into what `post` does.

It will be sufficient for us to have a reproducible example using RSpec. However, my assumption is that RSpec has nothing to do with this, and writing the same in Test::Unit would indicate the same problem.

**Comment by yalmasri** [comment]
@pirj seems the issue is not from `rspec-rails`, I have created a new clean project and it works with no errors.

I will try to figure out what is the issue in my project and if it's related to `rspec-rails` I will open another issue.

**Comment by pirj** [comment]
Thanks!

**Comment by yalmasri** [comment]
@pirj I have created a new project with rspec and minitest:

https://github.com/yalmasri/rspec-nested

Please note the the issue is not with rspec only, when I run minitest I have the same issue as rspe. you can clone the project and run both tests, I have left `puts` to print the params before sending the request and on receiving the params in the controller.

NOTE: in the nested model I have a validation with `with_options`, when I comment this code, I receive the params well formed, but when I uncomment it the issue happens.

I'm not sure if the issue is related to rspec or rails, I leave this comment just to address the issue and share my experience and if you want to look on it will be better.

Thanks for the support

**Comment by pirj** [comment]
It seems like a bug on the Rails side. I suggest you open a ticket for them.

Hope this debug session will be helpful, it clearly indicates the input and the output that don't match:

![image](https://user-images.githubusercontent.com/6916/107999388-509d7100-6ff8-11eb-92e7-939960e97ae2.png)

It's hard for me to pinpoint where things go wrong, I can only guess it's somewhere in `@request.assign_parameters`.

I could reproduce it on 6.1.2.1, 6.1.2, 6.1.1 and 6.0.3.5.

And you're always welcome.

**Comment by yalmasri** [comment]
@pirj thanks for the help
