### ISSUE TITLE
Bug when using `to_s` as a subject name

### ISSUE THREAD

**Issue by corroded** [rspec/rspec-rails#2478]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.6.6
Rails version: 6.0.3.5
RSpec version: 3.10.1

## Observed behaviour

We have dependabot and the recent upgrade failed some of our specs. Particularly specs that specifically test the method `to_s` on an object. An example:

### AR Object
```ruby
class SomeActiveRecordObject < ApplicationRecord
  validates :name, presence: true
  delegate :to_s, to: :name
end
```

### Spec
```ruby
RSpec.describe SomeActiveRecordObject do
  subject(:some_active_record_object) { described_class.new }

  describe '#to_s' do
    subject(:to_s) { some_active_record_object.to_s }

    before { some_active_record_object.name = 'new name' }

    it 'delegates to name' do
      expect(some_active_record_object.to_s).to eq 'new name'
    end
  end
end
```

## Expected behaviour

The expected behaviour is for the spec to pass seeing it's very simple. This spec fails with the new code because `name` is blank in the beginning and is somehow being memoised already.

## Can you provide an example app?

The above already shows the example. Further more, we already have an idea on what the bug is but not sure how to fix it.

This is the specific commit that breaks it: https://github.com/rspec/rspec-rails/pull/2461/files

More specifically this change:

```ruby
        def run_in_transaction?
          use_transactional_tests && !self.class.uses_transaction?(self)
        end
```

The issue is when the `subject` is named `to_s` (as in `subject(:to_s) { something.to_s }`), `uses_transaction` somehow uses the actual active record object - instead of the RSpec example. 

This is the "offending line": https://github.com/rails/rails/blob/df41acdad93783dcac49f03036c3f34cb1c6c667/activerecord/lib/active_record/test_fixtures.rb#L96

```ruby
      def uses_transaction?(method)
        @uses_transaction = [] unless defined?(@uses_transaction)
        @uses_transaction.include?(method.to_s) # for some reason "method" here becomes the AR object - so it 'memoises' the value already even before you hit the before block
      end
    end
```

I have added an example spec to the existing spec for name collision - I think it's related there. Here is the sample:

https://github.com/rspec/rspec-rails/compare/main...corroded:main

### Final note

You don't actually need to inherit from AR for this to happen - but you do need to have included `include ActiveRecord::TestFixtures` since it's that method that is the problem. Not sure if it's an rspec-rails issue or a bug with active-record fixtures (or both!)

**Comment by JonRowe** [comment]
Your example spec doesn't actually use `subject` there at all (you would have to call `subject` or `to_s` to trigger it).

Subjects however, are methods, `to_s` is a special method for Ruby, as it's used to cast objects to strings, so it's possible RSpec is calling to_s on the example to print something that is obscuring the real cause, can you change the name to find the real error?

**Comment by corroded** [comment]
> Your example spec doesn't actually use `subject` there at all (you would have to call `subject` or `to_s` to trigger it).

That's the thing. From my understanding `to_s` is lazily assigned and the subject won't run until you call `subject` or `to_s` as you mentioned, but that line `uses_transaction?` apparently calls that subject instead. `method` is SUPPOSED to be an RSpec example - but in this case, it becomes whatever the subject was i.e. `some_active_record_object`. 

If you look at the sample spec I added, if you change the name of the subject to `to_ss` it will pass. It is specifically if the name is `to_s` that it fails

**Comment by corroded** [comment]
@JonRowe Here is an example screenshot of a `pry` I did to illustrate (see memoized_helpers.rb:339 -> active_record/test_fixtures.rb:94)

![image](https://user-images.githubusercontent.com/46548/110556107-d5ebef80-8178-11eb-804d-9f92d5e0b943.png)

See how `method` is supposed to be an `RSpec::ExampleGroups::ToS` but calling `to_s` on it makes it the actual `subject`?

If I change the subject name to `to_ss` it never reaches that `uses_transaction?` part (from memoized_helpers.rb:339 -> memoized_helpers.rb:121)

![image](https://user-images.githubusercontent.com/46548/110556174-f1ef9100-8178-11eb-813e-6d55f26b01f7.png)

**Comment by tomdalling** [comment]
I think this is solved pretty well by just adding a nice error message about reserved names. The main problem is how difficult it is to debug, and an error message will make it easy.
