### ISSUE TITLE
ActiveModel::MissingAttributeError when returning attribute for Model#primary_key

### ISSUE THREAD

**Issue by robinboening** [rspec/rspec-rails#2483]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.1
Rails version: 6.1
RSpec version: latest `main` branch

## Observed behaviour

Imagine a model `Event` which belongs to a `User`, but the relation is named `creator` and the `primary_key` is defined (doesn't matter what attribute is assigned to `primary_key` so for simplicity I am going with the default `id`).

```
class Event < ApplicationRecord
  belongs_to :creator,
    primary_key: :id,
    class_name: 'User',
    foreign_key: :creator_id
end
```

Now, in my event model spec I am expecting the primary key to be used.

```
RSpec.describe Event, type: :model do
  describe '#creator' do
    it 'uses primary_key' do
      expect(User).to receive(:primary_key).at_least(:once).and_return(:id)
      Event.create(creator: User.create)
    end
  end
end
``` 

This example fails with

```
ActiveModel::MissingAttributeError:
       can't write unknown attribute `id`
```

## Expected behaviour

I expect the example to succeed as it was succeeding with Rails 6.0.x

## Can you provide an example app?

https://github.com/robinboening/rspec-issue-demo

**Comment by pirj** [comment]
```diff
- expect(User).to receive(:primary_key).at_least(:once).and_return(:id)
+ expect(User).to receive(:primary_key).at_least(:once).and_return('id')
```

Found by using `and_wrap_original`.

**Comment by robinboening** [comment]
@pirj thanks for figuring out the solution! Could you elaborate on why this needs to be String now? What change caused this, do you know?

Thank you! ❤️

**Comment by pirj** [comment]
It's what Rails is using under the hood. I can't explain their decision to use strings instead of symbols 🤷 
You're always welcome!
