### ISSUE TITLE
Generator spec example

### ISSUE THREAD

**Issue by gingermusketeer** [rspec/rspec-rails#2488]
**Is your feature request related to a problem? Please describe.**
Looking at the documentation for generator specs I am not sure how I should be testing generators. How do I setup the test and make assertions about the success or failure of the generator under test.

https://relishapp.com/rspec/rspec-rails/v/4-0/docs/generator-specs/generator-spec

Also noticed that there is no example provided like there are for other spec types https://relishapp.com/rspec/rspec-rails/v/4-0/docs/generator-specs/generator-spec

**Describe the solution you'd like**
An example of how to test generators showing asserting the contents of particular files.

**Describe alternatives you've considered**

**Additional context**
I ran into this problem from  a rails plugin, not sure if that is any different, hopefully not.

The generator is loaded through a railtie, might be good to include an example of how to trigger the generator to be loaded.

**Comment by pirj** [comment]
You can check RSpec's own generator specs for examples https://github.com/rspec/rspec-rails/tree/main/spec/generators/rspec

It would be helpful to add a couple of commented out examples to https://github.com/rspec/rspec-rails/blob/main/lib/generators/rspec/generator/templates/generator_spec.rb along with documentation extension. A PR is welcome.

**Comment by mhenrixon** [comment]
@pirj I've tried to my best ability to look for examples in the rspec generator specs but I simply can't make it work.

I copied the `spec/support/generators.rb` to my own machine and tried running it but it chokes on:

```
An error occurred while loading ./spec/generator/stimulus_generator_spec.rb.
Failure/Error: destination File.expand_path('../../tmp', __dir__)

NoMethodError:
  undefined method `destination' for RSpec::ExampleGroups::Stimulus:Class
  Did you mean?  description
# ./spec/support/generators.rb:9:in `set_default_destination'
# ./spec/support/generators.rb:13:in `setup_default_destination'
# ./spec/generator/stimulus_generator_spec.rb:9:in `block in <main>'
# ./spec/generator/stimulus_generator_spec.rb:8:in `<main>'
```

I felt like it shouldn't be this hard so wanted to chime in with my experience. Without a working example, I can't really provide a PR to guide others either.

**Comment by pirj** [comment]
@mhenrixon I believe you need [`ammeter`](https://github.com/alexrothenberg/ammeter) to test your generators if you intend to test generators the same [way `rspec-rails` does](https://github.com/rspec/rspec-rails/tree/main/spec/generators/rspec). This is purely optional, but `rspec-rails` on its own doesn't provide any convenience helpers to test generators.
