### ISSUE TITLE
Routing specs do not seem to handle non-ASCII URLs

### ISSUE THREAD

**Issue by goulvench** [rspec/rspec-rails#2494]
I want to test some special routes that include non-ASCII characters in a Rails app, but Rspec doesn't seem to handle that. Rails properly handles these routes, but I guess Rspec delegates URL parsing to some subsystem that is expecting ASCII only, unlike Rails (which monkey-patches the String class [for multi_byte support](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/core_ext/string/multibyte.rb)).

### Environment
* Ruby version: 2.5.8
* rspec-core version: 3.10.1
* Rails version: 6.1.3.1

### Steps to reproduce

```ruby
# encoding: utf-8
require 'rails_helper'
RSpec.describe 'Routes', type: :routing do
  include RSpec::Rails::RequestExampleGroup
  it 'handles non-ASCII URLs' do
    expect(get: '/évènements').to route_to('events#index')
  end
  it 'handles non-ASCII URLs in redirections' do
    expect(get '/évènements').to redirect_to('/events')
  end
end
```

### Expected behavior

```shell
2 examples, 0 failures
```

### Actual behavior

```ruby
Failures:

  1) Routes handles non-ASCII URLs
     Failure/Error: expect(get: '/évènements').to route_to('events#index')
       bad URI(is not URI?): /évènements

  2) Routes handles non-ASCII URLs in redirections
     Failure/Error: expect(get '/évènements').to redirect_to('/events')
     
     URI::InvalidURIError:
       URI must be ascii only "http://www.example.com:80/\u00E9v\u00E8nements"
```

**Comment by JonRowe** [comment]
RSpec is not actually doing anything with URLs, we use Rails own test helpers which are in this case, `rack-test`. This seems to be a known issue in rack-test:

https://github.com/rack/rack-test/issues/248
https://github.com/rack/rack-test/issues/266

Closing because this is better off fixed in the library raising the error.
