### ISSUE TITLE
issue with nokogiri, not being able to run the tests

### ISSUE THREAD

**Issue by A7madXatab** [rspec/rspec-rails#2497]
So, i have upgraded my ruby version to ruby 3.0.1. I have a rails application with rspec.

When i try to run the command

```
bundle exec rspec spec
```
i get the following error

```
oadError:
  incompatible library version - /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri/nokogiri.bundle
# /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri/extension.rb:25:in `require'
# /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri/extension.rb:25:in `rescue in <top (required)>'
# /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri/extension.rb:4:in `<top (required)>'
# /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri.rb:11:in `require'
# /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri.rb:11:in `<top (required)>'
# ./spec/spec_helper.rb:3:in `require'
# ./spec/spec_helper.rb:3:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- nokogiri/3.0/nokogiri
#   /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri/extension.rb:6:in `require'
```
I've tried fixing everything with rvm, but still this bug didint fix, any issues ?

Environment:

ruby : 3.0.1
nokogiri 1.11.3
rails: 6.1
Thanks

**Comment by pirj** [comment]
Unfortunately, this has nothing to do with RSpec.
Try `require 'nokogiri'` from `irb` and to see if it reproduces with the same error.
I'd suggest `rvm reinstall && bundle pristine`.

If the above doesn't help, please use our help channels https://rspec.info/help/, or StackOverflow. It's highly unlikely it's an RSpec bug and we can do anything about this.
