### ISSUE TITLE
rails generators not respecting RSpec's `default_path`

### ISSUE THREAD

**Issue by vivekmiyani** [rspec/rspec-rails#2507]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.0
Rails version: 6.1.3.2
RSpec version: main

## Other RSpec configuration

RSpec is configured to use `behaviour` directory i.e.

```ruby
RSpec.configure do |c|
  c.default_path = "behavior"
end
```

## Observed behaviour

When running rspec generator by default `spec` directory got chosen

```
$ rails generate rspec:model user
    ...
    create  spec/models/user_spec.rb
    ...
```

## Expected behaviour

Generator should place file inside `behaviour` directory instead.

```
$ rails generate rspec:model user
    ...
    create  behaviour/models/user_spec.rb
    ...
```

## Can you provide an example app?

I don't have any at the moment.

**Comment by vivekmiyani** [comment]
Happy to raise the PR :)

**Comment by pirj** [comment]
PR is welcome!

**Comment by vivekmiyani** [comment]
@pirj There are lot of code which contains hard-coded `spec` directory,

So while I am working on this

```
```

**Comment by jasonkarns** [comment]
Once configuration is available to the generators, it would be great if the generator would also respect `infer_spec_type_from_file_location` and omit the `type:` metadata.

**Comment by JonRowe** [comment]
`infer_spec_type_from_file_location` exists to maintain backward compatibility, at some point we'll remove it so I don't want generators not generating types.
