### ISSUE TITLE
rspec-rails stopped stubbing views in controller test after upgrading to Rails 6

### ISSUE THREAD

**Issue by headshota** [rspec/rspec-rails#2517]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.5.1
Rails version: 6.0.3.3
RSpec version: 5.0.2

## Observed behaviour

After upgrading my Rails application to version 6, rspec stopped stubbing view rendering. (https://relishapp.com/rspec/rspec-rails/v/5-0/docs/controller-specs/views-are-stubbed-by-default)

I have tried several rspec and rspec-rails versions but result is always the same.

Calling`render_views false` in the example group has not effect. `render_views?` returns `false` in the example.

When I debug the controller action with `binding.pry`, in Rails 5, calling `render` returns `""`. In Rails 6, calling `render` renders the real template.

## Expected behaviour

The expected behavior is that calling render should result in an empty string, but instead calling a controller action in spec is rendering the template like it would normally.

**Comment by pirj** [comment]
Wondering how [this](https://github.com/rspec/rspec-rails/blob/fe95eacb376f7fa558d3ffeeaa9afa6d3110a540/features/controller_specs/render_views.feature#L47) managers to pass?

Can you set a breakpoint [here](https://github.com/rspec/rspec-rails/blob/fe95eacb376f7fa558d3ffeeaa9afa6d3110a540/lib/rspec/rails/view_rendering.rb#L148) outside and inside the hook?

**Comment by headshota** [comment]
@pirj Thanks for quick response.

The spec fails on Rails 6 with:
```
Failure/Error: expect(response.body).to eq("")
       expected: ""
            got: "<html>...</html>\n"
```

Both breakpoints get called:

```
 => 148:        binding.pry
    149:         before do
    150:        binding.pry
```
```
    148:        binding.pry
    149:         before do
 => 150:        binding.pry
```

**Comment by JonRowe** [comment]
@headshota Is that on a clean app? As thats part of our build and currently passes on the most recent versions of Rails 6.0 and 6.1, so its possible this is something on your machine / gems?

**Comment by headshota** [comment]
@JonRowe After spending quite some time on it, I found out that it is indeed something cause by my app (not a clean app). Seems that this issue is not happening for newly created controllers. My Apologies. will close this issue now.

**Comment by JonRowe** [comment]
Thanks for confirming! ❤️  🧡  💚

**Comment by headshota** [comment]
Just in case anyone encounters the same issue. This was caused by setting `view_paths` in `before_action` callback and using this new path to set a layout on the controller. Apparently in previous versions of Rails this worked, but now it's necessary to set view_paths on class level (using `prepend_view_paths` or similar) for stubbing to work.

**Comment by bonol** [comment]
> 
Thanks for this info! @headshota 
Do you mind putting an example here of how the view_paths need to be set? I am having the same issue. Thanks heaps!

**Comment by bonol** [comment]
1
