### ISSUE TITLE
Parameter name is not equal the model name when executing `scaffold_controller` with namespace

### ISSUE THREAD

**Issue by kenzo-tanaka** [rspec/rspec-rails#2532]
Hi👋
First of all thank you for the very helpful gem!

## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.6.3p62
Rails version: 6.1.4.1
RSpec core version: 3.10.1
RSpec rails version: 5.0.2

## Observed behaviour

When the request spec is created by executing the `scaffold_controller` command with namespace, the parameter name is not equal the model name.

Here is a pull request that reproduces the behaviour
https://github.com/kenzo-tanaka/rails_sandbox/pull/14

```shell
$ rails g model Product name:string price:integer
$ rails db:migrate
$ rails g scaffold_controller admin/products --model-name=product --no-helper --no-assets --no-controller-specs --no-routing-specs --no-view-specs
```

```rb
describe "POST /create" do
  context "with valid parameters" do
    it "creates a new Product" do
      expect {
        # Here, I expected `{ product: valid_attributes }` like the test of update action
        post admin_products_url, params: { admin_product: valid_attributes } 
      }.to change(Product, :count).by(1)
    end
    # ...
end
```

## Expected behaviour

I expected that the autogenerated code is like this:

```rb
describe "POST /create" do
  context "with valid parameters" do
    it "creates a new Product" do
      expect {
        post admin_products_url, params: { product: valid_attributes } 
      }.to change(Product, :count).by(1)
    end
    # ...
end
```

## Can you provide an example app?

https://github.com/kenzo-tanaka/rails_sandbox/pull/14/files

---

I'm sorry if I misunderstood something about this behaviour🙏

**Comment by pirj** [comment]
Seems related to #2491 and #2492. @PedroAugustoRamalhoDuarte What do you think?

**Comment by PedroAugustoRamalhoDuarte** [comment]
Yes, its wrong. In [create action](https://github.com/rspec/rspec-rails/blob/d3e7b85877fcbcec63f8a76434d8750e7f3b7aef/lib/generators/rspec/scaffold/templates/request_spec.rb#L68) uses ns_file_name method and in [update_action](https://github.com/rspec/rspec-rails/blob/d3e7b85877fcbcec63f8a76434d8750e7f3b7aef/lib/generators/rspec/scaffold/templates/request_spec.rb#L109) uses file_name method.

In my pull request i have changed only model name and I hadn't seen this inconsistency in params

**Comment by kenzo-tanaka** [comment]
@pirj @PedroAugustoRamalhoDuarte Thank you for quick response!
If it's a simple issue, can I try it?

https://github.com/rspec/rspec-rails/blob/d3e7b85877fcbcec63f8a76434d8750e7f3b7aef/lib/generators/rspec/scaffold/templates/request_spec.rb#L68

I think that `ns_file_name` is needed to replace `singular_table_name`.
