### ISSUE TITLE
Request spec returns 204 for a post request. Manual testing shows that the request works as expected

### ISSUE THREAD

**Issue by ianaverno** [rspec/rspec-rails#2558]
I have a very simple controller for Tags:

```
class Api::V1::TagsController < ApplicationController
  before_action :set_tag, only: :update

  def index
    tasks = Tag.chronologically

    render json: tasks
  end

  def create
    tag = Tag.new(tag_params)

    if tag.save
      render json: tag
    else
      render_422(tag)
    end
  end

  def update
    if @tag.update(tag_params)
      render json: @tag
    else
      render_422(@tag)
    end
  end

  private

  def tag_params
    params.permit(:title)
  end

  def set_tag
    @tag = Tag.find_by!(id: params[:id])
  end

end
```

I've tested this manually and the post to create tag action in Postman and it works as expected, however, when I run the request spec the behaviour is unexplainably weird:

```
require 'rails_helper'

RSpec.describe "Tags", type: :request do
  let!(:tag1) { create :tag }
  let!(:tag2) { create :tag }
  let!(:tag3) { create :tag }
  let(:body) { JSON.parse response.body, symbolize_names: true }

  describe "GET /index" do
    it "returns tags in chronological order" do
      get api_v1_tags_path
      expect(response.status).to eq(200)
      expect(response.content_type).to eq("application/json; charset=utf-8")
      expect(body[0].keys).to include(:id, :title)
      expect(body.map{|t| t[:title]}).to eq([tag1.title, tag2.title, tag3.title])
    end
  end

  describe "POST /create" do
    it "creates the tag and returns tag json" do
      headers = { "Content-Type" => "application/json" }
      post api_v1_tasks_path, params: { title: "Urgent" }.to_json, headers: headers
      puts "body: #{response.body.inspect} status: #{response.status}"
      expect(response.status).to eq(200)
      expect(response.content_type).to eq("application/json; charset=utf-8")
      expect(body.keys).to include(:id, :title, :created_at, :updated_at)
      expect(body[:title]).to eq("Urgent")
    end
  end
end
```

output:
```
Randomized with seed 49215

Tags
  POST /create
body: "" status: 204
    creates the tag and returns tag json (FAILED - 1)
  GET /index
    returns tags in chronological order

Failures:

  1) Tags POST /create creates the tag and returns tag json
     Failure/Error: expect(response.status).to eq(200)

       expected: 200
            got: 204

       (compared using ==)
     # ./spec/requests/tags_spec.rb:27:in `block (3 levels) in <top (required)>'

Finished in 0.17793 seconds (files took 0.84214 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/requests/tags_spec.rb:23 # Tags POST /create creates the tag and returns tag json
```

**Comment by pirj** [comment]
What `tag.as_json` would print in the controller `create` action if you make a request manually, from postman, or from specs?

**Comment by ianaverno** [comment]
> 

![image](https://user-images.githubusercontent.com/5175391/149625514-aa8062b6-de64-41c1-94a8-668014755674.png)
Here's prtscrn of postman request to post create

**Comment by ianaverno** [comment]
@pirj thanks, for you reply
My confusion is because manually testing with postman points to endpoints working correctly, and there seems to be some kind of infrastructure issue with request specs I couldn't figure out yet, hence reaching out

**Comment by pirj** [comment]
Let me repeat my question:
> What `tag.as_json` would print in the controller `create` action if you make a request manually, from postman, or from specs?

My guess is that Rails renders HTTP 204 when `tag.as_json` is `nil`. How this can happen if `tag.save` returns a truthy value is interesting.

It will be very helpful if you could submit a reproduction repo or a script (see e.g. https://github.com/rspec/rspec-rails/blob/main/snippets/use_active_record_false.rb).
Otherwise, unfortunately, we won't be able to help.

**Comment by ianaverno** [comment]
@pirj 
added you to collaborators:
https://github.com/ianaverno/test-rspec

**Comment by ianaverno** [comment]
@pirj 
I've resolved the issue
the issue was the variable for headers set with let was incorrect, and the one set within it was ignored (it seems)

 sorry for bothering
