### ISSUE TITLE
Has anyone ever received superclass mismatch for class FailedExampleNotification when running rspec?

### ISSUE THREAD

**Issue by tsabz** [rspec/rspec-rails#2572]
<img width="987" alt="Screen Shot 2022-02-11 at 5 57 39 PM" src="https://user-images.githubusercontent.com/36241267/153681890-4d2d1728-a2e7-4f91-bd2c-328c633e08d2.png">

**Comment by pirj** [comment]
I suggest you set a conditional breakpoint in `dependencies.rb:274`:
```ruby
... rescue binding.pry
```
and see:
 - what it was trying to load as a dependency
 - where `FailedExampleNotification` is defined already

Please share as much information as you reasonably can that can shed light n this issue.

**Comment by tsabz** [comment]
Update I had to run bundle exec rspec {whatever spec you're running} instead rspec file.rb
