### ISSUE TITLE
DEPRECATION WARNING: Non-URL-safe CSRF tokens are deprecated.

### ISSUE THREAD

**Issue by hashmaster3k** [rspec/rspec-rails#2577]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin20]
Rails version: 7.0.2.2
RSpec version: 
 - RSpec 3.11
   - rspec-core 3.11.0
   - rspec-expectations 3.11.0
   - rspec-mocks 3.11.0
   - rspec-rails 5.1.0
   - rspec-support 3.11.0

## Observed behaviour
When running ```bundle exec rspec``` I get the following deprecation warning:
```
DEPRECATION WARNING: Non-URL-safe CSRF tokens are deprecated. Use 6.1 defaults or above. (called from <top (required)> at /Users/hashimgari/Codebases/heritage-calendarize/spec/rails_helper.rb:8)
```

Line 8 of rails_helper.rb is ```require 'rspec/rails'```

## Expected behaviour
No deprecation warning?

## Can you provide an example app?
None at the moment.

**Comment by pirj** [comment]
What is there on line 8?

**Comment by pirj** [comment]
Do you happen to see that when you run `rails console`?
Are you certain that [this option](https://guides.rubyonrails.org/configuring.html#config-action-controller-urlsafe-csrf-tokens) is correctly set for the test environment?

**Comment by hashmaster3k** [comment]
Thanks all. It was a configuration issue. I just updated to Rails 7 and forgot to change the ```config.load_defaults```.

**Comment by phorsuedzie** [comment]
FYI: It is a side-effect of https://github.com/rails/rails/commit/c4d9dac9403e92f38ab9506f6ed82cf45dcae296: `config.load_defaults` always calls the deprecated method to configure the current default.

Looks like one escape only by:
- finishing the migration to 7.0 (and remove `config.load_defaults` eventually), or
- Rails 7.1+
