### ISSUE TITLE
compact_blank autocorrects on Rails 6.0 causing an error

### ISSUE THREAD

**Issue by jcoyne** [rspec/rspec-rails#2593]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.3
Rails version: 6.0
RSpec version: 1.27.0

## Observed behaviour

Ran autocorrect and it transformed `.reject(&:blank?)` to `.compact_blank`.  However compact_blank is not in Rails 6.0

See https://github.com/projectblacklight/blacklight/pull/2674#pullrequestreview-938485726

## Expected behaviour

This cop should not be in Rspec-rails 5.x because the Readme states that "Rspec-rails 5.x is for Rails 5.2 or 6.x"

## Can you provide an example app?

https://github.com/projectblacklight/blacklight/pull/2674

**Comment by pirj** [comment]
You probably meant to open this in https://github.com/rubocop/rubocop-rails/

**Comment by jcoyne** [comment]
🤦 Sorry. Stupid mistake.
