### ISSUE TITLE
reset_sessions! during system specs (ie. after_teardown) should occur as late as possible

### ISSUE THREAD

**Issue by timdiggins** [rspec/rspec-rails#2595]
**Is your feature request related to a problem? Please describe.**

It's really difficult to integrate the capybara-screenshot gem with rails system specs. (see https://github.com/mattheworiordan/capybara-screenshot/issues/225), but I think there is a generic issue for other libraries and integrations that you want the resetting of capybara sessions to happen as late as possible (and critically, after all RSpec Notifiers have formatted their output).

The minitest `after_teardown` callback occurs during the `after` hooks in the lifecycle of system specs, but occurs after all the `after` hooks (after example.run during the  `around`) in all other specs.  

https://github.com/rspec/rspec-rails/blob/9fb6c9c482da29b8803dd6f17b34d37a6367b8f2/lib/rspec/rails/adapters.rb#L69-L78

https://github.com/rspec/rspec-rails/blob/9fb6c9c482da29b8803dd6f17b34d37a6367b8f2/lib/rspec/rails/example/system_example_group.rb#L103-L116

The `after_teardown` is where the `Capybara.reset_sessions!` happens and (as of Rails 6.0) the take_screenshot occurs  occurs during before_teardown/
 
**Describe the solution you'd like**

I'd like the after_teardown to happen during an around callback.
This wouldn't be possible if rspec-rails was still supporting Rails v5.2

This may change behaviour for downstream users, but should be able to be included in 6 because a major•revision with an appropriate warning in the changelog?

I'll do a possible implementation/illustration in a PR.

**Describe alternatives you've considered**

I've considered whether this should be an adaptation of rails (I don't think there's any argument for changing rails).

I've considered if this should be an adaptation of downstream libraries such as capybara-screenshot (see https://github.com/mattheworiordan/capybara-screenshot/issues/225, this seems tricky to do -- though this may be down to architectural decisions in capybara-screenshot).

I've also attempted to monkey-patch either the rails `ActionDispatch::SystemTesting::TestHelpers::SetupAndTeardown` class in an ad hoc way in my own rails projects but this is quite difficult to do because it is already heavily monkey-patched by `RSpec::Rails::SystemExampleGroup`.

**Additional context**

I will raise this in rspec@googlegroups.com, but I think it's probably easier to see as set out in this issue.

**Comment by JonRowe** [comment]
Closed in #2596
