### ISSUE TITLE
Relishapp Rspec Down?

### ISSUE THREAD

**Issue by markoj3s** [rspec/rspec-rails#2607]
Hi,

I am trying to access Rspec's documentation but when I'm trying to access https://relishapp.com/rspec/ I am getting "404 - File or directory not found.".

**Comment by pirj** [comment]
Thanks for reporting.
This is a duplicate of [this issue](https://github.com/rspec/rspec-metagem/issues/70).
I'll close this one, and let's discuss there.

**Comment by markoj3s** [comment]
Thank you for the quick reply @pirj !
Sorry, I tried to search for an existing issue but couldn't find it. Thanks for sharing!
