### ISSUE TITLE
uninitialized constant ActiveRecord::TestFixtures

### ISSUE THREAD

**Issue by fbjork** [rspec/rspec-rails#261]
Just updated from rspec-rails 2.0.1 to 2.1.0 and I get the follow error:

/Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-rails-2.1.0/lib/rspec/rails/fixture_support.rb:9:in `<module:FixtureSupport>': uninitialized constant ActiveRecord::TestFixtures (NameError)
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-rails-2.1.0/lib/rspec/rails/fixture_support.rb:4:in`module:Rails'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-rails-2.1.0/lib/rspec/rails/fixture_support.rb:2:in `<module:RSpec>'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-rails-2.1.0/lib/rspec/rails/fixture_support.rb:1:in`<top (required)>'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`block in require'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:227:in `load_dependency'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-rails-2.1.0/lib/rspec/rails.rb:12:in `<top (required)>'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `block in require'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:227:in`load_dependency'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /Users/fredrik/Projects/profiles/spec/spec_helper.rb:5:in`<top (required)>'
    from /Users/fredrik/Projects/profiles/spec/controllers/application_controller_spec.rb:1:in `require'
    from /Users/fredrik/Projects/profiles/spec/controllers/application_controller_spec.rb:1:in`<top (required)>'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.1.0/lib/rspec/core/configuration.rb:334:in `load'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.1.0/lib/rspec/core/configuration.rb:334:in`block in load_spec_files'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.1.0/lib/rspec/core/configuration.rb:334:in `map'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.1.0/lib/rspec/core/configuration.rb:334:in`load_spec_files'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.1.0/lib/rspec/core/command_line.rb:18:in `run'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.1.0/lib/rspec/core/runner.rb:55:in`run_in_process'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.1.0/lib/rspec/core/runner.rb:46:in `run'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.1.0/lib/rspec/core/runner.rb:10:in`block in autorun'
rake aborted!

I'm not using activerecord in my app, could that have anything to do with it?

**Comment by debugferro** [comment]
This error keeps happenings.
My gemfile:
`gem 'mongoid', '~> 7.0.5'
group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 5.0.0'
  gem 'mongoid-rspec'
  gem 'database_cleaner'
  gem 'database_cleaner-mongoid'
end`

I created the app using --skip-active-record. In config/application.rb I have the following:
`require "rails"
require "active_model/railtie"
require "active_job/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"

require "rails/test_unit/railtie"`

Inside rails_helper.rb I have:
`config.use_active_record = false`
`require 'spec_helper'
require 'mongoid-rspec'
require 'mongoid'
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../config/environment', __dir__)

abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rspec/rails'

RSpec.configure do |config|
  config.use_active_record = false

  config.use_transactional_fixtures = false

  # config.include FactoryBot::Syntax::Methods
  config.include Mongoid::Matchers, type: :model

  config.infer_spec_type_from_file_location!

  config.filter_rails_from_backtrace!
end
`

With this file I keep getting this error when running rspec:

`ActiveRecord::ConnectionNotEstablished:
       No connection pool for 'ActiveRecord::Base' found.`
       
I tried to remove ActiveRecord constant inside rails_helper.rb, and surprisingly it is there:

`Object.send(:remove_const, :ActiveRecord)`

So I get:

`NameError:
       uninitialized constant ActiveRecord::TestFixtures::ActiveRecord`
       
 I tried to clean up gems, uninstall, and reinstall everything again, but this error keeps showing up. I compared this project with another one that is running rspec and mongodb, and both have the same configuration. I'm completely lost.

**Comment by JonRowe** [comment]
> ActiveRecord::ConnectionNotEstablished:
No connection pool for 'ActiveRecord::Base' found.

This is the error you need to fix, you have config somewhere requiring `active_record` in a way that connects it, try removing other gems?

**Comment by pirj** [comment]
@debugferro The easiest to find out what is requiring AR is to set a breakpoint (`binding.pry` or `puts caller_locations`) in `active_record.rb`. E.g.:
```
$ bundle show activerecord
/home/pirj/.rvm/gems/ruby-2.7.2@my-project/gems/activerecord-6.0.3.4
$ vim /home/pirj/.rvm/gems/ruby-2.7.2@my-project/gems/activerecord-6.0.3.4/lib/active_record.rb
```

If you're still troubled with this, please feel free to post on our mailing list https://rspec.info/help/

**Comment by debugferro** [comment]
@JonRowe @pirj 
Thank you for both answers. Yes, I think something was requiring AR. When I removed this part of the code from rails_helper.rb it started working:
````
require 'mongoid-rspec'
require 'mongoid'
````

I don't know which one of them, but what matters is that is working.
Thank you again!
