### ISSUE TITLE
Document view_assigns and make it part of the official API

### ISSUE THREAD

**Issue by pedz** [rspec/rspec-rails#2622]
I am attempting to write a view spec that adheres to the RSpec Style Guide.  In particular, [Instance Variables](https://rspec.rubystyle.guide/#instance-variables) are frowned upon.  The edit path for a Rails view requires a saved instance of the model.  The instance can be created with something like
```ruby
assign(:import_file, create(:import_file))
```
but `import_file` can not be accessed in the spec.  I'm not clear why this is desirable but assuming it is, then some way to access the instance needs to be provided.

And it is!  Using `view_assigns` the edit path can be produced for example with 
```ruby
let(:path) { import_file_path(view_assigns[:import_file]) }
```
My request is simply that this be documented and mentioned in the examples that use `assign`.

**Comment by JonRowe** [comment]
A more typical way of doing this in RSpec would be:

```
let(:file) { create(:import_file) }
let(:path) { import_file_path(file) }

it "does something with a file" do
  assign(:import_file, file)
  render
  expect(rendered).to match "Go to #{path} to download your file"
end
```

But as you've noted you have access to the Rails api for `view_assigns` which is documented as part of their API (its not our API) https://api.rubyonrails.org/classes/AbstractController/Rendering.html#method-i-view_assigns

**Comment by pedz** [comment]
Your approach is clearly better.  Thank you.
