### ISSUE TITLE
6.0.0 Release Loads .rspec Configuration

### ISSUE THREAD

**Issue by gordysc** [rspec/rspec-rails#2623]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
Rails version: 7.0.4
RSpec 3.11
  - rspec-core 3.11.0
  - rspec-expectations 3.11.1
  - rspec-mocks 3.11.1
  - rspec-rails 6.0.0
  - rspec-support 3.11.1

## Observed behaviour

For release 5.1.2 we could configure rspec-rails to use rails_helper.rb in the .rspec config file (instead of adding require `rails_helper` in each individual spec). 

With release 6.0.0 we appear to now load the `.rspec` config file when we use the Rails generator for creating a model. This then loads `rails_helper.rb` which throws a pending migration error since the generated model's migration has not yet run.

For example: 

```sh
rails g model user email password_digest

Failure/Error: abort e.to_s.strip

SystemExit:
  Migrations are pending. To resolve this issue, run:

          bin/rails db:migrate RAILS_ENV=development

  You have 1 pending migration:
```

## Expected behaviour

We should do one of the following:

1. Revert to the previous existing behavior (not sure if this change was intentional)
2. Document that requiring `rails_helper` in the `.rspec` configuration is deprecated moving forward
3. Or improve the check in the template rails_helper.rb when generating a model (unsure of how this would work)

## Can you provide an example app?

https://github.com/gordysc/rspec-generator-issue

**Comment by pirj** [comment]
This is most probably caused by [this change](https://github.com/rspec/rspec-rails/pull/2508/files#diff-568257156bf83ce38cb4fc9f6ad996242c5a50b7bac89b6689bc3ebdfa26135dR25). We need to load `.rspec`, but certainly `spec/rails_helper.rb` is not required to run generators.

I'd suggest wrapping all the `spec/rails_helper.rb` in a `if Rails.env.test?` as a workaround.

**Comment by gordysc** [comment]
Ah, that'd do it. Any reason that check couldn't be something added to the rails_helper that's generated on the install?

**Comment by pirj** [comment]
The primary reason is that some projects include parts that are testable without loading up the whole Rails env, and they don't need `spec/rails_helper.rb`. Some specs, e.g. custom cops, would require a different helper, `spec/rubocop_helper.rb` etc.

Our RSpec Core's `.rspec` initializer [only adds `--require spec_helper`](https://github.com/rspec/rspec-core/blob/71823ba11ec17a73b25bdc24ebab195494c270dc/lib/rspec/core/project_initializer/.rspec#L1).

There are also some scenarios when specs are called initially in the `development` env, and this is why we force-set the env to be test [here](https://github.com/rspec/rspec-rails/blob/0857cbcce9be7086431fd2a09de6abfdaba441f0/lib/generators/rspec/install/templates/spec/rails_helper.rb#L3).

**Comment by JonRowe** [comment]
We could add a note about it to the generated `rails_helper.rb` as this may be hit more than we think, I'd happily review a PR for that @gordysc
