### ISSUE TITLE
Is Minitest a dependency? I'm trying to remove it as a runtime dependency, and running into issues

### ISSUE THREAD

**Issue by ndbroadbent** [rspec/rspec-rails#2633]
I was [surprised to see that `minitest` is listed as a runtime  dependency](https://github.com/rails/rails/issues/45182#issuecomment-1304969910) in the ActiveSupport gemspec.

I spent some time trying to see if I could make this an optional dependency: https://github.com/DocSpring/rails/commit/f416f0c025b257a4d3ee903f7dfa2b24c23a4092

I got stuck when my application started crashing in `lib/rspec/rails/adapters.rb`. It looks like this file cannot be loaded if `minitest` is unavailable, but `minitest` is not listed as an explicit dependency for `rspec-rails`. (I guess it's a transitive dependency via activesupport.)

I tried this in `adapters.rb`:

```
    if defined?(Kernel.gem)
      begin
        gem 'minitest'
      rescue Gem::LoadError
      end
    else
      begin
        require 'minitest'
      rescue LoadError
      end
    end
    
    if defined? Minitest
      ...
```

But it started crashing in `fixture_support.rb`:

```
        include RSpec::Rails::SetupAndTeardownAdapter
        include RSpec::Rails::MinitestLifecycleAdapter
        include RSpec::Rails::MinitestAssertionAdapter
```

So I was just wondering if `rspec-rails` requires Minitest in order to run, or is it possible to completely remove the minitest gem from my application? I was under the impression that I only needed RSpec. Thanks!

**Comment by pirj** [comment]
If you'll load `active_support`, it would attempt to require `minitest`, right?
I don't see how it's possible to use Rails without Active Support.
So, as outlined in that Rails issue, it makes sense to attempt to untangle `active_support` from depending on `minitest` in runtime, and see if it works with `rspec-rails`, or do we still rely on the presence of e.g. `setup`/`teardown`.

Would you be up for such research and PRs?

**Comment by ndbroadbent** [comment]
@pirj Yes I was attempting to do that today, I forked Rails and tried to remove the minitest dependency: https://github.com/DocSpring/rails/commit/f416f0c025b257a4d3ee903f7dfa2b24c23a4092

That's what brought me to rspec-rails, since there seems to be a minitest dependency in here too. It looks like a lot of logic depends on some setup / teardown / fixtures code from minitest though, so I was a bit confused

**Comment by JonRowe** [comment]
`rspec-rails` is a wrapper for Rails test helpers within RSpec, Rails test helpers are all based on `minitest` and prior to that `test-unit` so we have a transitative dependency on `minitest` as Rails does, if you don't want to even have minitest on your system, you can use RSpec with Rails without `rspec-rails`, you can look at for example rack-test and setup your Rails app directly? Depends on what you are attempting to achieve here

**Comment by ndbroadbent** [comment]
Thanks @JonRowe, that makes sense! Sorry I didn't realize that, in that case it totally makes sense for minitest to be a dependency. (I just thought it might have been unneeded so wanted to see if it could be tidied up.)

**Comment by JonRowe** [comment]
If Rails were to make minitest optional I'd be happy to review a PR making that also possible here 👍
