### ISSUE TITLE
Rspec not fetching from controllers with '.to_json' of instances

### ISSUE THREAD

**Issue by bubbaspaarx** [rspec/rspec-rails#2634]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin21]
Rails version: Rails 6.1.7
RSpec version: RSpec 3.12

## Observed behaviour

I am not certain this is a direct rspec error but when testing a controller action, we expect our response to be a full json object of the instance we are fetching. What we receive though is a json object of 

```
=> render(json: @instance)
"{\"type\":\"class_name\"}"
```

If I manually call '.to_json' on my instance at the point of render

```
=> render(json: @instance.to_json)
<full object json response>
```

I get a full response back of my whole object, which is the expected behaviour and is matched with development and production environments. 

I can't see a reason why the implicit 'to_json' is not called when calling from rspec which is stated in the rails docs

 [![rails guide][1]][1]

  [1]: https://i.stack.imgur.com/NO2mQ.png

Any help is greatly appreciated. TIA

The controller action

```
def show
  render(json: @book)
end
```

book_controller_spec.rb
'json' is a custom JSONHelper which just parses the response.body

```ruby
RSpec.describe(Api::V1::BooksController, type: :controller) do
  context '#show' do
    it 'returns the book with the correct ID' do
      get :show, params: { id: 1 }
      expect(json[:id]).to(eq(1))
    end
  end
end
```

**Comment by pirj** [comment]
What the `response.body.read` in spec with `.to_json` in the controller and without it?

**Comment by bubbaspaarx** [comment]
Hi @pirj 

We get a 'NoMethodError' initially. - 'undefined method 'read' for.....(then the String)'. Happens with either .to_json or not. The only difference is that with .to_json we get the full expected object as a string.

**Comment by JonRowe** [comment]
I've experimented with this a bit and this is as far as I can see entirely a rails side decision, are you aware there are different formats for `as_json` / `to_json`? Maybe see if you can replicate the single node format and check out: https://api.rubyonrails.org/classes/ActiveModel/Serializers/JSON.html ?

Closing for now but if you do find something at fault ourside please re open
