### ISSUE TITLE
RSpec/FactoryBot/ConsistentParenthesesStyle

### ISSUE THREAD

**Issue by jcoyne** [rspec/rspec-rails#2635]
False positive on methods that have nothing to do with factory bot.
```
spec/test_app_templates/lib/generators/test_app_generator.rb:22:5: C: [Correctable] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call with parentheses
    generate 'blacklight:install', '--devise'
    ^^^^^^^^
```

We are not even using factory_bot

**Comment by JonRowe** [comment]
:wave: I think you have the wrong repo?

**Comment by pirj** [comment]
@jcoyne I can't transfer the issue cross-org, please feel free to open in [`rubocop-rspec`](https://github.com/rubocop/rubocop-rspec/issues).

**Comment by jcoyne** [comment]
Oops. Sorry. I've moved it to rubocop-rspec
