### ISSUE TITLE
Uninitialized constant "ControllerName" for anonymous controller

### ISSUE THREAD

**Issue by SylvanoTombo** [rspec/rspec-rails#2646]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.6
Rails version: 7.0.4
RSpec version:  3.11

## Observed behaviour
Controller name uninitialized for anonymous controller.

## Expected behaviour
Controller should be resolved.

## Can you provide an example app?
```
require "spec_helper"
require "rails_helper"

class OtherController < ApplicationController; end

RSpec.describe OtherController, :type => :controller do
  controller do
    def custom
      puts request.headers
    end
  end

  specify "manually draw the route to request a custom action" do
    routes.draw { get "custom" => "other#custom" }

    get :custom
    expect(response.body).to eq "custom called"
  end
end
```

Getting error:
NameError:
       uninitialized constant Other

**Comment by pirj** [comment]
May I kindly ask you for a full backtrace?

**Comment by JonRowe** [comment]
We test this in our cucumber tests almost verbatim (we render a response and your only `puts`ing some headers) however I tried your example locally and got:

```
 ActionController::MissingExactTemplate:
       OtherController#custom is missing a template for request formats: text/html
```

As I actually expect, your example returns no response so needs a template, adding back the render fixes this, so closing unless you can provide a reproduction.
