### ISSUE TITLE
Misleading error message for `have_been_enqueued` matcher with other enqueued jobs

### ISSUE THREAD

**Issue by janko** [rspec/rspec-rails#2649]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.6
Rails version: 6.1.6.1
RSpec version: 3.12
rspec-rails version: 6.0.1

## Observed behaviour

When I run the following expectation, it fails if there are other jobs enqueued:

```rb
expect(MyJob).to have_been_enqueued #~>
# expected to enqueue exactly 1 jobs, but enqueued 2
# Queued jobs:
#   AnotherJob job with [...], on queue default
```

## Expected behaviour

I expected the `have_been_enqueued` matcher to allow other jobs to be enqueued, because the naming suggests that it's only expecting that job to have been enqueued, not that also no other job has been enqueued.

With this behaviour, I don't know how to verify that a specific job was enqueued, while still allowing other enqueued jobs.

**Comment by janko** [comment]
Oh, the issue was that `MyJob` was being enqueued multiple times, but the error message showed another job class enqueued as being the problem. It seems there is room for improvement in the error message, so that it accurately says that `MyJob` was enqueued multiple times, and doesn't show any other enqueued jobs.

**Comment by JonRowe** [comment]
I'll happily review a PR to improve the error message

**Comment by janko** [comment]
Thanks, I realized I haven't found this output confusing anymore since I reported it, so I'm closing this 🙂
