### ISSUE TITLE
Helper method in a controller (created via `helper_method`) not being reachable in a RSpec helper test

### ISSUE THREAD

**Issue by weezhard0** [rspec/rspec-rails#2654]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.2.0
Rails version: 7.0.4.2
RSpec version:
RSpec 3.12
  - rspec-core 3.12.0
  - rspec-expectations 3.12.1
  - rspec-mocks 3.12.1
  - rspec-rails 6.0.1
  - rspec-support 3.12.0

## Observed behaviour

I am not sure if this is a bug or if I am missing something. When I create a helper method  using Rails `helper_method` method, I am not able to reach it in a Rspec helper test.

```
class ApplicationController < ActionController::Base
   helper_method :is_happy?

   private

   def is_happy?
      true
   end
end
```

```
it 'returns Sad when when is sad' do
      allow(helper).to receive(:happy?).and_return(false)

      expect(helper.show_mood).to eq "Sad"
end
```

But when I try to run this test, I got the following error:

> 
> Failure/Error: allow(helper).to receive(:is_happy?).and_return(false)
>        #<ActionView::Base:0x00000000009e70> does not implement: is_happy?

## Expected behaviour

Since I am stubing the helper method, I would expect the test to pass. 

## Can you provide an example app?

- https://github.com/weezhard0/demo-rails-rspec
- https://github.com/weezhard0/demo-rails-rspec/blob/main/spec/helpers/application_helper_spec.rb

**Comment by JonRowe** [comment]
I'm afraid you'll have to write a controller spec to test a controller helper, as its not reachable via `ApplicationHelper`.

**Comment by weezhard0** [comment]
> I'm afraid you'll have to write a controller spec to test a controller helper, as its not reachable via `ApplicationHelper` or a specific helper module. You might be able to run a helper example against the controller class but I'm not sure of any side effects that may ensue.

I am not and I don-t want to test the controller helper. I want to test method on ApplicationHelper. The problem is, this method  (helper), uses a helper method defined in the controller. And since I don't want to test it, neither rely on its implementation, I am trying to stub it. And this should be allowed. I saw a bunch of code here in github that do this.

**Comment by JonRowe** [comment]
You can do that, you just need to turn off verifying partial doubles for this test:

```
around(:example) do |example|
  without_partial_double_verification do
    example.call
  end
end
```
