### ISSUE TITLE
Times in --profile explanation?

### ISSUE THREAD

**Issue by dsusviela** [rspec/rspec-rails#2655]
This is not really a bug, but I didn't find anything on the docs, and don't know where to ask.

## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.7
Rails version: 7.0.4.2
RSpec version: 
  - rspec-core 3.11.0
  - rspec-expectations 3.11.0
  - rspec-mocks 3.11.0
  - rspec-rails 5.1.1
  - rspec-support 3.11.0

## Observed behaviour

I have a spec file with 13 examples, when running with the `--profile 13` running my examples shows that the total time spent on them only accounts for `18.3%` of the total time. I wonder where `rspec` is spending the rest of the time.

```
Top 13 slowest examples (0.14978 seconds, 18.3% of total time):
    0.04215 seconds
    0.02262 seconds
    0.01329 seconds
    0.01266 seconds
    0.01187 seconds
    0.01129 seconds
    0.01058 seconds
    0.00678 seconds
    0.0055 seconds
    0.00515 seconds
    0.00332 seconds
    0.00234 seconds
    0.00222 seconds

Finished in 0.81792 seconds (files took 2.86 seconds to load)
13 examples, 0 failures

```

**Comment by JonRowe** [comment]
Each example records it's own execution time, this doesn't take into account any time taken by RSpec itself to set the example up to run and specifically doesn't include any `:suite` or `:context` hooks you may have (as these times are shared across several specs), the load time is from the time taken to load `rspec/core` or the time from initialising the config to when the suite starts, so can be slightly inaccurate in odd load cases.

**Comment by JonRowe** [comment]
It might be a fun exercise for someone to capture timing of those hooks and include them into the meta data for examples so that the formatter can explain more / produce more accurate results

**Comment by pirj** [comment]
[`test-prof`](https://github.com/test-prof/test-prof) offers RSpecDissect that may be of some help.

**Comment by dsusviela** [comment]
@pirj thats sweet, i stumbled upon an article about the gem actually and optimizing tests, but it didn't mention anything about RSpecDissect. I'll take a look
