### ISSUE TITLE
Cannot access the document on relishapp



### ISSUE THREAD

**Issue by otorain** [rspec/rspec-rails#2658]
I want to read the document by this link: https://relishapp.com/rspec , But I got an error like this

![S30306-20082959.png](https://user-images.githubusercontent.com/25400144/223106568-93694a3e-fe70-45e4-9074-4140b85e535a.png)

**Comment by JonRowe** [comment]
Unforunately RelishApp is down, possibly permanently see: https://ruby.social/@RSpec/109953139797068285

Closing because there is nothing we can do about this, we are looking to replace the Relish hosting.

**Comment by billwanjohi** [comment]
I'm sorry, I don't understand; what is the recommended way of consuming rspec-rails documentation? There are still several references to RelishApp in the main branch: https://github.com/search?q=repo%3Arspec%2Frspec-rails%20relishapp&type=code

I did find https://rspec.info/features/6-0/rspec-rails/, but that seems to only be one version.

Is there a local option?

**Comment by JonRowe** [comment]
The RSpec website, e.g. https://rspec.info/features/6-0/rspec-rails/ is now the recommended way to consume our documentation, there are older api docs for rspec-rails, but I've not gone back and generated docs for unsupported versions, you can read the features for any version in the repo e.g. https://github.com/rspec/rspec-rails/tree/5-1-maintenance/features, doing so locally would require downloading the source and reading that way, theres no way to render the features locally that I'm aware of.

**Comment by JonRowe** [comment]
(Also thanks for the reminder to go link pruning, they've all been replaced now cheers 😂 )
