### ISSUE TITLE
DEPRECATION WARNING: TestFixtures#fixture_path is deprecated  and will be removed in Rails 7.2

### ISSUE THREAD

**Issue by jasnow** [rspec/rspec-rails#2661]
FYI: Getting 
```
DEPRECATION WARNING: TestFixtures#fixture_path is deprecated 
and will be removed in Rails 7.2. Use #fixture_paths instead. (called from block in 
<module:FixtureSupport> at /usr/local/rvm/gems/ruby-3.2.1@ruby3.2-railsedge/
gems/rspec-rails-6.0.1/lib/rspec/rails/fixture_support.rb:24)
```
while running "rake" command.

**Comment by pirj** [comment]
Would you like to send a PR to fix that, @jasnow ?

**Comment by jasnow** [comment]
Forked, cloned, ran "bundle" and "rake" and got this (after a long time):
```
173 scenarios (173 passed)
640 steps (640 passed)
8m1.161s
```
Let you deal with
```
'archive-tar-minitar' has been deprecated; just install 'minitar'.
```
and
```
Multiple cases of:
    /usr/local/rvm/gems/ruby-3.2.1@ruby3.2-railsedge/gems/mail-2.8.1/lib/
    mail/parsers/address_lists_parser.rb:32457: warning: statement not reached
```
 Before I change anything, is that correct behavior?

**Comment by jasnow** [comment]
I will be patient.

**Comment by jasnow** [comment]
Example: Run "rake" on this repo: https://github.com/jasnow/tasks_edge

**Comment by jasnow** [comment]
This newsletter mentioned this deprecation.

**Comment by JonRowe** [comment]
Thanks for reporting, we don't need any further citation, just someone to find the time to fix it, I reopened so people can see this is an unfixed issue we'd like someone to tackle.
