### ISSUE TITLE
Does RSpec have :see_other matcher, like "be_see_other" ?

### ISSUE THREAD

**Issue by loqimean** [rspec/rspec-rails#2674]
### Problem:
Hi, I seen that RSpec (at least requests spec) doesn't have `be_see_other` matcher, what is really needed for turbo_stream requests testing, I'd  just have an error:
<img width="1421" alt="Screenshot 2023-04-27 at 17 12 36" src="https://user-images.githubusercontent.com/49816584/234889015-150fc160-feef-414f-ae15-ef838c3f2391.png">

### Possible solution:
Add `be_see_other` matcher))

**Comment by pirj** [comment]
`be_ok` etc don't come from `rspec-rails`, but are rather `rspec-expectations`' [predicate matchers](http://rspec.info/features/3-12/rspec-expectations/built-in-matchers/predicates/), dynamic matchers against object's predicate methods.
[`ActionDispatch::TestResponse`](https://api.rubyonrails.org/classes/ActionDispatch/TestResponse.html) ([or actually]
(https://github.com/rails/rails/blob/7c70791470fc517deb7c640bead9f1b47efb5539/actionpack/lib/action_dispatch/http/response.rb#L88) [`Rack::Response::Helpers`](https://github.com/rack/rack/blob/ab360dd5ba16361c562bdf482af8ab14141807a6/lib/rack/response.rb#L172)) don't implement `see_other?`. This is what the error tells.
I suggest using `.to have_http_status(:see_other)` for such HTTP codes.
