### ISSUE TITLE
Allow erb extension for template files

### ISSUE THREAD

**Issue by BigBigDoudou** [rspec/rspec-rails#2683]
**Is your feature request related to a problem? Please describe.**

If I want to override the default template, for example `lib/generators/rspec/model/templates/model_spec.rb`, I need to create a file `lib/templates/rspec/model/model_spec.rb`. In this file, there is erb syntax. Because of that, some checks (rubocop...) do not pass.

**Describe the solution you'd like**

When searching for templates, check for files with rb or erb extensions.

**Describe alternatives you've considered**

Currently I need to exclude the templates from the checks (pre-commit hooks...).

**Additional context**

Example: let's just say I want to remove `require 'rails_helper'` from the template. I copy-paste the content from `lib/generators/rspec/model/templates/model_spec.rb` into `lib/templates/rspec/model/model_spec.rb` then I do the changes. I run rubocop::

<img width="600" alt="Screen Shot 2023-06-19 at 09 19 07" src="https://github.com/rspec/rspec-rails/assets/34060090/530be8f8-f987-4035-82ce-45a66237a7ec">

**Comment by JonRowe** [comment]
:wave: The generators are based off Rails generators, which basically take a path to look for and I'm not sure how well that would supporting looing for multiple files, and then how priority would work for that. So I'm going to close this as "not planned".

However you should be able to easily add `Exclude: lib/templates/rspec/**/*.rb` to your rubocop config either for all rules or individual rules which would solve your problem.
