### ISSUE TITLE
`url_for` fails to generate route with using `resource` method in config/routes.rb

### ISSUE THREAD

**Issue by muramasa64** [rspec/rspec-rails#2688]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.2.2
Rails version: 7.0.7.2
RSpec version: 3.12
- rspec-core 3.12.2
- rspec-expectations 3.12.3
- rspec-mocks 3.12.6
- rspec-rails 6.0.3
- rspec-support 3.12.1

## Observed behaviour

When:

- add route `resource :redirect, expect: [:new, :create, :destroy]` to config/routes.rb
- controller has `show` action
- add redirect test for redirect#show

Then:

- Test 1 (Failure):  use `url_for`
- Test 2 (success): use `<controller>_url`

```
$ rspec
F.

Failures:

  1) redirects redirect to root using url_for
     Failure/Error: get url_for(args.merge(action: :show))
     
     ActionController::UrlGenerationError:
       No route matches {:action=>"show", :controller=>"redirects"}
     # ./spec/requests/redirects_spec.rb:12:in `block (2 levels) in <top (required)>'

Finished in 0.06852 seconds (files took 1.54 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/requests/redirects_spec.rb:11 # redirects redirect to root using url_for
```

If I use `get 'redirect' => 'redirects#show' in config/routes.rb, both tests pass.

## Expected behaviour

- both tests pass

## Can you provide an example app?
- [repository](https://github.com/muramasa64/rails-bug-app)

**Comment by pirj** [comment]
Do you think it’s rspec-rails to blame? Can you please confirm that this is not an issue with Rails’ built-in testing?

**Comment by muramasa64** [comment]
Hmm...

I also tried writing test cases with minitest. `url_for` returned `No route matches` as well.

I understand that this is not an rspec-rails issue. The issue will be closed.

```ruby
require 'test_helper'

class RedirectsControllerTest < ActionDispatch::IntegrationTest
  include Rails.application.routes.url_helpers

  # failuer
  test "should redirect root" do
    get url_for(host: 'localhost', controller: 'redirects', action: :show)
    assert_response :redirect
  end

  # success
  test "should redirect root2" do
    get redirect_url
    assert_response :redirect
  end
end
```

**Comment by muramasa64** [comment]
This problem was not rspec-rails.
