### ISSUE TITLE
"expect to receive with" throws error when switching to Rails 7.1

### ISSUE THREAD

**Issue by fsuchan** [rspec/rspec-rails#2699]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.2.1
Rails version: 7.1.1
RSpec version: 3.12 (rspec-rails 6.0.3)

## Observed behaviour

Example spec `expect(Worker).to receive(:perform_async).with(param1, param2)`

returns `ArgumentError: wrong number of arguments (given 2, expected 0)`

Switching to deprecated `Worker.should_receive(:perform_async).with(param1, param2)` passes.

## Expected behaviour

Passes with "expect to receive with" syntax.

**Comment by pirj** [comment]
Can you reproduce it with a regular object?
What is the backtrace? Can you set a breakpoint and see what method is called with two arguments, which doesn’t really accept any?
Is that a Sidekiq worker Worker?

**Comment by fsuchan** [comment]
@pirj yes, that's a Sidekiq worker 👍

Full example that worked on Rails 7.0 but not on 7.1:
```
it 'sends an email' do
  user = Fabricate(:user, encrypted_password: nil)
  
  expect(EmailWorker).to receive(:perform_async).with('UserInvite::Email', user.id)
  
  Invite::Create.call(user:)
end
```

**Comment by StanBright** [comment]
I have a possibly relevant issue with the same gem/ruby versions. It does not fail with ArgumentError.

However, it carries the stub/expectation through different examples and fails with a multiple calls error:

```ruby
     Failure/Error: expect(ListSubscriptionMailer).to receive(:email_confirmation).and_return(mock_mail)

       (ListSubscriptionMailer (class)).email_confirmation(*(any args))
           expected: 1 time with any arguments
           received: 2 times with any arguments
```

**Comment by pirj** [comment]
@StanBright i suggest you to yse ‘and_wrap_original’ and to figure out what makes the second call.

**Comment by StanBright** [comment]
The second call is coming from a different spec case. The specs are run randomly, and it fails randomly - i.e. if the spec with the mocked expectation is run before the other case, there's no error.

The same mocking works fine on Rails 7.0 projects. Seemingly, there's something odd with Rspec and Rails 7.1.

**Comment by vrinek** [comment]
Regarding the initial issue, I am getting the same for every `with` in my specs after upgrading to Rails 7.1:
```
     ArgumentError:
       wrong number of arguments (given 2, expected 0)
     # /usr/local/bundle/gems/activesupport-7.1.1/lib/active_support/core_ext/object/with.rb:24:in `with'
     # ./spec/lib/mail_configurator_spec.rb:43:in `block (4 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

According to [ActiveSupport's changelog](https://github.com/rails/rails/blob/v7.1.1/activesupport/CHANGELOG.md#rails-710beta1-september-13-2023), `Object#with` was added with 7.1.0.beta1:
> *   Add `Object#with` to set and restore public attributes around a block
> 
>     ```ruby
>     client.timeout # => 5
>     client.with(timeout: 1) do
>       client.timeout # => 1
>     end
>     client.timeout # => 5
>     ```

Relevant commit: https://github.com/rails/rails/commit/1884323574b35b3a2286850f3c98f677633728f1

**Comment by pirj** [comment]
Thanks for digging that, @vrinek 
The problem is here then 
‘’’
          next if own_methods.include?(method)
‘’’
https://github.com/rspec/rspec-mocks/blob/868bf98d2aae5f0db15441a41b86b5f9346a12dd/lib/rspec/mocks/matchers/receive.rb#L60

We have a fix for this already, but it doesn’t work somehow https://github.com/rspec/rspec-mocks/commit/a2af97db4799477463fcc75d73373eb64f63ba83

Cc @byroot

**Comment by byroot** [comment]
If someone share a reproduction script or repo, I'll happily debug this. But right now the repro steps are too blurry for me to investigate.

**Comment by justisb** [comment]
On Rails 7.1 any test that uses the `expect(x).to receive(:foo).with('bar')` pattern will break because Rails introduced their own `Object#with`patch in ActiveSupport that interferes with the RSpec `with` method: https://github.com/rails/rails/blob/7-1-stable/activesupport/lib/active_support/core_ext/object/with.rb

**Comment by justisb** [comment]
Ah this was actually fixed for us by ensuring the rspec-mocks dependency was updated to 3.12.5, rather than only checking that rspec/rspec-rails was up-to-date.

I notice the original issue does not include the rspec-mocks version so it's possible that it's the same issue of not noticing the child dependency versions.

**Comment by JonRowe** [comment]
There was a patch kindly provided by byroot in rspec-mocks 3.12.5 (current is 3.12.6) @fsuchan what version of rspec-mocks are you running?

**Comment by fsuchan** [comment]
@JonRowe can confirm, 3.12.6 solves the issue, we were still on 3.12.3 👍

**Comment by vimalloc** [comment]
I'm running into this exact issue, except it's not rspec-mocks, but instead `enqueue_job`:

```ruby
  it 'does not enqueue a job' do
    expect { 'Foo'.downcase }.to not_enqueue_job.with('Bar')
  end
```

I think we have a few custom matchers that run into this issue too.

I'm gonna open an issue on the rails repo to see what they say, but I wanted to bring this up here as well!

Cheers.

**Comment by byroot** [comment]
@vimalloc I suspect `not_enqueue_job` is in something like rspec-rails, better open your issue there. You can tag me as well, I'll have a look if I can.

**Comment by vimalloc** [comment]
@byroot thank you! I have an issue with a lot more details here, if you want to look at it! https://github.com/rails/rails/issues/49958

**Comment by byroot** [comment]
I provided a workaround on the Rails issue, and started working on a fix at https://github.com/rspec/rspec-expectations/pull/1434.

If there is a maintainer that could approve CI so I can see what need to be fixed for very old rubies I can't run on my machine, that would be much appreciated.

**Comment by kashiftariq1997** [comment]
expect(assigns(:documents_to_review)).to_query include(*investment.investor_signature_envelopes.review)

get error:
 ArgumentError:
       include() is not supported, please supply an argument

**Comment by pirj** [comment]
Apparently, you’re passing an empty array splatted, resulting in no arguments to `include`, @kashiftariq1997 

This issue is unrelated. I suggest you to seek further help using https://rspec.info/help, SO, or open a new issue with proper reproduction example.

**Comment by byroot** [comment]
Please provide a repro and I'll fix it.

**Comment by JonRowe** [comment]
The issue is not within this repo specifically, the relevant change that`7.1.0` used is to change from a simple method alias (which means you get the same matcher class) to one using `alias_matcher` which is an `rspec-expectations` feature using a `AliasMatcher` class that allows the description to be tweaked.

**Comment by byroot** [comment]
`AliasedMatcher` inherits from `MatcherDelegtor`, which itself inherits from `BaseDelegator`, so should be fixed by https://github.com/rspec/rspec-expectations/pull/1434 as well.

@themilkman are you using the latest rspec gems?

**Comment by pramodtech** [comment]
I had to downgrade rspec-expectations from 3.13.3 to 3.13.0 to fix this issue.
