### ISSUE TITLE
 :git => "git://github.com/rspec/rspec.git" Not working anymore

### ISSUE THREAD

**Issue by zhengxiangyue** [rspec/rspec-rails#2734]
Hi, `git://github.com/rspec/rspec.git` used to work fine until recently. What has been changed is it removed or made private? Thanks

**Comment by JonRowe** [comment]
Hi the repo was moved to `github.com/rspec/rspec-metagem` some time ago, but the redirect has recently broken because we're preparing a monorepo at `rspec/rspec`

**Comment by zhengxiangyue** [comment]
Thanks @JonRowe . Is it safe for us to replace the git source with `rspec-metagem`? Is there plan to truncate/remove that repo in the future? Thanks.

**Comment by JonRowe** [comment]
It will be archived when the monorepo is ready but we won't remove it
