### ISSUE TITLE
Controllers specs don't currently work on the Rails main branch (8.0.0.alpha)

### ISSUE THREAD

**Issue by jeromedalbert** [rspec/rspec-rails#2761]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.3.1
Rails version: main branch (8.0.0.alpha)
RSpec version: 6.1.2

## Observed behaviour

When running a controller spec, I get the following error (see reproduction steps in the reproduction section of this issue):

```
Failures:

  1) HelloController#index
     Failure/Error: before { get :index }

     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"hello"}
```

## Expected behaviour

Spec should pass:

```
.

Finished in 0.0127 seconds (files took 0.39717 seconds to load)
1 example, 0 failures
```

## Can you provide an example reproduction?

Here is a minimal reproduction of the issue:

```ruby
# my_app.rb
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails', branch: 'main'
  gem 'rspec-rails', '6.1.2'
end

require 'rails'
require 'action_controller/railtie'
require 'rspec/rails'

class MyApp < Rails::Application
  config.eager_load = false

  routes.append { root to: 'hello#index' }
end

MyApp.initialize!

class HelloController < ActionController::Base
  def index
    render plain: 'Hello'
  end
end

describe HelloController, type: :controller do
  describe '#index' do
    before { get :index }

    it { expect(response).to be_successful }
  end
end

RSpec::Core::Runner.run([$__FILE__])
```

Run this file with `ruby my_app.rb`, and the spec should fail. It passes if you change to `gem 'rails', github: 'rails/rails', ref: 'a27a1751cfd499f69499e943f12e3400b55a323e'`, and fails for the commit with `gem 'rails', github: 'rails/rails', ref: 'e97db3b3957781c781a61fb01265feb2b57688bb'`. Here is a link to the commit: https://github.com/rails/rails/commit/e97db3b3957781c781a61fb01265feb2b57688bb.

### Additional information

- Since that commit is very recent (last week) I wasn't sure whether to file a bug here or in https://github.com/rails/rails. I decided to file it here.
- A current workaround to make the spec pass is to add `before { Rails.application.reload_routes! }`  in the spec, or `config.before(:suite) { Rails.application.reload_routes! }` in your rails helper.

**Comment by jrafanie** [comment]
@jeromedalbert not sure if you noticed but changing to eager_load makes your example pass:

```
  config.eager_load = true
```

Note, rails [defaults](https://github.com/rails/rails/blob/1b534a4d102510c2594db3ca95259612183c4089/railties/lib/rails/generators/rails/app/templates/config/environments/test.rb.tt#L18) to eager loadin test for CI in new apps.

**Comment by jeromedalbert** [comment]
Yeah, the main issue is when running tests on one's local.

**Comment by jrafanie** [comment]
> A current workaround to make the spec pass is to add before { Rails.application.reload_routes! } in the spec, or config.before(:suite) { Rails.application.reload_routes! } in your rails helper.

I wonder if makes sense to eager load routes before it tries to fetch the routes in the specific types of example groups: [controller](https://github.com/rspec/rspec-rails/blob/4ab08fa954fe4e0ae6f2302fa7201dcad3f11521/lib/rspec/rails/example/controller_example_group.rb#L185), [request](https://github.com/rspec/rspec-rails/blob/4ab08fa954fe4e0ae6f2302fa7201dcad3f11521/lib/rspec/rails/example/request_example_group.rb#L22), [routing](https://github.com/rspec/rspec-rails/blob/4ab08fa954fe4e0ae6f2302fa7201dcad3f11521/lib/rspec/rails/example/routing_example_group.rb#L40), [system](https://github.com/rspec/rspec-rails/blob/4ab08fa954fe4e0ae6f2302fa7201dcad3f11521/lib/rspec/rails/example/system_example_group.rb#L157) by adding something like:

```ruby
        routes_reloader = ::Rails.application.routes_reloader
        routes_reloader.execute_unless_loaded if routes_reloader&.respond_to?(:execute_unless_loaded)
```

**Comment by jeromedalbert** [comment]
Looks like the breaking commit that introduced deferred routes was [reverted](https://github.com/rails/rails/commit/d189cbcb565e41c4d66ae33b323a4ec60889da7a) for now, and Rails main is working is working at the moment.

**Comment by pirj** [comment]
Thanks for the heads-up. Can this be closed, or is there anythibg actionable left?
