### ISSUE TITLE
raise_error assertions in request specs are failing on Rails 7.2+

### ISSUE THREAD

**Issue by J-Marriott** [rspec/rspec-rails#2786]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.2.2
Rails version: 7.2.1
RSpec version: 6.1.4

## Observed behaviour

I'm attempting to upgrade a project from Rails 7.1.3.4 to Rails 7.2.1 and request specs that test for an an error being raised are failing.

The tests fails on 7.2+ and pass on Rails versions <=7.1.3.4

I generated a new test app and got the same results as above.

I've updated my request specs to assert the response (which passes), but thought it was odd that this behaviour changed between Rails versions.

```
class ApplicationController < ApplicationController
  def index
    raise_error StandardError.new('This is an error')
  end
end
```

```
require 'rails_helper'

RSpec.describe "Applications", type: :request do
  describe "GET /index" do
    it 'raises an error' do
      expect { get '/index' }.to raise_error
    end
  end
end
```

Rails 7.2.1

![image](https://github.com/user-attachments/assets/ebdbeffc-cd7f-4f50-b97a-07fa3eccba13)

and on Rails 7.1.3.4

![image](https://github.com/user-attachments/assets/1477e431-6d92-4fe6-90e5-8b4281781d81)

## Can you provide an example reproduction?

https://github.com/J-Marriott/test-rails-rspec

**Comment by pirj** [comment]
What exception is raised with Rails 7.1 exactly?

**Comment by pirj** [comment]
Do you intentionally use `raise_error` without a specified exception? Bacause this can conceal type errors, argument errors and such.
RSpec [emits a warning](https://github.com/rspec/rspec-expectations/blob/2bf42aaa1621202f0fb71b371dbf6c3fec1f4291/lib/rspec/matchers/built_in/raise_error.rb#L189) for such usage, and there’s a [cop](https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecunspecifiedexception) to prevent such usage.

**Comment by J-Marriott** [comment]
The original spec was for missing parameters and the test was to confirm ActionController::ParameterMissing was raised, which passed on 7.1. 

I can see the exception is raised in the logs, but the assertion fails.

**Comment by pirj** [comment]
> By default, Rails will attempt to rescue from exceptions raised during tests and respond with HTML error pages. This behavior can be controlled by the [config.action_dispatch.show_exceptions](https://guides.rubyonrails.org/configuring.html#config-action-dispatch-show-exceptions) configuration.

I don’t know why it’s still mentioned in the Rails Guides, because in the 7.2 release notes it’s said to be [removed](https://guides.rubyonrails.org/7_2_release_notes.html#action-pack-removals).

In request specs, just like in underlying integration tests, you make expectations against the HTTP response, and supporting propagation of exceptions was eventually going to happen.

Please adjust your examples to expect the HTTP code Rails sends in the response.
