### ISSUE TITLE
Remove `infer_spec_type_from_location!` from generator

### ISSUE THREAD

**Issue by runephilosof-abtion** [rspec/rspec-rails#2803]
**Is your feature request related to a problem? Please describe.**
Be consistent. Don't make infer spec types the default, and then also generate the types in the spec files. Also don't describe it as opt-in, when it is on by default.

rubocop-rails has [a cop](https://docs.rubocop.org/rubocop-rspec_rails/cops_rspecrails.html#rspecrailsinferredspectype) that helps with this inconsistency and removes the types in the spec files
> After setting up rspec-rails, you will have enabled config.infer_spec_type_from_file_location! by default in spec/rails_helper.rb. This cop works in conjunction with this config. 

**Describe the solution you'd like**
Remove `infer_spec_type_from_location!` from https://github.com/rspec/rspec-rails/blob/124cbcb2c689e6e9addaaac482b6ff2ec2342684/lib/generators/rspec/install/templates/spec/rails_helper.rb#L83

It is described as the old behavior.
https://github.com/rspec/rspec-rails/blob/124cbcb2c689e6e9addaaac482b6ff2ec2342684/Changelog.md?plain=1#L779
> The old behaviour

But it is not very old or opt-in, because it is still enabled by default in the generator.
[This PR](https://github.com/rspec/rspec-rails/pull/1002#issue-31913596) describes it as "truly opt-in".
But, for that to be true, `infer_spec_type_from_location!` would have to be commented out or removed in the generator.

**Describe alternatives you've considered**
Make it configurable whether `type: ` is generated by the spec generators
https://github.com/rspec/rspec-rails/blob/124cbcb2c689e6e9addaaac482b6ff2ec2342684/lib/generators/rspec/model/templates/model_spec.rb#L4

**Additional context**

**Comment by JonRowe** [comment]
Thanks for the heads up, I agree it should be at least commented out and the wording flipped, so it is.
