### ISSUE TITLE
InferredSpecType not working with Rails 8.

### ISSUE THREAD

**Issue by joel** [rspec/rspec-rails#2815]
The exact same view spec pass with 

```
Ruby version: 3.3.6
Rails version: 7.2.2
RSpec version: 7.1.0
```

but fails with 

```
Ruby version: 3.3.6
Rails version: 8.0.0
RSpec version: 7.1.0
```

```
require "rails_helper"

RSpec.describe "users/new" do
  before do
    assign(:user, User.new(name: "MyString"))
  end

  it "renders new user form" do
    render

    assert_select "form[action=?][method=?]", users_path, "post" do
      assert_select "input[name=?]", "user[name]"
    end
  end
end
```

```
 NoMethodError:
       undefined method `assign' for #<RSpec::ExampleGroups::UsersNew0x000000012e4d0150>
```

**Comment by joel** [comment]
Okay, it feels the [InferredSpecType](https://www.rubydoc.info/gems/rubocop-rspec_rails/RuboCop/Cop/RSpecRails/InferredSpecType) is failing to its job.

```
require "rails_helper"

RSpec.describe "users/new", type: :view do
  before do
    assign(:user, User.new(name: "MyString"))
  end

  it "renders new user form" do
    render

    assert_select "form[action=?][method=?]", users_path, "post" do
      assert_select "input[name=?]", "user[name]"
    end
  end
end
```

Is passing

**Comment by pirj** [comment]
Is this spec generated or hand-written?

With inferring option and turned off, you have to add type metadata.

The cop doesn’t fail, it is marked as unsafe and for a good reason - it has no way to know if inferring is on or off. If inferring is off, disable it immediately the cop, it’s what its doc says.

**Comment by joel** [comment]
Okay, I see this is a recent change [Comment out infer_spec_type_from_file_location! in generated rails_helper.rb](https://github.com/rspec/rspec-rails/commit/efca5295a196d74c187ebd0349abd10903c68928#diff-86c6eceb5f674cb6e3590f6cf646ebaaf395fa52a578310c21e2af16814e75aeL83), I use a template to set up my rails app, I did not spot that regression. Thanks.
