### ISSUE TITLE
RSpec for Rails 8 Authentication

### ISSUE THREAD

**Issue by BlazingRockStorm** [rspec/rspec-rails#2819]
Rails 8 introduces a basic authentication generator with the default test file:
```
test/mailers/previews/passwords_mailer_preview.rb
```
It just the password mailer test by Minitest

I think it is a good idea to add RSpec generator for Rails 8 built-in authenticator.

For the time being, the tests is only for sign in, sign out and reset password features.

If being approved by the RSpec team, I will make a pull request.

**Comment by pirj** [comment]
Sounds like a reasonable addition. A PR is welcome.

**Comment by JonRowe** [comment]
This was added in #2811
