### ISSUE TITLE
controller is nil in global before(:each, :type => :controller) hook

### ISSUE THREAD

**Issue by trkoch** [rspec/rspec-rails#391]
``` ruby
RSpec.configure do |config|
  config.before(:each, :type => :controller) do
     # controller is nil
  end
end
```

This has already been reported in the legacy branch, see https://github.com/dchelimsky/rspec/issues/23. I figured I move it to the correct branch, hope thats okay.

**Comment by SergeyBukhman** [comment]
So this was never really fixed, right? This still happens to me: http://stackoverflow.com/questions/6394414/rspec-rails-login-filter

**Comment by cupakromer** [comment]
@SergeyBukhman this is a very old issue and the SO post is also fairly outdated. Controller specs are not meant to run arbitrary requests against (those are `request` or `feature` specs).

Please log a new issue for the behavior you are seeing including your Ruby, RSpec, and Rails versions. :blue_heart:
