### ISSUE TITLE
:bypass_rescue no longer available in ControllerExampleGroup

### ISSUE THREAD

**Issue by lenny** [rspec/rspec-rails#425]
I posted about this on the rspec-users mailing list and David requested a ticket so.....

Me

> As best I can tell, bypass_rescue from rspec-rails-1 is no longer part of rspec-rails, '> 2'. I had been using it on occasion for things like:

```
describe CorrespondencesController do
  ...
  describe '#show' do
    it "should raise an AuthorizationError if current user is not the correspondent " do
      bypass_rescue
      ...
      expect { do_get }.to raise_error(AuthorizationError)
```

David

> No guarantees since so much changed in Rails between v2 and v3, but if it's reasonable to add I think we should.

**Comment by archonic** [comment]
Sorry to raise the dead here but this method is still described in the docs:
https://relishapp.com/rspec/rspec-rails/docs/controller-specs/bypass-rescue

But using rspec-rails 3.8.2, I'm seeing that there's no method `bypass_rescue`.

**Comment by benoittgt** [comment]
Hello @archonic 

Can you provide a test where you have this issue?

**Comment by JonRowe** [comment]
@archonic this is for controller specs, not request specs.
