### ISSUE TITLE
Undefined method assigns in a controller spec.

### ISSUE THREAD

**Issue by fivetwentysix** [rspec/rspec-rails#468]
```
NoMethodError:
       undefined method `assigns' for #<RSpec::Mocks::MessageExpectation:0x007f953e5183a0>
```

Source:

```
require 'spec_helper'

describe CompaniesController do

  describe "GET 'new'" do
    it "initiates a company" do
      Company.should_receive(:new).assigns(:company)
      get :new
      assigns(:company).should == Company.new
    end

    it "returns http success" do
      get :new
      response.should be_success
    end
  end

end
```

Project: https://github.com/PatrickMa/hacker_story/tree/rspec_problem

**Comment by ZASMan** [comment]
I'm having this issue when testing a post request now, is the above syntax still correct?

**Comment by JonRowe** [comment]
No, this issue was caused by `Company.should_receive(:new).assigns(:company)` the mock does not support `.assigns(:company)`, simply changing it to `Company.should_receive(:new)` would have removed the error.
