### ISSUE TITLE
render not rendering correct template in view spec

### ISSUE THREAD

**Issue by midas** [rspec/rspec-rails#541]
I am currently using a view spec to test a [Rabl](https://github.com/nesquena/rabl) index template that renders JSON or XML.  I also have an index template for rendering html.  The file structure looks like:

```
app/
  views/
    things/
      index.html.haml
      index.rabl
spec/
  views/
    things/
      index.html_spec.rb
      index.rabl_spec.rb
```

The [Rabl](https://github.com/nesquena/rabl) template has no mime type as it is shared between XML and JSON.

The spec for the [Rabl](https://github.com/nesquena/rabl) view is spec/views/things/index.rabl_spec.rb and it contains:

``` ruby
require 'spec_helper'

describe 'things/index.rabl' do

  before :each do
    assign :things, things

    render
    # render :template => 'things/index.rabl'
    # render :file => 'things/index.rabl'
  end

  let :things do
    [
      thing1,
      thing2
    ]
  end

  let :thing1 do
    Factory :thing
  end

  let :thing2 do
    Factory :thing
  end

  it "should have the correct JSON" do
    debugger
    rendered.should be_json_eql( %(
      {
        "things":
        [
          {
            "thing":
            {
            }
          }
        ]
      }
    ) )
  end

end
```

When i run the spec it fails due to an exception for a nil variable that is not used in the [Rabl](https://github.com/nesquena/rabl) template.  The variable is actually used in the things/index.html.haml template.  In addition, the things/index.html.haml file appears in the stack trace for the exception.  I have also tried calling the render method with the :template and the :file options, as you can see in the commented code above.

I placed a breakpoint in the lib/rspec/rails/example/view_example_group.rb  file at line 46 and checked the options variable's contents.  The contents look completely sane.

In another [Rabl](https://github.com/nesquena/rabl) spec I have that is for my API only (does not an index.html.haml template) the [Rabl](https://github.com/nesquena/rabl) spec is working as expected.

 I am at a loss for why this is happening.

**Comment by mhussain654** [comment]
vvv
