### ISSUE TITLE
Support for decoding signed cookies

### ISSUE THREAD

**Issue by kennethkalmer** [rspec/rspec-rails#545]
It would be great if rspec-rails could support decoding signed cookies in the controller specs.
- Reference: [StackOverflow question](http://stackoverflow.com/a/9094206/284612)
- Refinement: [SignedCookies helper](https://gist.github.com/2694930)

I'd be willing to fork and take a stab at this if it stands a chance of being accepted into the project.

**Comment by h8rry** [comment]
Any updates to this?
