### ISSUE TITLE
Does rspec work with optional path scopes?

### ISSUE THREAD

**Issue by karl-petter** [rspec/rspec-rails#562]
Hi,

I'm not an expert on rails and have just started to use rspec. I'm creating a new app which will be in several different languages. So as suggested here http://guides.rubyonrails.org/i18n.html#setting-the-locale-from-the-url-params I use an optional path scope in my routes.rb to get the locale:

```
  scope "(:locale)", :locale => /en|sv/ do
    resources :badges
  end
```

but when i do that my specs starts to fail and complains about missing routes.

```
badges/show renders Name and the badge image.
     Failure/Error: render
     ActionView::Template::Error:
       No route matches {:action=>"edit", :controller=>"badges", :locale=>#<Badge id: 283, name: "Win34", image: "test-cyan.png", created_at: "2012-06-14 16:49:09", updated_at: "2012-06-14 16:49:09">}
```

If one looks in the hash it presents the value for the locale key is the object to show. Is this a bug? My application works perfectly fine, it's just these specs that fails. And if I remove the scope in routes.rb the tests works fine.

**Comment by paulmwatson** [comment]
Thanks @noplay, that solved my problem
