### ISSUE TITLE
Anonymous controller problem

### ISSUE THREAD

**Issue by Exoth** [rspec/rspec-rails#573]
I've got such a before_filter in ApplicationController:

```
def foo
  redirect_to(params.except(:ref, :marker), status: 301) if params[:ref] || params[:marker]
end
```

And I want to test it using anonymous controller like this:

```
require 'spec_helper'

describe ApplicationController, type: :controller do
  controller do
    def index
      head :ok
    end
  end

  it "should redirect without ref and marker if any of them is given in request" do
    get :index, ref: 1, marker: 2, foo: 3
    response.should redirect_to('/anonymous/?foo=3')
  end
end
```

But this results in "was a redirect to http://test.host/flights/?controller=anonymous&foo=3" as inside ApplicationController it continues to use usual routing of the application where anonymous controller is not defined.

What is the supposed way to test such before_filters?

**Comment by n0nick** [comment]
The same issue reproduces for me with rspec 3.0.4 (ruby 2.0.0p594).

I ran @kirikak2's spec and the first example fails:
https://gist.github.com/n0nick/594432eee7ccf7ee2a2c

**Comment by JonRowe** [comment]
I'd suggest you try with 3.2 and then if it's still broken open a new issue with some reproducible examples given this issue is very old.
