### ISSUE TITLE
"No route matches" error when testing controllers with a namespace

### ISSUE THREAD

**Issue by nechmads** [rspec/rspec-rails#575]
If you have controllers with a namespace (e.g: Admin::MyController), trying to run any test will fail with:
ActionController::RoutingError:No route matches

example test:
describe Admin::MyController do
  describe 'index' do 
    it 'should work' do
      get :index
    end
  end
end

If you uncomment the following line in routes.rb, everything seems to work (although it is not a good and recommended solution):
match ':controller(/:action(/:id))(.:format)'

**Comment by dsounded** [comment]
Have it been fixed somehow ?

**Comment by JonRowe** [comment]
@dsounded this is a very old issue and the issue was in Rails and not RSpec.
