### ISSUE TITLE
Request Specs Converting Non String Values to Strings

### ISSUE THREAD

**Issue by vizjerai** [rspec/rspec-rails#610]
as a request spec both of these fails because they get converted into strings.

``` ruby
require 'spec_helper'

describe 'parameters' do
  before { post 'orders.json', order: {boolean: true, integer: 123} }
  it 'should have boolean value' do
    request.params['order']['boolean'].should == true
  end
  it 'should have integer value' do
    request.params['order']['integer'].should == 123
  end
end
```

as a controller spec boolean passes, integer fails.

``` ruby
require 'spec_helper'

describe OrdersController do
  before { post :create, order: {boolean: true, integer: 123} }
  it 'should have boolean value' do
    controller.params['order']['boolean'].should == true
  end
  it 'should have integer value' do
    controller.params['order']['integer'].should == 123
  end
end
```

This is with Rails 3.2.8 and RSpec 2.11.0

**Comment by skatenerd** [comment]
If anyone's struggling with this, as of rails 4.2, you can get it to work with:

        post :create, {order: {boolean: true, integer: 123}, :format => :json}

Shoutout to [these folks](http://stackoverflow.com/a/36350469)

**Comment by jrochkind** [comment]
In Rails5, I seem to be having this problem again.

**Comment by jrochkind** [comment]
In Rails5, I seem to be having this problem again. Even with `format: :json`, all integers get turned into strings, which does _not_ match how Rails is actually delivering them to me in production (from a json-format post'd body). 

Is there a regression in rails5?

**Comment by bkudria** [comment]
@jrochkind try `as: :json`

**Comment by jrochkind** [comment]
Yep, that's what worked. Sorry I forgot to come back and update, I was knee deep in yak shaving. 

Not sure where one would have figured that out from any documentation, but hey now it's here for those who end up here by googling, thanks @bkudria!

**Comment by rishi-suresh-keshav** [comment]
In rails 4.2.9, Rspec 3.6, I had to do `post :create, params.merge(format: :json)` to make it work. This was very annoying!!

**Comment by EdwinRozario** [comment]
Still have this issue when writing a request spec for API with POST to url and not an action.

```
params = { count: 1 }
post "/posts.json?#{params.to_query}"
```

`count` is a string when running the test and in real application its an integer.

**Comment by JonRowe** [comment]
All params are strings always. Thats the HTML standard. You can apply further parsing, and Rails will parse request bodies as JSON, I'm unsure wether it should parse your example as JSON, but it's a Rails issue.
