### ISSUE TITLE
Not clearing actionmailer deliveries array between specs

### ISSUE THREAD

**Issue by iainbeeston** [rspec/rspec-rails#661]
If you use the test delivery method with actionmailer, emails are stored in ActionMailer::Base.deliveries when they're sent. At present it seems like rspec-rails doesn't clear this array between examples (eg. [this](http://stackoverflow.com/questions/5843284/clearing-out-activemailerbase-deliveries-after-rspec-test) stackoverflow question). This means that examples that send e-mails and check this array to check for success are not independent of one-another.

I'm happy to write a pull-request to clear this array between examples (if actionmailer is being used and the test delivery method is selected), but I just wanted to confirm that this is a bug first (is it a bug?)

**Comment by karlingen** [comment]
For me the problem was that I had forgotten to add  `type: :mailer` to the spec:

```
describe UserMailer, type: :mailer do
  # some tests
end
```

Adding that solved my problem.

**Comment by eliotsykes** [comment]
(Apologies for resurrecting an old thread, hoping this will save fellow devs hours of head scratching). 

For devs running into the same issue as @firedev and @yggie, where the emails you find in `ActionMailer::Base.deliveries` are the same email duplicated or there is only one email when there should be multiple emails. 

I ran into this too and believe its to do with ActionMailer's internal state. 

An instance of ActionMailer::Base should only be used to send one email (in version 4.1.x at least). If you try to send multiple emails with the same instance of a mailer, the internal state can cause unexpected behavour to happen (as above). 

It may help to think of mailers like controllers where a controller instance only handles a single request/response; a mailer instance only handles one mail.

If you have a mailer method that causes multiple emails to be sent, done like this will cause problems:

```rb
# Avoid this
class InvoiceMailer < ActionMailer::Base
  def invoice_mail(customer)
    admin_mail = mail(to: 'admin@example.com', subject: 'About to send an invoice', ...)
    admin_mail.deliver

    # This new mail() call tramples on the internal state caused by the first mail() call.
    mail(to: customer, subject: 'Your invoice', ...)
  end
end

# Prefer this
class InvoiceMailer < ActionMailer::Base
  def invoice_alert
    mail(to: 'admin@example.com', subject: 'About to send an invoice', ...)
  end

  def invoice_mail(customer)
    # Note invoice_alert is invoked as a *class* method, not instance method:
    InvoiceMailer.invoice_alert.deliver

    mail(to: customer, subject: 'Your invoice', ...)
  end
end

# ActionMailer instance methods are invoked as class methods, and causes something like this
# to happen:
# InvoiceMailer.new.invoice_mail('foo@bar.com')
InvoiceMailer.invoice_mail('foo@bar.com').deliver
```
