### ISSUE TITLE
Reload ActiveModel object when checking changes

### ISSUE THREAD

**Issue by ghost** [rspec/rspec-rails#684]
Hello everybody,

This ([Reload object is they are reloadable (mainly for AR)](https://github.com/rspec/rspec-expectations/pull/96)) was already brought up a year ago so in here it goes :) It'd be nice to reload an ActiveModel object when checking for a change

e.g

``` ruby
describe "Update a Customer" do

    let(:customer) {Customer.create name: "Isaac"}
    before{visit edit_customer_path(customer)}

    it "should update customer with a new name" do
        fill_in "Name", with: "Newton"
        expect {
            click_button("Update Customer")
            tag.reload #This shouldn't be necessary
        }.to change(customer, :name).from("Isaac").to("Newton")
    end
end
```

Cheers!

**Comment by mikegrassotti** [comment]
This seems to trip up a lot of developers. Agreed it does not make sense to call reload automagically. Seems we could save a lot of lost hours by watching for this situation and provide a warning (which can be suppressed) as is done here: https://github.com/rspec/rspec-expectations/pull/768

**Comment by JonRowe** [comment]
@axos88 That's because ActiveRecord objects are compared by id by ActiveRecord, and not deep introspection of attributes. e.g.
```Ruby
customer = Customer.last
Customer.last.update_attributes! name: 'Bob'
customer == Customer.last
# => true
customer.name == Customer.last.name
# => false
```

RSpec expects objects to behave according to Ruby semantics

**Comment by axos88** [comment]
I know `why` it happens, but it does cause surprising and incorrect behaviour in this probably very common case ( I find myself writing tests like `expect { subject }.to change { thing.reload }.to have_attributes(something: 'newvalue')` quite often....

A warning should be printed at the very least if this is not something that could be easily fixed on the rspec side

**Comment by JonRowe** [comment]
We do print a warning, we tell you it did not change 😂but in all seriousness by Ruby semantics it hasn't changed, it's not RSpecs fault the magic of Rails is broken here, if you feel strongly about this I suggest you go open an Issue/PR for Rails making ActiveRecord objects not `==` when there attributes are not `==`, for them it would be as simple as:

```Ruby
def ==(other)
  other.id && self.id == other.id && self.attributes == other.attributes
end
```

**Comment by JonRowe** [comment]
Also It think `expect { perform_action; thing.reload }.to change { thing }.to have_attributes(something: 'newvalue')` would provide the experience you want.

**Comment by kuboon** [comment]
https://github.com/rspec/rspec-rails/issues/684#issuecomment-13049580
this works but reloads twice.

This is my solution. (but looks ugly)
```
expect { subject.tap{customer.reload} }.to change { customer.name }.from("Isaac").to("Newton")
```
