### ISSUE TITLE
Rails 4 test failures on ActiveRecord::Associations::CollectionProxy

### ISSUE THREAD

**Issue by agrobbin** [rspec/rspec-rails#707]
I'm not sure if this is the right place for this issue to be filed, but I thought I would start here.

After upgrading to Rails 4.0.0.beta1, I am experiencing many errors in my test suite related to `ActiveRecord::Associations::CollectionProxy::ActiveRecord_Associations_CollectionProxy...`

As an example, this test passed on Rails 3.2.12:

``` ruby
let(:institution) { stub_model(Institution) }

describe "#current_user" do
  before do
    controller.stub(:current_institution).and_return(institution)
    controller.stub(:session).and_return({user_id: 'cookie'})
    institution.students.stub(:find_by_cookie).and_return(current_user)
  end

  it "should call #find_by_cookie on students" do
    institution.students.should_receive(:find_by_cookie).with('cookie')
    get :index
  end
end
```

But, when running on Rails 4.0.0.beta1, this test fails with the following error:

```
  3) InstitutionsController#current_user should call #find_by_cookie on students
     Failure/Error: institution.students.should_receive(:find_by_cookie).with('cookie')
       (#<ActiveRecord::Associations::CollectionProxy::ActiveRecord_Associations_CollectionProxy_Student:0x007fe078ee2860>).find_by_cookie("cookie")
           expected: 1 time
           received: 0 times
     # ./spec/controllers/institutions_controller_spec.rb:79:in `block (3 levels) in <top (required)>'
```

If I have missed the issue related to this, or am filing it in the wrong repository, let me know. Thanks!

As a note, the code being tested is below:

``` ruby
def current_user
  return @current_user if defined?(@current_user)
  @current_user = current_institution.students.find_by_cookie(session[:user_id]) if session[:user_id]
end
```

**Comment by masterkain** [comment]
apparently this problem surfaced again, I'm using rails 5-0-stable:

before: https://github.com/rails/rails/blob/133a1759a4c317e7836699bba2530603a84d7ccb/activerecord/lib/active_record/associations/collection_association.rb#L37
after: https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/associations/collection_association.rb#L42
