### ISSUE TITLE
response.body doesn't work properly with rspec-rails 2.13.0

### ISSUE THREAD

**Issue by biznickman** [rspec/rspec-rails#708]
I just ran into an issue.  Not sure why it breaks, however all requests to response.body within the latest version of the gem return empty responses.  Here's a sample test that fails:

``` ruby
    it "responds to json" do
      get :index , :format => :json
      response.body.valid_json?.should be_true
    end
```

**Comment by rendon** [comment]
@Jeewes :+1:
