### ISSUE TITLE
Routes from dummy app not available in specs of (mountable) engine

### ISSUE THREAD

**Issue by flauwekeul** [rspec/rspec-rails#769]
## Steps to reproduce

I'm using **rspec-rails 2.13.2** and **rails 3.2.13**.

Create a Rails plugin as described in [this stackoverflow answer](http://stackoverflow.com/questions/8507798/rails-3-1-plugin-gem-dummy-test-app-rspec/9300185#9300185).

Then I've added routes to my engine as follows:

``` ruby
# /config/routes.rb

Foobar::Engine.routes.draw do
  root to: 'pages#index'
end
```

My only rspec test is this:

``` ruby
# /spec/controllers/pages_controller_spec.rb

require "spec_helper"

describe Foobar::PagesController do
  describe "GET /admin" do
    it "routes to pages#index" do
      expect(get: "/admin").to route_to(controller: "pages", action: "index")
    end
  end
end
```

My dummy app has this route:

``` ruby
# /spec/dummy/config/routes.rb

Rails.application.routes.draw do
  mount Foobar::Engine => "/admin"
end
```
## Problem

When running `rspec` in the root of the engine folder I get this error:

```
Failures:

  1) Foobar::PagesController GET /admin routes to pages#index
     Failure/Error: expect(get: "/admin").to route_to(controller: "pages", action: "index")
       No route matches "/admin"
     # ./spec/controllers/pages_controller_spec.rb:8:in `block (3 levels) in <top (required)>'
```
## Expected

I don't expect this test to fail as I mounted the engine's routes in the dummy app. Am I doing something wrong or is this a bug in rspec-rails?

Thanks in advance!

P.S. I've also posted a [stackoverflow question](http://stackoverflow.com/questions/17116012/rspec-cannot-find-plugin-routes) about this.

**Comment by chase439** [comment]
None of the solutions above work. The problem is I'm trying to use the routes from "dummy" application inside the gem's engine's spec. Even though it can be loaded via rspec's `routes { Rails.application.routes }`, rspec doesn't know how to route to the main dummy app, but instead only to the engine's controllers.

**Comment by benoittgt** [comment]
@chase439 could you provide a reproduction example? Is this https://github.com/rspec/rspec-rails/issues/1250 can help you?

**Comment by chase439** [comment]
@benoittgt Thanks but that doesn't help. #1250 basically includes the engine's routes into rspec context. What I need is the main_app (aka dummy app or Rails.application) routes in rspec. I can't provide project code right now as it's inside enterprise network.

**Comment by benoittgt** [comment]
@chase439 I will be super happy to help you on my free time. But I need at minimum an app to reproduce the behavior. 🙂

**Comment by BrunoAwdd** [comment]
You must add:

```
RSpec.describe My controller, type: :controller do
  routes { MyPlugin::Engine.routes }
```

then your spec will work

**Comment by alexsmartens** [comment]
I didn't like the Idea of including routes in every controller and set it up in this way:
```
# spec/support/engine_routes_helper.rb

RSpec.shared_context "Engine routes", shared_context: :metadata do
  routes { MyPlugin::Engine.routes  }
end
```

```
# spec/rails_helper.rb

require "support/engine_routes_helper"
RSpec.configure do |config|
...
  config.include_context "Engine routes", type: :controller
end
```
Now all controllers share this routes context.

**Comment by pirj** [comment]
You can include those routes to some controllers with metadata.
