### ISSUE TITLE
Undefined method `message`

### ISSUE THREAD

**Issue by mattconnolly** [rspec/rspec-rails#773]
I'm seeing some undefined method `message` errors using rspec with rails 4.0.0rc2. I'm using spec 2.13.

I'm not sure if this is the right place to flag this... I saw the issue closed in the rails project:

https://github.com/rails/rails/issues/9085

**Comment by mkolenda** [comment]
I'm in a Catch-22 situation with this issue.  

With gem 'test-unit' I get the error undefined method `message' for....  
Without the 'test-unit' gem I get the error ..2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require': cannot load such file -- test/unit/assertions (LoadError). (this issue https://github.com/rspec/rspec-rails/issues/1262)

I'm running: Ruby 2.2.0, rspec-rails (2.13.1), test-unit (3.0.8), rails (4.0.13)

**Comment by cupakromer** [comment]
Support for Ruby 2.2 on Rails 4.0 does not start until RSpec 3.2.

**Comment by cupakromer** [comment]
The other issue is specifically about using a routing matcher in a controller spec. Moving the spec into a route spec should resolve the issue for the time being.
