### ISSUE TITLE
Rspec testing with subdomain constraint

### ISSUE THREAD

**Issue by nayefc** [rspec/rspec-rails#789]
I've been stuck on this issue for almost two days now; I've seen literally all answers on stackoverflow and none work for me. I'm running on Rails 3.

I have an `api` subdomain that I'm trying to test the controllers in. The controllers are in `app/controllers/v1`. The route I am trying to test is: `GET /v1/payments` for the `index` action.

So far, I am using `http://api.lvh.me:3000/v1/payments` when running the requests. In rspec though, since I have a subdomain, it keeps throwing at me a No Route Found error like this:

```
Failure/Error: get :index
     ActionController::RoutingError:
       No route matches {:controller=>"v1/payments"}
```

I've added `api.example.com` to my `/etc/hosts` and I've added each of the following to a before block (each line separately, not all together obviously):

`request.host = 'api.example.com'`
`request.host = 'api.example.com:3000'`
`request.host = 'api.example.com:3000/v1/payments'`
`request.host = 'api.lvh.me:3000'`
`request.host = 'api.lvh.me:3000/v1/payments'`

They all failed with the same error. I even added `request.path = 'v1/payments'` as that's always set in the development environment but that also failed.

How am I getting a No Route Error? Is it because I only see `:controller =>` and no `:action =>`? Or is it just completely not getting the subdomain?

I did add api.example.com to /etc/hosts, so that should not be an issue when I add `request.host = 'api.example.com'`, right?

In the `requests/` integration tests, if I do: `get "api.lvh.me:3000/v1/payments"`, it works. Can I specify the path directly in controllers tests? If not, how else can I fix this issue?

Any help will be greatly appreciated!

Thanks,

**Comment by gferrarocamus** [comment]
For future googlers:

I ended up here trying to solve an ` ActionController::RoutingError` in my request tests.

I'm using an `:api` namespace in my `routes.rb` like so:
```
  namespace :api, :path => "", :constraints => { :subdomain => "api" }, defaults: { format: :json } do
    #some routes
  end

  devise_for :users,
              :constraints => { :subdomain => "api" },
              defaults: { format: :json },
              path: '',
              path_names: {
                # some path names
              },
              controllers: {
                # some controllers
              }
```

The above suggestions didn't work for me. However the solution came from [this StackOverflow answer](https://stackoverflow.com/a/30413528). I just added the line `before { host! "api.example.com" }` in my tests:

```
require 'rails_helper'

RSpec.describe 'Users', type: :request do
  before { host! "api.example.com" }

  describe 'GET /users' do
    context 'authenticated' do
      #some test
    end
  end

  #some more tests
end

```

And that did the trick.

**Comment by enowmbi** [comment]
> For future googlers:
> 
> I ended up here trying to solve an ` ActionController::RoutingError` in my request tests.
> 
> I'm using an `:api` namespace in my `routes.rb` like so:
> 
> ```
>   namespace :api, :path => "", :constraints => { :subdomain => "api" }, defaults: { format: :json } do
>     #some routes
>   end
> 
>   devise_for :users,
>               :constraints => { :subdomain => "api" },
>               defaults: { format: :json },
>               path: '',
>               path_names: {
>                 # some path names
>               },
>               controllers: {
>                 # some controllers
>               }
> ```
> 
> The above suggestions didn't work for me. However the solution came from [this StackOverflow answer](https://stackoverflow.com/a/30413528). I just added the line `before { host! "api.example.com" }` in my tests:
> 
> ```
> require 'rails_helper'
> 
> RSpec.describe 'Users', type: :request do
>   before { host! "api.example.com" }
> 
>   describe 'GET /users' do
>     context 'authenticated' do
>       #some test
>     end
>   end
> 
>   #some more tests
> end
> ```
> 
> And that did the trick.

**Comment by mirkode** [comment]
Dang @gferrarocamus! You made and saved my day! Thanks for that comment...

**Comment by pirj** [comment]
A PR with documentation update is welcome!

**Comment by mirkode** [comment]
Hi @pirj ,
sure! Will check if I find out how to add it to the documentation.

**Comment by mirkode** [comment]
@pirj added a PR. Hope it's correct like that.
