### ISSUE TITLE
Allow running an action from a before(:all) block

### ISSUE THREAD

**Issue by rosenfeld** [rspec/rspec-rails#796]
I'm not sure if this is the best way to deal with this issue, so let me explain it.

Currently, if you have multiple examples for a given performed action you have basically two options:

(1):

```
before {get 'index'}
example('a'){...} # assertions inside the blocks
example('b'){...}
example('c'){...}
....
```

or (2):

```
before {get 'index'}
example 'a and b and c...' do
   expect(...)... # test for a
   expect(...)... # test for b
   expect(...)... # test for c
   ...
end
```

If "get 'index'" takes 100ms and you want to test 10 different things on it, (2) will perform almost 1s faster then (1). On the other side, your specs will be clearer and read better when writing it as (1).

So you see where I want to get in, right? I'd like to be able to express my specs as in (1) but performing as in (2).

Here's how I could achieve that in theory:

```
context 'GET index' do
  before(:all){ get 'index' }
  # examples as in (1) here
end
```

Or using something like the given-when-then approach.

The before(:all) trick, if supported, won't work for most set-ups running the examples inside a transaction using `config.before(:each)` (see rspec/rspec#6).

Can you think of another way of speeding up (1) by avoiding the before block to always run? Currently I'm performing some tricks to cache the wanted results in the before block and running the action only once. That way I can get the multiple examples as in (1) with the performance of (2) but at the expense of an ugly set-up involving a before(:all) to set up a hash as an instance variable that is kept among the examples and storing the wanted results (and database records created) in this hash.

Besides the mess, if I just want to run a single example, I'll have to query the database in the cached before(:each) even if I don't use that record in that specific example.

I'd love to hear you opinions on how you can improve the test suite total running time for cases like this while keeping your examples well written.

**Comment by fakefarm** [comment]
Shame this thread didn't resolve. I am in a similar situation as @rosenfeld was and I'm not sure what to do.

**Comment by pirj** [comment]
As Jon said above,

> You don't have to have one assertion per test

So
```ruby
before { get ... }
it 'does all the different things' do
   expect(...)... # test for a
   expect(...)... # test for b
   expect(...)... # test for c
end
```
is perfectly fine, @fakefarm. You can even inline `get` into the example.

Or, alternatively, if you want to have different examples for your expectations, you can use `before_all` from `test-prof`. It wraps the example **group** in a transaction that is rolled back after all the examples defined in that example group finished running. https://github.com/test-prof/test-prof/blob/master/docs/recipes/before_all.md

**Comment by JonRowe** [comment]
We also have have an "aggregate_failures" functionality now which allows you to get the combined set of errors (or 1 pass) which mitigates some of the issues with regards to output from this initial request.

**Comment by rosenfeld** [comment]
@fakefarm I've been using the gem I created a few years ago based on @myronmarston's Fiber based solution to implement something like and around-all block in order to support transactions in groups and it has been working great since then. Maybe you could give it a try and see if it suits your needs: https://github.com/rosenfeld/rspec_nested_transactions
