### ISSUE TITLE
Getting 'uninitialized constant' (NameError) when overriding an engine controller only using rspec

### ISSUE THREAD

**Issue by kassi** [rspec/rspec-rails#809]
I have a weird (loading?) problem. I'm using rails 3.2.14 and rspec-rails 2.14.0.
I'm using an engine and have overridden an engine controller using the decorator pattern described in the docs.

When I run `bundle exec rake`, which runs the specs as default, I'm getting the error message 'uninitialized constant' in my decorator. It complains about the name that's defined in the engine (so not loaded yet).

When I run the printed command with `/fully/specified/path/to/ruby -S rspec` it works.

When I run `ruby -S rspec` it works, too.

When I run `rspec` it fails again, even though `which rspec` tells me it's in the same rvm gemset version as ruby is.

When I use testunit with the same code, I'm not getting any errors - even calling `rake` works fine. That's why I related this issue to rspec-rails.

The app btw works fine. It's using the decorator, overriding controller actions and extending the model of the engine from the main app.

I already created a question on [stackoverflow](http://stackoverflow.com/questions/18198911) and set up two demo projects: [decorator_demo_rspec](https://github.com/kassi/decorator_demo_rspec) and [decorator_demo_testunit](https://github.com/kassi/decorator_demo_testunit).

**Comment by samphippen** [comment]
@cupakromer is this still real? Can we close because stale?

**Comment by JonRowe** [comment]
I vote close as stale until theres a reproduction in current rspec / rails versions.
