### ISSUE TITLE
Custom scaffold's controller template

### ISSUE THREAD

**Issue by apux** [rspec/rspec-rails#818]
I want to customize the scaffold's controller template in my rails project.

https://github.com/rspec/rspec-rails/blob/master/lib/generators/rspec/scaffold/templates/controller_spec.rb

Is there any way to do that?

**Comment by visoft** [comment]
This seems to have changed. I'm using Rails 5 (master) with RSpec-Rails 3.1. The paths you provided @cupakromer, don't seem to work any longer. I have `/lib/templates/rspec/scaffold/controller_spec.rb`, but it's completely ignored.

**Comment by JonRowe** [comment]
I believe Rails 5 isn't officially supported yet, because it's a significant refactor of Rails internally and will require significant work for us to support . @cupakromer knows more than I though

**Comment by visoft** [comment]
I dropped down to Rails 4.2.4 and the paths seem to work fine.

**Comment by JayTeeSF** [comment]
Can someone please share the piece of code (or module) that does the template lookup? I've seen this question repeatedly asked (through the years) and knowing what lookups the template, might help. (I'd appreciate it :-) )

**Comment by cickes** [comment]
Is there a solution for this in Rails 5?

Trying to override model_spec.  Cannot get it to work.  Tried these locations.
`lib/templates/rspec/model/model_spec.rb`  
`lib/generators/rspec/model/templates/model_spec.rb`  
`lib/templates/rspec/model/model_spec.rb`

**Comment by yagudaev** [comment]
To clarify, the `rails g scaffold_controller ExistingModel name:string` actually goes to `lib/templates/rspec/scaffold/*_spec.rb` NOT to `lib/templates/rspec/scaffold_controller/*_spec.rb`
