### ISSUE TITLE
`render` method with explicit `template` needs request params in view specs

### ISSUE THREAD

**Issue by waiting-for-dev** [rspec/rspec-rails#872]
In a view spec, calling `render` method with explicit `template` option seems to go all the routing layer way before rendering the template.

For example, let's say we have a `books` controller and a `new` action, with its `new` template. If we are specifying something about that template, we can easily do:

    describe `users/new` do
      let(:user) { double('user') }
      before :each do
        assign(:user, user)
      end
      it "has some text" do
        render
        expect(rendered).to have_content 'something'
      end
    end

But if we want to describe something that is related with the layout, for example the title:

      it "has some title" do
        render template: 'users/new', layout: 'layouts/application'
        expect(rendered).to have_title 'Some title'
      end

That gives the error `No route matches...`. To make it pass, we must indicate the needed `id` parameter before:

      it "has some title" do
        controller.request.path_parameters[:user] = user
        render template: 'users/new', layout: 'layouts/application'
        expect(rendered).to have_title 'Some title'
      end

Is this behavior intended? In order to mix template and layout, is it needed to go through de routing stack? If so, maybe that should be advised in the docs. But I think ideally view specifications should be isolated always from the routing.

Thanks a lot.

**Comment by samphippen** [comment]
@waiting-for-dev can you confirm this still affects you? Would you be able to provide a reproduction case of the following form:

1) rails new an app up, and commit it
2) do a second commit which contains all the stuff that causes the bug you're talking about

then push that to a repo and link it here.

**Comment by waiting-for-dev** [comment]
Hey, sorry, not working in that anymore. It is from more than two years ago! ;) I think if nobody has any complain we can close it...
