### ISSUE TITLE
Unable to test OPTIONS requests in Rails integration tests

### ISSUE THREAD

**Issue by melcher** [rspec/rspec-rails#925]
I'm implementing CORS and want to test `OPTIONS` requests in my rspec Request specs, e.g.:

```
process :options, "users"
```

This is the preferred method to test :options requests since Rails 4+ removed the "options" request from its integration test runner / test cases (see https://github.com/rails/rails/commit/5dced4ee9be8cecdc43eb0c14f24a58d742762de and https://github.com/rails/rails/commit/e92a0653c01d6203d21a5237b1868118e784830e).

This currently fails with

```
super: no superclass method `process' for #<RSpec::Core::ExampleGroup....>
```

The reason for this is that rspec-rails RequestExampleGroup includes the following modules from Rails:

```
include ActionDispatch::Integration::Runner
....
include ActionController::TemplateAssertions
```

`ActionDispatch::Integration::Runner` will delegate `#process` calls that hit its method_missing to its current session and moves the resulting instance variables back and forth, in the same way that `get`, `patch`, `post`, `head`, etc. work.

`ActionController::TemplateAssertions` then defines `#process` directly as

``` ruby
# File actionpack/lib/action_controller/test_case.rb, line 60
def process(*args)
  @_partials = Hash.new(0)
  @_templates = Hash.new(0)
  @_layouts = Hash.new(0)
  super
end
```

This call to super creates the error you see. I'm not familiar enough with super/respond_to? to know if there's a simple way for the call to super to trigger the method missing on `ActionDispatch::Integration::Runner`, or if there is an intended way for this to work, but I'm pretty stuck. Maybe there's another way to test options requests? Also happy to provide a patch if someone familiar with this can provide direction. Thanks.

edit: clarified note on method missing

**Comment by EricLondon** [comment]
```
rails -v
Rails 4.2.1

gem list | grep -i rspec
guard-rspec (4.5.2)
rspec (3.3.0)
rspec-collection_matchers (1.1.2)
rspec-core (3.3.1)
rspec-expectations (3.3.0)
rspec-given (3.7.0)
rspec-mocks (3.3.1)
rspec-nc (0.2.0)
rspec-rails (3.3.2)
rspec-sidekiq (2.0.0)
rspec-support (3.3.0)
rspec_junit_formatter (0.2.3)
```

file: spec/requests/rack_cors_spec.rb
```
require 'rails_helper'

RSpec.describe 'Rack Cors', type: :request do

  it 'todo / in progress' do

    # integration_session.__send__ :process, 'OPTIONS', '/api/auth/validate_token'
    # NoMethodError: undefined method `process' for nil:NilClass
    # must reset! first:
    reset!

    integration_session.__send__ :process, 'OPTIONS', '/api/auth/validate_token'
    # ActionController::RoutingError: No route matches [OPTIONS] "/api/auth/validate_token"

  end

end
```

It seems as though it's making it past CORS middleware and hitting my Rails routes. Any thoughts on how to get this to work? thanks!

**Comment by monfresh** [comment]
I got it to work with this helper method: https://github.com/codeforamerica/ohana-api/blob/master/spec/support/request_helpers.rb#L9-L16

and specs that look like this: https://github.com/codeforamerica/ohana-api/blob/master/spec/api/cors_spec.rb

**Comment by lessan** [comment]
Just a quick note that in Rails 5, the `process` method requires named parameters after the method and url. So for example:
```
process :options, path, params: parameters, headers: headers_or_env
```
https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L328
