### ISSUE TITLE
RSpec API request merges array objects

### ISSUE THREAD

**Issue by novikserg** [rspec/rspec-rails#985]
I am not sure if it's exactly RSpec issue, but when I, for example, have the following code in my RSpec API test:
```ruby
let(:params) {
  { 'fruits' =>
        [ { apples: [{ apple_field: '1' }, { apple_field: '2' }],
           oranges: [{ orange_field: '3' }, { orange_field: '4' }]
         },
         { apples: [{ apple_field: '5' }, { apple_field: '6' }],
           oranges: [{ orange_field: '7' }, { orange_field: '8' }]
         }]
  }
}
    
it do
  post '/api/v1/fruits', params
  #expect blabla here
end
```
My controller gets the `params` looking like this:   
```ruby
{ 'fruits' =>
    [ { apples: [{ apple_field: '1' }, { apple_field: '2' }, { apple_field: '5' }, { apple_field: '6' }],
        oranges: [{ orange_field: '3' }, { orange_field: '4' }, { orange_field: '7' }, { orange_field: '8' }]
      }
    ]
}
```
So it basically merges them all. When I add some other key to these objects like this:   
```ruby
let(:params) {
  { 'fruits' =>
        [ { some_key: 'some_value', apples: [{ apple_field: '1' }, { apple_field: '2' }],
           oranges: [{ orange_field: '3' }, { orange_field: '4' }]
         },
         { some_key: 'whatever', apples: [{ apple_field: '5' }, { apple_field: '6' }],
           oranges: [{ orange_field: '7' }, { orange_field: '8' }]
         }]
  }
}
```
They are handled properly and do not get merged. I am using edge Rails and RSpec. Advice please?

**Comment by cybdoom** [comment]
I have the same issue
I try send request via rspec, and got them merged...

**Comment by JonRowe** [comment]
If you can provide a reproducible isolated example for s @cybdoom that would be a great help

**Comment by cybdoom** [comment]
Hi! Thank You for quick response!
Here is the link to my repo on bitbucket (I can not share it as public due
to commercial reasons): https://bitbucket.org/trackerrails
Give me Your bitbucket account if exists and I'll add You to collaborators!
The mentioned spec is app/specs/requests/tracks_spec.rb L:68
Thank You in advantage!
--
Eugene Narovlyansky, Software Developer

чт, 7 мая 2015 г. в 1:21, Jon Rowe <notifications@github.com>:

**Comment by cybdoom** [comment]
Mistyped in the link, here it is:  https://bitbucket.org/trackerrails
/trackerrails

пт, 8 мая 2015 г. в 18:23, Наровлянский Евгений <cybdoom@gmail.com>:

**Comment by samphippen** [comment]
hi @cybdoom none of us can really be added to a private repo for all sorts of horrifying intellectual property and warranty reasons. We need you to either provide a **new** repo with a reproduction case, or we won't be able to help.

Could you please take the following steps:

1. initialise a new repo with the correct version of rails
2. commit **just the rails new stuff**
3. do a second commit which includes all of your changes.

Thanks ^_^

**Comment by meaton-potatoes** [comment]
I just encountered this problem and made a public repo with an example: https://github.com/meaton-potatoes/rspec-params-bug

I don't believe this is a Rails issue.

**Comment by NikitaKolokoltsev** [comment]
I had a similar issue, but with a bit different type of "merging". I had been sending params like this:

```
put 'https://localhost:3000/api', params: {
  attributes: [
    { id: social_account.id, name: 'User' },
    { network: 'local', name: 'Another User', link: 'https://localhost:3000/another_user', main: true }
  ]
}
```

But after that request was made params came to the server in such form:
```
{
  attributes: [
    { id: social_account.id, name: 'User', network: 'local' },
    { name: 'Another User', link: 'https://localhost:3000/another_user', main: true }
  ]
}
```
And, as you understand, that lead to updating the wrong field for the first user, and not updating the corresponding field for another user.

### **WHAT ACTUALLY HELPED ME!!!**
I just added `as: :json` to the put request and it fixed the problem:
```
put 'https://localhost:3000/api', params: {...}, as: :json
```
🌈🌈🌈
