### ISSUE TITLE
Having unexpected fail in rails Rspec testing.

### ISSUE THREAD

**Issue by Hussein1147** [rspec/rspec-rails#995]
Hello i am having an issue with rspec testing. Some have suggested that i downgrade my Webrat to 0.7.1 but this doesnt solve my issue. here is the error messgage:
Failures:

  1) LayoutLinks should have a Help page at '/help' 
     Failure/Error: response.should have_selector('title', :content=>"Help")
       expected following output to contain a <title>Help</title> tag:
       <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
     # ./spec/requests/layout_links_spec.rb:18:in `block (2 levels) in <top (required)>'

  2) LayoutLinks should have a About page at '/about' 
     Failure/Error: response.should have_selector('title', :content=>"About")
       expected following output to contain a <title>About</title> tag:
       <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
     # ./spec/requests/layout_links_spec.rb:14:in `block (2 levels) in <top (required)>'

  3) LayoutLinks should have a Contact page at '/contact' 
     Failure/Error: response.should have_selector('title', :content=>"Contact")
       expected following output to contain a <title>Contact</title> tag:
       <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
     # ./spec/requests/layout_links_spec.rb:10:in `block (2 levels) in <top (required)>'

Finished in 0.20972 seconds
13 examples, 3 failures

Failed examples:

rspec ./spec/requests/layout_links_spec.rb:17 # LayoutLinks should have a Help page at '/help' 
rspec ./spec/requests/layout_links_spec.rb:13 # LayoutLinks should have a About page at '/about' 
rspec ./spec/requests/layout_links_spec.rb:9 # LayoutLinks should have a Contact page at '/contact' 

Randomized with seed 45459

**Comment by obromios** [comment]
Just to clarify this.  JonRowe, are you saying that ```have_selector('title', :content=>"Help")``` is a webrat selector and we should be changing to the appropriate capybara selector?

**Comment by JonRowe** [comment]
Haven't the foggiest but probably.
