### ISSUE TITLE
expect(subject).to assigns(instance_variable)

### ISSUE THREAD

**Issue by asiniy** [rspec/rspec-rails#999]
I faced with a difficult to test in rspec. 

I love the `subject` & `expect(subject).to` way to declare tests in rspec, but it have some functionality missing (at least, few [Stackoverflow](http://stackoverflow.com/questions/23180023/rspec-controller-subject-instance-variables) discussions didn't help me).

Is there any way to tests controller assigns instance variables like that?

``` ruby
    subject { get :index }

    describe 'by owner of records' do
      it { expect(subject).to render_template(:index) } # works
      it { expect(subject).to assigns(:records).to([some_array]) # it should test controllers assigns @records.
```

**Comment by stevepentler** [comment]
**Rails 5 Update:**
#[assigns](https://apidock.com/rails/ActionController/TestProcess/assigns) is deprecated

Though it can be a [code smell](https://github.com/rails/rails/issues/18950), to upgrade older apps you can transition to [#instance_variable_get](https://apidock.com/ruby/Object/instance_variable_get). 

Rspec example:
`expect(@controller.instance_variable_get(:@people).first).to eq(person)`
